r"""BKM simple roots of g_{Delta_5} as conjectural Yangian-deformation generators.

STATUS: CONJECTURAL (AP-CY14).  No Drinfeld presentation for a Yangian
deformation of this BKM algebra exists.  This module constructs the DICTIONARY between BKM simple root
vectors and conjectural Yangian generators, identifying:

    (A) Real simple roots  <-->  Cartan-type generators h_i(u)
    (B) Imaginary simple roots of mult 1  <-->  single current generators
    (C) Imaginary simple roots of mult > 1  <-->  multiplet generators

The dictionary is UNCONDITIONAL at the level of the Lie algebra (the BKM
side is proved).  The YANGIAN SIDE is conjectural: the putative affine
deformation Y(g_hat_{Delta_5}) has not been constructed.

MATHEMATICAL CONTENT
====================

1. REAL SIMPLE ROOTS (CARTAN GENERATORS).

   g_{Delta_5} has 3 real simple roots delta_1, delta_2, delta_3 in Lambda^{2,1}_{II}
   with Gram matrix A_{ij} = ((2,-2,-2),(-2,2,-2),(-2,-2,2)).

   In a standard Yangian Y(g), the real simple roots alpha_i correspond
   to the Cartan generators:
     h_i(u) = 1 + hbar * h_i / (u - c_i)     (Drinfeld generating function)
     e_i(u), f_i(u)                             (raising/lowering)

   For g_{Delta_5}: the 3 real simple roots give 3 Cartan generators
   h_1(u), h_2(u), h_3(u) with the Cartan matrix = Gram matrix of Lambda^{2,1}_{II}.
   The Weyl group W = <s_1, s_2, s_3> (generated by reflections in delta_i)
   acts on the Yangian by automorphisms.

   This part is STANDARD Yangian theory (Drinfeld, 1985): a BKM algebra
   with real simple roots alpha_1,...,alpha_r has a Yangian with r Cartan
   generators indexed by the real simple roots.

2. IMAGINARY SIMPLE ROOTS.

   The imaginary simple roots of g_{Delta_5} are organized by discriminant
   D = (alpha, alpha) in {-1, 0, 3, 4, 7, 8, 11, ...} with multiplicities
   |c(D)| from phi_{0,1}.

   KEY STRUCTURAL POINT: for a BKM algebra, the imaginary simple roots
   alpha with (alpha, alpha) <= 0 are GENERATORS of the Lie algebra that
   have no analogue in finite-dimensional or affine Kac-Moody theory.
   They correspond to BPS states in the physical interpretation.

   D = -1 sector (lightlike, c(-1) = 1):
     A single imaginary simple root of norm -1 and multiplicity 1.
     This is the Weyl vector contribution.  In the Yangian, this would be
     a SINGLE additional generator e_W(u) (Weyl vector current) beyond
     the Cartan generators.  This is the simplest imaginary generator.

   D = 0 sector (isotropic/lightlike, c(0) = 10):
     The lightlike roots have (alpha, alpha) = 0 (isotropic vectors in
     Lambda^{2,1}_{II}).  The multiplicity 10 means: each primitive isotropic
     direction in Lambda^{2,1}_{II} has multiplicity c(0) = 10.

     In the lattice Lambda^{2,1}_{II} there are finitely many primitive isotropic
     directions (up to Weyl group action).  The total contribution is
     10 generators per primitive isotropic direction.

     In the Yangian interpretation: the D = 0 generators form a
     10-dimensional REPRESENTATION of the Weyl group S_3.  This
     decomposes as 10 = 1 + 1 + 1 + 1 + 3 + 3 (under S_3), giving
     sub-multiplets of generators.

     CRITICAL: c(0) = 10 also determines the BKM weight:
     kappa_BKM = c(0)/2 = 5 (the weight of Delta_5).

   D > 0 sector (spacelike, |c(D)| generators each):
     D equiv 0 mod 4: bosonic roots, c(D) > 0, multiplicity c(D)
     D equiv 3 mod 4: fermionic roots, c(D) < 0, multiplicity |c(D)|

     These are the "higher imaginary" generators.  In the Yangian, each
     would be an additional current generator e_D^{(a)}(u) for
     a = 1, ..., |c(D)|.

     For a standard Yangian, these have no analogue.  The correct
     framework is the COHOMOLOGICAL HALL ALGEBRA (CoHA):

3. CoHA APPROACH (AP-CY7 COMPLIANT).

   The CoHA of K3 x E gives the positive half:
     CoHA(K3 x E) = U(n_+(g_{Delta_5}))

   This is an ASSOCIATIVE algebra (AP-CY7), NOT a chiral algebra.
   The CoHA product is the convolution on BM homology of the moduli stack.

   The generators of n_+ are EXACTLY the imaginary simple root vectors.
   At each discriminant D, the BPS states form a vector space of dimension
   |c(D)|, and the CoHA multiplication encodes the BKM Lie bracket.

   The passage CoHA -> Yangian requires the DRINFELD DOUBLE construction:
     CoHA = U(n_+)  --(Drinfeld double)-->  Y(g_{Delta_5})

   For C^3: CoHA(C^3) = Y^+(gl_hat_1) --> DY(gl_hat_1) = Y(gl_hat_1)
   (Schiffmann-Vasserot, PROVED).

   For K3 x E: CoHA(K3xE) = U(n_+(g_{Delta_5})) --> "Y(g_{Delta_5})"
   (CONJECTURAL, requires CY-A_3).

4. GENERATOR COUNT.

   The total generator count for the conjectural Yangian Y(g_{Delta_5}):

   Real sector:    3 Cartan triples (h_i, e_i, f_i) for i = 1,2,3
   D = -1 sector:  1 imaginary generator (Weyl vector current)
   D = 0 sector:   10 lightlike generators (BKM weight sector)
   D = 3 sector:   64 fermionic generators
   D = 4 sector:   108 bosonic generators
   D = 7 sector:   513 fermionic generators
   ...             (continues to infinity: class M)

   At discriminant cutoff D_max, the total count is:
     N(D_max) = 3 + sum_{D=-1}^{D_max} |c(D)|  (only valid D)

   The growth is exp(2*pi*sqrt(D_max)) by Rademacher.

5. WHAT IS MISSING.

   A Drinfeld presentation of Y(g_{Delta_5}) requires:
   (a) Serre relations between imaginary generators (UNKNOWN for BKM)
   (b) The coproduct on imaginary generators (UNKNOWN)
   (c) The R-matrix beyond the abelian (gl_1) sector (UNKNOWN)

   The MO R-matrix (thm:k3e-mo-rmatrix) gives the charge-1 R-matrix
   for the abelian sector.  The non-abelian generalization requires
   the full Yangian deformation of the BKM algebra, which has not been constructed.

   The STRUCTURAL OBSTRUCTION: for a BKM algebra, the imaginary simple
   roots do NOT satisfy standard Serre relations.  Instead, they satisfy
   "Borcherds-Serre" relations involving the multiplicity function.
   The Yangian deformation of these relations is an open problem.

CONVENTIONS
===========
  - AP-CY7: CoHA is associative, NOT E_1-chiral.  The "E_1-sector of
    G(X)" formulation assumes G(X) exists.  We say CoHA = U(n_+).
  - AP-CY14: all Yangian results are CONJECTURAL.
  - AP-CY8: bar Euler = BKM denominator requires CY-A + Vol I anchor.
  - AP113: kappa subscripts.  kappa_BKM = 5, not bare kappa.

REFERENCES
==========
  Borcherds, "Generalized Kac-Moody algebras" (1988)
  Gritsenko-Nikulin, "Automorphic forms and Lorentzian KM algebras II" (1998)
  Maulik-Okounkov, arXiv:1211.1287 (stable envelopes, R-matrix)
  Schiffmann-Vasserot, arXiv:1301.6466 (CoHA and Yangians)
  Drinfeld, "Quantum groups" (1985)
  Guay, "Affine Yangians and deformed double current algebras" (2007)
"""

from __future__ import annotations

import math
from collections import defaultdict
from fractions import Fraction
from typing import Any, Dict, List, NamedTuple, Optional, Tuple


# ---------------------------------------------------------------------------
# Import helpers
# ---------------------------------------------------------------------------

def _import_bkm_bar():
    """Import k3_elliptic_genus_bkm_bar from the same directory."""
    try:
        from compute.lib import k3_elliptic_genus_bkm_bar
        return k3_elliptic_genus_bkm_bar
    except (ImportError, ModuleNotFoundError):
        import importlib, os, sys
        _lib_dir = os.path.dirname(os.path.abspath(__file__))
        if _lib_dir not in sys.path:
            sys.path.insert(0, _lib_dir)
        return importlib.import_module('k3_elliptic_genus_bkm_bar')


def _import_bkm_chiral():
    """Import bkm_chiral_algebra from the same directory."""
    try:
        from compute.lib import bkm_chiral_algebra
        return bkm_chiral_algebra
    except (ImportError, ModuleNotFoundError):
        import importlib, os, sys
        _lib_dir = os.path.dirname(os.path.abspath(__file__))
        if _lib_dir not in sys.path:
            sys.path.insert(0, _lib_dir)
        return importlib.import_module('bkm_chiral_algebra')


# =========================================================================
# 0. Constants
# =========================================================================

STATUS = 'CONJECTURAL'  # AP-CY14

# Gram matrix of Lambda^{2,1}_{II} (real simple root inner products)
GRAM_MATRIX = ((2, -2, -2), (-2, 2, -2), (-2, -2, 2))
NUM_REAL_SIMPLE_ROOTS = 3

# Weyl group of Lambda^{2,1}_{II}: S_3 (symmetric group on 3 elements)
WEYL_GROUP_ORDER = 6  # |S_3| = 6

# The Weyl vector rho = (1/2)(delta_1 + delta_2 + delta_3)
WEYL_VECTOR_COORDS = (Fraction(1, 2), Fraction(1, 2), Fraction(1, 2))

# Known c(D) values for reference (from k3_elliptic_genus_bkm_bar.py)
# VERIFIED [DC] exact computation, [CF] cross-engine k3_elliptic_genus_bkm_bar.py
KNOWN_MULTIPLICITIES = {
    -1: 1,        # D=-1: polar, bosonic, single Weyl vector root
    0: 10,        # D=0: lightlike, bosonic, kappa_BKM sector
    3: -64,       # D=3: first fermionic
    4: 108,       # D=4: first spacelike bosonic
    7: -513,      # D=7: fermionic
    8: 808,       # D=8: bosonic
    11: -2752,    # D=11: fermionic
    12: 4016,     # D=12: bosonic
    15: -11775,   # D=15: fermionic
    16: 16524,    # D=16: bosonic
}


# =========================================================================
# 1. Real simple roots -> Cartan generators
# =========================================================================

class RealSimpleRoot(NamedTuple):
    """A real simple root of g_{Delta_5} with its Yangian generator data.

    The 3 real simple roots delta_1, delta_2, delta_3 live in Lambda^{2,1}_{II}.
    Each gives a Cartan triple (h_i, e_i, f_i) in the conjectural Yangian.
    """
    index: int                  # 1, 2, or 3
    label: str                  # 'delta_1', 'delta_2', 'delta_3'
    norm_sq: int                # (delta_i, delta_i) = 2
    inner_products: Tuple[int, ...]  # (delta_i, delta_j) for j = 1,2,3
    yangian_generator_type: str  # 'Cartan triple (h, e, f)'
    weyl_reflection_order: int  # order of s_i in the Weyl group
    status: str


def real_simple_roots() -> List[RealSimpleRoot]:
    r"""Construct the 3 real simple roots of g_{Delta_5}.

    The real simple roots delta_1, delta_2, delta_3 in Lambda^{2,1}_{II} have:
      delta_1 = 2f_2 - f_3
      delta_2 = 2f_{-2} - f_3
      delta_3 = f_3

    Gram matrix: A_{ij} = (delta_i, delta_j) = ((2,-2,-2),(-2,2,-2),(-2,-2,2))

    These would correspond to the Cartan generators h_i(u) in a conjectural
    Yangian deformation Y(g_hat_{Delta_5}):
      h_i(u) = 1 + hbar * h_i / (u - c_i)  (Drinfeld generating function)
      [e_i(u), f_j(w)] = delta_{ij} * delta(u-w) * h_i(u)  (Drinfeld relation)

    The Cartan matrix A = (A_{ij}/2) enters the Serre relations of the Yangian.

    STATUS: The real simple root data is PROVED (Gritsenko-Nikulin).
    The Yangian interpretation is CONJECTURAL (AP-CY14).
    """
    roots = []
    labels = ['delta_1', 'delta_2', 'delta_3']
    for i in range(NUM_REAL_SIMPLE_ROOTS):
        roots.append(RealSimpleRoot(
            index=i + 1,
            label=labels[i],
            norm_sq=GRAM_MATRIX[i][i],
            inner_products=GRAM_MATRIX[i],
            yangian_generator_type='Cartan triple (h, e, f)',
            weyl_reflection_order=2,  # s_i^2 = 1
            status=STATUS,
        ))
    return roots


def cartan_matrix() -> Tuple[Tuple[int, ...], ...]:
    r"""The Cartan matrix a_{ij} = 2*(delta_i, delta_j)/(delta_i, delta_i).

    For the Gram matrix A = ((2,-2,-2),(-2,2,-2),(-2,-2,2)):
      a_{ij} = 2 * A_{ij} / A_{ii} = A_{ij}  (since A_{ii} = 2 for all i)

    So the Cartan matrix equals the Gram matrix for Lambda^{2,1}_{II}.

    This Cartan matrix is of HYPERBOLIC type: the determinant
    det(A) = 2*(2*2 - (-2)(-2)) - (-2)((-2)*2 - (-2)(-2)) + (-2)((-2)(-2) - 2*(-2))
    = 2*(4-4) + 2*(-4-4) - 2*(4+4)
    = 0 - 16 - 16 = -32

    The negative determinant confirms hyperbolicity (Lorentzian signature).
    """
    n = NUM_REAL_SIMPLE_ROOTS
    result = []
    for i in range(n):
        row = []
        for j in range(n):
            row.append(2 * GRAM_MATRIX[i][j] // GRAM_MATRIX[i][i])
        result.append(tuple(row))
    return tuple(result)


def cartan_matrix_determinant() -> int:
    """Compute det(Cartan matrix) = det(Gram matrix).

    For the 3x3 matrix A = ((2,-2,-2),(-2,2,-2),(-2,-2,2)):
    det = 2*(4 - 4) - (-2)*(-4 - 4) + (-2)*(4 + 4)
        = 0 - (-2)*(-8) + (-2)*(8)
        = 0 - 16 - 16 = -32

    VERIFIED [DC] direct computation.
    """
    A = GRAM_MATRIX
    det = (A[0][0] * (A[1][1] * A[2][2] - A[1][2] * A[2][1])
           - A[0][1] * (A[1][0] * A[2][2] - A[1][2] * A[2][0])
           + A[0][2] * (A[1][0] * A[2][1] - A[1][1] * A[2][0]))
    return det


def weyl_group_data() -> Dict[str, Any]:
    r"""Data about the Weyl group W of g_{Delta_5}.

    The Weyl group is generated by reflections s_1, s_2, s_3 in the
    real simple roots delta_1, delta_2, delta_3.

    For Lambda^{2,1}_{II} with Gram matrix ((2,-2,-2),(-2,2,-2),(-2,-2,2)):
    the Weyl group is the symmetric group S_3 (order 6), acting on
    the fundamental polyhedron P_{II} with Aut(P_{II}) = S_3.

    The full orthogonal group of Lambda^{2,1}_{II} is:
      O(Lambda^{2,1}_{II})_+ = W * Aut(P_{II}) = S_3 * S_3

    In the conjectural deformation model, the Weyl group would act on
    Y(g_hat_{Delta_5}) by automorphisms:
      s_i: e_j(u) -> (ad e_i)^{-a_{ij}} f_j(u)  (Lusztig automorphism)

    where a_{ij} is the Cartan matrix entry.  This action permutes the
    imaginary root spaces.
    """
    return {
        'weyl_group': 'S_3',
        'order': WEYL_GROUP_ORDER,
        'generators': ['s_1', 's_2', 's_3'],
        'presentation': 's_i^2 = 1, (s_1 s_2)^inf = (s_1 s_3)^inf = (s_2 s_3)^inf = ...',
        'note': (
            'For the HYPERBOLIC Gram matrix, the Coxeter group is infinite. '
            'But the Weyl group modulo the lattice automorphisms is S_3 '
            '(the automorphism group of the fundamental polyhedron).'
        ),
        'action_on_yangian': 'Lusztig automorphisms permuting root spaces',
        'status': STATUS,
    }


# =========================================================================
# 2. Imaginary simple roots -> Yangian generators
# =========================================================================

class ImaginarySimpleRootSector(NamedTuple):
    """A sector of imaginary simple roots at a given discriminant D.

    At each discriminant D, the imaginary simple roots form a vector
    space of dimension |c(D)|.  The parity (bosonic/fermionic) is
    determined by the sign of c(D).
    """
    discriminant: int           # D = (alpha, alpha) for the root alpha
    multiplicity: int           # |c(D)| = number of independent generators
    c_value: int                # c(D) from phi_{0,1} (signed)
    parity: str                 # 'bosonic' (c > 0) or 'fermionic' (c < 0)
    norm_type: str              # 'timelike' (D < 0), 'lightlike' (D = 0), 'spacelike' (D > 0)
    yangian_generator_type: str  # description of the Yangian generator
    coha_interpretation: str    # CoHA interpretation (AP-CY7 compliant)
    status: str


def imaginary_simple_root_sectors(D_max: int = 30) -> List[ImaginarySimpleRootSector]:
    r"""Classify all imaginary simple root sectors by discriminant.

    For each discriminant D with c(D) != 0, the BKM algebra g_{Delta_5}
    has |c(D)| imaginary simple root vectors of norm D.

    The Yangian generator type depends on the sector:

    D = -1 (timelike, c(-1) = 1):
      A single generator e_W(u) -- the Weyl vector current.
      This is unique (multiplicity 1) and bosonic.
      In the CoHA: this is the UNIQUE BPS state at the polar charge.

    D = 0 (lightlike, c(0) = 10):
      10 generators at the lightlike wall.  These live in isotropic
      directions of Lambda^{2,1}_{II}.  The multiplicity 10 = c(0) gives
      kappa_BKM = c(0)/2 = 5 via the Borcherds weight formula.
      In the CoHA: these are 10 independent BPS states at charge 0
      (in the lightlike chamber), carrying the Hall multiplication
      that encodes the BKM Lie bracket between isotropic roots.
      CRITICAL (AP-CY7): the CoHA product is associative,
      not a vertex algebra OPE.

    D > 0 (spacelike, |c(D)| generators):
      These are the higher imaginary generators.  At each D, there are
      |c(D)| independent generators, bosonic if c(D) > 0 (D equiv 0 mod 4),
      fermionic if c(D) < 0 (D equiv 3 mod 4).
      In the CoHA: these are BPS bound states at charge D.

    STRUCTURAL OBSTRUCTION (AP-CY14):
      For a STANDARD Kac-Moody algebra, imaginary roots arise as
      COMPOSITES of real roots (via the Weyl orbit and root addition).
      For a BKM algebra, imaginary SIMPLE roots are primitive generators
      that do not decompose.  A Yangian Y(g) for a BKM algebra g must
      accommodate these generators, but no such Yangian has been
      constructed for ANY BKM algebra.

    Returns sectors sorted by discriminant.
    """
    bkm_bar = _import_bkm_bar()
    table = bkm_bar.c_table_from_phi01(D_max)

    sectors = []
    for D in sorted(table.keys()):
        c_val = table[D]
        if c_val == 0:
            continue

        mult = abs(c_val)
        parity = 'bosonic' if c_val > 0 else 'fermionic'

        if D < 0:
            norm_type = 'timelike'
        elif D == 0:
            norm_type = 'lightlike'
        else:
            norm_type = 'spacelike'

        # Yangian generator type
        if D == -1:
            yang_type = (
                'Single current e_W(u) (Weyl vector). '
                'Unique imaginary generator of multiplicity 1.'
            )
            coha_interp = (
                'Unique BPS state at the polar charge vector. '
                'Corresponds to the Weyl vector contribution in the '
                'denominator identity.'
            )
        elif D == 0:
            yang_type = (
                f'{mult} lightlike generators. '
                f'kappa_BKM = c(0)/2 = {c_val // 2}. '
                'These generators span the lightlike root space '
                'and determine the Borcherds lift weight.'
            )
            coha_interp = (
                f'{mult} BPS states at lightlike charge. '
                'The CoHA multiplication (associative, AP-CY7) on '
                'this sector encodes the BKM Lie bracket between '
                'isotropic root vectors. NOT an OPE.'
            )
        else:
            yang_type = (
                f'{mult} {parity} generators at discriminant D={D}. '
                f'{"Fermionic (odd) root vectors." if parity == "fermionic" else "Bosonic (even) root vectors."}'
            )
            coha_interp = (
                f'{mult} BPS bound states at charge D={D}. '
                f'The CoHA product (associative) gives the Hall '
                f'multiplication on this {parity} sector.'
            )

        sectors.append(ImaginarySimpleRootSector(
            discriminant=D,
            multiplicity=mult,
            c_value=c_val,
            parity=parity,
            norm_type=norm_type,
            yangian_generator_type=yang_type,
            coha_interpretation=coha_interp,
            status=STATUS,
        ))

    return sectors


def imaginary_generator_at_discriminant(D: int) -> Dict[str, Any]:
    r"""Detailed data for the imaginary generator sector at discriminant D.

    Returns the multiplicity, parity, norm type, and the conjectural
    Yangian generator interpretation.

    For D = -1: single Weyl vector current.
    For D = 0: 10 lightlike generators (kappa_BKM sector).
    For D > 0: |c(D)| BPS-type generators.
    """
    bkm_bar = _import_bkm_bar()
    table = bkm_bar.c_table_from_phi01(max(D + 10, 30))

    c_val = table.get(D, 0)
    if c_val == 0:
        return {
            'discriminant': D,
            'c_value': 0,
            'multiplicity': 0,
            'has_generators': False,
            'note': f'No simple roots at discriminant D={D} (c(D)=0 or D is not a valid discriminant).',
        }

    mult = abs(c_val)
    parity = 'bosonic' if c_val > 0 else 'fermionic'
    norm_type = 'timelike' if D < 0 else ('lightlike' if D == 0 else 'spacelike')

    result = {
        'discriminant': D,
        'c_value': c_val,
        'multiplicity': mult,
        'parity': parity,
        'norm_type': norm_type,
        'has_generators': True,
        'status': STATUS,
    }

    if D == -1:
        result['yangian_data'] = {
            'type': 'Weyl vector current e_W(u)',
            'uniqueness': 'This is the UNIQUE imaginary simple root of multiplicity 1.',
            'role': (
                'The Weyl vector rho = (1/2)(delta_1 + delta_2 + delta_3) determines '
                'the leading exponential in the denominator identity. In the conjectural '
                'Yangian, e_W(u) generates the minimal imaginary extension beyond the '
                'real (Cartan) sector.'
            ),
            'analogy': (
                'For the Monster Lie algebra (BKM on II_{1,1}), the D=-1 generator '
                'is the unique simple imaginary root that extends the Heisenberg from '
                'the hyperbolic plane to the full algebra. For g_{Delta_5}, the role '
                'is analogous: it extends the rank-3 real sector to the full BKM.'
            ),
        }
    elif D == 0:
        result['yangian_data'] = {
            'type': f'{mult} lightlike generators',
            'kappa_BKM': c_val // 2,
            'weight_formula': f'weight(Delta_5) = c(0)/2 = {c_val}/2 = {c_val // 2}',
            'role': (
                f'The {mult} lightlike generators span the isotropic root space '
                'of Lambda^{2,1}_{II}. Their multiplicity determines the weight of the '
                'Borcherds product (the primitive Gritsenko-Nikulin denominator Delta_5 of weight 5). '
                'In the conjectural Yangian, these form a multiplet under the '
                'Weyl group S_3.'
            ),
            's3_decomposition': (
                '10 = 1 + 1 + 1 + 1 + 3 + 3 as S_3 representation (conjectural). '
                'The decomposition depends on how the isotropic directions in '
                'Lambda^{2,1}_{II} transform under the Weyl group. Each S_3-orbit of '
                'primitive isotropic vectors carries a sub-multiplet of generators.'
            ),
        }
    else:
        result['yangian_data'] = {
            'type': f'{mult} {parity} generators at D={D}',
            'role': (
                f'{"Fermionic" if parity == "fermionic" else "Bosonic"} BPS generators '
                f'at discriminant D={D}. In the conjectural Yangian, these are '
                f'additional currents e_D^{{(a)}}(u) for a = 1,...,{mult}.'
            ),
            'serre_obstruction': (
                'For a standard Kac-Moody algebra, the Serre relations between '
                'generators are determined by the Cartan matrix. For a BKM algebra, '
                'the imaginary simple roots satisfy Borcherds-Serre relations: '
                '[e_alpha, [e_alpha, e_beta]] = 0 when (alpha, beta) = 0 for '
                'imaginary alpha with (alpha, alpha) <= 0. The Yangian deformation '
                'of these relations is UNKNOWN.'
            ),
        }

    return result


# =========================================================================
# 3. Generator census
# =========================================================================

def generator_census(D_max: int = 30) -> Dict[str, Any]:
    r"""Complete census of Yangian generators through discriminant D_max.

    Counts:
    - Real Cartan generators: 3 (from delta_1, delta_2, delta_3)
    - Imaginary generators: sum_{D=-1}^{D_max} |c(D)| (over valid D)

    The total generator count grows as exp(2*pi*sqrt(D_max)) by Rademacher.
    This confirms class M (infinite number of generators).

    Returns detailed census with breakdown by sector.
    """
    bkm_bar = _import_bkm_bar()
    table = bkm_bar.c_table_from_phi01(D_max)

    # Real generators
    real_count = NUM_REAL_SIMPLE_ROOTS  # = 3 Cartan triples
    real_total = 3 * real_count  # h, e, f for each

    # Imaginary generators by sector
    timelike_count = 0  # D < 0
    lightlike_count = 0  # D = 0
    spacelike_bosonic_count = 0  # D > 0, c(D) > 0
    spacelike_fermionic_count = 0  # D > 0, c(D) < 0

    sectors = {}
    for D in sorted(table.keys()):
        c_val = table[D]
        if c_val == 0:
            continue
        mult = abs(c_val)
        parity = 'bosonic' if c_val > 0 else 'fermionic'

        if D < 0:
            timelike_count += mult
        elif D == 0:
            lightlike_count += mult
        elif c_val > 0:
            spacelike_bosonic_count += mult
        else:
            spacelike_fermionic_count += mult

        sectors[D] = {'c': c_val, 'mult': mult, 'parity': parity}

    imaginary_total = (timelike_count + lightlike_count
                       + spacelike_bosonic_count + spacelike_fermionic_count)
    grand_total = real_count + imaginary_total

    return {
        'D_max': D_max,
        'real_simple_roots': real_count,
        'real_generator_triples': real_total,
        'imaginary_generators': {
            'timelike_D_lt_0': timelike_count,
            'lightlike_D_eq_0': lightlike_count,
            'spacelike_bosonic': spacelike_bosonic_count,
            'spacelike_fermionic': spacelike_fermionic_count,
            'total': imaginary_total,
        },
        'grand_total': grand_total,
        'sectors': sectors,
        'kappa_BKM': table.get(0, 0) // 2,
        'class': 'M (infinite generators, Rademacher growth)',
        'growth_estimate': f'exp(2*pi*sqrt({D_max})) ~ {math.exp(2 * math.pi * math.sqrt(D_max)):.0f}',
        'status': STATUS,
    }


# =========================================================================
# 4. CoHA-to-Yangian dictionary (AP-CY7 compliant)
# =========================================================================

def coha_to_yangian_dictionary(D_max: int = 20) -> Dict[str, Any]:
    r"""Dictionary between CoHA generators and conjectural Yangian generators.

    CRITICAL (AP-CY7): The CoHA is an ASSOCIATIVE algebra.
    It is NOT a chiral algebra, NOT an E_1-chiral algebra.
    The CoHA product is the convolution product on BM homology.

    The dictionary:
      CoHA(K3 x E)  =  U(n_+(g_{Delta_5}))   (PROVED, Gritsenko-Nikulin + SV)
      n_+           =  bigoplus_{alpha > 0} g_alpha   (positive nilpotent)
      generators of n_+ = imaginary simple root vectors of g_{Delta_5}

    For the conjectural Yangian:
      CoHA(K3 x E) = Y^+(g_{Delta_5})   (positive half of the Yangian)
      Y(g_{Delta_5}) = Drinfeld double of Y^+(g_{Delta_5})

    Comparison with C^3 (where everything is proved):
      CoHA(C^3) = Y^+(gl_hat_1) = SHc^+   (Schiffmann-Vasserot, PROVED)
      Y(gl_hat_1) = W_{1+inf}              (PROVED, via Drinfeld double)

    For K3 x E:
      CoHA(K3xE) = U(n_+(g_{Delta_5}))     (PROVED)
      "Y(g_{Delta_5})"                      (CONJECTURAL, no construction)
      The Drinfeld double construction requires:
      (a) A Hopf algebra structure on U(n_+)  -- exists (universal enveloping)
      (b) A dual pairing n_+ x n_- -> k       -- exists (Killing form)
      (c) The double DD(U(n_+))                -- exists abstractly
      (d) DD(U(n_+)) = Y(g_{Delta_5})         -- CONJECTURAL (no proof)

    The obstruction at step (d): for finite-dimensional g, the Drinfeld double
    of the positive Borel gives the Yangian.  For BKM algebras, the infinite
    number of imaginary simple roots creates convergence issues in the double.
    """
    bkm_bar = _import_bkm_bar()
    table = bkm_bar.c_table_from_phi01(D_max)

    # CoHA generators = n_+ generators = imaginary simple roots
    coha_generators = {}
    total_coha_dim = 0
    for D in sorted(table.keys()):
        c_val = table[D]
        if c_val == 0:
            continue
        mult = abs(c_val)
        total_coha_dim += mult
        parity = 'bosonic' if c_val > 0 else 'fermionic'
        coha_generators[D] = {
            'dim': mult,
            'parity': parity,
            'coha_role': f'BPS states at charge D={D}',
            'yangian_role': f'Current generators e_D^{{(a)}}(u), a=1,...,{mult}',
        }

    return {
        'coha_identification': {
            'statement': 'CoHA(K3xE) = U(n_+(g_{Delta_5}))',
            'status': 'PROVED',
            'reference': 'Gritsenko-Nikulin + Schiffmann-Vasserot framework',
        },
        'coha_is_associative': True,
        'coha_is_chiral': False,  # AP-CY7
        'coha_is_e1_chiral': False,  # AP-CY7: requires G(X) to exist
        'coha_generators': coha_generators,
        'total_coha_dimension': total_coha_dim,
        'yangian_double': {
            'statement': '"Y(g_{Delta_5})" = Drinfeld double of Y^+(g_{Delta_5})',
            'status': 'CONJECTURAL',
            'obstruction': (
                'The Drinfeld double of U(n_+) for a BKM algebra with '
                'infinitely many imaginary simple roots has convergence '
                'issues. No general construction exists.'
            ),
        },
        'c3_comparison': {
            'coha': 'Y^+(gl_hat_1) = SHc+ (PROVED)',
            'yangian': 'Y(gl_hat_1) = W_{1+inf} (PROVED)',
            'double': 'DD(SHc+) = W_{1+inf} (PROVED, Schiffmann-Vasserot)',
            'key_difference': (
                'For C^3, gl_hat_1 is an AFFINE Kac-Moody algebra (no '
                'imaginary simple roots). The Drinfeld double is standard. '
                'For K3 x E, g_{Delta_5} is a BKM algebra with infinitely '
                'many imaginary simple roots. The double is non-standard.'
            ),
        },
        'status': STATUS,
    }


# =========================================================================
# 5. Borcherds-Serre relations (the structural obstruction)
# =========================================================================

def borcherds_serre_relations() -> Dict[str, Any]:
    r"""The Borcherds-Serre relations for g_{Delta_5} and their
    Yangian-deformation status.

    For a STANDARD Kac-Moody algebra with Cartan matrix (a_{ij}):
      Serre relation: (ad e_i)^{1 - a_{ij}} e_j = 0

    For a BKM algebra, the relations are modified:
    (1) Between REAL simple roots: standard Serre relations hold.
    (2) Between a REAL root alpha_i and an IMAGINARY root alpha_j:
        [e_i, e_j] = 0 if (alpha_i, alpha_j) = 0
        (ad e_i)^{1 - a_{ij}} e_j = 0 otherwise
    (3) Between two IMAGINARY simple roots alpha_i, alpha_j:
        [e_i, e_j] = 0 if (alpha_i, alpha_j) = 0
        [e_i, [e_i, e_j]] = 0 if (alpha_i, alpha_i) = 0 (lightlike i)
        No constraint if (alpha_i, alpha_i) < 0 (timelike i)

    The Yangian deformation of these relations:
    (1) Real-real: KNOWN (standard Yangian Serre, Drinfeld 1985)
        [e_i(u), [e_i(v), e_j(w)]] - [e_i(v), [e_i(u), e_j(w)]]
        = hbar^2 * (explicit formula)
    (2) Real-imaginary: partially known (affine Yangian generalizations)
    (3) Imaginary-imaginary: COMPLETELY UNKNOWN for BKM

    The obstruction for (3): the BKM imaginary-imaginary Serre relations
    are trivial ([e_i, e_j] = 0 when inner product vanishes), so the
    Yangian deformation would need to deform the trivial relation into
    a nontrivial one parametrized by the discriminant.
    """
    # Compute real-real inner products
    real_real = {}
    for i in range(NUM_REAL_SIMPLE_ROOTS):
        for j in range(NUM_REAL_SIMPLE_ROOTS):
            if i <= j:
                real_real[(i+1, j+1)] = {
                    'inner_product': GRAM_MATRIX[i][j],
                    'cartan_entry': 2 * GRAM_MATRIX[i][j] // GRAM_MATRIX[i][i],
                    'serre_power': 1 - 2 * GRAM_MATRIX[i][j] // GRAM_MATRIX[i][i] if i != j else None,
                    'yangian_deformation': 'KNOWN (standard Drinfeld Serre)',
                }

    return {
        'real_real_serre': {
            'relations': real_real,
            'status': 'STANDARD (Drinfeld 1985)',
            'yangian_deformation_status': 'KNOWN',
        },
        'real_imaginary_serre': {
            'description': (
                'For real alpha_i and imaginary alpha_j with (alpha_i, alpha_j) != 0: '
                '(ad e_i)^{1 - a_{ij}} e_j = 0. '
                'The Yangian deformation is partially known from affine Yangian '
                'generalizations (Guay 2007, Kodera-Nakajima 2018).'
            ),
            'status': 'PARTIALLY KNOWN',
            'yangian_deformation_status': 'PARTIAL (affine cases)',
        },
        'imaginary_imaginary_serre': {
            'description': (
                'For imaginary alpha_i, alpha_j with (alpha_i, alpha_j) = 0: '
                '[e_i, e_j] = 0. '
                'This is a TRIVIAL relation. The Yangian deformation of a '
                'trivial relation is the fundamental open problem.'
            ),
            'status': 'TRIVIAL (Borcherds)',
            'yangian_deformation_status': 'COMPLETELY UNKNOWN',
            'obstruction': (
                'No construction of a Yangian Y(g) exists for ANY BKM '
                'algebra g with nontrivial imaginary simple roots. '
                'The obstruction is that the Drinfeld presentation '
                'fundamentally relies on finite Cartan matrix data, '
                'while BKM algebras have infinite-dimensional imaginary '
                'root spaces with no Cartan matrix encoding.'
            ),
        },
        'status': STATUS,
    }


# =========================================================================
# 6. The correct framework: what is known, what is conjectural
# =========================================================================

def framework_assessment() -> Dict[str, Any]:
    r"""Assessment of what framework can accommodate conjectural Yangian-deformation generators.

    QUESTION: Can each BKM simple root vector be realized as a Yangian generator?

    ANSWER (structured by what is known):

    (A) Real simple roots -> Yangian generators:
        STATUS: YES (standard).
        The 3 real simple roots give Cartan triples (h_i, e_i, f_i).
        The Yangian presentation is the standard Drinfeld presentation
        with Cartan matrix = Gram matrix of Lambda^{2,1}_{II}.
        This part requires NO new mathematics.

    (B) Imaginary simple root at D = -1 (mult 1) -> Yangian generator:
        STATUS: PLAUSIBLE but UNPROVED.
        A single generator e_W(u) extending the Cartan sector.
        Analogous to the imaginary root extension in affine Yangians.
        The affine Yangian Y(g_hat) has one imaginary generator
        (the center), which generates the loop extension.
        For g_{Delta_5}, the D=-1 root plays an analogous role.

    (C) Imaginary simple roots at D = 0 (mult 10) -> Yangian generators:
        STATUS: CONJECTURAL.
        The 10 lightlike generators have no direct analogue in
        affine or toroidal Yangians.  The closest analogue is the
        quantum toroidal algebra U_{q,t}(gl_hat_hat_1), which has
        TWO central extensions (not 10).

    (D) Imaginary simple roots at D > 0 (mult |c(D)|) -> Yangian generators:
        STATUS: UNKNOWN.
        No framework exists for Yangian generators corresponding to
        spacelike imaginary simple roots of a BKM algebra.
        The CoHA gives the ASSOCIATIVE multiplication, but extracting
        Yangian currents from the CoHA requires the Drinfeld double,
        which has not been constructed for BKM.

    STRUCTURAL CONCLUSION:
        The identification "BKM simple root <-> Yangian generator" is:
        - PROVED for real roots (standard Yangian theory)
        - PLAUSIBLE for the unique D=-1 root (affine analogy)
        - CONJECTURAL for D=0 roots (no analogue exists)
        - UNKNOWN for D>0 roots (fundamental obstruction)

        The CORRECT FRAMEWORK is likely NOT a standard Yangian but
        rather a GENERALIZED Yangian or HALL-ALGEBRA YANGIAN that
        accommodates infinite-dimensional imaginary root spaces.
        This is new mathematics that does not yet exist.
    """
    return {
        'real_roots': {
            'count': NUM_REAL_SIMPLE_ROOTS,
            'yangian_realization': 'STANDARD Cartan triples (h, e, f)',
            'status': 'PROVED (standard Yangian theory)',
            'new_math_required': False,
        },
        'd_minus1': {
            'count': KNOWN_MULTIPLICITIES[-1],
            'yangian_realization': 'Single current e_W(u) (Weyl vector)',
            'status': 'PLAUSIBLE (affine Yangian analogy)',
            'new_math_required': False,
            'analogy': 'Affine Yangian Y(g_hat) has imaginary root extension',
        },
        'd_zero': {
            'count': KNOWN_MULTIPLICITIES[0],
            'yangian_realization': '10 lightlike currents (conjectural)',
            'status': 'CONJECTURAL',
            'new_math_required': True,
            'closest_analogue': (
                'Quantum toroidal U_{q,t}(gl_hat_hat_1) has 2 central extensions '
                '(not 10). The 10 lightlike generators of g_{Delta_5} have no '
                'direct counterpart in known quantum group theory.'
            ),
        },
        'd_positive': {
            'count': 'infinite (sum |c(D)| over D > 0)',
            'yangian_realization': 'UNKNOWN',
            'status': 'UNKNOWN (fundamental obstruction)',
            'new_math_required': True,
            'obstruction': (
                'No Drinfeld presentation for Yangians of BKM algebras '
                'with spacelike imaginary simple roots. The CoHA provides '
                'the associative structure (AP-CY7) but not the Yangian '
                'currents. The Drinfeld double of the CoHA has not been '
                'constructed for any BKM algebra.'
            ),
        },
        'verdict': (
            'Real simple roots are standard Yangian generators. '
            'The unique D=-1 imaginary root is analogous to affine extensions. '
            'The D=0 and D>0 imaginary roots require NEW MATHEMATICS: '
            'a generalized Yangian presentation for BKM algebras that '
            'accommodates infinite-dimensional imaginary root spaces. '
            'This is one of the five load-bearing open problems.'
        ),
        'status': STATUS,
    }


# =========================================================================
# 7. Comprehensive summary
# =========================================================================

def bkm_yangian_summary(D_max: int = 20) -> Dict[str, Any]:
    r"""Comprehensive summary of the BKM-to-Yangian generator identification.

    Combines all results from this module into a single assessment.
    """
    real_roots_data = real_simple_roots()
    census = generator_census(D_max)
    coha_dict = coha_to_yangian_dictionary(D_max)
    serre = borcherds_serre_relations()
    framework = framework_assessment()

    return {
        'title': 'BKM simple roots of g_{Delta_5} as Yangian generators',
        'real_simple_roots': {
            'count': len(real_roots_data),
            'gram_matrix': GRAM_MATRIX,
            'determinant': cartan_matrix_determinant(),
            'yangian_status': 'STANDARD (Cartan triples)',
        },
        'imaginary_simple_roots': {
            'D_minus1': {
                'multiplicity': KNOWN_MULTIPLICITIES[-1],
                'status': framework['d_minus1']['status'],
            },
            'D_zero': {
                'multiplicity': KNOWN_MULTIPLICITIES[0],
                'kappa_BKM': KNOWN_MULTIPLICITIES[0] // 2,
                'status': framework['d_zero']['status'],
            },
            'D_positive_summary': {
                'first_fermionic': (3, KNOWN_MULTIPLICITIES[3]),
                'first_bosonic': (4, KNOWN_MULTIPLICITIES[4]),
                'status': framework['d_positive']['status'],
            },
        },
        'generator_census': {
            'real': census['real_simple_roots'],
            'imaginary_total': census['imaginary_generators']['total'],
            'grand_total': census['grand_total'],
        },
        'coha_status': {
            'identification': coha_dict['coha_identification']['status'],
            'is_associative': True,
            'is_chiral': False,
        },
        'serre_relations': {
            'real_real': serre['real_real_serre']['yangian_deformation_status'],
            'real_imaginary': serre['real_imaginary_serre']['yangian_deformation_status'],
            'imaginary_imaginary': serre['imaginary_imaginary_serre']['yangian_deformation_status'],
        },
        'framework_verdict': framework['verdict'],
        'status': STATUS,
    }
