r"""BKM deformed Serre relations from the Borcherds deformed OPE.

STATUS: CONJECTURAL (AP-CY14). The Yangian deformation of BKM vertex
operators has not been constructed rigorously. This module derives the
CONCRETE form of the Serre relations from the deformed OPE, making
the spectral flow approach explicit at each discriminant level.

MATHEMATICAL CONTENT
====================

The spectral flow h_eps = (D+1) - D*eps -> 1 at eps=1 makes all
imaginary root vertex operators weight-1 Yangian currents. The Serre
relations come from the deformed OPE structure at eps=1.

1. DEFORMED OPE FORMULA.

   For two vertex operators V_eps(alpha, z) and V_eps(beta, w) on the
   lattice VOA V_{II_{2,1}}, the deformed OPE is:

       V_eps(alpha, z) V_eps(beta, w) = (z-w)^{P(alpha,beta,eps)}
           * :V_eps(alpha+beta, w): * (1 + corrections)

   where the DEFORMED OPE EXPONENT is:

       P(alpha, beta, eps) = (alpha, beta)
           + eps * [(alpha,alpha)(beta,beta)/4 + (alpha,beta)]
           + O(eps^2)

   and corrections involve derivatives of phi(z) (descendant fields).

   At eps=1 (formal Yangian limit):
       P(alpha, beta, 1) = (alpha, beta)
           + (alpha,alpha)(beta,beta)/4 + (alpha,beta)
       = 2*(alpha,beta) + (alpha,alpha)(beta,beta)/4

   SELF-OPE (alpha = beta at discriminant D, so (alpha,alpha) = -2D):
       P_self(D, eps) = -2D + eps*(D^2 - 2D)
       P_self(D, 1) = -2D + D^2 - 2D = D^2 - 4D = D(D-4)

   CROSS-OPE (alpha at D1, beta at D2, generic (alpha,beta) = 0):
       P_cross(D1, D2, eps) = 0 + eps * D1*D2
       P_cross(D1, D2, 1) = D1*D2

2. SERRE RELATIONS BY DISCRIMINANT.

   The Serre relation at discriminants (D1, D2) is determined by the
   pole structure of the deformed OPE at eps=1:

   (a) If P(D1, D2, 1) >= 0: the OPE is REGULAR, and the Yangian
       bracket VANISHES: [e_{D1}(u), e_{D2}(v)] = 0.
       This is the deformed Borcherds-Serre relation.

   (b) If P(D1, D2, 1) < 0: the OPE has a pole of order |P|, and the
       Yangian bracket is NONTRIVIAL with |P| independent terms:
       [e_{D1}(u), e_{D2}(v)] = sum_{k=1}^{|P|} c_k (u-v)^{-k} * (...)

   The Serre IDEAL is generated by relations of type (a) and the
   closure conditions from type (b).

3. DISCRIMINANT-BY-DISCRIMINANT ANALYSIS.

   D = -1 (Weyl vector, mult 1, bosonic):
       Self-OPE exponent: P(-1, 1) = (-1)((-1)-4) = (-1)(-5) = 5
       REGULAR: (z-w)^5 has no pole.
       Serre: the single Weyl vector current is FREE (no self-relation).
       [e_W(u), e_W(v)] = 0 (trivially).

   D = 0 (lightlike, mult 10, bosonic):
       Self-OPE exponent: P(0, 1) = 0*(0-4) = 0
       MARGINAL: (z-w)^0 = 1, no pole but no zero either.
       This is the LOGARITHMIC case: the OPE produces a logarithmic
       singularity from the descendant corrections at O(eps^2).
       The 10 lightlike currents have NONTRIVIAL but WEAK interactions.
       Undeformed Borcherds-Serre: [e_alpha, e_beta] = 0 for
       (alpha,beta) = 0 (orthogonal lightlike roots).
       Deformation: the O(eps^2) correction can BREAK this commutativity.
       Cross-OPE between different D=0 roots: the inner product
       (alpha_a, alpha_b) depends on the specific pair within II_{2,1}.
       For primitive isotropic vectors: (alpha_a, alpha_b) can be
       0, 1, or -1 depending on the pair.

   D = 3 (first spacelike fermionic, mult 64):
       Self-OPE exponent: P(3, 1) = 3*(3-4) = 3*(-1) = -3
       POLE of order 3: the self-OPE has a TRIPLE POLE.
       Serre: nontrivial self-relation with 3 independent terms.
       [e_3^{(a)}(u), e_3^{(b)}(v)] = c_1 * (u-v)^{-1} * (...)
           + c_2 * (u-v)^{-2} * (...) + c_3 * (u-v)^{-3} * (...)
       The (u-v)^{-1} term gives the Lie bracket (current algebra).
       The (u-v)^{-2} and (u-v)^{-3} terms give Serre constraints.
       FERMIONIC: the 64 generators anticommute, so the self-OPE
       involves anticommutators {e_3^{(a)}, e_3^{(b)}}.

   D = 4 (first spacelike bosonic, mult 108):
       Self-OPE exponent: P(4, 1) = 4*(4-4) = 0
       MARGINAL: same as D=0 case. Logarithmic.
       108 bosonic generators with marginal self-interaction.

   D = 7 (fermionic, mult 513):
       Self-OPE exponent: P(7, 1) = 7*(7-4) = 7*3 = 21
       REGULAR: (z-w)^{21} has no pole.
       Serre: the 513 fermionic generators are FREE at leading order.
       [{e_7^{(a)}(u), e_7^{(b)}(v)}] = 0 (leading order).

   D = 8 (bosonic, mult 808):
       Self-OPE exponent: P(8, 1) = 8*(8-4) = 32
       REGULAR: (z-w)^{32} is very regular.
       Serre: the 808 bosonic generators are FREE at leading order.

4. CROSS-DISCRIMINANT SERRE.

   Cross-OPE exponent: P_cross(D1, D2, 1) = D1*D2 (for generic
   orthogonal roots between different discriminant sectors).

   D1=D2=0: P = 0 (marginal)
   D1=-1, D2=0: P = 0 (marginal)
   D1=-1, D2=3: P = -3 (pole of order 3)
   D1=0, D2=3: P = 0 (marginal)
   D1=0, D2=4: P = 0 (marginal)
   D1=3, D2=3: P = 9 (self-OPE: regular -- wait, this is CROSS between
       different roots at same D=3, vs self-OPE which uses P_self)
   D1=3, D2=4: P = 12 (regular)
   D1=3, D2=7: P = 21 (regular)
   D1=4, D2=7: P = 28 (regular)

   CRITICAL: the cross-discriminant Serre is MOSTLY TRIVIAL for D1, D2 > 0.
   The nontrivial cross-Serre is concentrated in the LOW-DISCRIMINANT sector
   (D = -1, 0, 3, 4). This is the "infrared" of the BKM algebra.

5. IMAGINARY-REAL MIXING (ADJOINT ACTION).

   For a real simple root delta_i (Cartan generator h_i(z)) and an
   imaginary root alpha at discriminant D:

       h_i(z) V_eps(alpha, w) ~ (delta_i, alpha) / (z-w) * V_eps(alpha, w)

   This is the ADJOINT ACTION: h_i acts on V_eps(alpha) by the
   inner product (delta_i, alpha). The deformation does NOT change
   this at leading order: the Cartan-imaginary OPE has a simple pole
   whose residue is the root eigenvalue.

   In mode form: [h_{i,0}, e_D^{(a)}_n] = (delta_i, alpha_a) * e_D^{(a)}_n
   This is the standard Lie algebra adjoint action, PRESERVED by the
   Omega deformation.

6. FINITENESS OF THE SERRE IDEAL.

   The Serre ideal of the conjectural Yangian deformation of the BKM algebra is INFINITELY GENERATED
   but FINITELY DETERMINED, in the following sense:

   (a) INFINITELY GENERATED: at each discriminant D with c(D) != 0,
       there are new generators and hence new potential Serre relations.
       Since D ranges over all valid discriminants (D = 0, 3, 4, 7, 8, ...
       growing without bound), the total number of Serre relations is
       infinite.

   (b) FINITELY DETERMINED: the self-OPE exponent P_self(D, 1) = D(D-4)
       is POSITIVE for D >= 5 (and D < 0). This means the self-Serre
       relation is TRIVIAL for D >= 5. The nontrivial self-Serre is
       concentrated in D in {0, 3, 4}.

       Similarly, the cross-OPE exponent P_cross(D1, D2, 1) = D1*D2
       is positive whenever D1, D2 > 0, so cross-Serre between
       two spacelike sectors is generically trivial.

   The SERRE KERNEL: the nontrivial Serre relations come from:
   - D = 0 self-OPE (10 generators, marginal)
   - D = 3 self-OPE (64 generators, triple pole)
   - D = 4 self-OPE (108 generators, marginal)
   - D = -1 to D = 3 cross-OPE (Weyl-to-spacelike, pole of order 3)
   - D = 0 to D = 0 cross-OPE (lightlike-lightlike, marginal)

   This finite set of "low-energy" Serre relations, together with
   the trivial high-energy Serre (commuting for D >= 5), determines
   the full Serre ideal.

   STRUCTURAL RESULT: The conjectural Yangian-deformation Serre ideal has a FINITE
   SERRE KERNEL (the nontrivial low-D relations) and an INFINITE
   TAIL of trivial relations (commuting generators for D >= 5).
   The Serre kernel is determined by 182 generators across D in {0, 3, 4}
   (10 + 64 + 108 = 182).

7. COMPARISON WITH STANDARD BORCHERDS-SERRE.

   The standard BKM Serre relation for imaginary roots is:
       [e_alpha, e_beta] = 0  when (alpha, beta) = 0

   The deformation PRESERVES this for D1*D2 > 0 with generic
   orthogonal roots: the deformed OPE exponent D1*D2 > 0 gives a
   regular OPE, so the deformed bracket still vanishes.

   The deformation BREAKS the commutativity when:
   - P_self(D, 1) < 0, i.e., 0 < D < 4, i.e., D = 3 only.
   - P_cross(D1, D2, 1) < 0: impossible for D1, D2 > 0.
   - P involves specific non-generic inner products (alpha, beta) != 0.

   So the ONLY discriminant at which the standard Borcherds-Serre
   commutativity is genuinely broken by the deformation is D = 3
   (the first fermionic level). This is a REMARKABLE structural result:
   the deformation concentrates all nontrivial Serre structure at the
   lowest spacelike level.

AP COMPLIANCE
=============

AP-CY7:   Vertex algebra methods, not CoHA. The Serre relations come
           from the OPE of vertex operators on V_{II_{2,1}}.
AP-CY14:  ALL results are CONJECTURAL. The deformation has not been
           constructed rigorously.
AP-CY20:  Omega-background intermediary stated explicitly.
AP-CY8:   Bar Euler = BKM denominator requires CY-A + Vol I anchor.
AP113:    kappa subscripts: kappa_BKM = 5, never bare kappa.
AP-CY31:  Spectral parameter u is Yangian spectral, NOT worldsheet.
AP-CY24:  All numerical values verified against function output.
AP-CY9:   Discriminant constraint: D = 0 or 3 mod 4 for index 1.
           D = 1 is NOT a valid discriminant (1 mod 4). c(1) = 0.

Manuscript references:
    Chapter: k3_times_e.tex (ch:k3-times-e)
    Section: subsec:k3e-deformed-serre
    Serre obstruction: rem:borcherds-serre-obstruction
    Yangian currents: subsubsec:k3e-yangian-currents-serre
    Borcherds vertex approach: borcherds_vertex_yangian.py

References
----------
    Borcherds, "Generalized Kac-Moody algebras" (1988)
    Borcherds, "Monstrous moonshine and monstrous Lie superalgebras" (1992)
    Gritsenko-Nikulin, "Automorphic forms and Lorentzian KM algebras II" (1998)
    Drinfeld, "Quantum groups" (1985)
    Nekrasov, "Seiberg-Witten prepotential from instanton counting" (2002)
"""

from __future__ import annotations

import math
from collections import defaultdict
from fractions import Fraction
from typing import Any, Dict, List, NamedTuple, Optional, Tuple


# ---------------------------------------------------------------------------
# Import helpers
# ---------------------------------------------------------------------------

def _import_bkm_bar():
    """Import k3_elliptic_genus_bkm_bar from the same directory."""
    try:
        from compute.lib import k3_elliptic_genus_bkm_bar
        return k3_elliptic_genus_bkm_bar
    except (ImportError, ModuleNotFoundError):
        import importlib, os, sys
        _lib_dir = os.path.dirname(os.path.abspath(__file__))
        if _lib_dir not in sys.path:
            sys.path.insert(0, _lib_dir)
        return importlib.import_module('k3_elliptic_genus_bkm_bar')


def _import_borcherds_vertex():
    """Import borcherds_vertex_yangian from the same directory."""
    try:
        from compute.lib import borcherds_vertex_yangian
        return borcherds_vertex_yangian
    except (ImportError, ModuleNotFoundError):
        import importlib, os, sys
        _lib_dir = os.path.dirname(os.path.abspath(__file__))
        if _lib_dir not in sys.path:
            sys.path.insert(0, _lib_dir)
        return importlib.import_module('borcherds_vertex_yangian')


def _import_bkm_yangian():
    """Import bkm_yangian_generators from the same directory."""
    try:
        from compute.lib import bkm_yangian_generators
        return bkm_yangian_generators
    except (ImportError, ModuleNotFoundError):
        import importlib, os, sys
        _lib_dir = os.path.dirname(os.path.abspath(__file__))
        if _lib_dir not in sys.path:
            sys.path.insert(0, _lib_dir)
        return importlib.import_module('bkm_yangian_generators')


# =========================================================================
# 0. Constants
# =========================================================================

STATUS = 'CONJECTURAL'  # AP-CY14

# Gram matrix of II_{2,1}
GRAM_MATRIX = ((2, -2, -2), (-2, 2, -2), (-2, -2, 2))

# Known c(D) values (VERIFIED against phi01_fourier.py and
# k3_elliptic_genus_bkm_bar.py, cross-checked with bkm_yangian_generators.py)
KNOWN_C_TABLE = {
    -1: 1,        # D=-1: polar, bosonic, Weyl vector
    0: 10,        # D=0: lightlike, kappa_BKM = c(0)/2 = 5
    3: -64,       # D=3: first fermionic
    4: 108,       # D=4: first spacelike bosonic
    7: -513,      # D=7: fermionic
    8: 808,       # D=8: bosonic
    11: -2752,    # D=11: fermionic
    12: 4016,     # D=12: bosonic
    15: -11775,   # D=15: fermionic
    16: 16524,    # D=16: bosonic
}

# Valid discriminants satisfy D = 0 or 3 mod 4 (AP-CY9, index 1 constraint)
VALID_DISCRIMINANT_RESIDUES = {0, 3}

# The Serre-critical discriminants: those where P_self(D, 1) <= 0
# P_self(D, 1) = D*(D-4): negative for 0 < D < 4, zero for D in {0, 4}
SERRE_CRITICAL_D = {0, 3, 4}

# The Serre kernel generator count: sum of |c(D)| for D in SERRE_CRITICAL_D
# 10 + 64 + 108 = 182
SERRE_KERNEL_SIZE = sum(abs(KNOWN_C_TABLE[D]) for D in SERRE_CRITICAL_D)


# =========================================================================
# 1. Deformed OPE exponent
# =========================================================================

def deformed_ope_exponent_self(D: int, epsilon: float = 1.0) -> float:
    r"""Compute the deformed self-OPE exponent P_self(D, eps).

    For a vertex operator V_eps(alpha, z) with alpha at discriminant D
    (meaning (alpha, alpha) = -2D in the BKM convention):

        V_eps(alpha, z) V_eps(alpha, w) ~ (z-w)^{P_self(D, eps)} * (...)

    Undeformed (eps=0):
        P_self(D, 0) = (alpha, alpha) = -2D

    Omega-deformed at leading order:
        P_self(D, eps) = -2D + eps * (D^2 - 2D)

    At eps=1 (formal Yangian limit):
        P_self(D, 1) = -2D + D^2 - 2D = D^2 - 4D = D*(D-4)

    The OPE is:
        REGULAR (no pole) when P_self >= 0: D <= 0 or D >= 4 (at eps=1)
        SINGULAR (pole) when P_self < 0: 0 < D < 4 (at eps=1)
        MARGINAL when P_self = 0: D = 0 or D = 4 (at eps=1)

    For the valid discriminants (AP-CY9: D = 0 or 3 mod 4):
        D = -1: P = (-1)(-5) = 5 (regular)
        D = 0:  P = 0*(-4) = 0 (marginal)
        D = 3:  P = 3*(-1) = -3 (POLE of order 3)
        D = 4:  P = 4*0 = 0 (marginal)
        D = 7:  P = 7*3 = 21 (regular)
        D = 8:  P = 8*4 = 32 (regular)

    Parameters
    ----------
    D : int
        Discriminant of the root.
    epsilon : float
        Deformation parameter (default 1.0 for Yangian limit).

    Returns
    -------
    float
        The deformed self-OPE exponent.

    Examples
    --------
    >>> deformed_ope_exponent_self(-1, 1.0)
    5.0
    >>> deformed_ope_exponent_self(0, 1.0)
    0.0
    >>> deformed_ope_exponent_self(3, 1.0)
    -3.0
    >>> deformed_ope_exponent_self(4, 1.0)
    0.0
    """
    undeformed = -2 * D
    correction = D * D - 2 * D
    return float(undeformed + epsilon * correction)


def deformed_ope_exponent_cross(D1: int, D2: int, epsilon: float = 1.0,
                                inner_product: int = 0) -> float:
    r"""Compute the deformed cross-OPE exponent P_cross(D1, D2, eps).

    For vertex operators V_eps(alpha, z) and V_eps(beta, w) with alpha
    at discriminant D1 and beta at discriminant D2:

        V_eps(alpha, z) V_eps(beta, w) ~ (z-w)^{P_cross} * (...)

    where:
        P_cross(D1, D2, eps) = (alpha, beta)
            + eps * [(alpha,alpha)(beta,beta)/4 + (alpha,beta)]

    For generic (orthogonal) roots: (alpha, beta) = 0, so:
        P_cross(D1, D2, eps) = eps * (-2*D1)*(-2*D2)/4
            = eps * D1 * D2

    For non-generic roots: (alpha, beta) = inner_product != 0, so:
        P_cross = inner_product + eps * (D1*D2 + inner_product)
        = inner_product * (1 + eps) + eps * D1 * D2

    At eps=1:
        P_cross(D1, D2, 1) = 2*inner_product + D1*D2

    Parameters
    ----------
    D1, D2 : int
        Discriminants of the two roots.
    epsilon : float
        Deformation parameter.
    inner_product : int
        The lattice inner product (alpha, beta). Default 0 (generic case).

    Returns
    -------
    float
        The deformed cross-OPE exponent.

    Examples
    --------
    >>> deformed_ope_exponent_cross(3, 4, 1.0)
    12.0
    >>> deformed_ope_exponent_cross(0, 3, 1.0)
    0.0
    >>> deformed_ope_exponent_cross(-1, 3, 1.0)
    -3.0
    """
    return float(inner_product * (1.0 + epsilon) + epsilon * D1 * D2)


# =========================================================================
# 2. OPE singularity classification
# =========================================================================

class OPESingularity(NamedTuple):
    """Classification of the OPE singularity at a given (D1, D2, eps).

    The singularity type determines the Serre relation:
    - 'regular': P > 0, Serre bracket vanishes, generators commute.
    - 'marginal': P = 0, logarithmic correction possible, requires O(eps^2).
    - 'pole': P < 0, nontrivial bracket with |P| independent terms.
    """
    D1: int
    D2: int
    ope_type: str                  # 'self' or 'cross'
    exponent: float                # P(D1, D2, eps)
    singularity_type: str          # 'regular', 'marginal', 'pole'
    pole_order: int                # max(0, -floor(P)) -- number of singular terms
    serre_type: str                # description of the Serre relation
    inner_product: int             # (alpha, beta) used


def classify_ope_singularity(D1: int, D2: int, epsilon: float = 1.0,
                             inner_product: Optional[int] = None
                             ) -> OPESingularity:
    r"""Classify the OPE singularity between roots at discriminants D1, D2.

    This determines the Serre relation type:
    - Regular (P > 0): trivial Serre (generators commute)
    - Marginal (P = 0): logarithmic, requires higher-order analysis
    - Pole (P < 0): nontrivial Serre with |P| independent constraints

    Parameters
    ----------
    D1, D2 : int
        Discriminants.
    epsilon : float
        Deformation parameter.
    inner_product : int or None
        Override lattice inner product. If None, uses 0 for cross-OPE
        and the self-OPE formula for D1 == D2.

    Returns
    -------
    OPESingularity
    """
    if D1 == D2 and inner_product is None:
        # Self-OPE
        P = deformed_ope_exponent_self(D1, epsilon)
        ip = -2 * D1  # (alpha, alpha) = -2D
        ope_type = 'self'
    else:
        # Cross-OPE
        ip = inner_product if inner_product is not None else 0
        P = deformed_ope_exponent_cross(D1, D2, epsilon, ip)
        ope_type = 'cross' if D1 != D2 else 'cross-within-sector'

    # Classify
    if P > 1e-10:
        sing_type = 'regular'
        pole_ord = 0
        serre = (
            f'Trivial Serre: bracket vanishes at leading order. '
            f'P = {P:.1f} > 0 gives (z-w)^{{{P:.0f}}} with no pole.'
        )
    elif abs(P) < 1e-10:
        sing_type = 'marginal'
        pole_ord = 0
        serre = (
            f'Marginal Serre: P = 0 gives (z-w)^0 = 1. '
            f'Logarithmic correction possible at O(eps^2). '
            f'The bracket is INDETERMINATE at leading order.'
        )
    else:
        sing_type = 'pole'
        pole_ord = int(math.ceil(-P - 1e-10))
        serre = (
            f'Nontrivial Serre: P = {P:.1f} gives a pole of order {pole_ord}. '
            f'The bracket has {pole_ord} independent term{"s" if pole_ord > 1 else ""}. '
        )
        if pole_ord == 1:
            serre += 'Simple pole: standard current algebra bracket.'
        elif pole_ord == 2:
            serre += 'Double pole: bracket + Schwinger term.'
        elif pole_ord >= 3:
            serre += (
                f'Higher pole: bracket + {pole_ord - 1} Serre constraints '
                f'from (z-w)^{{-2}}, ..., (z-w)^{{-{pole_ord}}}.'
            )

    return OPESingularity(
        D1=D1, D2=D2, ope_type=ope_type,
        exponent=P, singularity_type=sing_type,
        pole_order=pole_ord, serre_type=serre,
        inner_product=ip,
    )


# =========================================================================
# 3. Discriminant-by-discriminant Serre analysis
# =========================================================================

def serre_at_discriminant(D: int, epsilon: float = 1.0) -> Dict[str, Any]:
    r"""Complete Serre analysis at a given discriminant D.

    Computes the self-OPE exponent, classifies the singularity, and
    determines the Serre relation type for the |c(D)| generators at
    discriminant D.

    Parameters
    ----------
    D : int
        Discriminant.
    epsilon : float
        Deformation parameter.

    Returns
    -------
    dict with keys:
        discriminant, c_value, multiplicity, parity, self_ope_exponent,
        singularity, serre_type, generator_status, status.
    """
    bkm_bar = _import_bkm_bar()
    table = bkm_bar.c_table_from_phi01(max(D + 10, 30))

    c_val = table.get(D, 0)
    if c_val == 0:
        return {
            'discriminant': D,
            'c_value': 0,
            'multiplicity': 0,
            'has_generators': False,
            'note': (
                f'No simple roots at D={D} (c(D)=0). '
                f'D mod 4 = {D % 4}. '
                f'Valid discriminants require D mod 4 in {{0, 3}} (AP-CY9).'
            ),
            'status': STATUS,
        }

    mult = abs(c_val)
    parity = 'bosonic' if c_val > 0 else 'fermionic'

    # Self-OPE exponent
    P_self = deformed_ope_exponent_self(D, epsilon)

    # Classification
    sing = classify_ope_singularity(D, D, epsilon)

    # Generator interaction status
    if sing.singularity_type == 'regular':
        gen_status = (
            f'{mult} {parity} generators are FREE at leading order '
            f'(trivial self-Serre, P = {P_self:.0f} > 0). '
            f'No constraints from the self-OPE.'
        )
    elif sing.singularity_type == 'marginal':
        gen_status = (
            f'{mult} {parity} generators have MARGINAL self-interaction '
            f'(P = 0). Logarithmic correction determines whether the '
            f'generators commute or have weak interactions. '
            f'Requires O(eps^2) analysis.'
        )
    else:  # pole
        gen_status = (
            f'{mult} {parity} generators have NONTRIVIAL self-Serre '
            f'with pole of order {sing.pole_order}. '
            f'The self-OPE produces {sing.pole_order} independent '
            f'Serre constraint{"s" if sing.pole_order > 1 else ""}.'
        )

    return {
        'discriminant': D,
        'c_value': c_val,
        'multiplicity': mult,
        'parity': parity,
        'has_generators': True,
        'self_ope_exponent': P_self,
        'self_ope_exponent_formula': f'D*(D-4) = {D}*({D}-4) = {D*(D-4)}',
        'singularity': sing._asdict(),
        'serre_type': sing.serre_type,
        'generator_status': gen_status,
        'status': STATUS,
    }


def serre_census(D_max: int = 20, epsilon: float = 1.0) -> Dict[str, Any]:
    r"""Census of all Serre relations up to discriminant D_max.

    Classifies every discriminant sector into:
    - regular (free generators, trivial Serre)
    - marginal (indeterminate, logarithmic)
    - pole (nontrivial Serre, constrained generators)

    At eps=1 with the formula P_self(D, 1) = D*(D-4):
    - D = -1: P = 5, regular
    - D = 0: P = 0, marginal
    - D = 3: P = -3, pole of order 3 (UNIQUE nontrivial self-Serre)
    - D = 4: P = 0, marginal
    - D >= 7: P >= 21, regular (all free)

    Parameters
    ----------
    D_max : int
        Maximum discriminant to survey.
    epsilon : float
        Deformation parameter.

    Returns
    -------
    dict with classification census.
    """
    bkm_bar = _import_bkm_bar()
    table = bkm_bar.c_table_from_phi01(D_max)

    regular = []
    marginal = []
    pole = []

    for D in sorted(table.keys()):
        c_val = table[D]
        if c_val == 0:
            continue

        P_self = deformed_ope_exponent_self(D, epsilon)
        sing = classify_ope_singularity(D, D, epsilon)

        entry = {
            'discriminant': D,
            'c_value': c_val,
            'multiplicity': abs(c_val),
            'parity': 'bosonic' if c_val > 0 else 'fermionic',
            'self_ope_exponent': P_self,
            'singularity_type': sing.singularity_type,
            'pole_order': sing.pole_order,
        }

        if sing.singularity_type == 'regular':
            regular.append(entry)
        elif sing.singularity_type == 'marginal':
            marginal.append(entry)
        else:
            pole.append(entry)

    # Summary counts
    total_generators = sum(abs(table[D]) for D in table if table[D] != 0)
    regular_generators = sum(e['multiplicity'] for e in regular)
    marginal_generators = sum(e['multiplicity'] for e in marginal)
    pole_generators = sum(e['multiplicity'] for e in pole)

    return {
        'D_max': D_max,
        'epsilon': epsilon,
        'total_sectors': len(regular) + len(marginal) + len(pole),
        'total_generators': total_generators,
        'regular': {
            'count': len(regular),
            'generators': regular_generators,
            'sectors': regular,
            'description': (
                'Free generators: self-OPE is regular (P > 0), '
                'Serre bracket vanishes at leading order.'
            ),
        },
        'marginal': {
            'count': len(marginal),
            'generators': marginal_generators,
            'sectors': marginal,
            'description': (
                'Marginal generators: self-OPE exponent P = 0. '
                'Logarithmic correction possible. Requires O(eps^2) analysis.'
            ),
        },
        'pole': {
            'count': len(pole),
            'generators': pole_generators,
            'sectors': pole,
            'description': (
                'Constrained generators: self-OPE has pole(s), '
                'giving nontrivial Serre relation(s).'
            ),
        },
        'serre_kernel': {
            'discriminants': sorted({e['discriminant'] for e in marginal + pole}),
            'total_generators': marginal_generators + pole_generators,
            'description': (
                'The Serre kernel: discriminants with nontrivial or marginal '
                'self-Serre. All other discriminants have trivial (free) Serre. '
                'The full Serre ideal is determined by this finite kernel.'
            ),
        },
        'structural_result': (
            f'At eps=1, the self-OPE exponent P(D) = D*(D-4) is: '
            f'negative ONLY for D = 3 (P = -3), zero for D in {{0, 4}}, '
            f'positive for all other valid discriminants. '
            f'The Serre kernel has {marginal_generators + pole_generators} '
            f'generators across D in {{0, 3, 4}} = '
            f'10 + 64 + 108 = 182 generators. '
            f'All {regular_generators} generators at D >= 7 (and D = -1) '
            f'are FREE.'
        ),
        'status': STATUS,
    }


# =========================================================================
# 4. Cross-discriminant Serre table
# =========================================================================

def cross_serre_table(D_list: Optional[List[int]] = None,
                      epsilon: float = 1.0) -> Dict[str, Any]:
    r"""Compute the cross-discriminant Serre table.

    For each pair (D1, D2) with D1 <= D2, computes the cross-OPE
    exponent and classifies the Serre relation.

    At eps=1 with generic orthogonal roots:
        P_cross(D1, D2, 1) = D1 * D2

    This is:
    - Positive for D1, D2 > 0 (trivial cross-Serre)
    - Zero if D1 = 0 or D2 = 0 (marginal)
    - Negative if D1 < 0 and D2 > 0, i.e., D1 = -1 (Weyl) and D2 > 0

    Parameters
    ----------
    D_list : list of int or None
        Discriminants to include. Default: [-1, 0, 3, 4, 7, 8].
    epsilon : float
        Deformation parameter.

    Returns
    -------
    dict with cross-Serre table.
    """
    if D_list is None:
        D_list = [-1, 0, 3, 4, 7, 8]

    entries = []
    nontrivial = []

    for i, D1 in enumerate(D_list):
        for D2 in D_list[i:]:  # D2 >= D1
            if D1 == D2:
                # Self-OPE handled separately
                continue

            P = deformed_ope_exponent_cross(D1, D2, epsilon)
            sing = classify_ope_singularity(D1, D2, epsilon, inner_product=0)

            entry = {
                'D1': D1,
                'D2': D2,
                'cross_ope_exponent': P,
                'formula': f'D1*D2 = {D1}*{D2} = {D1*D2}',
                'singularity_type': sing.singularity_type,
                'pole_order': sing.pole_order,
            }
            entries.append(entry)

            if sing.singularity_type != 'regular':
                nontrivial.append(entry)

    return {
        'D_list': D_list,
        'epsilon': epsilon,
        'total_pairs': len(entries),
        'entries': entries,
        'nontrivial': nontrivial,
        'nontrivial_count': len(nontrivial),
        'structural_result': (
            f'Cross-Serre with generic orthogonal roots: '
            f'P_cross(D1, D2) = D1*D2. Nontrivial when D1*D2 <= 0. '
            f'For D_list = {D_list}: {len(nontrivial)} nontrivial pairs '
            f'(involving D = -1 or D = 0).'
        ),
        'status': STATUS,
    }


# =========================================================================
# 5. Imaginary-real mixing (adjoint action)
# =========================================================================

def imaginary_real_mixing(D: int) -> Dict[str, Any]:
    r"""Compute the imaginary-real mixing OPE (adjoint action).

    For a real simple root delta_i (Cartan generator h_i(z)) and an
    imaginary root alpha at discriminant D:

        h_i(z) V_eps(alpha, w) ~ (delta_i, alpha) / (z - w) * V_eps(alpha, w)

    This is the ADJOINT ACTION: h_i acts on V_eps(alpha) by the inner
    product (delta_i, alpha). The Omega deformation PRESERVES this at
    leading order.

    In mode form:
        [h_{i,0}, e_D^{(a)}_n] = (delta_i, alpha_a) * e_D^{(a)}_n

    The deformation does NOT break the Cartan-imaginary commutation
    relation, because the spectral flow shifts conformal weights but
    does not change the Cartan eigenvalues (root labels).

    For II_{2,1} with Gram matrix A = ((2,-2,-2),(-2,2,-2),(-2,-2,2)):
    the inner product (delta_i, alpha) depends on the specific imaginary
    root alpha. For a root alpha = (n, l, m) in the lattice II_{2,1}
    (using the standard Siegel upper half-plane coordinates):

        (delta_1, alpha) = 2n - 2l - 2m
        (delta_2, alpha) = -2n + 2l - 2m
        (delta_3, alpha) = -2n - 2l + 2m

    The root eigenvalues are INTEGERS (lattice inner products), so
    the Cartan action is always well-defined.

    Parameters
    ----------
    D : int
        Discriminant of the imaginary root sector.

    Returns
    -------
    dict with adjoint action data.
    """
    bkm_bar = _import_bkm_bar()
    table = bkm_bar.c_table_from_phi01(max(D + 10, 30))
    c_val = table.get(D, 0)

    if c_val == 0:
        return {
            'discriminant': D,
            'has_mixing': False,
            'note': f'No imaginary generators at D={D}.',
            'status': STATUS,
        }

    mult = abs(c_val)
    parity = 'bosonic' if c_val > 0 else 'fermionic'

    return {
        'discriminant': D,
        'c_value': c_val,
        'multiplicity': mult,
        'parity': parity,
        'has_mixing': True,
        'ope_formula': (
            'h_i(z) V_eps(alpha, w) ~ (delta_i, alpha) / (z - w) * V_eps(alpha, w)'
        ),
        'mode_commutator': (
            '[h_{i,0}, e_D^{(a)}_n] = (delta_i, alpha_a) * e_D^{(a)}_n'
        ),
        'cartan_eigenvalue_type': 'integer (lattice inner product)',
        'deformation_stability': (
            'The Cartan-imaginary OPE is PRESERVED by the Omega deformation '
            'at leading order. The spectral flow shifts conformal weights '
            'but does not change root eigenvalues.'
        ),
        'adjoint_decomposition': (
            f'The {mult}-dimensional imaginary root space at D={D} '
            f'decomposes into Cartan eigenspaces under the 3 real '
            f'Cartan generators h_1, h_2, h_3. Each eigenspace is '
            f'a weight space of the Weyl group S_3.'
        ),
        'status': STATUS,
    }


# =========================================================================
# 6. Serre ideal finiteness analysis
# =========================================================================

def serre_ideal_finiteness(D_max: int = 20, epsilon: float = 1.0
                           ) -> Dict[str, Any]:
    r"""Analyze the finiteness structure of the conjectural Yangian-deformation Serre ideal.

    The key structural result: the Serre ideal of the conjectural BKM
    Yangian is INFINITELY GENERATED but FINITELY DETERMINED.

    INFINITELY GENERATED: at each D with c(D) != 0, there are new
    generators and potential Serre relations. Since D ranges over
    infinitely many valid discriminants, the total Serre count is infinite.

    FINITELY DETERMINED: the self-OPE exponent P_self(D, 1) = D*(D-4)
    is positive for D >= 5 and D < 0, so the self-Serre is trivial
    outside the finite set {0, 3, 4}. The cross-Serre P_cross = D1*D2
    is positive for D1, D2 > 0.

    The SERRE KERNEL: the nontrivial Serre relations come from
    D in {0, 3, 4} (self-OPE) and the D = -1 to D > 0 cross-OPE.
    This finite kernel determines the full Serre ideal.

    Parameters
    ----------
    D_max : int
        Maximum discriminant for the census.
    epsilon : float
        Deformation parameter.

    Returns
    -------
    dict with finiteness analysis.
    """
    census = serre_census(D_max, epsilon)

    # Compute the critical discriminant where P_self(D, 1) turns positive
    # P_self(D, 1) = D*(D-4): positive for D >= 5, negative for 0 < D < 4
    # Zero at D = 0, 4. The first valid D above 4 is D = 7 (= 3 mod 4).
    # P_self(7, 1) = 7 * 3 = 21 > 0.
    critical_D_boundary = 5  # D >= 5: all self-Serre trivial

    # The Serre kernel
    kernel_D = sorted(SERRE_CRITICAL_D)
    kernel_sizes = {D: abs(KNOWN_C_TABLE[D]) for D in kernel_D}
    kernel_total = sum(kernel_sizes.values())

    # Count the "tail" (free generators)
    tail_generators = census['regular']['generators']

    # Structural dimensions of the Serre kernel relations
    # At D = 3 (only pole): pole order 3, so 3 independent Serre constraints
    # per pair of generators in the 64-dimensional space.
    # Total Serre constraints at D = 3: 3 * C(64, 2) for anticommutators
    # (fermionic), plus 3 * 64 for self-anticommutators.
    d3_constraints = 3  # pole order at D = 3

    return {
        'D_max': D_max,
        'epsilon': epsilon,
        'total_generators': census['total_generators'],
        'infinitely_generated': True,
        'finitely_determined': True,
        'serre_kernel': {
            'discriminants': kernel_D,
            'sizes': kernel_sizes,
            'total': kernel_total,
            'description': (
                f'Serre kernel: {kernel_total} generators across D = {kernel_D}. '
                f'D=0: {kernel_sizes[0]} marginal bosonic. '
                f'D=3: {kernel_sizes[3]} fermionic with pole of order {d3_constraints}. '
                f'D=4: {kernel_sizes[4]} marginal bosonic.'
            ),
        },
        'serre_tail': {
            'generators': tail_generators,
            'description': (
                f'{tail_generators} generators at D >= 7 (and D = -1) '
                f'are FREE: self-Serre trivial (P > 0).'
            ),
        },
        'critical_boundary': {
            'D': critical_D_boundary,
            'description': (
                f'For D >= {critical_D_boundary}: P_self(D, 1) = D*(D-4) > 0, '
                f'so all self-Serre relations are trivial.'
            ),
        },
        'unique_nontrivial_pole': {
            'discriminant': 3,
            'pole_order': d3_constraints,
            'multiplicity': kernel_sizes[3],
            'parity': 'fermionic',
            'description': (
                'D = 3 is the UNIQUE discriminant with a genuine pole '
                '(P = -3) in the self-OPE at eps=1. '
                '64 fermionic generators with triple-pole self-OPE. '
                'This is the only sector where the standard Borcherds-Serre '
                'commutativity [e_alpha, e_beta] = 0 is BROKEN by the deformation.'
            ),
        },
        'commutativity_comparison': {
            'standard_borcherds_serre': (
                '[e_alpha, e_beta] = 0 for imaginary roots with (alpha,beta) = 0. '
                'This is the trivial Borcherds-Serre relation.'
            ),
            'deformed_serre': (
                'At eps=1, the deformation PRESERVES commutativity for '
                'D >= 5 (P_self > 0) and D = -1 (P_self = 5). '
                'Commutativity is BROKEN only at D = 3 (P_self = -3). '
                'The marginal sectors D = 0 and D = 4 (P_self = 0) are '
                'indeterminate at leading order.'
            ),
            'deformation_breaks_commutativity': {
                'D_values': [3],
                'description': (
                    'The Omega deformation breaks the Borcherds-Serre '
                    'commutativity ONLY at D = 3. All other discriminants '
                    'either preserve commutativity (regular) or are '
                    'indeterminate (marginal).'
                ),
            },
        },
        'status': STATUS,
    }


# =========================================================================
# 7. Explicit D=3 Serre relation (the unique nontrivial case)
# =========================================================================

def d3_serre_relation(epsilon: float = 1.0) -> Dict[str, Any]:
    r"""Derive the explicit Serre relation at D = 3.

    D = 3 is the UNIQUE discriminant where the deformed self-OPE has a
    genuine pole (P = -3, triple pole). This sector has:
    - c(3) = -64: 64 fermionic generators
    - Norm: (alpha, alpha) = -6 for each root
    - Self-OPE: V_eps(alpha, z) V_eps(alpha, w) ~ (z-w)^{-3} * (...)

    The triple pole produces 3 layers of Serre data:

    Layer 1 (z-w)^{-3}: The MOST SINGULAR term.
        Coefficient: proportional to the BKM structure constant
        C_{alpha,alpha}^{(3)} = C_3 * V_eps(2*alpha, w)
        where C_3 encodes the triple self-contraction.

        For fermionic generators (anticommutating):
        {e_3^{(a)}(u), e_3^{(a)}(u)} ~ C_3 * (u-v)^{-3}
        The anticommutator of a fermionic current with itself
        is proportional to 1/(u-v)^3.

    Layer 2 (z-w)^{-2}: The SCHWINGER term.
        Coefficient: proportional to the derivative of V_eps(2*alpha, w)
        and the central extension of the current algebra.
        {e_3^{(a)}(u), e_3^{(b)}(v)} has a (u-v)^{-2} term
        proportional to delta_{ab} * (central element).

    Layer 3 (z-w)^{-1}: The CURRENT ALGEBRA BRACKET.
        Coefficient: the leading Lie bracket / anticommutator.
        {e_3^{(a)}(u), e_3^{(b)}(v)} ~ f_3^{ab} * e_{6}^{(c)}(v) / (u-v)
        where f_3^{ab} are the BKM structure constants at the
        D = 3 level, and the output is at D = 6.
        NOTE: D = 6 is NOT a valid discriminant (6 mod 4 = 2,
        violates AP-CY9). So the (z-w)^{-1} term must involve
        a COMPOSITE field (normally-ordered product), not a simple
        generator at D = 6.

    The Serre relation proper: the condition that the triple pole
    is expressible in terms of the algebra generators is the D = 3
    Serre constraint. This constraint has 3 * C(64, 2) + 3 * 64
    components (for the 64 x 64 anticommutator matrix at 3 pole
    orders), but the BKM structure (root multiplicities, Weyl
    group action) reduces the independent constraints.

    Parameters
    ----------
    epsilon : float
        Deformation parameter.

    Returns
    -------
    dict with the explicit D = 3 Serre relation data.
    """
    D = 3
    c_val = KNOWN_C_TABLE[D]
    mult = abs(c_val)
    P_self = deformed_ope_exponent_self(D, epsilon)
    pole_order = int(math.ceil(-P_self - 1e-10))

    # Check that 2*D = 6 is not a valid discriminant
    d_double = 2 * D  # = 6
    d_double_valid = (d_double % 4) in VALID_DISCRIMINANT_RESIDUES
    # 6 mod 4 = 2, NOT in {0, 3}, so D = 6 is invalid

    # The target of the (z-w)^{-1} bracket
    # Since D = 6 is not a valid discriminant, the bracket output
    # must be a COMPOSITE (normally-ordered product of lower-D generators)
    # The simplest decomposition: D = 3 + 3
    # alpha + alpha = 2*alpha has norm (2*alpha, 2*alpha) = 4*(-6) = -24
    # giving discriminant D(2*alpha) = -(-24)/2 = 12 in the BKM convention
    # Wait: (alpha, alpha) = -2D = -6 for D = 3
    # (2*alpha, 2*alpha) = 4*(alpha,alpha) = 4*(-6) = -24
    # D(2*alpha) = -(2*alpha, 2*alpha)/2 = 12
    # D = 12 IS a valid discriminant (12 mod 4 = 0), c(12) = 4016

    d_sum = D + D  # = 6 for discriminant addition (not norm doubling)
    # The actual output: the vertex operator V_eps(alpha + beta, w)
    # at root alpha + beta, where (alpha+beta, alpha+beta) =
    # (alpha,alpha) + 2*(alpha,beta) + (beta,beta)
    # For self-OPE (beta = alpha): = -6 + 2*(-6) + (-6) = -24
    # Discriminant of alpha+alpha: -(-24)/2 = 12

    return {
        'discriminant': D,
        'c_value': c_val,
        'multiplicity': mult,
        'parity': 'fermionic',
        'self_ope_exponent': P_self,
        'pole_order': pole_order,
        'layers': {
            'layer_3': {
                'pole_order': 3,
                'description': (
                    'Most singular: (z-w)^{-3} term. '
                    'Coefficient proportional to V_eps(2*alpha, w), '
                    'which lives at discriminant D = 12 (norm -24). '
                    'This is a DESCENDANT of the D = 12 sector '
                    '(c(12) = 4016, bosonic).'
                ),
                'output_discriminant': 12,
                'output_c_value': KNOWN_C_TABLE.get(12, 'unknown'),
            },
            'layer_2': {
                'pole_order': 2,
                'description': (
                    'Schwinger term: (z-w)^{-2} coefficient. '
                    'Proportional to d/dw V_eps(2*alpha, w) and central '
                    'elements. Gives the anomalous dimension / central '
                    'extension of the fermionic current algebra at D = 3.'
                ),
            },
            'layer_1': {
                'pole_order': 1,
                'description': (
                    'Current algebra bracket: (z-w)^{-1} coefficient. '
                    '{e_3^{(a)}(u), e_3^{(b)}(v)} ~ structure constant * '
                    'composite field at D = 12. NOT a simple generator '
                    'at D = 6 (which is not a valid discriminant, '
                    '6 mod 4 = 2 violates AP-CY9).'
                ),
                'target_discriminant_sum': d_sum,
                'target_valid': d_double_valid,
                'actual_target_discriminant': 12,
                'mechanism': (
                    'The bracket output is at D(alpha+alpha) = 12 '
                    '(from the norm doubling: (2*alpha, 2*alpha) = -24, '
                    'D = 12). The D = 12 sector has c(12) = 4016 generators. '
                    'The bracket maps 64 x 64 -> 4016, picking out specific '
                    'directions in the D = 12 root space.'
                ),
            },
        },
        'd6_not_valid': {
            'discriminant': 6,
            'mod_4': 6 % 4,
            'valid': d_double_valid,
            'consequence': (
                'D = 6 is NOT a valid discriminant (6 mod 4 = 2). '
                'The naive sum D1 + D2 = 3 + 3 = 6 does not give a valid '
                'root. Instead, the output lives at D = 12 (the discriminant '
                'of the doubled root 2*alpha with norm 4*(alpha,alpha) = -24).'
            ),
        },
        'structural_significance': (
            'D = 3 is the UNIQUE discriminant with a genuine pole in the '
            'deformed self-OPE. The triple pole produces the ONLY '
            'nontrivial Serre relation that BREAKS the standard Borcherds '
            'commutativity [e_alpha, e_beta] = 0. This is the central '
            'new result of the deformed OPE approach: the conjectural '
            'Yangian deformation of the BKM algebra '
            'has nontrivial self-interaction concentrated at a single '
            'discriminant level.'
        ),
        'status': STATUS,
    }


# =========================================================================
# 8. D = 0 lightlike sector (10 generators, marginal self-OPE)
# =========================================================================

def d0_lightlike_serre(epsilon: float = 1.0) -> Dict[str, Any]:
    r"""Analyze the lightlike (D = 0) sector: 10 generators, marginal OPE.

    D = 0 is the lightlike sector with c(0) = 10 bosonic generators.
    Self-OPE exponent: P_self(0, 1) = 0*(0-4) = 0 (MARGINAL).

    The 10 lightlike generators correspond to isotropic vectors in
    II_{2,1}. The inner product between different isotropic vectors
    depends on the specific pair:

    In II_{2,1}, the isotropic vectors form a 1-parameter family
    (the light cone). The primitive isotropic vectors are classified
    by the Weyl group S_3 action. Two isotropic vectors alpha, beta
    can have (alpha, beta) = 0, 1, or -1.

    Cross-OPE between two D = 0 roots:
    - If (alpha, beta) = 0: P_cross = 0 (marginal)
    - If (alpha, beta) = 1: P_cross = 2*1 + 0 = 2 (regular)
    - If (alpha, beta) = -1: P_cross = 2*(-1) + 0 = -2 (POLE of order 2)

    So the 10 lightlike generators split into:
    - Orthogonal pairs: marginal interaction (P = 0)
    - Positively paired: regular (commuting, P = 2)
    - Negatively paired: nontrivial bracket (P = -2, double pole)

    This is the D = 0 LIGHTLIKE SERRE STRUCTURE: the 10 generators
    have a rich internal structure governed by the lattice geometry
    of isotropic vectors in II_{2,1}.

    Returns
    -------
    dict with lightlike sector Serre data.
    """
    D = 0
    c_val = KNOWN_C_TABLE[D]
    mult = abs(c_val)
    P_self = deformed_ope_exponent_self(D, epsilon)

    # Possible inner products between different D = 0 roots
    possible_ips = {
        0: {
            'cross_ope_exponent': deformed_ope_exponent_cross(0, 0, epsilon, 0),
            'singularity': 'marginal',
            'description': 'Orthogonal isotropic vectors. Marginal interaction.',
        },
        1: {
            'cross_ope_exponent': deformed_ope_exponent_cross(0, 0, epsilon, 1),
            'singularity': 'regular',
            'description': 'Positively paired. Commuting at leading order.',
        },
        -1: {
            'cross_ope_exponent': deformed_ope_exponent_cross(0, 0, epsilon, -1),
            'singularity': 'pole',
            'pole_order': 2,
            'description': (
                'Negatively paired. Double pole: nontrivial bracket. '
                'This is the ONLY case where two D = 0 generators '
                'have a genuine pole in their cross-OPE.'
            ),
        },
    }

    return {
        'discriminant': D,
        'c_value': c_val,
        'multiplicity': mult,
        'parity': 'bosonic',
        'self_ope_exponent': P_self,
        'self_ope_type': 'marginal',
        'kappa_BKM': c_val // 2,  # = 5, the weight of Delta_5
        'cross_ope_by_inner_product': possible_ips,
        'internal_structure': (
            '10 lightlike generators have rich internal structure: '
            'the cross-OPE depends on the lattice inner product '
            '(alpha, beta) between isotropic vectors. '
            'Orthogonal pairs (ip=0): marginal. '
            'Positive pairs (ip=1): commuting. '
            'Negative pairs (ip=-1): nontrivial bracket (double pole).'
        ),
        'weyl_group_decomposition': (
            'Under the Weyl group S_3 of II_{2,1}: '
            'the 10 lightlike generators decompose as '
            '10 = 1 + 1 + 1 + 1 + 3 + 3 '
            '(S_3 representations). '
            'The singlet pairs are orthogonal (ip=0), '
            'while the triplet pairs can have ip = 1 or -1.'
        ),
        'status': STATUS,
    }


# =========================================================================
# 9. Complete deformed Serre summary
# =========================================================================

def deformed_serre_summary(D_max: int = 20, epsilon: float = 1.0
                           ) -> Dict[str, Any]:
    r"""Complete summary of the BKM deformed Serre relations.

    This is the main entry point, gathering all results from the
    discriminant-by-discriminant analysis into a unified picture.

    Parameters
    ----------
    D_max : int
        Maximum discriminant.
    epsilon : float
        Deformation parameter.

    Returns
    -------
    dict with complete summary.
    """
    census = serre_census(D_max, epsilon)
    cross_table = cross_serre_table(epsilon=epsilon)
    finiteness = serre_ideal_finiteness(D_max, epsilon)
    d3 = d3_serre_relation(epsilon)
    d0 = d0_lightlike_serre(epsilon)

    # The 6 questions answered
    answers = {
        'Q1_D_minus1_self_OPE': {
            'question': (
                'D = -1 (Weyl vector, mult 1): deformed self-OPE?'
            ),
            'answer': (
                'P_self(-1, 1) = (-1)(-5) = 5. REGULAR. '
                'The single Weyl vector current e_W(u) is FREE: '
                'no self-Serre relation. [e_W(u), e_W(v)] = 0.'
            ),
            'exponent': deformed_ope_exponent_self(-1, epsilon),
        },
        'Q2_D0_ten_currents': {
            'question': (
                'D = 0 (10 roots, mult 1 each): self and cross OPE?'
            ),
            'answer': (
                'Self-OPE: P_self(0, 1) = 0 (MARGINAL). '
                'Cross-OPE depends on lattice inner product: '
                'ip = 0 -> marginal, ip = 1 -> regular (commuting), '
                'ip = -1 -> double pole (nontrivial bracket). '
                'The 10 currents have rich internal structure '
                'governed by the isotropic vector geometry of II_{2,1}.'
            ),
            'self_exponent': deformed_ope_exponent_self(0, epsilon),
            'detail': d0,
        },
        'Q3_D3_first_spacelike': {
            'question': (
                'D = 3 (first spacelike fermionic, mult 64): Serre relation?'
            ),
            'answer': (
                'P_self(3, 1) = 3*(-1) = -3. TRIPLE POLE. '
                'The 64 fermionic generators have the UNIQUE nontrivial '
                'self-Serre in the entire BKM algebra. Three layers: '
                '(z-w)^{-3} (structure constant), (z-w)^{-2} (Schwinger), '
                '(z-w)^{-1} (current bracket into D = 12 sector). '
                'Output at D = 12 (not D = 6, which is invalid).'
            ),
            'exponent': deformed_ope_exponent_self(3, epsilon),
            'detail': d3,
        },
        'Q4_D1_discriminant_validity': {
            'question': (
                'D = 1: what happens at discriminant 1?'
            ),
            'answer': (
                'D = 1 is NOT a valid discriminant for phi_{0,1} of index 1 '
                '(AP-CY9: D must satisfy D = 0 or 3 mod 4; D = 1 has '
                '1 mod 4 = 1 which is not in {0, 3}). c(1) = 0. '
                'There are NO generators at D = 1. '
                'The next valid discriminant after D = 0 is D = 3.'
            ),
        },
        'Q5_imaginary_real_adjoint': {
            'question': (
                'Imaginary-real mixing: OPE between imaginary and Cartan?'
            ),
            'answer': (
                'h_i(z) V_eps(alpha, w) ~ (delta_i, alpha) / (z-w) * V_eps(alpha, w). '
                'This is the adjoint action: Cartan generators act by root '
                'eigenvalues. The deformation PRESERVES this at leading order. '
                'The Cartan-imaginary bracket is the standard weight decomposition.'
            ),
        },
        'Q6_finiteness': {
            'question': (
                'Is the Serre ideal finitely generated?'
            ),
            'answer': (
                'INFINITELY GENERATED but FINITELY DETERMINED. '
                'The Serre kernel (nontrivial relations) is concentrated at '
                'D in {0, 3, 4} with 182 generators total. '
                'All generators at D >= 5 are FREE (self-Serre trivial). '
                'The UNIQUE genuine pole is at D = 3 (triple pole). '
                'The full infinite Serre ideal is determined by the '
                'finite kernel plus the trivial tail.'
            ),
            'detail': finiteness,
        },
        'Q7_commutativity_breaking': {
            'question': (
                'Does the deformation break the Borcherds-Serre commutativity?'
            ),
            'answer': (
                'The standard BKM Serre [e_alpha, e_beta] = 0 for '
                '(alpha, beta) = 0 is PRESERVED for D >= 5 (regular OPE). '
                'Commutativity is BROKEN only at D = 3 (the unique pole). '
                'At D = 0 and D = 4 (marginal), commutativity is '
                'indeterminate at leading order; higher corrections decide. '
                'The deformation concentrates ALL nontrivial Serre structure '
                'at the single discriminant D = 3.'
            ),
        },
    }

    return {
        'title': (
            'BKM deformed Serre relations from the Borcherds OPE: '
            'complete analysis'
        ),
        'key_formula': 'P_self(D, 1) = D * (D - 4)',
        'key_result': (
            'The self-OPE exponent P_self(D, 1) = D*(D-4) is negative '
            'ONLY for D = 3. The conjectural Yangian-deformation Serre ideal has a finite '
            'kernel of 182 generators at D in {0, 3, 4} and an infinite '
            'tail of free generators at D >= 5. The UNIQUE genuine '
            'pole (nontrivial Serre) is at D = 3 with pole order 3.'
        ),
        'answers': answers,
        'census': census,
        'cross_table': cross_table,
        'status': STATUS,
    }
