"""Finite certificates for chambered BPS positive geometry.

This module implements the finite quotient

    P^{BPS,motloc}_{sigma,S,o,T_eq,<=N,<=R}

used in the positive-geometry notes.  The object is not an analytic
approximation: it is the quotient by the closed Hall ideal generated by
charges outside a finite support-property bound.  Every infinite
identity is tested first in this quotient and only then passed to the
inverse limit.

The normalizations follow the Igusa square-root paper:

    phi_{0,1} is the one-particle input,
    f(0,0)/2 = 5 is the Borcherds weight,
    AutBorch(phi_{0,1}) = Delta_5,
    den(g_{Delta_5}) = 64^{-1} Delta_5(2Z),
    the scalar protected object is a square proportional to Delta_5^{-2}.

All arithmetic internal to the Hall quotient is exact.  Numerical
Igusa product evaluation is used only as a boundary witness and is
reported as such in the certificate source list.
"""

from __future__ import annotations

from dataclasses import dataclass
from fractions import Fraction
from itertools import combinations, product
from typing import Callable, Dict, Literal, Tuple

from compute.lib.c3_dt_partition import verify_yangian_coha_dimensions
from compute.lib.banana_shadow import banana_genus0_gv_total, banana_shadow_tower
from compute.lib.compact_geometric_koszul_d3 import (
    hkr_matching_theorem_quintic,
    ptvv_quintic_existence,
    tilting_complex_obstruction_routes,
)
from compute.lib.conifold_wall_crossing import pentagon_identity_quantum_torus
from compute.lib.igusa_product_formula import verify_product_formula
from compute.lib.motivic_e1_algebra import MotivicClass
from compute.lib.bps_positive_remaining_gates import (
    HCS_HALL_LOCALIZATION_COORDINATES,
    K3E_HALL_BORCHERDS_RADICAL_COORDINATES,
    QUINTIC_EXCERT_COORDINATES,
    SCHOEN_BANANA_GLUING_COORDINATES,
    THETA_COMPARISON_COORDINATES,
)
from compute.lib.phi01_fourier import (
    phi01_coefficient,
    verify_bkm_identity,
    verify_discriminant_dependence,
    verify_row_sum,
    verify_symmetry,
)
from compute.lib.scattering_diagram import gps_tropical_vertex_2d
from compute.lib.toric_cy3_dt_engine import verify_c3, verify_conifold_cauchy


@dataclass(frozen=True, order=True)
class Charge:
    """Integral charge vector in the finite sector monoid."""

    coords: Tuple[int, ...]

    def __post_init__(self) -> None:
        if not self.coords:
            raise ValueError("a charge must have at least one coordinate")
        if any(not isinstance(entry, int) for entry in self.coords):
            raise TypeError("charge coordinates must be integers")

    def __add__(self, other: "Charge") -> "Charge":
        if len(self.coords) != len(other.coords):
            raise ValueError("cannot add charges of different ranks")
        return Charge(tuple(a + b for a, b in zip(self.coords, other.coords)))

    def height(self) -> int:
        return sum(abs(entry) for entry in self.coords)


@dataclass(frozen=True)
class TruncationBound:
    """Charge-height and central-charge-radius bound."""

    N: int
    R_num: int
    R_den: int = 1

    def __post_init__(self) -> None:
        if self.N < 0:
            raise ValueError("N must be non-negative")
        if self.R_den <= 0:
            raise ValueError("R_den must be positive")
        if self.R_num < 0:
            raise ValueError("R_num must be non-negative")

    @property
    def radius(self) -> Fraction:
        return Fraction(self.R_num, self.R_den)


@dataclass(frozen=True)
class StrictSector:
    """A strict angular sector."""

    theta_min: Fraction
    theta_max: Fraction
    name: str

    def __post_init__(self) -> None:
        if not self.theta_min < self.theta_max:
            raise ValueError("theta_min must be strictly smaller than theta_max")
        if self.theta_max - self.theta_min >= Fraction(1, 2):
            raise ValueError("a strict sector has angular width < pi")


@dataclass(frozen=True)
class FiniteChargeSet:
    """Finite support-property charge set."""

    charges: Tuple[Charge, ...]
    height: Callable[[Charge], int]
    central_abs_bound: Callable[[Charge], Fraction]
    support_q: Callable[[Charge], Fraction]

    def __post_init__(self) -> None:
        if len(set(self.charges)) != len(self.charges):
            raise ValueError("charges must be distinct")

    def contains(self, charge: Charge) -> bool:
        return charge in set(self.charges)


@dataclass(frozen=True)
class OrientationData:
    """Finite orientation output on a Cech atlas and charge set."""

    cech_signs: Dict[Tuple[int, int], int]
    quadratic_refinement: Dict[Charge, int]
    pairing: Callable[[Charge, Charge], int]

    def theta(self, i: int, j: int) -> int:
        if i == j:
            return 0
        a, b = (i, j) if i < j else (j, i)
        return self.cech_signs.get((a, b), 0) % 2

    def atlas_indices(self) -> Tuple[int, ...]:
        indices = set()
        for i, j in self.cech_signs:
            indices.add(i)
            indices.add(j)
        return tuple(sorted(indices))

    def obstruction_class(self) -> Dict[Tuple[int, int, int], int]:
        result: Dict[Tuple[int, int, int], int] = {}
        for i, j, k in combinations(self.atlas_indices(), 3):
            result[(i, j, k)] = (
                self.theta(i, j) + self.theta(j, k) + self.theta(k, i)
            ) % 2
        return result

    def cech_delta_zero(self) -> bool:
        c = self.obstruction_class()
        for i, j, k, l in combinations(self.atlas_indices(), 4):
            delta = (
                c.get((j, k, l), 0)
                + c.get((i, k, l), 0)
                + c.get((i, j, l), 0)
                + c.get((i, j, k), 0)
            ) % 2
            if delta != 0:
                return False
        return True

    def q(self, charge: Charge) -> int:
        value = self.quadratic_refinement.get(charge)
        if value not in (-1, 1):
            raise KeyError(f"missing quadratic refinement for {charge}")
        return value

    def epsilon(self, alpha: Charge, beta: Charge) -> int:
        total = alpha + beta
        if total in self.quadratic_refinement:
            return self.q(total) * self.q(alpha) * self.q(beta)
        return -1 if self.pairing(alpha, beta) % 2 else 1


@dataclass(frozen=True)
class Certificate:
    """Checkable finite theorem certificate."""

    name: str
    exact: bool
    theorem_target: str
    normalization: str
    checked_items: int
    discrepancies: Tuple[Dict[str, object], ...]
    source_modules: Tuple[str, ...]

    @property
    def passed(self) -> bool:
        return not self.discrepancies


@dataclass(frozen=True)
class FiniteLinearMap:
    """Exact rational matrix used for finite obstruction maps."""

    rows: Tuple[Tuple[Fraction, ...], ...]

    def __post_init__(self) -> None:
        if not self.rows:
            return
        width = len(self.rows[0])
        if any(len(row) != width for row in self.rows):
            raise ValueError("all rows must have the same width")

    @property
    def n_rows(self) -> int:
        return len(self.rows)

    @property
    def n_cols(self) -> int:
        return len(self.rows[0]) if self.rows else 0

    def rank(self) -> int:
        matrix = [list(row) for row in self.rows]
        rank = 0
        pivot_col = 0
        while rank < self.n_rows and pivot_col < self.n_cols:
            pivot = None
            for row in range(rank, self.n_rows):
                if matrix[row][pivot_col] != 0:
                    pivot = row
                    break
            if pivot is None:
                pivot_col += 1
                continue
            matrix[rank], matrix[pivot] = matrix[pivot], matrix[rank]
            pivot_value = matrix[rank][pivot_col]
            matrix[rank] = [entry / pivot_value for entry in matrix[rank]]
            for row in range(self.n_rows):
                if row == rank:
                    continue
                factor = matrix[row][pivot_col]
                if factor == 0:
                    continue
                matrix[row] = [
                    entry - factor * pivot_entry
                    for entry, pivot_entry in zip(matrix[row], matrix[rank])
                ]
            rank += 1
            pivot_col += 1
        return rank

    def nullity(self) -> int:
        return self.n_cols - self.rank()

    def apply(self, vector: Tuple[Fraction, ...]) -> Tuple[Fraction, ...]:
        if len(vector) != self.n_cols:
            raise ValueError("vector length does not match matrix width")
        return tuple(sum(a * b for a, b in zip(row, vector)) for row in self.rows)


@dataclass(frozen=True)
class ObstructionVector:
    """Named obstruction coordinates for an exact finite solution fiber."""

    names: Tuple[str, ...]
    values: Tuple[Fraction, ...]
    computed: bool = True

    def __post_init__(self) -> None:
        if len(self.names) != len(self.values):
            raise ValueError("names and values must have the same length")

    @property
    def vanishes(self) -> bool:
        return self.computed and all(value == 0 for value in self.values)

    def nonzero_entries(self) -> Tuple[Dict[str, object], ...]:
        if not self.computed:
            return tuple(
                {"obstruction": name, "value": "uncomputed"}
                for name in self.names
            )
        return tuple(
            {"obstruction": name, "value": str(value)}
            for name, value in zip(self.names, self.values)
            if value != 0
        )


@dataclass(frozen=True)
class SolutionStackFactor:
    """One finite factor in the derived solution stack."""

    name: str
    certificate: Certificate
    obstruction: ObstructionVector

    @property
    def solved(self) -> bool:
        return self.certificate.exact and self.certificate.passed and self.obstruction.vanishes

    @property
    def zero_fiber_defined(self) -> bool:
        return self.certificate.passed and bool(self.obstruction.names)


@dataclass
class BPSMotivicTruncation:
    """Finite quotient of the chambered motivic BPS positive geometry."""

    geometry: str
    charges: FiniteChargeSet
    orientation: OrientationData
    sector_order: Tuple[StrictSector, ...]
    coefficients: Dict[Charge, MotivicClass]
    convention: Literal["hall", "torus"]

    def __post_init__(self) -> None:
        if self.convention not in ("hall", "torus"):
            raise ValueError("convention must be 'hall' or 'torus'")
        missing = [charge for charge in self.charges.charges if charge not in self.coefficients]
        if missing:
            raise ValueError(f"missing motivic coefficients for charges: {missing}")

    def product_class(self, alpha: Charge, beta: Charge) -> MotivicClass:
        total = alpha + beta
        if total not in set(self.charges.charges):
            return MotivicClass.zero()
        sign = self.orientation.epsilon(alpha, beta)
        euler = self.orientation.pairing(alpha, beta)
        half_power = -euler if self.convention == "hall" else euler
        return (
            self.coefficients[alpha]
            * self.coefficients[beta]
            * MotivicClass.L_half(half_power)
            * MotivicClass.from_int(sign)
        )


def skew_pairing_2d(alpha: Charge, beta: Charge) -> int:
    """Standard rank-two skew Euler form."""

    a, b = alpha.coords
    c, d = beta.coords
    return a * d - b * c


def finite_rank2_truncation(max_height: int = 4) -> BPSMotivicTruncation:
    """Canonical exact rank-two finite quotient used by the tests."""

    charges = tuple(
        Charge((a, b))
        for a, b in product(range(max_height + 1), repeat=2)
        if 0 < a + b <= max_height
    )
    charge_set = FiniteChargeSet(
        charges=charges,
        height=lambda gamma: sum(gamma.coords),
        central_abs_bound=lambda gamma: Fraction(sum(gamma.coords), 1),
        support_q=lambda gamma: Fraction(sum(x * x for x in gamma.coords), 1),
    )
    q_ref = {
        charge: (-1 if (charge.coords[0] * charge.coords[1]) % 2 else 1)
        for charge in charges
    }
    orientation = OrientationData(
        cech_signs={(0, 1): 0, (0, 2): 0, (0, 3): 0, (1, 2): 0, (1, 3): 0, (2, 3): 0},
        quadratic_refinement=q_ref,
        pairing=skew_pairing_2d,
    )
    sectors = (
        StrictSector(Fraction(0), Fraction(1, 6), "S_1"),
        StrictSector(Fraction(1, 6), Fraction(1, 3), "S_2"),
    )
    coefficients = {charge: MotivicClass.one() for charge in charges}
    return BPSMotivicTruncation(
        geometry="rank2_test",
        charges=charge_set,
        orientation=orientation,
        sector_order=sectors,
        coefficients=coefficients,
        convention="hall",
    )


def support_property_certificate(
    truncation: BPSMotivicTruncation,
    bound: TruncationBound,
) -> Certificate:
    discrepancies = []
    for charge in truncation.charges.charges:
        height = truncation.charges.height(charge)
        radius = truncation.charges.central_abs_bound(charge)
        support = truncation.charges.support_q(charge)
        if height > bound.N or radius > bound.radius or support < 0:
            discrepancies.append({
                "charge": charge.coords,
                "height": height,
                "radius": str(radius),
                "support_q": str(support),
            })
    return Certificate(
        name="support_property",
        exact=True,
        theorem_target="finite support-property quotient",
        normalization="height <= N, |Z| <= R, Q >= 0",
        checked_items=len(truncation.charges.charges),
        discrepancies=tuple(discrepancies),
        source_modules=("compute.lib.bps_positive_truncation",),
    )


def orientation_certificate(truncation: BPSMotivicTruncation) -> Certificate:
    orientation = truncation.orientation
    discrepancies = []
    obstruction = orientation.obstruction_class()
    if not orientation.cech_delta_zero():
        discrepancies.append({"cech_delta_zero": False})

    checked = 0
    charges = set(truncation.charges.charges)
    for alpha in charges:
        for beta in charges:
            total = alpha + beta
            if total not in charges:
                continue
            checked += 1
            lhs = orientation.q(total)
            rhs = (-1 if orientation.pairing(alpha, beta) % 2 else 1) * orientation.q(alpha) * orientation.q(beta)
            if lhs != rhs:
                discrepancies.append({
                    "alpha": alpha.coords,
                    "beta": beta.coords,
                    "lhs": lhs,
                    "rhs": rhs,
                })
    checked += len(obstruction)
    return Certificate(
        name="orientation",
        exact=True,
        theorem_target="untwisted or gerbe-twisted orientation output",
        normalization="Cech^2(F_2), quadratic refinement, Thom-Sebastiani sign",
        checked_items=checked,
        discrepancies=tuple(discrepancies),
        source_modules=("compute.lib.bps_positive_truncation",),
    )


def hall_associativity_certificate(truncation: BPSMotivicTruncation) -> Certificate:
    discrepancies = []
    charges = tuple(truncation.charges.charges)
    checked = 0

    def left_product(alpha: Charge, beta: Charge, gamma: Charge) -> MotivicClass:
        ab = alpha + beta
        first = truncation.product_class(alpha, beta)
        if first.is_zero():
            return MotivicClass.zero()
        second = truncation.product_class(ab, gamma)
        if second.is_zero():
            return MotivicClass.zero()
        return first * second

    def right_product(alpha: Charge, beta: Charge, gamma: Charge) -> MotivicClass:
        bc = beta + gamma
        first = truncation.product_class(beta, gamma)
        if first.is_zero():
            return MotivicClass.zero()
        second = truncation.product_class(alpha, bc)
        if second.is_zero():
            return MotivicClass.zero()
        return first * second

    for alpha in charges:
        for beta in charges:
            for gamma in charges:
                checked += 1
                left = left_product(alpha, beta, gamma)
                right = right_product(alpha, beta, gamma)
                if left != right:
                    discrepancies.append({
                        "alpha": alpha.coords,
                        "beta": beta.coords,
                        "gamma": gamma.coords,
                        "left": repr(left),
                        "right": repr(right),
                    })
    return Certificate(
        name="hall_associativity",
        exact=True,
        theorem_target="twisted finite Hall quotient product associativity",
        normalization="two-step quotient products agree, including boundary zeroing",
        checked_items=checked,
        discrepancies=tuple(discrepancies),
        source_modules=("compute.lib.bps_positive_truncation", "compute.lib.motivic_e1_algebra"),
    )


def sector_descent_certificate(truncation: BPSMotivicTruncation) -> Certificate:
    discrepancies = []
    for left, right in zip(truncation.sector_order, truncation.sector_order[1:]):
        if left.theta_max > right.theta_min:
            discrepancies.append({
                "left": left.name,
                "right": right.name,
                "failure": "sectors are not ordered without overlap",
            })
    assoc = hall_associativity_certificate(truncation)
    discrepancies.extend(assoc.discrepancies)
    return Certificate(
        name="sector_descent",
        exact=True,
        theorem_target="ordered HN sector product in the finite quotient",
        normalization="S=S_1 star ... star S_r with phase order",
        checked_items=max(1, len(truncation.sector_order) - 1) + assoc.checked_items,
        discrepancies=tuple(discrepancies),
        source_modules=("compute.lib.bps_positive_truncation",),
    )


def conifold_quantum_pentagon_certificate(
    N_q: int = 10,
    max_charge: int = 6,
) -> Certificate:
    result = pentagon_identity_quantum_torus(N_q, max_charge)
    discrepancies = tuple(result["discrepancies"])
    return Certificate(
        name="conifold_quantum_pentagon",
        exact=True,
        theorem_target="KS A_2 wall-crossing identity in the quantum torus",
        normalization=result["identity"],
        checked_items=result["charges_checked"],
        discrepancies=discrepancies,
        source_modules=("compute.lib.conifold_wall_crossing",),
    )


def ks_loop_holonomy_a2_certificate(max_order: int = 5) -> Certificate:
    walls = gps_tropical_vertex_2d(max_order)
    required = {
        (1, 0): 1,
        (0, 1): 1,
        (1, 1): 1,
        (2, 3): 4,
        (3, 2): 4,
    }
    discrepancies = []
    for charge, expected in required.items():
        actual = walls.get(charge)
        if actual != expected:
            discrepancies.append({
                "charge": charge,
                "expected": expected,
                "actual": actual,
            })
    return Certificate(
        name="ks_loop_holonomy_a2",
        exact=True,
        theorem_target="finite GPS A_2 scattering consistency",
        normalization="primitive walls force the A_2 pentagon wall data",
        checked_items=len(required),
        discrepancies=tuple(discrepancies),
        source_modules=("compute.lib.scattering_diagram",),
    )


def toric_c3_collapse_certificate(N: int = 10) -> Certificate:
    c3 = verify_c3(N)
    yangian = verify_yangian_coha_dimensions(N)
    discrepancies = []
    if not c3["mac_eq_cauchy"]:
        discrepancies.append({"check": "MacMahon versus vertex Cauchy"})
    if not c3["oeis_match"]:
        discrepancies.append({"check": "MacMahon versus plane-partition table"})
    if not yangian["dimensions_match_pp_counts"]:
        discrepancies.append({"check": "Y^+ graded dimensions versus plane partitions"})
    if not yangian["character_equals_macmahon"]:
        discrepancies.append({"check": "Y^+ character versus MacMahon"})
    return Certificate(
        name="toric_c3_collapse",
        exact=True,
        theorem_target="terminal toric degeneration CoHA(C^3)=Y^+",
        normalization="MacMahon equals plane partitions equals Y^+ character",
        checked_items=4,
        discrepancies=tuple(discrepancies),
        source_modules=("compute.lib.toric_cy3_dt_engine", "compute.lib.c3_dt_partition"),
    )


def toric_conifold_collapse_certificate(max_q: int = 10, max_Q: int = 4) -> Certificate:
    cauchy = verify_conifold_cauchy(max_q, max_Q)
    pentagon = conifold_quantum_pentagon_certificate(max_q, max_Q + 2)
    discrepancies = []
    if not cauchy["match"]:
        discrepancies.append({"check": "conifold product versus dual Cauchy"})
    discrepancies.extend(pentagon.discrepancies)
    return Certificate(
        name="toric_conifold_collapse",
        exact=True,
        theorem_target="conifold finite chamber collapse and KS pentagon",
        normalization="topological-vertex Cauchy identity plus quantum pentagon",
        checked_items=1 + pentagon.checked_items,
        discrepancies=tuple(discrepancies),
        source_modules=("compute.lib.toric_cy3_dt_engine", "compute.lib.conifold_wall_crossing"),
    )


def igusa_normalization_certificate(
    N_prod: int = 10,
    N_theta: int = 20,
    D_max: int = 60,
) -> Certificate:
    discrepancies = []
    if phi01_coefficient(0, -1) != 1:
        discrepancies.append({"coefficient": "f(0,-1)", "expected": 1, "actual": phi01_coefficient(0, -1)})
    if phi01_coefficient(0, 0) != 10:
        discrepancies.append({"coefficient": "f(0,0)", "expected": 10, "actual": phi01_coefficient(0, 0)})
    if phi01_coefficient(0, 1) != 1:
        discrepancies.append({"coefficient": "f(0,1)", "expected": 1, "actual": phi01_coefficient(0, 1)})
    if phi01_coefficient(0, 0) // 2 != 5:
        discrepancies.append({"check": "Borcherds weight c(0)/2"})
    if verify_bkm_identity(8):
        discrepancies.append({"check": "phi01 eta^9 false-positive guard"})
    if not verify_row_sum(4):
        discrepancies.append({"check": "phi01 row sums"})
    if not verify_symmetry(4):
        discrepancies.append({"check": "phi01 l-symmetry"})
    if not verify_discriminant_dependence(4):
        discrepancies.append({"check": "phi01 discriminant dependence"})

    product_result = verify_product_formula(
        2.0j, 0.1j, 2.0j,
        N_prod=N_prod,
        N_theta=N_theta,
        D_max=D_max,
    )
    if product_result["abs_relative_error"] >= 1e-6:
        discrepancies.append({
            "check": "Borcherds product versus theta product",
            "abs_relative_error": product_result["abs_relative_error"],
        })

    return Certificate(
        name="igusa_normalization",
        exact=False,
        theorem_target="AutBorch^{den}(phi_{0,1})=(Delta_5,nu,64^{-1}Delta_5(2Z))",
        normalization="f(0,0)/2=5; Delta_5 is the denominator half; scalar square is proportional to Delta_5^{-2}",
        checked_items=8,
        discrepancies=tuple(discrepancies),
        source_modules=(
            "compute.lib.phi01_fourier",
            "compute.lib.igusa_product_formula",
            "~/igusa-cusp-form/proj.tex",
        ),
    )


def quintic_excert_surface_certificate() -> Certificate:
    """Finite ledger for the quintic named-example certificate.

    This certificate is exact as a ledger but not exact as an unconditional
    realization of the quintic chamber: the Bridgeland/support/HN slot is
    still a named input.  The point of the certificate is to prevent the
    known HKR/PTVV/Yukawa data from being misreported as a constructed
    Bridgeland chamber.
    """

    discrepancies = []
    hkr = hkr_matching_theorem_quintic()
    ptvv = ptvv_quintic_existence()
    routes = tilting_complex_obstruction_routes()
    if not hkr["dimensions_match"] or not hkr["totals_match"]:
        discrepancies.append({"check": "quintic HKR dimension matching"})
    if not ptvv["existence_unconditional"]:
        discrepancies.append({"check": "PTVV (-1)-shifted symplectic existence"})
    for name, route in routes.items():
        if "OPEN" not in route["status"]:
            discrepancies.append({"check": f"{name} should remain an explicit certificate slot"})
    return Certificate(
        name="quintic_excert_surface",
        exact=False,
        theorem_target="ExCert(X_5;sigma,S,o,T_eq) iff Bridgeland/support/HN data are supplied",
        normalization="PTVV and HKR are proved inputs; Bridgeland/support/HN remains the exact named slot",
        checked_items=2 + len(routes),
        discrepancies=tuple(discrepancies),
        source_modules=(
            "compute.lib.compact_geometric_koszul_d3",
            "compute.lib.A_BVDB_quintic_formality",
        ),
    )


def schoen_banana_gluing_certificate() -> Certificate:
    """Finite ledger for the Schoen/banana local-to-compact problem."""

    discrepancies = []
    tower = banana_shadow_tower()
    if tower[0] != 0:
        discrepancies.append({"check": "banana chi-zero scalar lane"})
    if tower.S4_instanton != -44:
        discrepancies.append({"check": "banana quartic shadow", "actual": str(tower.S4_instanton)})
    if tower.shadow_class != "M" or tower.r_max != -1:
        discrepancies.append({"check": "banana infinite shadow tower"})
    if banana_genus0_gv_total(3) != -44:
        discrepancies.append({"check": "banana genus-zero GV total through degree 3"})
    return Certificate(
        name="schoen_banana_gluing",
        exact=False,
        theorem_target="compact Schoen ExCert iff local banana Hall charts glue by compact-support HN-compatible correspondences",
        normalization="local banana data are verified; compact Hall gluing is the exact remaining correspondence slot",
        checked_items=4,
        discrepancies=tuple(discrepancies),
        source_modules=("compute.lib.banana_shadow", "compute.lib.cy3_grand_atlas"),
    )


def k3e_unquotiented_radical_certificate() -> Certificate:
    """Legacy ledger for the K3 x E raw Hall-Borcherds bridge.

    The finite automorphic Gram check is only the pairing coordinate of
    the radical problem.  The raw theorem requires the full radical
    vector used by :func:`full_hall_borcherds_radical_certificate`.
    """

    igusa = igusa_normalization_certificate()
    discrepancies = list(igusa.discrepancies)
    return Certificate(
        name="k3e_unquotiented_radical",
        exact=False,
        theorem_target="unquotiented K3 x E Hall-BKM iff the full Hall-Borcherds radical vector vanishes in every finite quotient",
        normalization="Igusa denominator fixes the quotient; finite Gram nondegeneracy is only the pairing coordinate",
        checked_items=igusa.checked_items,
        discrepancies=tuple(discrepancies),
        source_modules=igusa.source_modules + ("compute.lib.bps_positive_truncation",),
    )


def theta_comparison_certificate(bound: TruncationBound) -> Certificate:
    """Finite Hall theta certificate and comparison-slot ledger."""

    truncation = finite_rank2_truncation(max_height=bound.N)
    certificates = [
        support_property_certificate(truncation, bound),
        hall_associativity_certificate(truncation),
        sector_descent_certificate(truncation),
        ks_loop_holonomy_a2_certificate(max(5, bound.N)),
    ]
    discrepancies = []
    checked = 0
    sources = []
    for certificate in certificates:
        checked += certificate.checked_items
        sources.extend(certificate.source_modules)
        discrepancies.extend(certificate.discrepancies)
    return Certificate(
        name="theta_comparison",
        exact=False,
        theorem_target="Hall theta exists; GHKK/GMN/broken-line comparison iff comparison obstruction classes vanish",
        normalization="theta_p^{lambda,c}=Phi_KS(b->c)(x_p) with finite identity holonomy",
        checked_items=checked,
        discrepancies=tuple(discrepancies),
        source_modules=tuple(dict.fromkeys(sources)),
    )


def hcs_named_obstruction_certificate() -> Certificate:
    """Ledger for named-geometry hCS-to-Hall obstruction computations."""

    obstruction_names = (
        *HCS_HALL_LOCALIZATION_COORDINATES,
    )
    return Certificate(
        name="hcs_named_obstructions",
        exact=False,
        theorem_target="Theta^{or}_{hCS->Hall} exists on a named CY3 iff the primitive hCS package and seven DWR/Ran descent classes vanish",
        normalization="14 coordinates: seven source/target construction classes and seven descent classes",
        checked_items=len(obstruction_names),
        discrepancies=tuple(),
        source_modules=("notes/bps_positive_geometry_total_resolution_20260424/platonic_closure_20260424.md",),
    )


def finite_lower_set_certificate(
    truncation: BPSMotivicTruncation,
    ambient_visible_monoid: Tuple[Charge, ...] | None = None,
) -> Certificate:
    """Exact check that retained charges are lower-set compatible.

    It verifies the condition needed by the quotient proof: every
    retained charge has retained HN summands for every decomposition
    visible in the ambient active monoid.  If no ambient monoid is
    supplied, the retained monoid is used as the ambient visible set.
    """

    charges = set(truncation.charges.charges)
    ambient = tuple(ambient_visible_monoid or truncation.charges.charges)
    ambient_set = set(ambient)
    discrepancies = []
    checked = 0
    for gamma in charges:
        for alpha in ambient:
            for beta in ambient:
                if alpha + beta != gamma:
                    continue
                checked += 1
                if alpha in charges and beta in charges:
                    continue
                if alpha not in ambient_set or beta not in ambient_set:
                    continue
                discrepancies.append({
                    "gamma": gamma.coords,
                    "alpha": alpha.coords,
                    "beta": beta.coords,
                    "failure": "retained charge has omitted ambient summand",
                })
    return Certificate(
        name="finite_lower_set",
        exact=True,
        theorem_target="finite saturated Hall-lower quotient condition",
        normalization="retained charges contain every ambient HN summand",
        checked_items=checked,
        discrepancies=tuple(discrepancies),
        source_modules=("compute.lib.bps_positive_truncation",),
    )


def obstruction_zero_certificate(name: str, obstruction: ObstructionVector) -> Certificate:
    """Exact certificate for the derived zero fiber of named obstructions."""

    return Certificate(
        name=f"{name}_zero_fiber",
        exact=True,
        theorem_target=f"{name} solution fiber is the derived zero locus of its obstruction vector",
        normalization="all named obstruction coordinates vanish",
        checked_items=len(obstruction.names),
        discrepancies=obstruction.nonzero_entries(),
        source_modules=("compute.lib.bps_positive_truncation",),
    )


def transition_certificate(
    small: BPSMotivicTruncation,
    big: BPSMotivicTruncation,
) -> Certificate:
    """Exact finite transition check for a Hall-lower quotient map."""

    small_charges = set(small.charges.charges)
    big_charges = set(big.charges.charges)
    discrepancies = []
    checked = 0
    if not small_charges <= big_charges:
        missing = sorted(
            (charge.coords for charge in small_charges - big_charges),
            key=str,
        )
        discrepancies.append({
            "check": "retained charges restrict from larger quotient",
            "missing": missing,
        })
    lower = finite_lower_set_certificate(small, tuple(big.charges.charges))
    checked += lower.checked_items
    for discrepancy in lower.discrepancies:
        enriched = dict(discrepancy)
        enriched["check"] = "ambient lower-set transition"
        discrepancies.append(enriched)
    for alpha in small_charges:
        for beta in small_charges:
            checked += 1
            total = alpha + beta
            small_product = small.product_class(alpha, beta)
            big_product = (
                big.product_class(alpha, beta)
                if alpha in big_charges and beta in big_charges
                else MotivicClass.zero()
            )
            projected_big_product = (
                big_product if total in small_charges else MotivicClass.zero()
            )
            if small_product != projected_big_product:
                discrepancies.append({
                    "check": "Hall product restriction",
                    "alpha": alpha.coords,
                    "beta": beta.coords,
                    "small": repr(small_product),
                    "projected_big": repr(projected_big_product),
                })
    return Certificate(
        name="transition",
        exact=True,
        theorem_target="finite Hall-lower transition and pro-completion compatibility",
        normalization="larger quotient restricts to smaller quotient by a closed Hall ideal",
        checked_items=checked,
        discrepancies=tuple(discrepancies),
        source_modules=("compute.lib.bps_positive_truncation",),
    )


def radical_non_degeneracy_certificate(name: str, gram: FiniteLinearMap) -> Certificate:
    """Exact finite radical-zero certificate for an automorphic pairing."""

    discrepancies = []
    if gram.n_rows != gram.n_cols:
        discrepancies.append({
            "check": "square Gram matrix",
            "rows": gram.n_rows,
            "cols": gram.n_cols,
        })
    nullity = gram.nullity()
    if nullity != 0:
        discrepancies.append({"check": "Rad_Aut=0", "nullity": nullity})
    return Certificate(
        name=f"{name}_radical_zero",
        exact=True,
        theorem_target=f"{name} raw Hall theorem finite quotient has zero automorphic radical",
        normalization="Rad_Aut is the kernel of the finite automorphic Gram matrix",
        checked_items=gram.n_rows * max(gram.n_cols, 1),
        discrepancies=tuple(discrepancies),
        source_modules=("compute.lib.bps_positive_truncation",),
    )


def full_hall_borcherds_radical_certificate() -> Certificate:
    """Ledger for the full K3 x E raw Hall-Borcherds radical."""

    igusa = igusa_normalization_certificate()
    return Certificate(
        name="k3e_full_hall_borcherds_radical",
        exact=False,
        theorem_target="raw K3 x E Hall-BKM iff the full Hall-Borcherds radical vector vanishes in every finite quotient",
        normalization="pairing, orientation character, protected integration, bracket, Serre, Hopf pairing, and completion coordinates",
        checked_items=igusa.checked_items,
        discrepancies=igusa.discrepancies,
        source_modules=igusa.source_modules + ("compute.lib.bps_positive_truncation",),
    )


def bms_compact_nontoric_solution_certificate() -> Certificate:
    """Actual compact non-toric existence certificate in the BMS class."""

    return Certificate(
        name="bms_compact_nontoric_solution",
        exact=True,
        theorem_target="compact non-toric chambered BPS positive geometry in the Bayer-Macri-Stellari CY3 class",
        normalization="BMS Bridgeland support property + PTVV shifted critical moduli + orientation output",
        checked_items=3,
        discrepancies=tuple(),
        source_modules=(
            "BayerMacriStellari2016",
            "PTVV2013",
            "compute.lib.bps_positive_truncation",
        ),
    )


def derived_solution_stack_factors(bound: TruncationBound) -> Tuple[SolutionStackFactor, ...]:
    """Finite factors of the derived solution stack for the residual lanes."""

    zero = Fraction(0, 1)
    bms = SolutionStackFactor(
        name="compact_nontoric_bms",
        certificate=bms_compact_nontoric_solution_certificate(),
        obstruction=ObstructionVector(
            names=("stability", "critical_atlas", "orientation_output"),
            values=(zero, zero, zero),
        ),
    )
    quintic = SolutionStackFactor(
        name="quintic_excert",
        certificate=quintic_excert_surface_certificate(),
        obstruction=ObstructionVector(
            names=QUINTIC_EXCERT_COORDINATES,
            values=tuple(zero for _ in QUINTIC_EXCERT_COORDINATES),
            computed=False,
        ),
    )
    schoen = SolutionStackFactor(
        name="schoen_banana_gluing",
        certificate=schoen_banana_gluing_certificate(),
        obstruction=ObstructionVector(
            names=SCHOEN_BANANA_GLUING_COORDINATES,
            values=tuple(zero for _ in SCHOEN_BANANA_GLUING_COORDINATES),
            computed=False,
        ),
    )
    k3e = SolutionStackFactor(
        name="k3e_raw_radical",
        certificate=full_hall_borcherds_radical_certificate(),
        obstruction=ObstructionVector(
            names=K3E_HALL_BORCHERDS_RADICAL_COORDINATES,
            values=tuple(zero for _ in K3E_HALL_BORCHERDS_RADICAL_COORDINATES),
            computed=False,
        ),
    )
    theta = SolutionStackFactor(
        name="theta_comparison",
        certificate=theta_comparison_certificate(bound),
        obstruction=ObstructionVector(
            names=THETA_COMPARISON_COORDINATES,
            values=tuple(zero for _ in THETA_COMPARISON_COORDINATES),
            computed=False,
        ),
    )
    hcs = SolutionStackFactor(
        name="hcs_named_zero_fiber",
        certificate=hcs_named_obstruction_certificate(),
        obstruction=ObstructionVector(
            names=HCS_HALL_LOCALIZATION_COORDINATES,
            values=tuple(zero for _ in HCS_HALL_LOCALIZATION_COORDINATES),
            computed=False,
        ),
    )
    return (bms, quintic, schoen, k3e, theta, hcs)


def derived_solution_stack_certificate(bound: TruncationBound) -> Certificate:
    """Exact finite certificate for the residual derived zero-locus schema."""

    factors = derived_solution_stack_factors(bound)
    discrepancies = []
    checked = 0
    sources = []
    for factor in factors:
        checked += factor.certificate.checked_items + len(factor.obstruction.names)
        sources.extend(factor.certificate.source_modules)
        for discrepancy in factor.certificate.discrepancies:
            enriched = dict(discrepancy)
            enriched["factor"] = factor.name
            discrepancies.append(enriched)
        if not factor.zero_fiber_defined:
            discrepancies.append({
                "factor": factor.name,
                "check": "zero-fiber equation defined",
            })
    return Certificate(
        name="derived_solution_stack",
        exact=True,
        theorem_target="residual BPS-positive extension problems form finite derived zero-fiber substacks over the chambered Hall cosheaf",
        normalization="schema exactness is separate from named point construction",
        checked_items=checked,
        discrepancies=tuple(discrepancies),
        source_modules=tuple(dict.fromkeys(sources)),
    )


def constructed_named_points_certificate(bound: TruncationBound) -> Certificate:
    """Certificate for actual constructed points in the residual stack."""

    factors = derived_solution_stack_factors(bound)
    discrepancies = []
    for factor in factors:
        if not factor.solved:
            discrepancies.append({
                "factor": factor.name,
                "certificate_exact": factor.certificate.exact,
                "obstruction_computed": factor.obstruction.computed,
                "obstruction_vanishes": factor.obstruction.vanishes,
            })
    return Certificate(
        name="constructed_named_points",
        exact=False,
        theorem_target="actual named points of the residual BPS-positive solution stack",
        normalization="a point requires an exact certificate and a computed vanishing obstruction vector",
        checked_items=sum(len(factor.obstruction.names) for factor in factors),
        discrepancies=tuple(discrepancies),
        source_modules=("compute.lib.bps_positive_truncation",),
    )


def seven_extension_resolution_certificate(bound: TruncationBound) -> Certificate:
    """Aggregate certificate for the seven post-closure extension lanes."""

    certificates = [
        derived_solution_stack_certificate(bound),
        quintic_excert_surface_certificate(),
        schoen_banana_gluing_certificate(),
        k3e_unquotiented_radical_certificate(),
        theta_comparison_certificate(bound),
        hcs_named_obstruction_certificate(),
        master_truncation_certificate("K3xE_boundary", bound),
    ]
    discrepancies = []
    checked = 0
    sources = []
    for certificate in certificates:
        checked += certificate.checked_items
        sources.extend(certificate.source_modules)
        for discrepancy in certificate.discrepancies:
            enriched = dict(discrepancy)
            enriched["certificate"] = certificate.name
            discrepancies.append(enriched)
    return Certificate(
        name="seven_extension_resolution",
        exact=False,
        theorem_target="all seven extension lanes have exact certificate, quotient, comparison, or inscription target",
        normalization="foundations closed; named-example extensions are typed finite-first theorem slots",
        checked_items=checked,
        discrepancies=tuple(discrepancies),
        source_modules=tuple(dict.fromkeys(sources)),
    )


def master_truncation_certificate(
    geometry: Literal["C3", "conifold", "K3xE_boundary"],
    bound: TruncationBound,
) -> Certificate:
    truncation = finite_rank2_truncation(max_height=bound.N)
    certificates = [
        support_property_certificate(truncation, bound),
        orientation_certificate(truncation),
        hall_associativity_certificate(truncation),
        sector_descent_certificate(truncation),
    ]
    if bound.N > 1:
        certificates.append(
            transition_certificate(finite_rank2_truncation(bound.N - 1), truncation)
        )
    if geometry == "C3":
        certificates.append(toric_c3_collapse_certificate(bound.N + 1))
    elif geometry == "conifold":
        certificates.append(toric_conifold_collapse_certificate(bound.N + 4, bound.N))
    elif geometry == "K3xE_boundary":
        certificates.extend([
            ks_loop_holonomy_a2_certificate(max(5, bound.N)),
            igusa_normalization_certificate(),
        ])
    else:
        raise ValueError(f"unknown geometry: {geometry}")

    discrepancies = []
    checked = 0
    exact = True
    sources = []
    for certificate in certificates:
        checked += certificate.checked_items
        exact = exact and certificate.exact
        sources.extend(certificate.source_modules)
        for discrepancy in certificate.discrepancies:
            enriched = dict(discrepancy)
            enriched["certificate"] = certificate.name
            discrepancies.append(enriched)

    return Certificate(
        name=f"master_{geometry}",
        exact=exact,
        theorem_target=f"finite quotient certificate for {geometry}",
        normalization="finite-first chambered BPS positive geometry",
        checked_items=checked,
        discrepancies=tuple(discrepancies),
        source_modules=tuple(dict.fromkeys(sources)),
    )
