"""Donaldson-Thomas partition function of C^3 and plane partition combinatorics.

Ground truth from the literature:
  MacMahon (1916): the generating function for 3D partitions (plane partitions)
    M(q) = prod_{n>=1} 1/(1-q^n)^n = sum_{k>=0} p(k) q^k
  where p(k) counts the number of plane partitions of k.

  DT theory of C^3:
    Z^{DT}_{C^3}(q) = M(-q)^{chi(C^3,O)}
  For the resolved conifold or with chi = 1 (virtual Euler characteristic weight):
    Z^{DT}_{C^3}(q) = M(-q)

  Connection to the affine Yangian Y^+(gl_hat_1):
    The cohomological Hall algebra (CoHA) of C^3 is isomorphic to Y^+(gl_hat_1),
    the positive half of the affine Yangian of gl_1 (Schiffmann-Vasserot 2013,
    Rapcak-Soibelman-Yang-Zhao 2020). The CoHA multiplication encodes adding
    boxes to 3D partitions. The graded dimension of the degree-n component
    of Y^+(gl_hat_1) equals the number of plane partitions of n:
      dim Y^+(gl_hat_1)_n = p(n)
    This is because the CoHA has a basis indexed by plane partitions, with
    the grading given by the total number of boxes.

  The affine Yangian Y(gl_hat_1) has three sets of generators:
    e_j, f_j, psi_j  (j >= 0)
  with the positive half Y^+ generated by the e_j alone. The relations
  encode the box-adding structure of 3D partitions.

CONVENTIONS:
  - q = formal variable / fugacity
  - p(n) = number of plane partitions of n
  - M(q) = MacMahon function = prod_{n>=1} 1/(1-q^n)^n
  - chi = Euler characteristic weight (chi=1 for bare C^3)

KNOWN VALUES (OEIS A000219):
  p(0) = 1, p(1) = 1, p(2) = 3, p(3) = 6, p(4) = 13, p(5) = 24,
  p(6) = 48, p(7) = 86, p(8) = 160, p(9) = 282, p(10) = 500,
  p(11) = 859, p(12) = 1479, p(13) = 2485, p(14) = 4167, p(15) = 6879,
  p(16) = 11297, p(17) = 18334, p(18) = 29601, p(19) = 47330,
  p(20) = 75278
"""

from __future__ import annotations

from fractions import Fraction
from typing import Dict, List, Optional, Tuple


# ---------------------------------------------------------------------------
# Core: power series arithmetic over Q (exact rational coefficients)
# ---------------------------------------------------------------------------

def _poly_mul_trunc(a: List[Fraction], b: List[Fraction],
                    N: int) -> List[Fraction]:
    """Multiply two truncated power series (as lists of Fraction) mod q^N."""
    result = [Fraction(0)] * N
    la, lb = len(a), len(b)
    for i in range(min(la, N)):
        if a[i] == 0:
            continue
        for j in range(min(lb, N - i)):
            result[i + j] += a[i] * b[j]
    return result


def _poly_inv_trunc(a: List[Fraction], N: int) -> List[Fraction]:
    """Invert a power series a(q) mod q^N, assuming a[0] != 0.

    Uses the recursion: if a * b = 1 mod q^N, then
      b[0] = 1/a[0]
      b[n] = -(1/a[0]) * sum_{k=1}^{n} a[k] * b[n-k]
    """
    if a[0] == 0:
        raise ValueError("Cannot invert power series with zero constant term")
    inv_a0 = Fraction(1, 1) / a[0]
    result = [Fraction(0)] * N
    result[0] = inv_a0
    la = len(a)
    for n in range(1, N):
        s = Fraction(0)
        for k in range(1, min(n + 1, la)):
            s += a[k] * result[n - k]
        result[n] = -inv_a0 * s
    return result


# ---------------------------------------------------------------------------
# MacMahon function M(q) = prod_{n>=1} 1/(1-q^n)^n
# ---------------------------------------------------------------------------

def macmahon_coefficients(N: int) -> List[Fraction]:
    """Compute the first N coefficients of M(q) = prod_{n>=1} 1/(1-q^n)^n.

    Returns [M_0, M_1, ..., M_{N-1}] where M(q) = sum_k M_k q^k + O(q^N).
    All coefficients are exact (Fraction).

    Strategy: compute log M(q) = sum_{n>=1} n * sum_{m>=1} q^{mn}/m
            = sum_{n>=1} sum_{m>=1} n * q^{mn} / m
    then exponentiate.
    """
    # Step 1: compute log M(q) mod q^N
    log_coeffs = [Fraction(0)] * N
    for n in range(1, N):
        for m in range(1, N):
            nm = n * m
            if nm >= N:
                break
            # Contribution: n/m * q^{nm}
            # From log(1/(1-q^n)^n) = n * sum_{m>=1} q^{nm}/m
            log_coeffs[nm] += Fraction(n, m)

    # Step 2: exponentiate via exp(f) where f = log_coeffs, f[0] = 0
    # Recursion: g[n] = (1/n) * sum_{k=1}^{n} k * f[k] * g[n-k]
    g = [Fraction(0)] * N
    g[0] = Fraction(1)
    for n in range(1, N):
        s = Fraction(0)
        for k in range(1, n + 1):
            s += Fraction(k) * log_coeffs[k] * g[n - k]
        g[n] = s / Fraction(n)

    return g


def macmahon_coefficients_product(N: int) -> List[Fraction]:
    """Compute M(q) mod q^N by direct product expansion.

    M(q) = prod_{n=1}^{N-1} 1/(1-q^n)^n mod q^N.

    This is a second independent computation for cross-validation.
    """
    # Start with the constant series 1
    result = [Fraction(0)] * N
    result[0] = Fraction(1)

    for n in range(1, N):
        # Multiply by 1/(1-q^n)^n = (1/(1-q^n))^n
        # First compute 1/(1-q^n) mod q^N: this is 1 + q^n + q^{2n} + ...
        # Then raise to the n-th power.
        #
        # More efficiently: multiply by 1/(1-q^n) a total of n times.
        for _ in range(n):
            # Multiply result by 1/(1-q^n) = 1 + q^n + q^{2n} + ...
            # In-place: result[k] += result[k-n] for k = n, n+1, ..., N-1
            for k in range(n, N):
                result[k] += result[k - n]

    return result


def plane_partition_counts(N: int) -> List[int]:
    """Return [p(0), p(1), ..., p(N-1)] where p(k) = # of plane partitions of k.

    These are the coefficients of M(q) = prod_{n>=1} 1/(1-q^n)^n.
    """
    coeffs = macmahon_coefficients(N)
    return [int(c) for c in coeffs]


# ---------------------------------------------------------------------------
# DT partition function of C^3
# ---------------------------------------------------------------------------

def dt_partition_function_c3(N: int, chi: int = 1) -> List[Fraction]:
    """Compute Z^{DT}_{C^3}(q) = M(-q)^chi mod q^N.

    For chi = 1 (bare C^3): Z(q) = M(-q) = prod_{n>=1} 1/(1-(-q)^n)^n
      = prod_{n>=1} 1/(1-(-1)^n q^n)^n

    Parameters:
        N: truncation order
        chi: Euler characteristic weight (default 1)

    Returns list of Fraction coefficients [Z_0, Z_1, ..., Z_{N-1}].
    """
    # First compute M(-q) mod q^N by substituting q -> -q
    m_coeffs = macmahon_coefficients(N)
    # M(-q) = sum_k M_k (-q)^k = sum_k M_k (-1)^k q^k
    m_neg = [m_coeffs[k] * (Fraction(-1) ** k) for k in range(N)]

    if chi == 1:
        return m_neg
    elif chi == -1:
        return _poly_inv_trunc(m_neg, N)
    elif chi == 0:
        result = [Fraction(0)] * N
        result[0] = Fraction(1)
        return result
    elif chi > 0:
        # M(-q)^chi by repeated multiplication
        result = [Fraction(0)] * N
        result[0] = Fraction(1)
        for _ in range(chi):
            result = _poly_mul_trunc(result, m_neg, N)
        return result
    else:
        # chi < 0: compute M(-q)^{|chi|} then invert
        pos = dt_partition_function_c3(N, chi=-chi)
        return _poly_inv_trunc(pos, N)


# ---------------------------------------------------------------------------
# DT/GW vertex: the topological vertex contribution
# ---------------------------------------------------------------------------

def topological_vertex_empty(N: int) -> List[Fraction]:
    """The topological vertex C_{emptyset,emptyset,emptyset}(q).

    For all three partitions empty: C_{0,0,0}(q) = M(q)
    (the MacMahon function itself).

    This is the "bare" vertex that computes Z^{DT}_{C^3}.
    """
    return macmahon_coefficients(N)


# ---------------------------------------------------------------------------
# Affine Yangian Y^+(gl_hat_1): graded dimensions from box-counting
# ---------------------------------------------------------------------------

def yangian_graded_dimensions(N: int) -> List[int]:
    """Graded dimensions of Y^+(gl_hat_1), the positive half of the
    affine Yangian of gl_1.

    dim Y^+(gl_hat_1)_n = p(n) = number of plane partitions of n.

    The CoHA (cohomological Hall algebra) of C^3 is isomorphic to
    Y^+(gl_hat_1) as graded algebras (Schiffmann-Vasserot, RSYZ).
    The basis is indexed by 3D partitions = plane partitions.
    The multiplication encodes adding boxes to plane partitions.

    Returns [dim_0, dim_1, ..., dim_{N-1}].
    """
    return plane_partition_counts(N)


def yangian_character(N: int) -> List[Fraction]:
    """Character of Y^+(gl_hat_1) as a power series in q.

    chi_{Y^+}(q) = sum_{n>=0} dim(Y^+_n) q^n = M(q)

    This is the generating function proof that CoHA = Y^+:
    the character of Y^+ equals the MacMahon function.
    """
    return macmahon_coefficients(N)


# ---------------------------------------------------------------------------
# Plane partition enumeration (explicit, for small n)
# ---------------------------------------------------------------------------

def enumerate_plane_partitions(n: int) -> List[List[List[int]]]:
    """Enumerate all plane partitions of n (for small n).

    A plane partition of n is a 2D array pi[i][j] of nonnegative integers
    such that:
      - pi[i][j] >= pi[i+1][j]  (weakly decreasing along rows)
      - pi[i][j] >= pi[i][j+1]  (weakly decreasing along columns)
      - sum of all entries = n

    Returns list of plane partitions, each as a list of rows (weakly
    decreasing lists). Empty rows are omitted.

    WARNING: exponential growth. Only practical for n <= ~15.
    """
    if n == 0:
        return [[]]  # single empty partition

    results = []

    def _generate(remaining: int, max_row_shape: Optional[List[int]],
                  current: List[List[int]]):
        """Recursively generate plane partitions.

        Args:
            remaining: number of boxes left to place
            max_row_shape: upper bound for next row (from row above), or None
            current: rows built so far
        """
        if remaining == 0:
            results.append([row[:] for row in current])
            return

        if max_row_shape is not None and all(v == 0 for v in max_row_shape):
            return

        # Generate next row: a partition (weakly decreasing) whose parts
        # are bounded by max_row_shape (if given) and sum <= remaining.
        # Also bounded: largest part <= max_row_shape[0] if given.
        max_first = remaining
        max_cols = remaining  # at most remaining columns
        if max_row_shape is not None:
            max_first = min(max_first, max_row_shape[0])
            max_cols = len(max_row_shape)

        def _gen_row(pos: int, rem: int, prev_val: int, row_so_far: List[int]):
            """Generate a single row (weakly decreasing, bounded by max_row_shape)."""
            if rem == 0 or pos >= max_cols:
                if sum(row_so_far) > 0:
                    new_shape = row_so_far[:]
                    current.append(new_shape)
                    _generate(rem, new_shape, current)
                    current.pop()
                return

            upper = min(prev_val, rem)
            if max_row_shape is not None and pos < len(max_row_shape):
                upper = min(upper, max_row_shape[pos])

            # Try values from upper down to 0
            for v in range(upper, 0, -1):
                row_so_far.append(v)
                _gen_row(pos + 1, rem - v, v, row_so_far)
                row_so_far.pop()

            # Also try stopping the row here (remaining columns = 0)
            if sum(row_so_far) > 0:
                new_shape = row_so_far[:]
                current.append(new_shape)
                _generate(rem, new_shape, current)
                current.pop()

        _gen_row(0, remaining, max_first, [])

    _generate(n, None, [])
    return results


def plane_partition_volume(pp: List[List[int]]) -> int:
    """Compute the volume (total number of boxes) of a plane partition."""
    return sum(sum(row) for row in pp)


# ---------------------------------------------------------------------------
# CoHA multiplication structure (combinatorial model)
# ---------------------------------------------------------------------------

def can_add_box(pp: List[List[int]], i: int, j: int, k: int) -> bool:
    """Check if a box can be added at position (i, j, k) to a plane partition.

    A box at (i,j) with height k+1 can be added if:
      - pp[i][j] == k (we are stacking on top of existing column)
      - pp[i-1][j] >= k+1 if i > 0 (row monotonicity)
      - pp[i][j-1] >= k+1 if j > 0 (column monotonicity)

    The plane partition pp is given as pp[i][j] = height of column at (i,j).
    We extend with zeros for positions outside the given array.
    """
    def _get(ii: int, jj: int) -> int:
        if ii < 0 or jj < 0:
            return k + 1  # no constraint from outside
        if ii >= len(pp):
            return 0
        if jj >= len(pp[ii]):
            return 0
        return pp[ii][jj]

    current = _get(i, j)
    if current != k:
        return False

    # Check constraints from neighbors
    if i > 0 and _get(i - 1, j) < k + 1:
        return False
    if j > 0 and _get(i, j - 1) < k + 1:
        return False

    return True


def addable_boxes(pp: List[List[int]]) -> List[Tuple[int, int, int]]:
    """List all positions (i, j, k) where a box can be added.

    This is the combinatorial incarnation of the CoHA action:
    the e_0 generator of Y^+(gl_hat_1) acts by adding a single box.
    """
    if not pp:
        return [(0, 0, 0)]

    max_i = len(pp)
    max_j = max(len(row) for row in pp) if pp else 0
    max_k = max(max(row) for row in pp if row) if pp else 0

    positions = []
    for i in range(max_i + 1):
        for j in range(max_j + 1):
            for k in range(max_k + 1):
                if can_add_box(pp, i, j, k):
                    positions.append((i, j, k))

    return positions


# ---------------------------------------------------------------------------
# Asymptotics: Wright's formula for plane partitions
# ---------------------------------------------------------------------------

def wright_asymptotic(n: int) -> float:
    """Wright's asymptotic formula for p(n) as n -> infinity.

    p(n) ~ (zeta(3))^{7/36} / (2^{11/36} * 3^{1/2} * pi^{1/2} * n^{25/36})
           * exp(3 * (zeta(3))^{1/3} * (n/2)^{2/3} + C)

    where C is a complicated constant. The leading exponential is:
      p(n) ~ A * n^{-25/36} * exp(B * n^{2/3})
    with B = 3 * (zeta(3)/4)^{1/3} = 3 * (zeta(3))^{1/3} / 2^{2/3}.

    Returns the asymptotic estimate.
    """
    import math

    # zeta(3) = Apery's constant
    zeta3 = 1.2020569031595943

    # Leading exponential: exp(3 * (zeta(3)/4)^{1/3} * n^{2/3})
    B = 3.0 * (zeta3 / 4.0) ** (1.0 / 3.0)
    exponent = B * (n ** (2.0 / 3.0))

    # Prefactor
    A = (zeta3 ** (7.0 / 36.0)) / (
        (2.0 ** (11.0 / 36.0)) * math.sqrt(3.0) * math.sqrt(math.pi)
    )

    return A * (n ** (-25.0 / 36.0)) * math.exp(exponent)


# ---------------------------------------------------------------------------
# Verification: M(q) product formula cross-check
# ---------------------------------------------------------------------------

def verify_macmahon_two_methods(N: int) -> Dict[str, object]:
    """Cross-validate M(q) computation via log-exp vs direct product.

    Two independent algorithms:
      1. Log-exp: compute log M(q), exponentiate
      2. Direct product: multiply 1/(1-q^n) factors iteratively

    Returns verification dict.
    """
    coeffs_logexp = macmahon_coefficients(N)
    coeffs_product = macmahon_coefficients_product(N)

    match = all(coeffs_logexp[k] == coeffs_product[k] for k in range(N))
    first_diff = None
    if not match:
        for k in range(N):
            if coeffs_logexp[k] != coeffs_product[k]:
                first_diff = k
                break

    return {
        "N": N,
        "match": match,
        "first_discrepancy": first_diff,
        "coefficients_int": [int(c) for c in coeffs_logexp[:min(N, 30)]],
    }


def verify_dt_c3_signs(N: int) -> Dict[str, object]:
    """Verify the sign pattern of Z^{DT}_{C^3}(q) = M(-q).

    For the DT partition function with chi=1:
      Z(q) = M(-q) = sum_k (-1)^k p(k) q^k

    The DT invariants n_k = (-1)^k p(k) alternate in sign.
    """
    m_coeffs = macmahon_coefficients(N)
    dt_coeffs = dt_partition_function_c3(N, chi=1)

    sign_pattern = []
    for k in range(N):
        expected = m_coeffs[k] * (Fraction(-1) ** k)
        sign_pattern.append({
            "k": k,
            "p(k)": int(m_coeffs[k]),
            "(-1)^k p(k)": int(expected),
            "Z_k": int(dt_coeffs[k]),
            "match": dt_coeffs[k] == expected,
        })

    all_match = all(sp["match"] for sp in sign_pattern)

    return {
        "N": N,
        "all_signs_correct": all_match,
        "first_few": sign_pattern[:10],
    }


def verify_yangian_coha_dimensions(N: int) -> Dict[str, object]:
    """Verify dim Y^+(gl_hat_1)_n = p(n) for n = 0, ..., N-1.

    The cohomological Hall algebra of C^3 has a basis indexed by
    plane partitions. The degree-n component has dimension p(n).
    The multiplication (adding boxes) gives Y^+(gl_hat_1) structure.
    """
    yangian_dims = yangian_graded_dimensions(N)
    pp_counts = plane_partition_counts(N)

    match = yangian_dims == pp_counts
    character = yangian_character(N)
    macmahon = macmahon_coefficients(N)
    char_match = all(character[k] == macmahon[k] for k in range(N))

    return {
        "N": N,
        "dimensions_match_pp_counts": match,
        "character_equals_macmahon": char_match,
        "dims": yangian_dims[:min(N, 25)],
    }


# ---------------------------------------------------------------------------
# Full verification suite
# ---------------------------------------------------------------------------

def verify_all(N: int = 30) -> Dict[str, object]:
    """Run all verifications up to order N."""
    return {
        "macmahon_cross_check": verify_macmahon_two_methods(N),
        "dt_sign_pattern": verify_dt_c3_signs(N),
        "yangian_coha": verify_yangian_coha_dimensions(N),
        "plane_partition_counts": plane_partition_counts(min(N, 51)),
    }


# ---------------------------------------------------------------------------
# Runner
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    print("=" * 70)
    print("DT PARTITION FUNCTION OF C^3 — PLANE PARTITIONS & AFFINE YANGIAN")
    print("=" * 70)

    N = 51
    counts = plane_partition_counts(N)
    print(f"\nPlane partition counts p(0)..p(50):")
    for k in range(N):
        print(f"  p({k:2d}) = {counts[k]}")

    print(f"\nMacMahon cross-validation (two methods, N={N}):")
    cv = verify_macmahon_two_methods(N)
    print(f"  Match: {cv['match']}")

    print(f"\nDT partition function Z^DT_{{C^3}}(q) = M(-q), first 20 coefficients:")
    dt = dt_partition_function_c3(21, chi=1)
    for k in range(21):
        print(f"  Z_{k} = {int(dt[k])}")

    print(f"\nY^+(gl_hat_1) graded dimensions (= plane partition counts):")
    yd = verify_yangian_coha_dimensions(21)
    print(f"  Match: {yd['dimensions_match_pp_counts']}")
    print(f"  Character = MacMahon: {yd['character_equals_macmahon']}")

    print(f"\nWright asymptotics vs exact at n=50:")
    exact = counts[50]
    asymp = wright_asymptotic(50)
    print(f"  p(50) exact   = {exact}")
    print(f"  p(50) Wright  = {asymp:.0f}")
    print(f"  ratio         = {asymp / exact:.4f}")
