r"""Deformed chiral CE differential d_h for V_k(gl_1).

MATHEMATICAL FRAMEWORK
=======================

Construction 5.12 (constr:quantum-ce-deformation) introduces the deformed
differential on chiral CE cochains:

    d_h = d_CE + h_1 * partial_1 + h_2 * partial_2 + h_3 * partial_3

where (h_1, h_2, h_3) are the Omega-background parameters with h_1+h_2+h_3=0,
and partial_i = iota_{xi_i} is contraction with the equivariant vector field
xi_i = z_i d/dz_i on C^3.

This engine makes d_h EXPLICIT for the simplest case: V_k(gl_1), the rank-1
Kac-Moody vertex algebra (Heisenberg VOA) with single generator J(z) and OPE

    J(z)J(w) ~ k/(z-w)^2.

BAR GENERATORS
==============

The bar complex B(V_k(gl_1)) is generated by desuspended modes:

    s^{-1}J_{-n}   for n in Z

with cohomological degree |s^{-1}J_{-n}| = |J_{-n}| - 1 = 1 in this
CE model. Desuspension lowers cohomological degree by 1.
In the bar complex, arity-p elements are tensor products:

    s^{-1}J_{-n_1} tensor ... tensor s^{-1}J_{-n_p}

THE CE DIFFERENTIAL d_CE
========================

The chiral CE differential encodes the OPE/commutator structure:

(i) On arity 1 (single bar generator):
    d_CE(s^{-1}J_{-n}) = 0

    for gl_1, because the Lie algebra is ABELIAN: the first-order pole in
    J(z)J(w) vanishes, so the Lie bracket is zero, and d_CE on a single
    generator has no target.

(ii) On arity 2 (tensor of two generators):
    d_CE(s^{-1}J_{-m} tensor s^{-1}J_{-n})
        = [J_m, J_n] contracted into arity-1 bar elements
        = k*m*delta_{m+n,0} * (unit)

    More precisely, d_CE on B_2 -> B_1 is the dual of the Lie bracket.
    Since [J_m, J_n] = k*m*delta_{m+n,0} * 1 (central), the CE differential
    kills arity-2 elements when m+n != 0 and sends the diagonal elements to
    a scalar (the cocycle evaluating the central extension).

    In the CE complex (not the bar complex), the differential on C^2 -> C^3
    would use the bracket. In the bar complex (coalgebra side), the
    differential on B_2 -> B_1 is:

    d_CE(s^{-1}J_{-m} | s^{-1}J_{-n}) = k*m*delta_{m+n,0} * (vacuum element)

    This is the bar differential d_2 encoding the commutator.

THE EQUIVARIANT OPERATORS partial_i
=====================================

The equivariant vector fields xi_i = z_i d/dz_i on C^3 act on the mode
J_{-n} by its weight under the i-th C^* action. For V_k(gl_1) placed on the
i-th copy of C in C^3, a mode J_{-n} has weight n under xi_i and weight 0
under the other xi_j.

More generally, in the Omega-background on C^3, the three C^* actions
correspond to three independent gradings of the algebra. For a single gl_1
(one complex boson), the natural grading is:

    partial_i(s^{-1}J_{-n}) = w_i(n) * s^{-1}J_{-n}

where w_i(n) is the weight of the mode J_{-n} under the i-th torus action.

The SIMPLEST and most natural choice (holomorphic CS on C^3 with the boson
along the diagonal): w_i(n) = n for all i. This is the "diagonal embedding"
where J_{-n} carries weight n under each of the three torus rotations.

With this choice:
    partial_i(s^{-1}J_{-n}) = n * s^{-1}J_{-n}

and the deformation becomes:
    d_h(s^{-1}J_{-n}) = d_CE(s^{-1}J_{-n}) + (h_1 + h_2 + h_3)*n * s^{-1}J_{-n}
                       = 0 + 0  (since h_1+h_2+h_3 = 0)

This is the E_3 KOSZUL TRIVIALITY: for the Heisenberg (free field), the
deformed differential d_h is IDENTICALLY d_CE. The Omega-background does
NOT deform the free field, because the three equivariant weights are all
equal (diagonal embedding) and the calabi-yau condition h_1+h_2+h_3=0
forces the total deformation to vanish.

For a NON-DIAGONAL embedding (e.g. J_{-n} on the first coordinate with
w_1(n)=n, w_2(n)=0, w_3(n)=0), partial_1 acts nontrivially but
partial_2 = partial_3 = 0, and d_h = d_CE + h_1*n, which is generically
nonzero. This breaks the CY condition: the boson is not CY_3 but CY_1,
and the h_1+h_2+h_3=0 constraint does not help.

d_h^2 = 0 CONSTRAINT (general embedding)
==========================================

For a general embedding W = (w_1, w_2, w_3) (where partial_i acts as
w_i * n on the mode J_{-n}), the condition d_h^2 = 0 requires:

    h . W = h_1*w_1 + h_2*w_2 + h_3*w_3 = 0

This is the COMPATIBILITY between the Omega-background and the embedding.
For the diagonal embedding W = (1,1,1), this reduces to h_1+h_2+h_3 = 0
(the standard CY constraint). For general W, it is a stronger condition.

Physically: the CY condition means the determinant of the normal bundle is
trivial. The diagonal embedding is the unique (up to scale) embedding where
the CY constraint on h (h_1+h_2+h_3=0) automatically ensures d_h^2 = 0.
Non-diagonal embeddings require h to lie in the kernel of the weight
matrix, which generically constrains h beyond h_1+h_2+h_3=0.

The GENERAL multi-boson case (rank N): N bosons J^a_{-n} (a=1,...,N)
placed along different directions in C^3. Then:
    partial_i(s^{-1}J^a_{-n}) = w^a_i(n) * s^{-1}J^a_{-n}
where w^a_i(n) depends on the direction of the a-th boson in C^3.

WHAT THIS ENGINE COMPUTES
=========================

1. The CE differential d_CE on bar elements of V_k(gl_1), arity 1 and 2.
2. The equivariant operators partial_i for three embedding types:
   (a) Diagonal: w_i(n) = n for all i (CY_3 embedding)
   (b) Axis-aligned: w_1(n) = n, w_2 = w_3 = 0 (CY_1 embedding)
   (c) General: w_i(n) specified by a weight matrix
3. The full d_h = d_CE + h_1*partial_1 + h_2*partial_2 + h_3*partial_3.
4. Verification that d_h^2 = 0 when h_1+h_2+h_3 = 0.
5. Verification that d_h = d_CE for the diagonal (CY_3) embedding.
6. Arity-2 computation: d_h on tensor products s^{-1}J_{-m} | s^{-1}J_{-n}.

CONVENTIONS
===========
- k = level of V_k(gl_1) (the OPE coefficient). Denoted Psi in the coproduct
  engines for consistency with the Yangian literature.
- [J_m, J_n] = k*m*delta_{m+n,0}
- Bar generators: s^{-1}J_{-n} has cohomological degree 1.
- Koszul signs: standard (desuspension by 1).
- Mode numbering: J_{-n} creates, J_n annihilates (for n > 0).

MANUSCRIPT REFERENCES
=====================
- chapters/theory/quantum_chiral_algebras.tex, Construction 5.12
  (constr:quantum-ce-deformation), lines 400-412.
- chapters/theory/quantum_chiral_algebras.tex, Remark rem:e3-not-symmetric
  (the E_3 structure is nontrivial only AFTER deformation).
- compute/lib/e2_bar_complex.py: E_2 bar complex (d_Y = 0 for Heisenberg
  confirms our d_CE = 0 at arity 1).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from fractions import Fraction
from typing import Dict, List, Optional, Sequence, Tuple, Union

import numpy as np
from sympy import Rational, Symbol, expand, simplify, symbols


# =========================================================================
#  1. Bar generators and elements
# =========================================================================

@dataclass(frozen=True)
class BarGenerator:
    """A bar generator s^{-1}J_{-n} of the bar complex B(V_k(gl_1)).

    Attributes
    ----------
    mode : int
        The mode index n in J_{-n}. Convention: mode=n means the generator
        is s^{-1}J_{-n}. Positive n = creation modes, negative n = annihilation.
    """
    mode: int

    @property
    def degree(self) -> int:
        """Cohomological degree = |J_{-n}| - 1 = 1 in this CE model."""
        return 1

    def __repr__(self) -> str:
        return f"s^{{-1}}J_{{-{self.mode}}}"


@dataclass
class BarElement:
    """A linear combination of tensor products of bar generators.

    An element of B_p(V_k(gl_1)) is a linear combination of
    s^{-1}J_{-n_1} | ... | s^{-1}J_{-n_p} (arity p).

    Stored as a dictionary: {(n_1, ..., n_p): coefficient}.
    """
    terms: Dict[Tuple[int, ...], complex]

    @property
    def arity(self) -> Optional[int]:
        """Arity (bar degree). None if mixed or empty."""
        arities = {len(k) for k in self.terms if self.terms[k] != 0}
        if len(arities) == 1:
            return arities.pop()
        if len(arities) == 0:
            return 0
        return None  # mixed arity

    def __repr__(self) -> str:
        if not self.terms:
            return "0"
        parts = []
        for modes, coeff in sorted(self.terms.items()):
            if abs(coeff) < 1e-15:
                continue
            gens = " | ".join(f"s^{{-1}}J_{{-{n}}}" for n in modes)
            if abs(coeff - 1.0) < 1e-15:
                parts.append(f"[{gens}]")
            elif abs(coeff + 1.0) < 1e-15:
                parts.append(f"-[{gens}]")
            else:
                parts.append(f"{coeff}*[{gens}]")
        return " + ".join(parts) if parts else "0"

    def __add__(self, other: "BarElement") -> "BarElement":
        result = dict(self.terms)
        for k, v in other.terms.items():
            result[k] = result.get(k, 0.0) + v
        return BarElement(result)

    def __rmul__(self, scalar: complex) -> "BarElement":
        return BarElement({k: scalar * v for k, v in self.terms.items()})

    def __neg__(self) -> "BarElement":
        return BarElement({k: -v for k, v in self.terms.items()})

    def is_zero(self, tol: float = 1e-12) -> bool:
        return all(abs(v) < tol for v in self.terms.values())

    def cleaned(self, tol: float = 1e-12) -> "BarElement":
        """Remove near-zero terms."""
        return BarElement({k: v for k, v in self.terms.items() if abs(v) >= tol})

    @staticmethod
    def zero() -> "BarElement":
        return BarElement({})

    @staticmethod
    def basis(modes: Tuple[int, ...], coeff: complex = 1.0) -> "BarElement":
        """Create a basis element coeff * [s^{-1}J_{-n_1} | ... | s^{-1}J_{-n_p}]."""
        return BarElement({modes: coeff})


# =========================================================================
#  2. Weight data: equivariant embeddings into C^3
# =========================================================================

@dataclass
class EquivariantEmbedding:
    """Specifies how V_k(gl_1) sits inside the C^3 Omega-background.

    The three equivariant vector fields xi_i = z_i d/dz_i (i=1,2,3)
    act on the mode J_{-n} with weight w_i(n).

    Attributes
    ----------
    weight_fn : callable
        weight_fn(i, n) -> weight of J_{-n} under xi_i (i in {1,2,3}).
    name : str
        Human-readable name for the embedding type.
    """
    name: str
    _weight_fn: object  # callable (i: int, n: int) -> complex

    def weight(self, i: int, n: int) -> complex:
        """Weight of s^{-1}J_{-n} under the i-th equivariant action."""
        assert i in (1, 2, 3), f"i must be 1, 2, or 3, got {i}"
        return self._weight_fn(i, n)


def diagonal_embedding() -> EquivariantEmbedding:
    """Diagonal CY_3 embedding: w_i(n) = n for all i.

    This is the natural embedding for a single boson in C^3 where the mode
    J_{-n} couples equally to all three coordinates. The CY condition
    h_1+h_2+h_3=0 then ensures the total deformation vanishes.
    """
    return EquivariantEmbedding(
        name="diagonal",
        _weight_fn=lambda i, n: n,
    )


def axis_embedding(axis: int = 1) -> EquivariantEmbedding:
    """Axis-aligned embedding: w_axis(n) = n, w_j(n) = 0 for j != axis.

    This places the boson along a single coordinate axis in C^3. The
    deformation d_h = d_CE + h_axis * n does NOT vanish generically.
    """
    return EquivariantEmbedding(
        name=f"axis-{axis}",
        _weight_fn=lambda i, n, ax=axis: n if i == ax else 0,
    )


def general_embedding(W: np.ndarray) -> EquivariantEmbedding:
    """General embedding from a 3-vector of weights.

    W = (w_1, w_2, w_3): the mode J_{-n} has weight w_i * n under xi_i.

    d_h^2 = 0 requires h . W = h_1*w_1 + h_2*w_2 + h_3*w_3 = 0.
    The CY condition h_1+h_2+h_3=0 guarantees this only when W is
    proportional to (1,1,1) (the diagonal embedding).
    """
    assert W.shape == (3,), f"W must be a 3-vector, got shape {W.shape}"
    return EquivariantEmbedding(
        name=f"general({W[0]},{W[1]},{W[2]})",
        _weight_fn=lambda i, n, _W=W: _W[i - 1] * n,
    )


# =========================================================================
#  3. The deformed chiral CE differential engine
# =========================================================================

class DeformedChiralCE:
    """Engine for the deformed chiral CE differential d_h on B(V_k(gl_1)).

    d_h = d_CE + h_1 * partial_1 + h_2 * partial_2 + h_3 * partial_3

    Parameters
    ----------
    k : float
        Level of V_k(gl_1). This is kappa_{ch} in the kappa-spectrum.
    h : tuple of 3 complex numbers
        Omega-background parameters (h_1, h_2, h_3).
    embedding : EquivariantEmbedding
        How V_k(gl_1) sits in C^3.
    """

    def __init__(
        self,
        k: float = 1.0,
        h: Tuple[complex, complex, complex] = (0.0, 0.0, 0.0),
        embedding: Optional[EquivariantEmbedding] = None,
    ):
        self.k = k
        self.h1, self.h2, self.h3 = h
        self.embedding = embedding or diagonal_embedding()

    @property
    def h_sum(self) -> complex:
        """h_1 + h_2 + h_3. Must be 0 for d_h^2 = 0."""
        return self.h1 + self.h2 + self.h3

    @property
    def calabi_yau_satisfied(self) -> bool:
        """Check h_1 + h_2 + h_3 = 0."""
        return abs(self.h_sum) < 1e-12

    def h_dot_W(self, n: int = 1) -> complex:
        """Compute h . W(n) = h_1*w_1(n) + h_2*w_2(n) + h_3*w_3(n).

        This is the effective deformation weight on the mode J_{-n}.
        d_h^2 = 0 requires h . W = 0 for all n (which for linear weights
        w_i(n) = W_i * n reduces to h_1*W_1 + h_2*W_2 + h_3*W_3 = 0).

        For the diagonal embedding (W_i = 1), this is h_1 + h_2 + h_3.
        """
        return sum(
            hi * self.embedding.weight(i, n)
            for i, hi in enumerate([self.h1, self.h2, self.h3], start=1)
        )

    @property
    def embedding_compatible(self) -> bool:
        """Check h . W = 0 (necessary for d_h^2 = 0 at arity >= 3).

        For the abelian gl_1, d_h^2 = 0 at arity 2 is automatic (the
        cross-terms from d_CE and partial_i cancel independently). At
        arity 3, d_h^2 = 0 requires the full compatibility h . W = 0.
        """
        return abs(self.h_dot_W(1)) < 1e-12

    # ----- d_CE: the undeformed CE differential -----

    def d_CE_arity1(self, n: int) -> BarElement:
        """d_CE(s^{-1}J_{-n}) for a single bar generator.

        For gl_1 (abelian Lie algebra): d_CE = 0 on arity-1 elements.
        The CE differential of an abelian Lie algebra is zero on degree-1
        cochains because there is no Lie bracket to dualize.
        """
        return BarElement.zero()

    def d_CE_arity2(self, m: int, n: int) -> BarElement:
        r"""d_CE(s^{-1}J_{-m} | s^{-1}J_{-n}) on an arity-2 bar element.

        The bar differential d_2 on B_2 -> B_1 encodes the commutator:
            d_CE([s^{-1}J_{-m} | s^{-1}J_{-n}])
                = commutator contribution to arity 1
                = [J_{-m}, J_{-n}] expressed in bar generators

        For V_k(gl_1):
            [J_{-m}, J_{-n}] = k*(-m)*delta_{-m+(-n),0}
                              = -k*m*delta_{m+n,0}

        So d_CE is nonzero only when m + n = 0 (i.e. n = -m), and gives:

            d_CE([s^{-1}J_{-m} | s^{-1}J_{m}]) = -k*m * (vacuum bar element)

        The vacuum bar element is the arity-0 unit in the bar complex (a scalar).
        We represent this as the empty tuple () with the appropriate coefficient.

        Sign convention: d_bar on [a|b] = a*b - (-1)^{|a||b|} b*a in the universal
        enveloping algebra. With |a|=|b|=1 (bar degree), this is a*b + b*a.
        For the Heisenberg: J_{-m}*J_{-n} + J_{-n}*J_{-m} = [J_{-m}, J_{-n}]
        (since gl_1 is abelian, the product in U(gl_1) is commutative, and the
        antisymmetrization gives the bracket). Actually in the Lie algebra context:

        The CE differential on the exterior algebra Lambda^*(g^*) is dual to the
        bracket. On the bar complex B(g) = T^c(g[1]), the differential is:

            d_2([a|b]) = [a, b]   (the Lie bracket, landing in arity 1)

        For our conventions with s^{-1}J modes:
            d_CE([s^{-1}J_{-m} | s^{-1}J_{-n}]) corresponds to [J_{-m}, J_{-n}]

        Since [J_{-m}, J_{-n}] = k*(-m)*delta_{m+n,0} is a SCALAR (central
        extension), it maps to the arity-0 piece (a scalar coefficient).

        We include the Koszul sign: for two degree-1 elements a, b,
            d_2([a|b]) = (-1)^{|a|} [a, b] = -[a, b]
        (the sign comes from the bar desuspension convention).

        Result: d_CE([s^{-1}J_{-m} | s^{-1}J_{-n}]) = -[J_{-m}, J_{-n}]
              = k*m*delta_{m+n,0} * (scalar)
        """
        if m + n != 0:
            return BarElement.zero()
        # m + n = 0, so n = -m.
        # [J_{-m}, J_{-n}] = [J_{-m}, J_m] = k*(-m)*delta_{0,0} = -k*m
        # With Koszul sign: d_CE = -[J_{-m}, J_m] = k*m
        coeff = self.k * m
        if abs(coeff) < 1e-15:
            return BarElement.zero()
        return BarElement({(): coeff})

    # ----- partial_i: equivariant contraction operators -----

    def partial_i_arity1(self, i: int, n: int) -> BarElement:
        r"""partial_i(s^{-1}J_{-n}) = iota_{xi_i}(s^{-1}J_{-n}).

        The contraction iota_{xi_i} with the equivariant vector field
        xi_i = z_i d/dz_i acts on bar generators by the weight:

            partial_i(s^{-1}J_{-n}) = w_i(n) * s^{-1}J_{-n}

        where w_i(n) is the weight of J_{-n} under the i-th torus action,
        determined by the embedding type.

        On arity-1 elements, partial_i is multiplication by the weight.
        It maps B_1 -> B_0 (contraction reduces arity by 1 when acting on
        the "form" direction, but on the bar complex, iota_{xi_i} acts as
        a derivation). For a single generator:

            iota_{xi_i}(s^{-1}J_{-n}) = w_i(n) * (arity-0 unit)

        Actually, more precisely: iota_{xi_i} is a degree -1 derivation of
        the bar complex. On a single bar generator (arity 1, degree 1),
        it produces a degree-0, arity-0 element (a scalar).

        For the DIAGONAL embedding: w_i(n) = n, so
            partial_i(s^{-1}J_{-n}) = n * (scalar)
        """
        w = self.embedding.weight(i, n)
        if abs(w) < 1e-15:
            return BarElement.zero()
        return BarElement({(): w})

    def partial_i_arity2(self, i: int, m: int, n: int) -> BarElement:
        r"""partial_i(s^{-1}J_{-m} | s^{-1}J_{-n}).

        As a derivation of the bar complex, partial_i satisfies the Leibniz rule:

            partial_i([a|b]) = partial_i(a) * b + (-1)^{|a|} a * partial_i(b)

        where * denotes the shuffle product on the bar complex.

        For degree-1 generators a = s^{-1}J_{-m}, b = s^{-1}J_{-n}:
            partial_i([a|b]) = w_i(m) * s^{-1}J_{-n}
                             + (-1)^1 * w_i(n) * s^{-1}J_{-m}
                             = w_i(m) * [s^{-1}J_{-n}]
                             - w_i(n) * [s^{-1}J_{-m}]

        This maps arity-2 to arity-1 (contraction reduces arity).
        """
        wm = self.embedding.weight(i, m)
        wn = self.embedding.weight(i, n)
        result = BarElement.zero()
        if abs(wm) >= 1e-15:
            result = result + BarElement.basis((n,), wm)
        if abs(wn) >= 1e-15:
            result = result + BarElement.basis((m,), -wn)
        return result

    # ----- d_h: the full deformed differential -----

    def d_h_arity1(self, n: int) -> BarElement:
        r"""d_h(s^{-1}J_{-n}) = d_CE + h_1*partial_1 + h_2*partial_2 + h_3*partial_3.

        On arity-1 elements:
            d_CE(s^{-1}J_{-n}) = 0  (abelian)
            partial_i(s^{-1}J_{-n}) = w_i(n) * (scalar)

        So d_h(s^{-1}J_{-n}) = (h_1*w_1(n) + h_2*w_2(n) + h_3*w_3(n)) * (scalar)

        For DIAGONAL embedding (w_i(n) = n for all i):
            d_h(s^{-1}J_{-n}) = n*(h_1+h_2+h_3) * (scalar) = 0
            when h_1+h_2+h_3 = 0.

        This is the E_3 KOSZUL TRIVIALITY for the free field.
        """
        result = self.d_CE_arity1(n)  # = 0
        for idx, hi in enumerate([self.h1, self.h2, self.h3], start=1):
            if abs(hi) >= 1e-15:
                result = result + hi * self.partial_i_arity1(idx, n)
        return result

    def d_h_arity2(self, m: int, n: int) -> BarElement:
        r"""d_h(s^{-1}J_{-m} | s^{-1}J_{-n}).

        d_h = d_CE + h_1*partial_1 + h_2*partial_2 + h_3*partial_3

        On arity-2 elements, the result has components in arity 1 AND arity 0:

        Arity-0 component (from d_CE):
            d_CE([s^{-1}J_{-m} | s^{-1}J_{-n}]) = k*m*delta_{m+n,0} * (scalar)

        Arity-1 component (from partial_i):
            h_i * partial_i([s^{-1}J_{-m} | s^{-1}J_{-n}])
                = h_i * [w_i(m)*s^{-1}J_{-n} - w_i(n)*s^{-1}J_{-m}]

        Total arity-1 piece:
            sum_i h_i * [w_i(m)*s^{-1}J_{-n} - w_i(n)*s^{-1}J_{-m}]

        For DIAGONAL embedding:
            = m*(h_1+h_2+h_3)*s^{-1}J_{-n} - n*(h_1+h_2+h_3)*s^{-1}J_{-m}
            = 0 when h_1+h_2+h_3 = 0.

        So for the diagonal Heisenberg: d_h = d_CE at ALL arities.
        """
        result = self.d_CE_arity2(m, n)  # arity-0 piece
        for idx, hi in enumerate([self.h1, self.h2, self.h3], start=1):
            if abs(hi) >= 1e-15:
                result = result + hi * self.partial_i_arity2(idx, m, n)
        return result

    # ----- d_h^2 verification -----

    def d_h_squared_arity1(self, n: int) -> BarElement:
        r"""Compute d_h(d_h(s^{-1}J_{-n})) and verify it is zero.

        d_h maps arity 1 -> arity 0.
        d_h on arity 0 is zero (there's nothing below arity 0).
        So d_h^2 on arity 1 is automatically zero.

        This is trivial but we include it for completeness.
        """
        inner = self.d_h_arity1(n)
        # inner is an arity-0 element (scalar). d_h on scalars = 0.
        return BarElement.zero()

    def d_h_squared_arity2(self, m: int, n: int) -> BarElement:
        r"""Compute d_h(d_h(s^{-1}J_{-m} | s^{-1}J_{-n})).

        d_h on arity 2 produces:
            arity-0: k*m*delta_{m+n,0}
            arity-1: sum_i h_i * [w_i(m)*(n) - w_i(n)*(m)]
                     = sum_i h_i * [w_i(m)*s^{-1}J_{-n} - w_i(n)*s^{-1}J_{-m}]

        Then d_h on the arity-1 piece:
            d_h(coeff_n * s^{-1}J_{-n}) = coeff_n * d_h_arity1(n)
                = coeff_n * (h_1*w_1(n) + h_2*w_2(n) + h_3*w_3(n)) * (scalar)

        For the full d_h^2, we need:
            d_h applied to the arity-1 output of the first d_h.

        d_h^2 = 0 is guaranteed when h_1+h_2+h_3 = 0 for the diagonal
        embedding. For general embeddings, d_h^2 = 0 requires a more
        detailed analysis.
        """
        # First application: d_h on arity-2
        first = self.d_h_arity2(m, n)

        # The arity-0 part of `first` is killed by d_h (nothing below arity 0).
        # The arity-1 part of `first` needs d_h applied to it.
        result = BarElement.zero()
        for modes, coeff in first.terms.items():
            if abs(coeff) < 1e-15:
                continue
            if len(modes) == 1:
                # arity-1 element: coeff * s^{-1}J_{-modes[0]}
                inner = self.d_h_arity1(modes[0])
                result = result + coeff * inner
            # arity-0 elements (len(modes) == 0) are killed by d_h
        return result

    # ----- Higher arity: arity 3 -----

    def d_CE_arity3(self, m: int, n: int, p: int) -> BarElement:
        r"""d_CE(s^{-1}J_{-m} | s^{-1}J_{-n} | s^{-1}J_{-p}).

        The bar differential on arity-3 elements of an abelian Lie algebra:

            d_CE([a|b|c]) = [a,b] | c - [a,c] | b + [b,c] | a
                          (with Koszul signs for degree-1 elements)

        More precisely, the bar differential d_2 on B_3 -> B_2 is:
            d_2([a|b|c]) = -([a,b]|c) + ([a,c]|b) - ([b,c]|a)

        For abelian gl_1 with [J_{-m}, J_{-n}] = -k*m*delta_{m+n,0}:

            d_CE = -(-k*m*delta_{m+n,0})*[c] + (-k*m*delta_{m+p,0})*[b]
                   -(-k*n*delta_{n+p,0})*[a]

        where [c] means s^{-1}J_{-p} in arity 1, etc.

        Simplifying with Koszul signs for three degree-1 elements [a|b|c]:
        The standard bar differential is:
            d([a|b|c]) = [a*b|c] - [a|b*c]
        where a*b means the product in the Lie algebra (= bracket for CE).
        But for the COALGEBRA bar complex, it maps B_3 -> B_2:
            d_bar([a|b|c]) = [a,b] tensor c  -  a tensor [b,c]

        With signs (|a|=|b|=|c|=1 after desuspension, so shifted degree is 0):
            d_bar([a|b|c]) = [a,b]|c + (-1)^{|a'|} a|[b,c]
        where |a'| = |a|-1 = 0 (bar-shifted degree), so the sign is +.

        For the Chevalley-Eilenberg complex of an abelian Lie algebra:
            d_bar([a|b|c]) = [J_{-m}, J_{-n}] | s^{-1}J_{-p}
                           + s^{-1}J_{-m} | [J_{-n}, J_{-p}]

        Each bracket gives a scalar times the identity (central extension),
        so the result is in arity 1:

            = -k*m*delta_{m+n,0} * s^{-1}J_{-p}
            + (-k*n)*delta_{n+p,0} * s^{-1}J_{-m}

        Wait -- the bracket [J_{-n}, J_{-p}] = k*(-n)*delta_{n+p,0} = -k*n*delta_{n+p,0}.
        When this is nonzero (a scalar), it multiplies s^{-1}J_{-m} in arity 1.
        But scalars times bar generators... the scalar from the bracket replaces
        the two generators [b|c] with a scalar, leaving [a] * scalar.

        Let me be more careful. The bar differential d: B_3 -> B_2 is:
            d([a|b|c]) = mu(a,b)|c - a|mu(b,c)

        where mu is the Lie bracket. For gl_1:
            mu(J_{-m}, J_{-n}) = [J_{-m}, J_{-n}] = -k*m*delta_{m+n,0} * 1

        So mu maps to a SCALAR (the identity element in U(gl_1)). In the bar
        complex, a scalar times c means we get a single bar element:

            d([a|b|c]) = mu(a,b) * [c] - [a] * mu(b,c)

        where mu(a,b) is a scalar coefficient.

        Result:
            d_CE([s^{-1}J_{-m} | s^{-1}J_{-n} | s^{-1}J_{-p}])
                = -k*m*delta_{m+n,0} * [s^{-1}J_{-p}]
                - (-k*n*delta_{n+p,0}) * [s^{-1}J_{-m}]
                = -k*m*delta_{m+n,0} * [s^{-1}J_{-p}]
                + k*n*delta_{n+p,0} * [s^{-1}J_{-m}]
        """
        result = BarElement.zero()

        # First term: mu(J_{-m}, J_{-n}) | s^{-1}J_{-p}
        # [J_{-m}, J_{-n}] = -k*m*delta_{m+n,0}
        if m + n == 0:
            coeff1 = -self.k * m
            result = result + BarElement.basis((p,), coeff1)

        # Second term: -s^{-1}J_{-m} | mu(J_{-n}, J_{-p})
        # [J_{-n}, J_{-p}] = -k*n*delta_{n+p,0}
        # With the minus sign from the bar differential: -(-k*n*delta_{n+p,0})
        if n + p == 0:
            coeff2 = self.k * n
            result = result + BarElement.basis((m,), coeff2)

        return result

    def partial_i_arity3(self, i: int, m: int, n: int, p: int) -> BarElement:
        r"""partial_i on an arity-3 bar element.

        Leibniz rule for the degree -1 derivation partial_i:
            partial_i([a|b|c]) = w_i(m)*[b|c] - w_i(n)*[a|c] + w_i(p)*[a|b]

        (Signs from Koszul: partial_i past a degree-1 element picks up (-1)^1.)
        """
        wm = self.embedding.weight(i, m)
        wn = self.embedding.weight(i, n)
        wp = self.embedding.weight(i, p)
        result = BarElement.zero()
        if abs(wm) >= 1e-15:
            result = result + BarElement.basis((n, p), wm)
        if abs(wn) >= 1e-15:
            result = result + BarElement.basis((m, p), -wn)
        if abs(wp) >= 1e-15:
            result = result + BarElement.basis((m, n), wp)
        return result

    def d_h_arity3(self, m: int, n: int, p: int) -> BarElement:
        """d_h on an arity-3 bar element."""
        result = self.d_CE_arity3(m, n, p)
        for idx, hi in enumerate([self.h1, self.h2, self.h3], start=1):
            if abs(hi) >= 1e-15:
                result = result + hi * self.partial_i_arity3(idx, m, n, p)
        return result

    def d_h_squared_arity3(self, m: int, n: int, p: int) -> BarElement:
        r"""Compute d_h(d_h(s^{-1}J_{-m} | s^{-1}J_{-n} | s^{-1}J_{-p})).

        d_h maps arity 3 -> {arity 2, arity 1}.
        Then d_h on arity-2 pieces -> {arity 1, arity 0}.
        Then d_h on arity-1 pieces -> arity 0.
        We collect all contributions and check they cancel.
        """
        first = self.d_h_arity3(m, n, p)

        result = BarElement.zero()
        for modes, coeff in first.terms.items():
            if abs(coeff) < 1e-15:
                continue
            if len(modes) == 2:
                inner = self.d_h_arity2(modes[0], modes[1])
                result = result + coeff * inner
            elif len(modes) == 1:
                inner = self.d_h_arity1(modes[0])
                result = result + coeff * inner
            # arity-0 killed by d_h
        return result


# =========================================================================
#  4. Verification functions
# =========================================================================

def verify_d_CE_arity1(k: float = 1.0) -> Dict[str, object]:
    """d_CE(s^{-1}J_{-n}) = 0 for all n."""
    eng = DeformedChiralCE(k=k)
    all_zero = True
    for n in range(-5, 6):
        result = eng.d_CE_arity1(n)
        if not result.is_zero():
            all_zero = False
    return {"ok": all_zero, "description": "d_CE = 0 on arity 1 (abelian gl_1)"}


def verify_d_CE_arity2(k: float = 1.0) -> Dict[str, object]:
    """d_CE on arity-2 elements: nonzero only when m+n=0."""
    eng = DeformedChiralCE(k=k)
    errors = []

    # m + n != 0: should be zero
    for m in range(-3, 4):
        for n in range(-3, 4):
            if m + n == 0:
                continue
            result = eng.d_CE_arity2(m, n)
            if not result.is_zero():
                errors.append(f"d_CE([J_{{-{m}}}|J_{{-{n}}}]) nonzero but m+n={m+n}!=0")

    # m + n = 0: should give k*m * (scalar)
    for m in range(-3, 4):
        n = -m
        result = eng.d_CE_arity2(m, n)
        expected_coeff = k * m
        actual_coeff = result.terms.get((), 0.0)
        if abs(actual_coeff - expected_coeff) > 1e-12:
            errors.append(
                f"d_CE([J_{{-{m}}}|J_{{{m}}}]) = {actual_coeff}, "
                f"expected {expected_coeff}"
            )

    return {"ok": len(errors) == 0, "errors": errors}


def verify_d_h_equals_d_CE_diagonal(
    k: float = 1.0, h: Tuple[complex, complex, complex] = (1.0, -0.5, -0.5)
) -> Dict[str, object]:
    """For diagonal embedding with h1+h2+h3=0, d_h = d_CE at all arities.

    This is the E_3 Koszul triviality for the Heisenberg.
    """
    eng = DeformedChiralCE(k=k, h=h, embedding=diagonal_embedding())
    errors = []

    # Arity 1
    for n in range(-3, 4):
        dh = eng.d_h_arity1(n)
        dce = eng.d_CE_arity1(n)
        diff = dh + (-1.0) * dce
        if not diff.is_zero():
            errors.append(f"arity 1, n={n}: d_h != d_CE, diff = {diff}")

    # Arity 2
    for m in range(-2, 3):
        for n in range(-2, 3):
            dh = eng.d_h_arity2(m, n)
            dce = eng.d_CE_arity2(m, n)
            diff = dh + (-1.0) * dce
            if not diff.is_zero():
                errors.append(f"arity 2, m={m}, n={n}: d_h != d_CE, diff = {diff}")

    # Arity 3
    for m in range(-1, 2):
        for n in range(-1, 2):
            for p in range(-1, 2):
                dh = eng.d_h_arity3(m, n, p)
                dce = eng.d_CE_arity3(m, n, p)
                diff = dh + (-1.0) * dce
                if not diff.is_zero():
                    errors.append(
                        f"arity 3, ({m},{n},{p}): d_h != d_CE, diff = {diff}"
                    )

    return {
        "ok": len(errors) == 0,
        "errors": errors,
        "h_sum": abs(eng.h_sum),
        "description": "d_h = d_CE for diagonal embedding (E_3 Koszul triviality)",
    }


def verify_d_h_squared_zero(
    k: float = 1.0,
    h: Tuple[complex, complex, complex] = (1.0, -0.3, -0.7),
    embedding: Optional[EquivariantEmbedding] = None,
) -> Dict[str, object]:
    """d_h^2 = 0 at arities 1, 2, 3."""
    emb = embedding or diagonal_embedding()
    eng = DeformedChiralCE(k=k, h=h, embedding=emb)
    errors = []

    # Arity 1: d_h^2 automatically zero (maps to arity -1)
    for n in range(-3, 4):
        result = eng.d_h_squared_arity1(n)
        if not result.is_zero():
            errors.append(f"arity 1, n={n}: d_h^2 != 0, got {result}")

    # Arity 2
    for m in range(-2, 3):
        for n in range(-2, 3):
            result = eng.d_h_squared_arity2(m, n)
            if not result.is_zero():
                errors.append(f"arity 2, ({m},{n}): d_h^2 != 0, got {result}")

    # Arity 3
    for m in range(-1, 2):
        for n in range(-1, 2):
            for p in range(-1, 2):
                result = eng.d_h_squared_arity3(m, n, p)
                if not result.is_zero():
                    errors.append(
                        f"arity 3, ({m},{n},{p}): d_h^2 != 0, got {result}"
                    )

    return {
        "ok": len(errors) == 0,
        "errors": errors,
        "embedding": emb.name,
        "h": (eng.h1, eng.h2, eng.h3),
        "h_sum": abs(eng.h_sum),
    }


def verify_d_h_nontrivial_axis(
    k: float = 1.0,
    h: Tuple[complex, complex, complex] = (1.0, -0.3, -0.7),
) -> Dict[str, object]:
    """For axis embedding, d_h != d_CE generically (deformation is visible).

    The axis embedding places the boson along one coordinate. The equivariant
    weight is nonzero only for that coordinate, so partial_1 acts nontrivially
    while partial_2 = partial_3 = 0. The total deformation h_1*partial_1
    does not vanish (even though h_1+h_2+h_3=0).
    """
    emb = axis_embedding(axis=1)
    eng = DeformedChiralCE(k=k, h=h, embedding=emb)
    found_nontrivial = False

    for n in range(-3, 4):
        if n == 0:
            continue
        dh = eng.d_h_arity1(n)
        dce = eng.d_CE_arity1(n)
        diff = dh + (-1.0) * dce
        if not diff.is_zero():
            found_nontrivial = True
            break

    return {
        "ok": found_nontrivial,
        "description": "d_h != d_CE for axis embedding (deformation visible)",
    }


def verify_d_h_squared_axis_violates(
    k: float = 1.0,
    h: Tuple[complex, complex, complex] = (1.0, -0.3, -0.7),
) -> Dict[str, object]:
    """For axis embedding with CY constraint, d_h^2 = 0 still holds.

    Even though the axis embedding is not CY_3, the differential d_h^2 = 0
    for the Heisenberg because the Lie algebra is abelian. The key insight:
    d_CE = 0 on arity 1, and partial_i^2 = 0 (contraction squared vanishes),
    and the cross-terms d_CE * partial_i + partial_i * d_CE vanish because
    d_CE = 0 on arity 1.

    For non-abelian algebras, d_h^2 = 0 would genuinely require h1+h2+h3=0
    AND a specific embedding. For the abelian case, d_h^2 = 0 is automatic.
    """
    emb = axis_embedding(axis=1)
    eng = DeformedChiralCE(k=k, h=h, embedding=emb)
    errors = []

    for m in range(-2, 3):
        for n in range(-2, 3):
            result = eng.d_h_squared_arity2(m, n)
            if not result.is_zero():
                errors.append(f"arity 2, ({m},{n}): d_h^2 != 0, got {result}")

    return {
        "ok": len(errors) == 0,
        "errors": errors,
        "description": (
            "d_h^2 = 0 for axis embedding (automatic for abelian algebra)"
        ),
    }


def verify_arity2_explicit(k: float = 1.0) -> Dict[str, object]:
    r"""Explicit computation of d_h(s^{-1}J_{-m} | s^{-1}J_{-n}) for
    several (m, n) pairs with generic h.

    Expected results for diagonal embedding with h1+h2+h3=0:
        d_h = d_CE (Koszul triviality), so:
        - (m, n) with m+n != 0: d_h = 0
        - (m, -m): d_h = k*m * (scalar)

    Expected results for axis-1 embedding:
        d_h has additional arity-1 terms from partial_1.
    """
    results = {}

    # Diagonal
    h = (0.5 + 0.1j, -0.2 + 0.3j, -0.3 - 0.4j)
    eng_diag = DeformedChiralCE(k=k, h=h, embedding=diagonal_embedding())

    for m, n in [(1, -1), (2, -2), (1, 2), (0, 0), (1, 0), (-1, 1)]:
        dh = eng_diag.d_h_arity2(m, n)
        dce = eng_diag.d_CE_arity2(m, n)
        diff = dh + (-1.0) * dce
        results[f"diag_({m},{n})_equals_dCE"] = diff.is_zero()

    # Axis-1
    eng_axis = DeformedChiralCE(k=k, h=h, embedding=axis_embedding(1))

    # For axis-1: d_h has extra terms h_1 * partial_1
    # partial_1([s^{-1}J_{-m}|s^{-1}J_{-n}]) = m*s^{-1}J_{-n} - n*s^{-1}J_{-m}
    # So d_h = d_CE + h_1*(m*[J_{-n}] - n*[J_{-m}])
    dh_axis = eng_axis.d_h_arity2(1, -1)
    # d_CE part: k*1 = k (scalar)
    # partial_1 part: h_1*(1*s^{-1}J_1 - (-1)*s^{-1}J_{-1})
    #               = h_1*(s^{-1}J_1 + s^{-1}J_{-1})
    # So we expect arity-0 coeff k and arity-1 terms h_1*[J_1] and h_1*[J_{-1}]
    expected_scalar = k * 1  # from d_CE
    expected_J_neg1 = h[0] * (-1) * (-1)  # h_1 * (-(-1)) = h_1
    expected_J_1 = h[0] * 1  # h_1 * w_1(1) = h_1*1 on s^{-1}J_1 slot
    # partial_1([s^{-1}J_{-1}|s^{-1}J_1]) = w_1(1)*s^{-1}J_1 - w_1(-1)*s^{-1}J_{-1}
    # = 1*s^{-1}J_1 - (-1)*s^{-1}J_{-1} = s^{-1}J_1 + s^{-1}J_{-1}
    # So h_1*partial_1 gives h_1*s^{-1}J_1 + h_1*s^{-1}J_{-1} at arity 1

    actual_scalar = dh_axis.terms.get((), 0.0)
    actual_J_neg1 = dh_axis.terms.get((-1,), 0.0)  # coefficient of s^{-1}J_1
    actual_J_1 = dh_axis.terms.get((1,), 0.0)  # coefficient of s^{-1}J_{-1}

    results["axis_(1,-1)_scalar"] = abs(actual_scalar - k) < 1e-12
    results["axis_(1,-1)_J1_coeff"] = abs(actual_J_neg1 - h[0]) < 1e-12
    results["axis_(1,-1)_Jneg1_coeff"] = abs(actual_J_1 - h[0]) < 1e-12

    all_ok = all(results.values())
    return {"ok": all_ok, "details": results}


def verify_h_constraint_violation(k: float = 1.0) -> Dict[str, object]:
    """When h1+h2+h3 != 0, d_h^2 may fail for non-abelian algebras.

    For the abelian gl_1, d_h^2 = 0 regardless because d_CE is trivial.
    We verify this: even with h1+h2+h3 != 0, d_h^2 = 0 for the Heisenberg.
    """
    h_bad = (1.0, 1.0, 1.0)  # h1+h2+h3 = 3 != 0
    eng = DeformedChiralCE(k=k, h=h_bad, embedding=diagonal_embedding())

    assert not eng.calabi_yau_satisfied, "CY should be violated"

    errors = []
    for m in range(-2, 3):
        for n in range(-2, 3):
            result = eng.d_h_squared_arity2(m, n)
            if not result.is_zero():
                errors.append(f"({m},{n}): d_h^2 != 0")

    return {
        "ok": len(errors) == 0,
        "h_sum": eng.h_sum,
        "description": (
            "d_h^2 = 0 even with CY violation (abelian algebra is special)"
        ),
    }


def verify_general_embedding_compatible(k: float = 1.0) -> Dict[str, object]:
    """General non-diagonal embedding with h . W = 0 (compatible).

    W = (1, 2, -3) with h chosen so that h . W = h_1 + 2*h_2 - 3*h_3 = 0.
    This ensures d_h^2 = 0 at all arities.
    """
    W = np.array([1.0, 2.0, -3.0])
    # Choose h with h . W = 0: h_1 + 2*h_2 - 3*h_3 = 0
    # e.g. h = (1, -2, -1): 1 + (-4) - (-3) = 1 - 4 + 3 = 0.
    h = (1.0, -2.0, -1.0)  # h . W = 1 - 4 + 3 = 0
    emb = general_embedding(W)
    eng = DeformedChiralCE(k=k, h=h, embedding=emb)

    assert eng.embedding_compatible, f"h.W = {eng.h_dot_W(1)} should be 0"

    # d_h != d_CE (non-diagonal, but compatible)
    found_diff = False
    for n in range(-3, 4):
        if n == 0:
            continue
        dh = eng.d_h_arity1(n)
        dce = eng.d_CE_arity1(n)
        diff = dh + (-1.0) * dce
        if not diff.is_zero():
            found_diff = True
            break

    # d_h^2 = 0 at arity 2 and 3 (compatible embedding)
    errors = []
    for m in range(-2, 3):
        for n in range(-2, 3):
            result = eng.d_h_squared_arity2(m, n)
            if not result.is_zero():
                errors.append(f"arity2 ({m},{n})")

    for m in range(-1, 2):
        for n in range(-1, 2):
            for p in range(-1, 2):
                result = eng.d_h_squared_arity3(m, n, p)
                if not result.is_zero():
                    errors.append(f"arity3 ({m},{n},{p})")

    return {
        "ok": found_diff and len(errors) == 0,
        "nontrivial_deformation": found_diff,
        "d_h_squared_zero": len(errors) == 0,
        "h_dot_W": eng.h_dot_W(1),
    }


def verify_general_embedding_incompatible(k: float = 1.0) -> Dict[str, object]:
    """General non-diagonal embedding with h . W != 0 (incompatible).

    W = (1, 2, -3) with generic h satisfying h_1+h_2+h_3=0 but NOT h.W=0.
    d_h^2 should FAIL at arity 3 (but succeed at arity 2 for abelian gl_1).
    """
    W = np.array([1.0, 2.0, -3.0])
    h = (0.5, -0.2, -0.3)  # h . W = 0.5 - 0.4 + 0.9 = 1.0 != 0
    emb = general_embedding(W)
    eng = DeformedChiralCE(k=k, h=h, embedding=emb)

    assert not eng.embedding_compatible, f"h.W = {eng.h_dot_W(1)} should be nonzero"

    # d_h^2 at arity 2: still 0 (abelian)
    arity2_ok = True
    for m in range(-2, 3):
        for n in range(-2, 3):
            result = eng.d_h_squared_arity2(m, n)
            if not result.is_zero():
                arity2_ok = False
                break

    # d_h^2 at arity 3: should FAIL for some triples
    found_failure = False
    for m in range(-1, 2):
        for n in range(-1, 2):
            for p in range(-1, 2):
                result = eng.d_h_squared_arity3(m, n, p)
                if not result.is_zero():
                    found_failure = True
                    break
            if found_failure:
                break
        if found_failure:
            break

    return {
        "ok": arity2_ok and found_failure,
        "arity2_ok": arity2_ok,
        "arity3_fails": found_failure,
        "h_dot_W": eng.h_dot_W(1),
        "description": (
            "Incompatible embedding: d_h^2=0 at arity 2 (abelian), "
            "d_h^2!=0 at arity 3 (h.W != 0)"
        ),
    }


# =========================================================================
#  5. Full verification suite
# =========================================================================

def verify_all() -> Dict[str, object]:
    results = {}

    print("=" * 72)
    print("DEFORMED CHIRAL CE DIFFERENTIAL d_h FOR V_k(gl_1)")
    print("Construction 5.12 (constr:quantum-ce-deformation)")
    print("=" * 72)
    print()
    print("d_h = d_CE + h_1*partial_1 + h_2*partial_2 + h_3*partial_3")
    print("OPE: J(z)J(w) ~ k/(z-w)^2  (no first-order pole)")
    print()

    print("Step 1: d_CE = 0 on arity-1 (abelian Lie algebra)")
    r = verify_d_CE_arity1(k=1.0)
    results["d_CE_arity1"] = r
    print(f"  ok={r['ok']}")

    print("Step 2: d_CE on arity-2 (commutator [J_{-m}, J_{-n}] = -k*m*delta)")
    for kval in [1.0, 2.0, 0.5]:
        r = verify_d_CE_arity2(k=kval)
        results[f"d_CE_arity2_k={kval}"] = r
        print(f"  k={kval}: ok={r['ok']}, errors={len(r['errors'])}")

    print("Step 3: d_h = d_CE for diagonal embedding (E_3 Koszul triviality)")
    for h_vals in [(1.0, -0.5, -0.5), (0.3, -0.1, -0.2), (2.0, 1.0, -3.0)]:
        r = verify_d_h_equals_d_CE_diagonal(k=1.0, h=h_vals)
        results[f"diagonal_h={h_vals}"] = r
        print(f"  h={h_vals}: ok={r['ok']}, h_sum={r['h_sum']:.2e}")

    print("Step 4: d_h^2 = 0 (diagonal embedding, CY constraint)")
    for h_vals in [(1.0, -0.3, -0.7), (0.5 + 0.1j, -0.2 - 0.1j, -0.3)]:
        r = verify_d_h_squared_zero(k=1.0, h=h_vals)
        results[f"d_h_sq_diag_h={h_vals}"] = r
        print(f"  h={h_vals}: ok={r['ok']}")

    print("Step 5: d_h != d_CE for axis embedding (deformation visible)")
    r = verify_d_h_nontrivial_axis(k=1.0)
    results["axis_nontrivial"] = r
    print(f"  ok={r['ok']}")

    print("Step 6: d_h^2 = 0 for axis embedding (abelian automatic)")
    r = verify_d_h_squared_axis_violates(k=1.0)
    results["axis_d_h_sq"] = r
    print(f"  ok={r['ok']}")

    print("Step 7: Explicit arity-2 computation")
    r = verify_arity2_explicit(k=1.0)
    results["arity2_explicit"] = r
    print(f"  ok={r['ok']}, details={r['details']}")

    print("Step 8: CY constraint violation (h1+h2+h3 != 0)")
    r = verify_h_constraint_violation(k=1.0)
    results["h_violation"] = r
    print(f"  ok={r['ok']}, h_sum={r['h_sum']}")

    print("Step 9: General compatible embedding (h.W = 0)")
    r = verify_general_embedding_compatible(k=1.0)
    results["general_compatible"] = r
    print(f"  ok={r['ok']}, h.W={r['h_dot_W']}")

    print("Step 10: General incompatible embedding (h.W != 0)")
    r = verify_general_embedding_incompatible(k=1.0)
    results["general_incompatible"] = r
    print(
        f"  ok={r['ok']}, arity2_ok={r['arity2_ok']}, "
        f"arity3_fails={r['arity3_fails']}, h.W={r['h_dot_W']}"
    )

    print()
    print("=" * 72)
    all_ok = all(
        v["ok"] for v in results.values() if isinstance(v, dict) and "ok" in v
    )
    if all_ok:
        print("ALL CHECKS PASSED")
    else:
        for key, val in results.items():
            if isinstance(val, dict) and not val.get("ok", True):
                print(f"FAIL: {key}: {val}")
    print("=" * 72)

    return results


if __name__ == "__main__":
    verify_all()
