"""Drinfeld center of Rep^{E_1}(CoHA) and the E_1/E_2 passage.

Ground truth: The cohomological Hall algebra (CoHA) of C^3 is isomorphic
to Y^+(gl_hat_1), the positive half of the affine Yangian of gl_1
(Schiffmann-Vasserot arXiv:1211.1287, RSYZ arXiv:1910.10006).

The monograph claims (Part IV):
    Z(Rep^{E_1}(CoHA)) = Rep^{E_2}(Y(gl_hat_1))

i.e. the Drinfeld center of the E_1-monoidal representation category of
the CoHA recovers the E_2-braided representation category of the FULL
affine Yangian Y(gl_hat_1).  At the algebra level, this is the statement
that the Drinfeld double of Y^+(gl_hat_1) is the full affine Yangian.

This module verifies the claim computationally at low levels by:

1. DIMENSION CHECK: The full affine Yangian Y = Y^- * Y^0 * Y^+
   (triangular decomposition / PBW) has graded character
       ch_Y(q) = M(q)^2 * P(q)
   where M(q) = MacMahon function (3D partitions, character of Y^+)
   and P(q) = Euler product (1D partitions, character of the Cartan Y^0).

   Level 0: dim = 1
   Level 1: dim = 3  (generators: e_0, f_0, psi_1)
   Level 2: dim = 11

2. DRINFELD DOUBLE STRUCTURE: The Drinfeld double of a graded bialgebra A
   is D(A) = A^{*,cop} tensor A with the double cross product structure.
   For A = Y^+, D(A) has:
   - A = Y^+ (positive generators e_i)
   - A^{*,cop} = Y^- (negative generators f_i, dual to e_i)
   - The pairing induces the Cartan subalgebra Y^0 via [e_i, f_j] = psi_{i+j}

3. R-MATRIX: The universal R-matrix of the Drinfeld double is
       R = sum_i e_i tensor e^i  (sum over basis / dual basis)
   On the Fock representation, the R-matrix acts as:
       R(u) ~ g(u)^{product over boxes}
   where g(u) is the structure function of the affine Yangian.
   The key identity g(u)*g(-u) = 1 ensures unitarity R(u)R(-u) = 1.

4. YANG-BAXTER: The R-matrix satisfies the quantum Yang-Baxter equation
       R_{12}(u-v) R_{13}(u) R_{23}(v) = R_{23}(v) R_{13}(u) R_{12}(u-v)
   which is the E_2 structure (braiding) of the representation category.

CONVENTIONS:
    - h1, h2, h3: deformation parameters with h1 + h2 + h3 = 0 (CY condition)
    - sigma_2 = h1*h2 + h1*h3 + h2*h3, sigma_3 = h1*h2*h3
    - g(z) = (z-h1)(z-h2)(z-h3) / ((z+h1)(z+h2)(z+h3))  (structure function)
    - M(q) = prod_{n>=1} 1/(1-q^n)^n  (MacMahon, 3D partition generating fn)
    - P(q) = prod_{n>=1} 1/(1-q^n)    (Euler, 1D partition generating fn)

REFERENCES:
    Maulik-Okounkov arXiv:1211.1287 (quantum groups from geometry)
    Schiffmann-Vasserot arXiv:1211.1287 (CoHA and affine Yangian)
    Tsymbaliuk arXiv:1404.5240 (affine Yangian presentation)
    Drinfeld (1987) (Drinfeld double construction)
"""

from __future__ import annotations

from fractions import Fraction
from typing import Dict, List, Optional, Tuple

from sympy import (
    Rational,
    Symbol,
    cancel,
    expand,
    factorial,
    oo,
    series,
    simplify,
    symbols,
)


# ---------------------------------------------------------------------------
# Partition combinatorics (1D and 3D)
# ---------------------------------------------------------------------------

def ordinary_partition_counts(N: int) -> List[int]:
    """Compute p_1D(0), ..., p_1D(N-1) where p_1D(n) = # of 1D partitions of n.

    These are the coefficients of P(q) = prod_{n>=1} 1/(1-q^n).

    p_1D(0) = 1, p_1D(1) = 1, p_1D(2) = 2, p_1D(3) = 3, p_1D(4) = 5, ...
    (OEIS A000041)
    """
    coeffs = [0] * N
    coeffs[0] = 1
    for k in range(1, N):
        for n in range(k, N):
            coeffs[n] += coeffs[n - k]
    return coeffs


def plane_partition_counts(N: int) -> List[int]:
    """Compute p_3D(0), ..., p_3D(N-1) where p_3D(n) = # of plane partitions of n.

    These are the coefficients of M(q) = prod_{n>=1} 1/(1-q^n)^n.

    p_3D(0) = 1, p_3D(1) = 1, p_3D(2) = 3, p_3D(3) = 6, p_3D(4) = 13, ...
    (OEIS A000219)
    """
    # Use the direct product expansion: multiply by 1/(1-q^k) a total of k times
    coeffs = [Fraction(0)] * N
    coeffs[0] = Fraction(1)
    for k in range(1, N):
        for _ in range(k):
            for n in range(k, N):
                coeffs[n] += coeffs[n - k]
    return [int(c) for c in coeffs]


def _poly_mul_trunc(a: List[int], b: List[int], N: int) -> List[int]:
    """Multiply two truncated power series (integer coefficients) mod q^N."""
    result = [0] * N
    la, lb = len(a), len(b)
    for i in range(min(la, N)):
        if a[i] == 0:
            continue
        for j in range(min(lb, N - i)):
            result[i + j] += a[i] * b[j]
    return result


# ---------------------------------------------------------------------------
# Graded dimensions of Y^+, Y^-, Y^0, and the full Y(gl_hat_1)
# ---------------------------------------------------------------------------

def yangian_positive_dimensions(N: int) -> List[int]:
    """Graded dimensions of Y^+(gl_hat_1), the positive half.

    dim Y^+_n = p_3D(n) (plane partition count).
    Y^+ = CoHA(C^3) is generated by e_0, e_1, e_2, ... with the CoHA product.
    The PBW basis at degree n is indexed by plane partitions of n.
    """
    return plane_partition_counts(N)


def yangian_negative_dimensions(N: int) -> List[int]:
    """Graded dimensions of Y^-(gl_hat_1), the negative half.

    dim Y^-_n = p_3D(n) = dim Y^+_n (by the anti-involution e_i <-> f_i).
    Y^- is generated by f_0, f_1, f_2, ... (dual to e_0, e_1, e_2, ...).
    """
    return plane_partition_counts(N)


def yangian_cartan_dimensions(N: int) -> List[int]:
    """Graded dimensions of Y^0(gl_hat_1), the Cartan subalgebra.

    Y^0 is the commutative polynomial algebra generated by psi_0, psi_1, psi_2, ...
    where psi_j has degree j.  Since psi_0 is central (and typically set to a
    scalar in a representation), the algebra modulo psi_0 is:
        Y^0 / (psi_0 - c) = k[psi_1, psi_2, ...]
    with psi_j at degree j (j >= 1).

    The dimension of the degree-n component equals the number of ordinary
    partitions of n (ways to write n = sum of positive integers).

    For the FULL algebra (including psi_0): psi_0 at degree 0 contributes
    a polynomial factor, but in the grading where we only count total degree
    of psi_1, psi_2, ..., the dimension is p_1D(n).

    dim Y^0_n = p_1D(n) for n >= 0.
    """
    return ordinary_partition_counts(N)


def drinfeld_double_dimensions(N: int) -> List[int]:
    """Graded dimensions of the Drinfeld double Drin(Y^+) = Y(gl_hat_1).

    By the PBW theorem for the affine Yangian (triangular decomposition):
        Y(gl_hat_1) = Y^- * Y^0 * Y^+
    as a filtered/graded vector space, so:
        dim Y_n = sum_{a+b+c=n} dim(Y^-_a) * dim(Y^0_b) * dim(Y^+_c)

    This is the Cauchy product (convolution) M(q)^2 * P(q) evaluated at level n.

    Equivalently: ch_Y(q) = M(q)^2 * P(q) where
        M(q) = MacMahon function (ch_{Y^+} = ch_{Y^-})
        P(q) = Euler product (ch_{Y^0})
    """
    p3d = plane_partition_counts(N)
    p1d = ordinary_partition_counts(N)

    dims = []
    for n in range(N):
        total = 0
        for a in range(n + 1):
            for b in range(n - a + 1):
                c = n - a - b
                total += p3d[a] * p1d[b] * p3d[c]
        dims.append(total)
    return dims


def drinfeld_double_character_product(N: int) -> List[int]:
    """Compute ch_Y(q) = M(q)^2 * P(q) via power series multiplication.

    Independent calculation for cross-validation against the PBW sum.
    """
    p3d = plane_partition_counts(N)
    p1d = ordinary_partition_counts(N)

    # M(q)^2
    mac_sq = _poly_mul_trunc(p3d, p3d, N)
    # M(q)^2 * P(q)
    full = _poly_mul_trunc(mac_sq, p1d, N)
    return full


# ---------------------------------------------------------------------------
# The Drinfeld double: generators and relations at low levels
# ---------------------------------------------------------------------------

def level_decomposition(N: int) -> Dict[int, Dict[str, int]]:
    """Decompose the Drinfeld double level by level.

    At each level n, reports:
    - dim(Y^+_n): number of positive generators/monomials
    - dim(Y^-_n): number of negative generators/monomials
    - dim(Y^0_n): number of Cartan generators/monomials
    - dim(Y_n): total dimension (PBW convolution)
    - new_generators: generators appearing for the first time at this level

    Level 0: {1} (unit). No new generators (psi_0 is a scalar in representations).
    Level 1: e_0, f_0, psi_1. Three new generators. dim = 3.
    Level 2: e_0^2, e_1, ...; f_0^2, f_1, ...; psi_1^2, psi_2, ... dim = 11.
    """
    p3d = plane_partition_counts(N)
    p1d = ordinary_partition_counts(N)
    dd = drinfeld_double_dimensions(N)

    result = {}
    for n in range(N):
        # New generators at level n (from each sector independently)
        # For Y^+: new generators are e_0, ..., e_{n-1} at level <= n
        # but the 'new' ones at exactly level n contribute to the
        # difference dim(Y^+_n) - (monomials from lower generators).
        # This is the dimension of the space of indecomposable elements.
        #
        # For the positive half:
        # The generators are e_0, e_1, e_2, ... with wt(e_i) = 1 for all i
        # in the box-counting grading. So all generators live at level 1.
        # At level n, the basis consists of ordered monomials of n generators.
        #
        # Actually, the correct picture: e_i has degree 1 in the
        # charge/box-count grading (each e_i adds one box). The mode
        # index i is a SECONDARY grading (conformal weight).
        # If we use only the charge grading:
        #   dim Y^+_n = p_3D(n)  (confirmed)
        #   At charge 1: span{e_0} (one generator), p_3D(1) = 1. Check.
        #   At charge 2: span{e_0^2, e_1, ...} = 3 elements, p_3D(2) = 3. Check.
        #
        # So the number of "new generators" is:
        # n=0: 0 (unit only)
        # n=1: 3 (e_0, f_0, psi_1)
        # n>=2: all higher-level elements are built from products + new modes

        new_e = p3d[n] if n >= 1 else 0
        new_f = p3d[n] if n >= 1 else 0
        new_psi = p1d[n] if n >= 1 else 0

        result[n] = {
            "dim_Y_plus": p3d[n],
            "dim_Y_minus": p3d[n],
            "dim_Y_zero": p1d[n],
            "dim_total": dd[n],
            "description": _level_description(n, p3d[n], p1d[n]),
        }

    return result


def _level_description(n: int, p3d_n: int, p1d_n: int) -> str:
    """Human-readable description of the generators at level n."""
    if n == 0:
        return "Unit element. psi_0 is central (set to scalar in representations)."
    elif n == 1:
        return (
            f"Generators: e_0 (positive), f_0 (negative), psi_1 (Cartan). "
            f"Relations: [e_0, f_0] = psi_1 (up to normalization by 1/sigma_3). "
            f"dim Y^+_1 = {p3d_n}, dim Y^-_1 = {p3d_n}, dim Y^0_1 = {p1d_n}."
        )
    elif n == 2:
        return (
            f"Y^+_2 = span{{e_0^2, e_1, (third basis element)}} (3 plane partitions of 2). "
            f"Y^-_2 = span{{f_0^2, f_1, ...}} (3 elements). "
            f"Y^0_2 = span{{psi_1^2, psi_2}} (2 ordinary partitions of 2). "
            f"Cross-terms from products of lower-level elements contribute to total dim."
        )
    else:
        return (
            f"dim Y^+_{n} = p_3D({n}) = {p3d_n}, "
            f"dim Y^-_{n} = p_3D({n}) = {p3d_n}, "
            f"dim Y^0_{n} = p_1D({n}) = {p1d_n}."
        )


# ---------------------------------------------------------------------------
# Structure function and R-matrix
# ---------------------------------------------------------------------------

def structure_function(h1, h2, h3=None):
    """Return g(z) as a sympy expression.

    g(z) = (z - h1)(z - h2)(z - h3) / ((z + h1)(z + h2)(z + h3))

    Key properties:
        g(-z) = 1/g(z)   (inversion identity)
        g(0) = -1         (when h_i != 0)
        g(z) -> 1 as z -> infinity
    """
    if h3 is None:
        h3 = -(h1 + h2)
    z = Symbol("z")
    return (z - h1) * (z - h2) * (z - h3) / ((z + h1) * (z + h2) * (z + h3))


def verify_structure_function_inversion(h1, h2, h3=None):
    """Verify g(z) * g(-z) = 1 (the fundamental inversion identity).

    This identity ensures:
    1. The R-matrix is unitary: R(u) R(-u) = 1
    2. The Cartan (psi) generators commute: [psi_i, psi_j] = 0
    3. The structure constants phi_j vanish for even j: phi_{2k} = 0
       (actually phi_2 = 0 and phi_4 = 0, but phi_6 != 0 in general)

    Proof: g(-z) = prod (-z - h_a)/(-z + h_a) = prod (z + h_a)/(z - h_a) = 1/g(z).
    """
    if h3 is None:
        h3 = -(h1 + h2)
    z = Symbol("z")
    g_z = (z - h1) * (z - h2) * (z - h3) / ((z + h1) * (z + h2) * (z + h3))
    g_neg_z = (-z - h1) * (-z - h2) * (-z - h3) / ((-z + h1) * (-z + h2) * (-z + h3))

    product = cancel(g_z * g_neg_z)
    return {
        "g_times_g_neg": product,
        "is_one": product == 1,
        "description": "g(z)*g(-z) = 1 ensures R-matrix unitarity R(u)R(-u) = 1",
    }


def r_matrix_diagonal_fock(h1, h2, h3=None, partition=None):
    """Compute the diagonal R-matrix element on the Fock representation.

    For a partition lambda, the R-matrix element in the tensor product
    of two Fock modules F(v1) tensor F(v2) with spectral parameter
    u = v1 - v2 is (on the diagonal |lambda> tensor |mu> component):

        R(u)_{lambda,empty} = prod_{s in lambda} g(u + c(s))

    where c(s) = h1 * arm(s) + h2 * leg(s) is the content of box s = (i,j).
    Here arm(s) = lambda_i - j (arm length) and leg(s) = lambda'_j - i (leg length),
    but for the ADDITIVE content in the Fock space, c(i,j) = h1*i + h2*j
    (with 0-indexed rows and columns).

    For the simplest cases:
        R(u)_{empty,empty} = 1
        R(u)_{box,empty} = g(u)  (single box at (0,0), content = 0)
        R(u)_{(2),empty} = g(u) * g(u + h2)  (row of 2: boxes at (0,0),(0,1))
        R(u)_{(1,1),empty} = g(u) * g(u + h1)  (column of 2: boxes at (0,0),(1,0))

    Parameters:
        h1, h2: deformation parameters (h3 = -(h1+h2) by CY condition)
        partition: a list of row lengths [lambda_1, lambda_2, ...]
                   If None, returns 1 (empty partition).

    Returns:
        A sympy expression in the variable u (spectral parameter).
    """
    if h3 is None:
        h3 = -(h1 + h2)

    if partition is None or len(partition) == 0:
        return Rational(1)

    u = Symbol("u")
    g_z = structure_function(h1, h2, h3)
    z = Symbol("z")

    result = Rational(1)
    for i, row_len in enumerate(partition):
        for j in range(row_len):
            content = h1 * i + h2 * j
            g_val = g_z.subs(z, u + content)
            result = result * g_val

    return cancel(result)


def r_matrix_unitarity_check(h1, h2, h3=None, partition=None):
    """Verify R(u) * R(-u) = 1 for the diagonal R-matrix elements.

    This follows from g(z)*g(-z) = 1 applied to each factor:
        R(u) = prod_s g(u + c(s))
        R(-u) = prod_s g(-u + c(s))

    But g(-u + c) != 1/g(u + c) in general; rather g(-(u-c)) = g(c-u) = 1/g(u-c).
    So we need: g(u+c) * g(-u+c) which is NOT g(u+c)*g(-(u+c)) unless c=0.

    Wait: g(-u+c) = g(-(u-c)). And g(-w) = 1/g(w) for any w.
    So g(-(u-c)) = 1/g(u-c). This equals 1/g(u+c) only if c = -c, i.e. c = 0.

    The correct unitarity statement for the R-matrix is:
        R_{12}(u) R_{21}(-u) = 1
    where R_{21} involves swapping the two tensor factors, which effectively
    replaces the content function with its negation.

    For diagonal elements (no off-diagonal mixing): R_{21} = R with
    contents negated (from swapping the two Fock spaces).
    So: R_{12}(u)_{lambda,mu} * R_{21}(-u)_{lambda,mu} = 1 becomes
        [prod_s g(u + c(s))] * [prod_s g(-u - c(s))] = 1
    which IS g(w)*g(-w) = 1 for w = u+c(s). Check.

    Returns verification results.
    """
    if h3 is None:
        h3 = -(h1 + h2)

    if partition is None or len(partition) == 0:
        return {"is_unitary": True, "product": Rational(1)}

    u = Symbol("u")
    z = Symbol("z")
    g_z = structure_function(h1, h2, h3)

    r_u = Rational(1)
    r_neg_u_swapped = Rational(1)
    for i, row_len in enumerate(partition):
        for j in range(row_len):
            content = h1 * i + h2 * j
            # R_{12}(u) factor: g(u + c)
            r_u = r_u * g_z.subs(z, u + content)
            # R_{21}(-u) factor: g(-u - c) = g(-(u+c)) = 1/g(u+c)
            r_neg_u_swapped = r_neg_u_swapped * g_z.subs(z, -(u + content))

    product = cancel(r_u * r_neg_u_swapped)
    return {
        "is_unitary": product == 1,
        "product": product,
        "partition": partition,
    }


# ---------------------------------------------------------------------------
# Yang-Baxter equation check (on 1-dimensional spaces)
# ---------------------------------------------------------------------------

def yang_baxter_check_charge_1(h1, h2, h3=None):
    """Verify the Yang-Baxter equation for the R-matrix on charge-1 spaces.

    On the charge-(1,1,1) sector of F tensor F tensor F, all three
    Fock spaces have a single state |box>, so the R-matrix acts as
    scalars. The Yang-Baxter equation:

        R_{12}(u-v) R_{13}(u) R_{23}(v) = R_{23}(v) R_{13}(u) R_{12}(u-v)

    becomes (all scalar):

        g(u-v) * g(u) * g(v) = g(v) * g(u) * g(u-v)

    which is trivially satisfied (commutativity of multiplication).

    The NONTRIVIAL check starts at charge (2,2,2) where each Fock space
    has 2 states ({|2>, |1,1>}) giving a 2x2 matrix at each step.

    At charge (1,1,1): the check is trivial but confirms the framework.
    """
    if h3 is None:
        h3 = -(h1 + h2)

    u, v = symbols("u v")
    z = Symbol("z")
    g_z = structure_function(h1, h2, h3)

    R12 = g_z.subs(z, u - v)
    R13 = g_z.subs(z, u)
    R23 = g_z.subs(z, v)

    lhs = cancel(R12 * R13 * R23)
    rhs = cancel(R23 * R13 * R12)

    return {
        "lhs": lhs,
        "rhs": rhs,
        "match": cancel(lhs - rhs) == 0,
        "description": "YBE on charge-(1,1,1): trivially satisfied (scalar R-matrix)",
    }


def yang_baxter_check_charge_mixed(h1, h2, h3=None):
    """Check R-matrix consistency on mixed charge sectors.

    On the charge-(2,1,0) sector:
    - F_2: 2 states {|2>, |1,1>}
    - F_1: 1 state {|box>}
    - F_0: 1 state {|empty>}

    R_{12}(u-v) acts on F_2 tensor F_1: this is a 2x2 matrix (2 states x 1 state,
    but the R-matrix can mix the two states in F_2).
    R_{13}(u) acts on F_2 tensor F_0: trivial (empty partition).
    R_{23}(v) acts on F_1 tensor F_0: scalar g(v).

    For the DIAGONAL part of R_{12}:
    On |2> tensor |box>:
        R_{12}(u) = g(u) * g(u + h2)  (from boxes at (0,0),(0,1) in partition (2))
    On |1,1> tensor |box>:
        R_{12}(u) = g(u) * g(u + h1)  (from boxes at (0,0),(1,0) in partition (1,1))

    The ratio R_{diag}(|2>)/R_{diag}(|1,1>) = g(u+h2)/g(u+h1) measures
    the relative weight of the two charge-2 states, which encodes
    the BRAIDING structure (E_2 data).

    Returns the diagonal R-matrix elements and their ratio.
    """
    if h3 is None:
        h3 = -(h1 + h2)

    u = Symbol("u")
    z = Symbol("z")
    g_z = structure_function(h1, h2, h3)

    # R-matrix on charge-(2,0): two partitions of 2
    # Partition (2) = row of 2: boxes at (0,0), (0,1)
    r_row = g_z.subs(z, u) * g_z.subs(z, u + h2)
    # Partition (1,1) = column of 2: boxes at (0,0), (1,0)
    r_col = g_z.subs(z, u) * g_z.subs(z, u + h1)

    ratio = cancel(r_row / r_col)

    # Check: the ratio should equal g(u+h2)/g(u+h1)
    expected_ratio = cancel(g_z.subs(z, u + h2) / g_z.subs(z, u + h1))

    return {
        "R_row_partition": cancel(r_row),
        "R_col_partition": cancel(r_col),
        "ratio": ratio,
        "expected_ratio": expected_ratio,
        "ratio_match": cancel(ratio - expected_ratio) == 0,
        "description": (
            "Diagonal R-matrix on charge-2 Fock states. "
            "The ratio g(u+h2)/g(u+h1) measures the braiding asymmetry "
            "between row and column partitions -- this is the E_2 structure."
        ),
    }


# ---------------------------------------------------------------------------
# Drinfeld center dimension: categorical counting
# ---------------------------------------------------------------------------

def drinfeld_center_dimension_from_coha(N: int) -> Dict[str, object]:
    """Compute the dimension of the Drinfeld center at each level.

    For the Drinfeld center Z(Rep^{E_1}(Y^+)):
    The objects are pairs (M, beta) where M is a Y^+-module and
    beta_{V}: M tensor V -> V tensor M is a half-braiding for all V.

    At the algebra level, Z(Rep(A)) = Rep(Drin(A)) for a bialgebra A.
    So dim Z_n = dim Drin(Y^+)_n.

    The key prediction:
        dim Z_n = dim Y(gl_hat_1)_n = [q^n] M(q)^2 * P(q)

    where M(q) = MacMahon function and P(q) = Euler product.

    Returns comparison of both computation methods.
    """
    dd_pbw = drinfeld_double_dimensions(N)
    dd_product = drinfeld_double_character_product(N)

    match = dd_pbw == dd_product
    p3d = plane_partition_counts(N)
    p1d = ordinary_partition_counts(N)

    levels = {}
    for n in range(N):
        levels[n] = {
            "dim_center": dd_pbw[n],
            "dim_Y_plus": p3d[n],
            "dim_Y_minus": p3d[n],
            "dim_Y_zero": p1d[n],
            "cross_check_match": dd_pbw[n] == dd_product[n],
        }

    return {
        "N": N,
        "dimensions": dd_pbw,
        "all_cross_checks_pass": match,
        "levels": levels,
        "character_formula": "ch_Z(q) = M(q)^2 * P(q)",
    }


# ---------------------------------------------------------------------------
# E_1 -> E_2 passage: the braiding from the R-matrix
# ---------------------------------------------------------------------------

def e1_to_e2_braiding_data(h1, h2, h3=None, max_charge=3):
    """Compute the braiding data for the E_1 -> E_2 passage.

    The E_1 structure of Rep(Y^+) is the monoidal structure given by
    the coproduct Delta: Y^+ -> Y^+ tensor Y^+.

    The E_2 structure of Rep(Y) = Z(Rep(Y^+)) is the braiding given
    by the universal R-matrix.

    At charge n, the braiding is determined by:
        sigma: V_n tensor W_m -> W_m tensor V_n
        sigma = tau * R(u)
    where tau is the swap and R(u) is the R-matrix.

    This function computes the R-matrix data (diagonal elements) on
    the Fock representation up to the given charge.

    Returns a dict with R-matrix data organized by partition pair.
    """
    if h3 is None:
        h3 = -(h1 + h2)

    # Enumerate partitions at each charge
    partitions_by_charge = {}
    partitions_by_charge[0] = [()]
    partitions_by_charge[1] = [(1,)]
    partitions_by_charge[2] = [(2,), (1, 1)]
    if max_charge >= 3:
        partitions_by_charge[3] = [(3,), (2, 1), (1, 1, 1)]
    if max_charge >= 4:
        partitions_by_charge[4] = [(4,), (3, 1), (2, 2), (2, 1, 1), (1, 1, 1, 1)]

    u = Symbol("u")
    z = Symbol("z")
    g_z = structure_function(h1, h2, h3)

    r_matrix_data = {}
    for charge in range(max_charge + 1):
        if charge not in partitions_by_charge:
            break
        for lam in partitions_by_charge[charge]:
            # R(u)_{lambda,empty} = prod_{s in lambda} g(u + c(s))
            # where c(i,j) = h1*i + h2*j
            r_val = Rational(1)
            boxes = []
            for i, row_len in enumerate(lam):
                for j in range(row_len):
                    content = h1 * i + h2 * j
                    r_val = r_val * g_z.subs(z, u + content)
                    boxes.append((i, j, content))

            r_matrix_data[lam] = {
                "R_diagonal": cancel(r_val),
                "boxes": boxes,
                "charge": charge,
            }

    return {
        "h_params": (h1, h2, h3),
        "r_matrix_data": r_matrix_data,
        "partitions_by_charge": partitions_by_charge,
        "description": (
            "Diagonal R-matrix elements R(u)_{lambda,empty} on the Fock representation. "
            "These encode the E_2 braiding of Rep(Y(gl_hat_1)) = Z(Rep(Y^+(gl_hat_1)))."
        ),
    }


# ---------------------------------------------------------------------------
# Full verification suite
# ---------------------------------------------------------------------------

def verify_drinfeld_center_coha(N: int = 8, h1=None, h2=None) -> Dict[str, object]:
    """Run the full verification of Z(Rep^{E_1}(CoHA)) = Rep^{E_2}(Y(gl_hat_1)).

    Tests:
    1. Dimension matching at each level
    2. Cross-validation of character formula
    3. Structure function inversion identity
    4. R-matrix unitarity
    5. Yang-Baxter equation (trivial sector)
    6. Braiding data (E_1 -> E_2 passage)
    """
    if h1 is None:
        h1 = Rational(1)
    if h2 is None:
        h2 = Rational(2)
    h3 = -(h1 + h2)

    results = {}

    # 1. Dimension check
    results["dimensions"] = drinfeld_center_dimension_from_coha(N)

    # 2. Level decomposition
    results["level_decomposition"] = level_decomposition(min(N, 6))

    # 3. Structure function inversion
    results["inversion"] = verify_structure_function_inversion(h1, h2, h3)

    # 4. R-matrix unitarity (several partitions)
    unitarity_checks = {}
    for lam in [(), (1,), (2,), (1, 1), (2, 1)]:
        unitarity_checks[lam] = r_matrix_unitarity_check(h1, h2, h3, list(lam))
    results["unitarity"] = unitarity_checks

    # 5. Yang-Baxter
    results["yang_baxter_trivial"] = yang_baxter_check_charge_1(h1, h2, h3)
    results["yang_baxter_mixed"] = yang_baxter_check_charge_mixed(h1, h2, h3)

    # 6. Braiding data
    results["braiding"] = e1_to_e2_braiding_data(h1, h2, h3, max_charge=3)

    return results


# ---------------------------------------------------------------------------
# Generating function identity
# ---------------------------------------------------------------------------

def character_identity_check(N: int = 20) -> Dict[str, object]:
    """Verify the generating function identity for the Drinfeld center character.

    ch_{Z(Rep(Y^+))}(q) = ch_{Y(gl_hat_1)}(q) = M(q)^2 * P(q)

    where:
        M(q) = prod_{n>=1} 1/(1-q^n)^n  (MacMahon, plane partitions)
        P(q) = prod_{n>=1} 1/(1-q^n)    (Euler, ordinary partitions)

    This can also be written as:
        M(q)^2 * P(q) = [prod_{n>=1} 1/(1-q^n)^n]^2 * prod_{n>=1} 1/(1-q^n)
                       = prod_{n>=1} 1/(1-q^n)^{2n+1}

    So ch_Y(q) = prod_{n>=1} 1/(1-q^n)^{2n+1}.

    At each level n, the coefficient gives the total dimension of Y(gl_hat_1)_n.
    """
    # Method 1: M(q)^2 * P(q)
    p3d = plane_partition_counts(N)
    p1d = ordinary_partition_counts(N)
    mac_sq = _poly_mul_trunc(p3d, p3d, N)
    method1 = _poly_mul_trunc(mac_sq, p1d, N)

    # Method 2: direct product prod_{n>=1} 1/(1-q^n)^{2n+1}
    coeffs = [0] * N
    coeffs[0] = 1
    for k in range(1, N):
        multiplicity = 2 * k + 1
        for _ in range(multiplicity):
            for n in range(k, N):
                coeffs[n] += coeffs[n - k]

    match = method1 == coeffs

    return {
        "N": N,
        "method1_M2P": method1[:min(N, 15)],
        "method2_direct": coeffs[:min(N, 15)],
        "all_match": match,
        "product_formula": "ch_Y(q) = prod_{n>=1} 1/(1-q^n)^{2n+1}",
        "first_discrepancy": (
            None if match
            else next(i for i in range(N) if method1[i] != coeffs[i])
        ),
    }


# ---------------------------------------------------------------------------
# Runner
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    print("=" * 72)
    print("DRINFELD CENTER OF Rep^{E_1}(CoHA) = Rep^{E_2}(Y(gl_hat_1))")
    print("=" * 72)

    N = 10
    print(f"\n--- Graded dimensions (levels 0..{N-1}) ---")
    p3d = plane_partition_counts(N)
    p1d = ordinary_partition_counts(N)
    dd = drinfeld_double_dimensions(N)
    dd2 = drinfeld_double_character_product(N)

    print(f"{'Level':>6} {'Y^+':>6} {'Y^0':>6} {'Y^-':>6} {'Y (PBW)':>10} {'Y (M^2P)':>10} {'Match':>6}")
    for n in range(N):
        print(f"{n:>6} {p3d[n]:>6} {p1d[n]:>6} {p3d[n]:>6} {dd[n]:>10} {dd2[n]:>10} {'OK' if dd[n] == dd2[n] else 'FAIL':>6}")

    print(f"\n--- Character identity: M(q)^2 * P(q) = prod 1/(1-q^n)^(2n+1) ---")
    ci = character_identity_check(20)
    print(f"  Match: {ci['all_match']}")
    if not ci['all_match']:
        print(f"  First discrepancy at level {ci['first_discrepancy']}")

    print(f"\n--- Structure function inversion g(z)*g(-z) = 1 ---")
    inv = verify_structure_function_inversion(Rational(1), Rational(2))
    print(f"  g(z)*g(-z) = {inv['g_times_g_neg']}, is 1: {inv['is_one']}")

    print(f"\n--- R-matrix unitarity ---")
    for lam in [(), (1,), (2,), (1, 1), (2, 1)]:
        uc = r_matrix_unitarity_check(Rational(1), Rational(2), partition=list(lam))
        print(f"  lambda={lam}: R(u)*R_{'{21}'}(-u) = {uc['product']}, unitary: {uc['is_unitary']}")

    print(f"\n--- Yang-Baxter (charge-1 sector) ---")
    yb = yang_baxter_check_charge_1(Rational(1), Rational(2))
    print(f"  Match: {yb['match']}")

    print(f"\n--- Mixed charge R-matrix (braiding asymmetry) ---")
    mc = yang_baxter_check_charge_mixed(Rational(1), Rational(2))
    print(f"  R(partition (2)) / R(partition (1,1)) = {mc['ratio']}")
    print(f"  Expected g(u+h2)/g(u+h1): {mc['expected_ratio']}")
    print(f"  Match: {mc['ratio_match']}")

    print(f"\n--- Level decomposition ---")
    ld = level_decomposition(6)
    for n in range(6):
        d = ld[n]
        print(f"  Level {n}: dim = {d['dim_total']} "
              f"(Y^+ = {d['dim_Y_plus']}, Y^0 = {d['dim_Y_zero']}, Y^- = {d['dim_Y_minus']})")
