r"""E_3 factorization homology on configuration spaces of C^3 for chiral algebras.

MATHEMATICAL CONTENT
====================

The perturbative partition function of 6d holomorphic Chern-Simons on C^3 is
a sum over Feynman diagrams = integrals over configuration spaces Conf_n(C^3).
The E_3 operad organises these integrals via the framed little 3-disks action.

This is the C^3 analogue of the Costello-Francis-Gwilliam (CFG) perturbative
Chern-Simons construction, where the CS partition function on R^3 is computed
as a sum over configuration space integrals Conf_n(R^3).

CONFIGURATION SPACES
====================

  Conf_n(C^3) = {(z_1,...,z_n) in (C^3)^n : z_i != z_j for i != j}

Topological structure:
  - real dimension 6n (C^3 is R^6)
  - pi_1(Conf_2(C^3)) = pi_1(S^5) = 0 (trivially braided topologically)
  - Cohomology: H*(Conf_n(C^3); Q) is generated by classes
      omega_{ij} in H^5(Conf_n(C^3))
    (codimension of the diagonal in C^3 is 6, so the linking sphere is S^5,
     giving degree-5 generators instead of degree-1 as for Conf_n(C))

  The TOPOLOGICAL braiding is TRIVIAL (pi_1 = 0). The nontrivial E_3
  braiding arises from the Omega-background deformation (h_1, h_2, h_3)
  which twists the framing by equivariant parameters (AP154: this is the
  TOPOLOGICAL E_3 from configuration spaces, not the algebraic E_3 from
  the Deligne conjecture).

PROPAGATORS AND FEYNMAN RULES
==============================

The holomorphic CS propagator on C^3 is:

  P(z, w) = Omega^{-1} * dbar^{-1}(delta(z - w))

where Omega = dz_1 ^ dz_2 ^ dz_3 is the holomorphic volume form.

For each pair (i, j) with spectral parameters u_i, u_j:

  (1) Heisenberg (free field): P_ij ~ omega^{ab} / (z_i - z_j)^2
      where omega^{ab} is the CY pairing. Gives free-field correlators.

  (2) Yangian (one-loop deformed): P_ij has poles at z_i - z_j = +/- h_k,
      with residue given by the structure function g(u_i - u_j).

  (3) Quantum toroidal (two-parameter): P_ij depends on TWO spectral
      parameters (u, v) per pair, with the Zamolodchikov factorization
      R_ch(u, v) = R_1(u) R_2(v) R_12(u-v).

FORMALITY
=========

  Conf_n(R^3): formal (Kontsevich 1999). The real Fulton-MacPherson
      compactification has a formality quasi-isomorphism.
  Conf_n(C^3): formal (Kriz 1994). The complex FM compactification
      FM_n(C^3) is formal over Q, following from the formality of
      complex algebraic varieties (Deligne 1971, mixed Hodge theory).

  The formality of Conf_n(C^3) means:
    C*(Conf_n(C^3); Q) ~ H*(Conf_n(C^3); Q)
  as E_inf algebras over Q. At the chain level (integral coefficients),
  the E_3 structure is genuine and does NOT collapse to E_2 (AP-CY33).

FEYNMAN INTEGRAL COMPUTATION
=============================

The n-point Feynman integral on C^3 is:

  I_n(h_1, h_2, h_3) = int_{Conf_n(C^3)} prod_{edges (i,j)} P_{ij}

For gl_1 (abelian), the relevant Feynman diagrams are:
  - Tree: line graphs (n-1 propagators)
  - One-loop: cycle graphs (n propagators)
  - Higher: all connected graphs on n vertices

The E_3 operad action organises the integrals:
  - The E_1 factor (labeled-ordered) gives the tree-level product
  - The E_2 factor (braided) gives the one-loop corrections (YBE)
  - The E_3 factor (3d coherence) gives the two-loop corrections (ZTE)

KONTSEVICH INTEGRAL ANALOGUE
=============================

The Kontsevich invariant for knots in R^3 is the universal Vassiliev
invariant, computed as iterated integrals over Conf_n(R^3). The C^3
analogue would be:

  Z_K(h_1, h_2, h_3) = sum_n int_{Conf_n(C^3)} omega_1 ^ ... ^ omega_n

where the omega_i are holomorphic configuration space forms. This is
CONJECTURAL for C^3 (the knot-theoretic interpretation requires a
3-manifold, and C^3 is 6-real-dimensional; the relevant "knots" are
complex surfaces in C^3, not curves).

The connection: the Kontsevich integral on R^3 computes the universal
E_2 invariant (knot polynomials). The C^3 analogue would compute a
universal E_3 invariant, if it exists.

AP COMPLIANCE
=============

- The E_3 structure is TOPOLOGICAL (little 3-disks on Conf_n(C^3)),
  NOT algebraic (Deligne conjecture). AP154 distinction respected.
- pi_1(Conf_2(C^3)) = 0: topological braiding is trivial. Nontrivial
  braiding from Omega-background only. AP-CY3: E_2 != commutative.
- The connection to the quantum toroidal algebra is CONJECTURAL
  (depends on CY-A_3). AP-CY6/AP-CY14.
- The spectral parameter z in the propagator is the YANGIAN spectral
  parameter, NOT a worldsheet coordinate. AP-CY31.
- kappa_ch subscripted throughout. AP113.
- Miki automorphism is algebra-specific (U_{q,t}), NOT operadic. AP-CY22.
- Configuration space formality is over Q; chain-level E_3 may differ
  from rational E_3. AP-CY33.

CONVENTIONS
===========
  h_1, h_2, h_3: Omega-background parameters, h_1 + h_2 + h_3 = 0
  sigma_2 = h_1 h_2 + h_1 h_3 + h_2 h_3
  sigma_3 = h_1 h_2 h_3 = kappa (the Planck constant)
  Conf_n(X): ordered configuration space of n distinct points in X
  FM_n(X): Fulton-MacPherson compactification of Conf_n(X)

REFERENCES
==========
  Costello-Francis-Gwilliam, "Factorization algebras in QFT" (2021)
  Costello, "M-theory in the Omega-background" (2017)
  Kontsevich, "Operads and motives in deformation quantization" (1999)
  Kriz, "On the rational homotopy type of configuration spaces" (1994)
  Fulton-MacPherson, "A compactification of configuration spaces" (1994)
  Arnold, "On some topological invariants of algebraic functions" (1970)
"""

from __future__ import annotations

import math
from fractions import Fraction
from functools import lru_cache
from typing import Dict, List, Optional, Tuple

import numpy as np
from sympy import (
    Rational,
    Symbol,
    binomial,
    cancel,
    expand,
    factor,
    factorial,
    simplify,
    symbols,
)


# =========================================================================
# 1. Configuration space topology
# =========================================================================

def conf_space_real_dim(n: int, ambient_complex_dim: int = 3) -> int:
    """Real dimension of Conf_n(C^d).

    Conf_n(C^d) is an open submanifold of (C^d)^n = R^{2dn},
    so dim_R Conf_n(C^d) = 2*d*n.
    """
    return 2 * ambient_complex_dim * n


def linking_sphere_dim(ambient_complex_dim: int = 3) -> int:
    """Dimension of the linking sphere S^{2d-1} of the diagonal in C^d.

    The diagonal Delta_{ij} in C^d x C^d has real codimension 2d.
    The linking sphere is S^{2d-1}.

    For C^1 (d=1): S^1, giving degree-1 generators (Arnold relations)
    For C^2 (d=2): S^3, giving degree-3 generators
    For C^3 (d=3): S^5, giving degree-5 generators
    """
    return 2 * ambient_complex_dim - 1


def fundamental_group_conf2(ambient_complex_dim: int = 3) -> str:
    """Fundamental group of Conf_2(C^d).

    Conf_2(C^d) ~ C^d x (C^d - {0}) ~ C^d x S^{2d-1} x R+.
    pi_1(Conf_2(C^d)) = pi_1(S^{2d-1}):
      d=1: pi_1(S^1) = Z (braid group, nontrivial braiding)
      d=2: pi_1(S^3) = 0 (trivial)
      d=3: pi_1(S^5) = 0 (trivial)
    """
    sphere_dim = linking_sphere_dim(ambient_complex_dim)
    if sphere_dim == 1:
        return "Z"
    else:
        return "0"


def conf_space_betti_numbers(n: int, ambient_complex_dim: int = 3,
                              max_degree: int = 20) -> List[int]:
    """Betti numbers of Conf_n(C^d) in low degrees.

    By the Arnold-Cohen theorem (complex case), H*(Conf_n(C^d); Q) is
    generated by classes omega_{ij} of degree (2d-1) subject to:
      - omega_{ij} = (-1)^{2d} omega_{ji} = omega_{ji} (for d >= 1, even sign)
      - Arnold relation: omega_{ij} omega_{jk} + omega_{jk} omega_{ki}
                         + omega_{ki} omega_{ij} = 0

    For d=1: omega_{ij} in H^1, giving the Arnol'd presentation.
    For d=3: omega_{ij} in H^5.

    For n=2: H*(Conf_2(C^d)) = H*(S^{2d-1}), so
      Betti: b_0 = 1, b_{2d-1} = 1, all others 0.

    For general n: the Poincare polynomial is given by the formula
      P(Conf_n(C^d); t) = prod_{k=0}^{n-1} (1 + k*t^{2d-1})
    (Cohen 1976, Totaro 1996).

    Parameters
    ----------
    n : int
        Number of points.
    ambient_complex_dim : int
        Complex dimension d of the ambient space C^d.
    max_degree : int
        Compute Betti numbers up to this degree.

    Returns
    -------
    list of int
        Betti numbers b_0, b_1, ..., b_{max_degree}.
    """
    deg = 2 * ambient_complex_dim - 1  # degree of generators omega_{ij}

    # Poincare polynomial: prod_{k=0}^{n-1} (1 + k * t^deg)
    # Note: k=0 factor is (1 + 0) = 1, contributing nothing.
    # Effective product: prod_{k=1}^{n-1} (1 + k * t^deg)
    betti = [0] * (max_degree + 1)
    betti[0] = 1

    for k in range(1, n):
        # Multiply current polynomial by (1 + k * t^deg)
        new_betti = list(betti)
        for j in range(max_degree + 1):
            if betti[j] != 0 and j + deg <= max_degree:
                new_betti[j + deg] += k * betti[j]
        betti = new_betti

    return betti


def conf_space_euler_char(n: int, ambient_complex_dim: int = 3) -> int:
    """Euler characteristic of Conf_n(C^d).

    chi(Conf_n(C^d)) = n! for d >= 2 (a consequence of the product formula
    for the Poincare polynomial, evaluated at t = -1).

    For d=1: chi(Conf_n(C)) = n! as well (Arnold).

    Proof: P(t) = prod_{k=1}^{n-1} (1 + k*t^{2d-1}).
    At t=-1: product = prod_{k=1}^{n-1} (1 + k*(-1)^{2d-1})
                     = prod_{k=1}^{n-1} (1 - k)  if 2d-1 is odd (d >= 1)
    Wait: 2d-1 is always odd. So (-1)^{2d-1} = -1.
    product = prod_{k=1}^{n-1} (1 - k) = (1-1)(1-2)...(1-(n-1))
            = 0 * (-1) * ... * (2-n) = 0 for n >= 2.

    This is WRONG for chi. The Euler characteristic is:
    chi = prod_{k=0}^{n-1} (1 + k*(-1)^{2d-1}) = prod (1-k) = 0 for n >= 2.

    Correction: the formula above counts the UNORDERED configuration space.
    For the ORDERED configuration space Conf_n(C^d) (as an open algebraic
    variety), chi = n! by inclusion-exclusion on the arrangement complement.

    Actually: Conf_n(C^d) is the complement of a hyperplane arrangement
    (the diagonal arrangement) in C^{dn}. The Euler characteristic of
    a complex hyperplane complement is always a signed count related to
    the Mobius function of the intersection lattice.

    For the braid arrangement in C^n: chi(Conf_n(C)) = (-1)^n * n!
    (the Mobius function of the partition lattice).
    For C^d with d >= 2: chi(Conf_n(C^d)) = 0 for n >= 2 because the
    cohomology generators have odd degree (2d-1 is odd for d >= 1)
    and the product formula gives chi = prod_{k=1}^{n-1}(1-k) which
    vanishes at k=1.

    Returns chi(Conf_n(C^d)).
    """
    if n <= 1:
        return 1
    # For d >= 1: chi = prod_{k=0}^{n-1} (1 + k * (-1)^{2d-1})
    # = prod_{k=0}^{n-1} (1 - k) = 0 for n >= 2 (k=1 term is 0).
    return 0


def conf_space_total_betti(n: int, ambient_complex_dim: int = 3) -> int:
    """Total Betti number sum_{k} b_k(Conf_n(C^d)).

    For d >= 2: P(1) = prod_{k=1}^{n-1} (1+k) = n!.
    """
    if n <= 1:
        return 1
    result = 1
    for k in range(1, n):
        result *= (1 + k)
    return result  # = n!


# =========================================================================
# 2. Propagator and structure functions on C^3
# =========================================================================

def _g_rational(z: complex, h1: complex, h2: complex,
                h3: Optional[complex] = None) -> complex:
    """Rational structure function g(z) = prod(z-h_i)/prod(z+h_i).

    This is the one-parameter (Yangian) propagator kernel.
    Poles at z = -h_i, zeros at z = h_i.

    The spectral parameter z is a YANGIAN spectral parameter (AP-CY31),
    NOT a worldsheet coordinate.
    """
    if h3 is None:
        h3 = -(h1 + h2)
    numer = (z - h1) * (z - h2) * (z - h3)
    denom = (z + h1) * (z + h2) * (z + h3)
    if abs(denom) < 1e-30:
        raise ZeroDivisionError(f"g(z) pole at z={z}")
    return numer / denom


def _g_two_param(u: complex, v: complex, h1: complex, h2: complex,
                 h3: Optional[complex] = None) -> complex:
    """Two-parameter structure function g_ch(u,v) = g(u)*g(v)*g(u-v).

    The Zamolodchikov factorization: three factors from the three
    spectral parameter combinations in the E_3 braiding.

    Factor 1: g(u) = direction-1 braiding
    Factor 2: g(v) = direction-2 braiding
    Factor 3: g(u-v) = crossing factor (Miki kernel)
    """
    if h3 is None:
        h3 = -(h1 + h2)
    return (_g_rational(u, h1, h2, h3) *
            _g_rational(v, h1, h2, h3) *
            _g_rational(u - v, h1, h2, h3))


def propagator_heisenberg(z_ij: complex, omega_ab: complex = 1.0) -> complex:
    """Free-field (Heisenberg) propagator on C^3.

    P(z_i, z_j) = omega^{ab} / (z_i - z_j)^2

    For the rank-1 Heisenberg, omega^{ab} is the scalar CY pairing.
    The power 2 is from the holomorphic Green function on C^3 in the
    direction transverse to the Wilson line.

    Parameters
    ----------
    z_ij : complex
        Spectral parameter difference z_i - z_j.
    omega_ab : complex
        CY pairing coefficient.
    """
    if abs(z_ij) < 1e-30:
        raise ZeroDivisionError("Propagator at coincident points")
    return omega_ab / z_ij**2


def propagator_yangian(z_ij: complex, h1: complex, h2: complex,
                       h3: Optional[complex] = None) -> complex:
    """Yangian (one-loop deformed) propagator on C^3.

    P(z_i, z_j) = g(z_i - z_j)

    where g is the rational structure function. The poles at
    z_ij = +/- h_k encode the Omega-background deformation.
    """
    if h3 is None:
        h3 = -(h1 + h2)
    return _g_rational(z_ij, h1, h2, h3)


def propagator_toroidal(u_ij: complex, v_ij: complex,
                        h1: complex, h2: complex,
                        h3: Optional[complex] = None) -> complex:
    """Quantum toroidal (two-parameter) propagator on C^3.

    P(z_i, z_j) = g_ch(u_i - u_j, v_i - v_j)

    Two spectral parameters (u, v) from the two transverse directions
    beyond the Wilson line in C^3. The Zamolodchikov factorization
    R_ch(u,v) = R_1(u) * R_2(v) * R_12(u-v) is encoded in g_ch.

    The spectral parameters (u, v) arise from the Omega-background
    (epsilon_1, epsilon_2), NOT from the normal bundle grading
    directly (AP-CY20).
    """
    if h3 is None:
        h3 = -(h1 + h2)
    return _g_two_param(u_ij, v_ij, h1, h2, h3)


# =========================================================================
# 3. Feynman diagram integrals on Conf_n(C^3)
# =========================================================================

def tree_integral_n_points(
    n: int, h1: complex, h2: complex,
    h3: Optional[complex] = None,
    spectral_params: Optional[List[complex]] = None,
) -> complex:
    """Tree-level (E_1) Feynman integral on Conf_n(C^3).

    The tree-level diagram is a line graph: propagators connect
    consecutive points (1,2), (2,3), ..., (n-1,n).

    I_n^{tree} = prod_{k=1}^{n-1} g(u_k - u_{k+1})

    This is the labeled-ordered (E_1) contribution: the product
    over consecutively ordered pairs.

    Parameters
    ----------
    n : int
        Number of points.
    h1, h2 : complex
        Omega-background parameters.
    spectral_params : list of complex, optional
        Spectral parameters u_1, ..., u_n. If None, uses default
        evenly spaced values avoiding poles (AP-CY28).

    Returns
    -------
    complex
        Tree-level integral value.
    """
    if h3 is None:
        h3 = -(h1 + h2)
    if n <= 1:
        return 1.0

    if spectral_params is None:
        # Default: evenly spaced, far from poles at +/- h_i (AP-CY28)
        spectral_params = [3.7 + 1.1 * k for k in range(n)]

    assert len(spectral_params) == n, \
        f"Need {n} spectral params, got {len(spectral_params)}"

    result = 1.0
    for k in range(n - 1):
        z_diff = spectral_params[k] - spectral_params[k + 1]
        result *= _g_rational(z_diff, h1, h2, h3)
    return result


def one_loop_integral_n_points(
    n: int, h1: complex, h2: complex,
    h3: Optional[complex] = None,
    spectral_params: Optional[List[complex]] = None,
) -> complex:
    """One-loop (E_2) Feynman integral on Conf_n(C^3).

    The one-loop diagram is a cycle: propagators connect
    (1,2), (2,3), ..., (n-1,n), (n,1).

    I_n^{1-loop} = prod_{k=1}^{n} g(u_k - u_{k+1 mod n})

    This is the braided (E_2) contribution: the product around the
    full cycle, encoding the Yang-Baxter structure.

    For n=2: I_2 = g(u_1-u_2) * g(u_2-u_1) = g(z)*g(-z) = 1
    by the CY inversion identity.

    Returns
    -------
    complex
        One-loop integral value.
    """
    if h3 is None:
        h3 = -(h1 + h2)
    if n <= 1:
        return 1.0

    if spectral_params is None:
        spectral_params = [3.7 + 1.1 * k for k in range(n)]

    result = 1.0
    for k in range(n):
        z_diff = spectral_params[k] - spectral_params[(k + 1) % n]
        result *= _g_rational(z_diff, h1, h2, h3)
    return result


def two_loop_e3_integral(
    h1: complex, h2: complex,
    h3: Optional[complex] = None,
    spectral_params: Optional[List[complex]] = None,
) -> complex:
    """Two-loop (E_3) Feynman integral on Conf_3(C^3).

    The two-loop contribution for 3 points uses the Zamolodchikov
    factorization: all 3 pairwise propagators.

    I_3^{E_3} = prod_{1<=i<j<=3} g_ch(u_i - u_j, v_i - v_j)

    For the single-parameter (E_2) case, this reduces to
    prod g(u_i - u_j) which is the standard Yangian 3-point function.

    The E_3 CORRECTION to the pairwise product is the ZTE obstruction
    (Theorem thm:zte-failure): the factored S_{ijk} = R_{ij}R_{ik}R_{jk}
    fails the tetrahedron equation at O(kappa^2). AP-CY30: factored !=
    solved for higher coherence.

    Here we compute the FACTORED (pairwise) version. The genuine E_3
    correction requires the ZTE correction engine.
    """
    if h3 is None:
        h3 = -(h1 + h2)

    if spectral_params is None:
        spectral_params = [3.7, 4.8, 6.1]

    assert len(spectral_params) == 3

    u = spectral_params
    result = 1.0
    for i in range(3):
        for j in range(i + 1, 3):
            result *= _g_rational(u[i] - u[j], h1, h2, h3)
    return result


def two_loop_e3_integral_two_param(
    h1: complex, h2: complex,
    h3: Optional[complex] = None,
    u_params: Optional[List[complex]] = None,
    v_params: Optional[List[complex]] = None,
) -> complex:
    """Two-loop E_3 integral with two spectral parameters.

    Uses the two-parameter structure function g_ch(u, v) for each pair.
    This is the C^3 analogue with both transverse directions active.

    I_3^{E_3,2-param} = prod_{i<j} g_ch(u_i - u_j, v_i - v_j)
    """
    if h3 is None:
        h3 = -(h1 + h2)

    if u_params is None:
        u_params = [3.7, 4.8, 6.1]
    if v_params is None:
        v_params = [2.3, 3.5, 5.2]

    assert len(u_params) == 3
    assert len(v_params) == 3

    result = 1.0
    for i in range(3):
        for j in range(i + 1, 3):
            du = u_params[i] - u_params[j]
            dv = v_params[i] - v_params[j]
            result *= _g_two_param(du, dv, h1, h2, h3)
    return result


# =========================================================================
# 4. Formality of Conf_n(C^3)
# =========================================================================

def cohomology_algebra_generators(n: int,
                                   ambient_complex_dim: int = 3) -> Dict:
    """Generators and relations of H*(Conf_n(C^d); Q).

    Generators: omega_{ij} for 1 <= i < j <= n, of degree 2d-1.
    Number of generators: C(n, 2) = n(n-1)/2.

    Relations:
      (1) omega_{ij}^2 = 0 (graded commutativity, since deg is odd)
      (2) Arnold relation: omega_{ij} omega_{jk} + omega_{jk} omega_{ki}
                           + omega_{ki} omega_{ij} = 0
          for all distinct i, j, k.
      (3) omega_{ij} omega_{kl} = (-1)^{(2d-1)^2} omega_{kl} omega_{ij}
                                = -omega_{kl} omega_{ij}  (since (2d-1)^2 is odd)

    The FORMALITY statement (Kriz 1994, Totaro 1996):
      C*(Conf_n(C^d); Q) is formal, i.e., quasi-isomorphic to its
      cohomology as a CDGA (commutative differential graded algebra).

    For C^3 specifically:
      - Generators in degree 5
      - Arnold relations in degree 10
      - The E_3 operad action on the CDGA is via the formality
        quasi-isomorphism from C*(E_3; Q) to H*(E_3; Q)
      - OVER Q: E_3 collapses to E_2 (formality kills the chain-level
        content). AP-CY33: the physical content (Miki, ZTE, etc.) lives
        at the chain level.
    """
    deg = 2 * ambient_complex_dim - 1
    num_generators = n * (n - 1) // 2
    # Arnold relations: one per unordered triple
    num_arnold = n * (n - 1) * (n - 2) // 6  # = C(n, 3)

    generators = []
    for i in range(1, n + 1):
        for j in range(i + 1, n + 1):
            generators.append(f"omega_{{{i}{j}}}")

    return {
        "n": n,
        "ambient_dim": ambient_complex_dim,
        "generator_degree": deg,
        "num_generators": num_generators,
        "generators": generators,
        "num_arnold_relations": num_arnold,
        "is_formal": True,  # Kriz 1994
        "formality_source": "Kriz 1994 (complex algebraic varieties)",
        "chain_level_E3_nontrivial": True,  # AP-CY33
        "rational_E3_collapses_to_E2": True,  # AP-CY33
    }


# =========================================================================
# 5. E_3 operadic structure on Conf_n(C^3)
# =========================================================================

def e3_operad_space_dim(n: int) -> int:
    """Dimension of the E_3 operad space E_3(n).

    E_3(n) = Conf_n(D^3) (configuration of n labelled disks in the 3-disk).
    E_3(n) ~ Conf_n(R^3) (homotopy equivalent).

    As a space: E_3(n) has the homotopy type of the complement of the
    braid arrangement in R^{3n}. For n=2: E_3(2) ~ S^2.

    Returns the real dimension of E_3(n).
    """
    return 3 * n


def e3_action_on_algebra(
    n: int, h1: complex, h2: complex,
    h3: Optional[complex] = None,
) -> Dict:
    """The E_3 operad action on the boundary algebra of 6d hCS on C^3.

    The E_3(n) space of n-ary operations acts on the chiral algebra A
    by the n-fold OPE. The Omega-background (h_1, h_2, h_3) deforms
    the E_3 structure:

      At sigma_3 = 0 (self-dual point): E_3 reduces to E_inf.
      At generic sigma_3: nontrivial E_3 braiding from the equivariant
        deformation, NOT from the topology of Conf_2(C^3) (which has
        pi_1 = 0).

    Returns a summary of the E_3 structure at arity n.
    """
    if h3 is None:
        h3 = -(h1 + h2)
    sigma3 = h1 * h2 * h3

    is_self_dual = abs(sigma3) < 1e-30

    return {
        "arity": n,
        "E3_space_dim": e3_operad_space_dim(n),
        "sigma3": sigma3,
        "is_self_dual": is_self_dual,
        "E_n_level": "E_inf" if is_self_dual else "E_3",
        "braiding_source": "trivial (self-dual)" if is_self_dual
                           else "Omega-background deformation",
        "topological_braiding": "trivial (pi_1(Conf_2(C^3)) = 0)",
        "num_pairwise_propagators": n * (n - 1) // 2,
        "structure_function": "g(z) = prod(z-h_i)/prod(z+h_i)",
    }


# =========================================================================
# 6. Dunn additivity: E_3 = E_1 x E_1 x E_1
# =========================================================================

class DunnDecomposition:
    """Dunn additivity decomposition of E_3 into three E_1 factors.

    By Dunn: E_3 ~ E_1 tensor_{E_0} E_1 tensor_{E_0} E_1.
    Each E_1 factor corresponds to one complex direction in C^3.

    The three E_1 factors and their algebraic operations:
      Factor 1 (z_1, instanton): CoHA Hall product, param q = e^{h_1}
      Factor 2 (z_2, spectral):  Yangian spectral shift, param t = e^{-h_2}
      Factor 3 (z_3, Miki):      S_3 triality, param q_3 = (qt)^{-1}
    """

    def __init__(self, h1: complex, h2: complex,
                 h3: Optional[complex] = None):
        self.h1 = h1
        self.h2 = h2
        self.h3 = h3 if h3 is not None else -(h1 + h2)

    @property
    def sigma3(self) -> complex:
        return self.h1 * self.h2 * self.h3

    def factor_data(self) -> List[Dict]:
        """Data for each of the three E_1 factors."""
        return [
            {
                "factor": 1,
                "direction": "z_1 (instanton)",
                "parameter": self.h1,
                "operation": "CoHA Hall product",
                "E_n_contribution": "E_1 (native)",
            },
            {
                "factor": 2,
                "direction": "z_2 (spectral)",
                "parameter": self.h2,
                "operation": "Yangian spectral shift",
                "E_n_contribution": "E_1 -> E_2 (Drinfeld center)",
            },
            {
                "factor": 3,
                "direction": "z_3 (Miki)",
                "parameter": self.h3,
                "operation": "S_3 triality (Miki automorphism)",
                "E_n_contribution": "E_2 -> E_3 (derived center)",
            },
        ]

    def verify_cy_condition(self) -> bool:
        """Verify h_1 + h_2 + h_3 = 0."""
        return abs(self.h1 + self.h2 + self.h3) < 1e-12

    def e3_degeneration_chain(self) -> List[Dict]:
        """The E_3 -> E_2 -> E_1 degeneration under h_i -> 0.

        h_3 = 0: E_3 -> E_2 (Miki factor collapses)
        h_2 = 0: E_2 -> E_1 (spectral factor collapses)
        h_1 = 0: E_1 -> E_0 (instanton factor collapses)
        """
        return [
            {
                "step": "E_3 -> E_2",
                "condition": f"h_3 = {self.h3} -> 0",
                "lost_factor": "Miki (z_3)",
                "remaining_algebra": "Affine Yangian Y(gl_hat_1)",
            },
            {
                "step": "E_2 -> E_1",
                "condition": f"h_2 = {self.h2} -> 0",
                "lost_factor": "spectral (z_2)",
                "remaining_algebra": "Yangian Y(gl_1)",
            },
            {
                "step": "E_1 -> E_0",
                "condition": f"h_1 = {self.h1} -> 0",
                "lost_factor": "instanton (z_1)",
                "remaining_algebra": "Heisenberg (free field)",
            },
        ]


# =========================================================================
# 7. CY inversion and functional identities
# =========================================================================

def verify_cy_inversion(h1: complex, h2: complex,
                        h3: Optional[complex] = None,
                        n_points: int = 32,
                        tol: float = 1e-9) -> Tuple[bool, float]:
    """Verify g(z)*g(-z) = 1 (CY inversion identity).

    This is the fundamental identity of the CY structure function,
    following from h_1 + h_2 + h_3 = 0.

    Proof: g(z)*g(-z) = prod_i (z-h_i)/prod_i (z+h_i)
                        * prod_i (-z-h_i)/prod_i (-z+h_i)
                      = prod_i (z-h_i)(-z-h_i) / prod_i (z+h_i)(-z+h_i)
                      = prod_i (h_i^2 - z^2) / prod_i (h_i^2 - z^2) = 1.
    """
    if h3 is None:
        h3 = -(h1 + h2)

    max_res = 0.0
    for j in range(n_points):
        # Test points far from poles (AP-CY28)
        z = 3.7 + 1.3 * np.exp(2j * math.pi * (j + 0.37) / n_points)
        try:
            val = _g_rational(z, h1, h2, h3) * _g_rational(-z, h1, h2, h3)
            res = abs(val - 1.0)
            max_res = max(max_res, res)
        except ZeroDivisionError:
            continue

    return max_res < tol, max_res


def verify_two_param_inversion(h1: complex, h2: complex,
                               h3: Optional[complex] = None,
                               n_points: int = 32,
                               tol: float = 1e-9) -> Tuple[bool, float]:
    """Verify g_ch(u,v)*g_ch(-u,-v) = 1 (two-parameter CY inversion).

    Proof: g_ch(u,v) = g(u)*g(v)*g(u-v).
    g_ch(u,v)*g_ch(-u,-v) = g(u)g(-u) * g(v)g(-v) * g(u-v)g(-(u-v)) = 1*1*1 = 1.
    """
    if h3 is None:
        h3 = -(h1 + h2)

    max_res = 0.0
    for j in range(n_points):
        u = 3.7 + 1.1 * np.exp(2j * math.pi * (j + 0.23) / n_points)
        v = 5.2 + 0.9 * np.exp(2j * math.pi * (j + 0.61) / n_points)
        try:
            g_fwd = _g_two_param(u, v, h1, h2, h3)
            g_inv = _g_two_param(-u, -v, h1, h2, h3)
            res = abs(g_fwd * g_inv - 1.0)
            max_res = max(max_res, res)
        except ZeroDivisionError:
            continue

    return max_res < tol, max_res


def verify_one_loop_trivial(h1: complex, h2: complex,
                            h3: Optional[complex] = None,
                            tol: float = 1e-9) -> Tuple[bool, float]:
    """Verify the one-loop integral at n=2 is trivial.

    I_2^{1-loop} = g(u_1-u_2)*g(u_2-u_1) = g(z)*g(-z) = 1.

    This is the statement that the double braiding is trivial for
    the CY structure function (the S-matrix at charge 1 is 1).
    """
    if h3 is None:
        h3 = -(h1 + h2)

    z = 3.7 + 1.1j  # Far from poles (AP-CY28)
    val = one_loop_integral_n_points(
        2, h1, h2, h3,
        spectral_params=[0.0, -(3.7 + 1.1j)]
    )
    # Actually: we need z and -z
    val = _g_rational(z, h1, h2, h3) * _g_rational(-z, h1, h2, h3)
    res = abs(val - 1.0)
    return res < tol, res


def verify_tree_factorization(h1: complex, h2: complex,
                              h3: Optional[complex] = None,
                              n: int = 4,
                              tol: float = 1e-9) -> Tuple[bool, float]:
    """Verify tree integral factorizes: I_n^{tree} = prod g(u_k - u_{k+1}).

    This is the E_1 (labeled-ordered) property: the tree integral is
    a product over consecutive pairs, independent of the "internal"
    structure. The factorization is the content of E_1 coassociativity
    (automatic for the cofree tensor coalgebra T^c).
    """
    if h3 is None:
        h3 = -(h1 + h2)

    # Compute via the engine
    params = [3.7 + 1.1 * k for k in range(n)]
    I_tree = tree_integral_n_points(n, h1, h2, h3, params)

    # Compute by hand: product of consecutive g-values
    manual = 1.0
    for k in range(n - 1):
        manual *= _g_rational(params[k] - params[k + 1], h1, h2, h3)

    res = abs(I_tree - manual)
    return res < tol, res


# =========================================================================
# 8. FM compactification and boundary strata
# =========================================================================

def fm_compactification_strata(n: int,
                                ambient_complex_dim: int = 3) -> Dict:
    """Boundary strata of the Fulton-MacPherson compactification FM_n(C^d).

    FM_n(C^d) is a smooth manifold with corners, compactifying Conf_n(C^d).
    The boundary strata are indexed by nested subsets S = {S_1, ..., S_k}
    of {1, ..., n} (screens).

    The codimension-1 strata correspond to subsets S of size >= 2:
    the stratum where all points in S collide simultaneously.

    The number of codimension-1 strata is sum_{k=2}^{n} C(n,k) = 2^n - n - 1.

    Each stratum is a fiber bundle:
      FM_S x Conf_n/S(C^d) -> FM^{codim 1}
    where FM_S is the FM compactification of the colliding points
    and Conf_n/S is the configuration of the remaining points plus
    the collision point.

    For C^3: each codimension-1 stratum has (real) codimension 1 in FM_n.
    The forms omega_{ij} extend to FM_n and restrict to the strata
    as products of lower-arity forms.
    """
    num_codim1 = 2**n - n - 1
    # Number of all strata (indexed by nested partitions)
    # For the purpose of this engine, we enumerate only codim-1.

    strata = []
    for size in range(2, n + 1):
        count = math.comb(n, size)
        strata.append({
            "subset_size": size,
            "num_strata": count,
            "fiber": f"FM_{size} x Conf_{n-size+1}(C^{ambient_complex_dim})",
        })

    return {
        "n": n,
        "ambient_dim": ambient_complex_dim,
        "num_codim1_strata": num_codim1,
        "strata_by_size": strata,
        "smooth_with_corners": True,
        "extends_omega_ij": True,
        "formality": "Kriz 1994",
    }


# =========================================================================
# 9. The perturbative partition function sum
# =========================================================================

def perturbative_partition_function(
    max_n: int,
    h1: complex, h2: complex,
    h3: Optional[complex] = None,
    coupling: complex = 1.0,
) -> Dict:
    """Perturbative partition function of 6d hCS on C^3.

    Z_pert = 1 + sum_{n>=2} (coupling^n / n!) * I_n

    where I_n is the n-point Feynman integral on Conf_n(C^3).

    For gl_1 (abelian), only tree-level and one-loop diagrams contribute
    (no cubic vertex at the abelian level). The cubic vertex appears
    at the non-abelian level (gl_N for N >= 2).

    At abelian level:
      I_n^{tree} = prod_{k=1}^{n-1} g(u_k - u_{k+1})
      I_n^{1-loop} = prod_{k=1}^{n} g(u_k - u_{k+1 mod n})

    For n=2:
      I_2^{tree} = g(u_1 - u_2) (single propagator)
      I_2^{1-loop} = g(u_1-u_2)*g(u_2-u_1) = 1 (CY inversion)

    Returns a summary with perturbative contributions through order max_n.
    """
    if h3 is None:
        h3 = -(h1 + h2)

    contributions = {}
    z_total = 1.0 + 0j

    for n in range(2, max_n + 1):
        params = [3.7 + 1.1 * k for k in range(n)]
        tree = tree_integral_n_points(n, h1, h2, h3, params)
        loop = one_loop_integral_n_points(n, h1, h2, h3, params)
        weight = coupling**n / math.factorial(n)

        contributions[n] = {
            "tree": tree,
            "one_loop": loop,
            "weight": weight,
            "tree_weighted": tree * weight,
            "loop_weighted": loop * weight,
        }
        z_total += (tree + loop) * weight

    return {
        "max_order": max_n,
        "h1": h1, "h2": h2, "h3": h3,
        "sigma3": h1 * h2 * h3,
        "coupling": coupling,
        "Z_pert": z_total,
        "contributions": contributions,
    }


# =========================================================================
# 10. E_3 factorization homology integrals
# =========================================================================

def factorization_homology_c3_tree_level(
    h1: complex, h2: complex,
    h3: Optional[complex] = None,
    max_charge: int = 4,
) -> Dict:
    """Factorization homology int_{C^3} F at tree level (sigma_3 = 0 limit).

    At the self-dual point sigma_3 = 0, the E_3 structure reduces to
    E_inf (commutative). The factorization homology is:

      int_{C^3} F = F tensor H_*(C^3; k) = F

    (since H_*(C^3; k) = k, concentrated in degree 0). The tree-level
    partition function on C^3 is just the vacuum (no nontrivial topology).

    The nontrivial content emerges at one-loop (sigma_3 != 0):
    the Omega-background breaks E_inf to E_3, and the factorization
    homology integral gains perturbative corrections.

    For the Fock space at charge q: the plethystic logarithm of the
    partition function gives the single-particle spectrum.

    At tree level:
      Z_q = prod_{n=1}^{inf} 1/(1-q^n)^n  (MacMahon function)
    counting 3D partitions (plane partitions).

    This matches the C^3 DT partition function (MNOP 2006).
    """
    if h3 is None:
        h3 = -(h1 + h2)
    sigma3 = h1 * h2 * h3

    # MacMahon coefficients: number of plane partitions of n
    macmahon = [1]  # pp(0) = 1
    for n in range(1, max_charge + 1):
        macmahon.append(_plane_partition_count(n))

    return {
        "h1": h1, "h2": h2, "h3": h3,
        "sigma3": sigma3,
        "tree_level": abs(sigma3) < 1e-12,
        "E_n_level": "E_inf" if abs(sigma3) < 1e-12 else "E_3",
        "partition_function_type": "MacMahon (plane partitions)",
        "macmahon_coefficients": macmahon,
        "dt_identification": "Z_{DT}(C^3) = M(q) (MacMahon)",
        "plethystic_log": "q/(1-q)^2 (single-particle: bosonic, 2-param)",
    }


@lru_cache(maxsize=128)
def _plane_partition_count(n: int) -> int:
    """Count plane partitions of n (3D partitions).

    Uses the recursion from the generating function
    M(q) = prod_{k>=1} 1/(1-q^k)^k.

    First few values: 1, 1, 3, 6, 13, 24, 48, 86, 160, 282, 500.

    # VERIFIED: [DC] direct computation, [LT] OEIS A000219
    """
    if n == 0:
        return 1
    if n < 0:
        return 0

    # Use the recursion: n * pp(n) = sum_{k=1}^{n} sigma_2(k) * pp(n-k)
    # where sigma_2(k) = sum_{d|k} d^2 is the sum of squares of divisors.
    total = 0
    for k in range(1, n + 1):
        s2 = sum(d * d for d in range(1, k + 1) if k % d == 0)
        total += s2 * _plane_partition_count(n - k)
    return total // n


# =========================================================================
# 11. Comparison: R^3 (CS) vs C^3 (hCS)
# =========================================================================

def comparison_r3_vs_c3() -> Dict:
    """Comparison table between perturbative CS on R^3 and hCS on C^3.

    CS on R^3 (Costello-Francis-Gwilliam, 2021):
      - Config space: Conf_n(R^3), real 3n-dimensional
      - Propagator: 1/|x_i - x_j| (Chern-Simons propagator)
      - Cohomology generators: omega_{ij} in H^2 (linking S^2)
      - Fundamental group: pi_1(Conf_2(R^3)) = 0 (trivial braiding)
      - Formality: Kontsevich 1999 (real FM compactification)
      - E_n level: E_3 (topological, from little 3-disks)
      - Output: Lie algebra invariants (Vassiliev invariants)
      - Partition function: perturbative CS invariant

    hCS on C^3 (this engine):
      - Config space: Conf_n(C^3), real 6n-dimensional
      - Propagator: g(z_i - z_j) (holomorphic structure function)
      - Cohomology generators: omega_{ij} in H^5 (linking S^5)
      - Fundamental group: pi_1(Conf_2(C^3)) = 0 (trivial braiding)
      - Formality: Kriz 1994 (complex FM compactification)
      - E_n level: E_3 (from holomorphic little 3-disks, Omega-deformed)
      - Output: quantum toroidal algebra (conjectural, AP-CY14)
      - Partition function: MacMahon M(q) at tree level

    Key DIFFERENCE: the braiding in both cases is topologically trivial
    (pi_1 = 0). For R^3 CS, the nontrivial structure comes from the
    Lie algebra structure constants (cubic vertex). For C^3 hCS, it comes
    from the Omega-background deformation (equivariant parameters h_1, h_2, h_3).
    """
    return {
        "R^3 (CS)": {
            "config_space_real_dim": "3n",
            "linking_sphere": "S^2",
            "generator_degree": 2,
            "pi_1_conf_2": "0",
            "formality": "Kontsevich 1999",
            "E_n_level": "E_3",
            "braiding_source": "Lie algebra cubic vertex",
            "partition_function": "perturbative CS invariant",
            "tree_level": "1 (no topology)",
        },
        "C^3 (hCS)": {
            "config_space_real_dim": "6n",
            "linking_sphere": "S^5",
            "generator_degree": 5,
            "pi_1_conf_2": "0",
            "formality": "Kriz 1994",
            "E_n_level": "E_3 (Omega-deformed)",
            "braiding_source": "Omega-background (h_1, h_2, h_3)",
            "partition_function": "MacMahon M(q) at tree level",
            "tree_level": "M(q) = prod 1/(1-q^k)^k",
        },
        "shared": {
            "pi_1_trivial": True,
            "topological_braiding_trivial": True,
            "E_n_level": "E_3",
            "formality": True,
            "ZTE_obstruction": "nontrivial (thm:zte-failure)",
        },
    }


# =========================================================================
# 12. Master summary
# =========================================================================

def e3_config_space_summary(
    h1: complex = Rational(37, 10),
    h2: complex = Rational(-41, 10),
    h3: Optional[complex] = None,
) -> Dict:
    """Master summary of E_3 factorization homology on Conf_n(C^3).

    Parameters chosen to avoid poles at +/- h_i (AP-CY28).
    h1 = 3.7, h2 = -4.1, h3 = 0.4 (CY condition).
    Poles of g(z) at z = -3.7, 4.1, -0.4.
    """
    if h3 is None:
        h3 = -(h1 + h2)

    h1_f = float(h1)
    h2_f = float(h2)
    h3_f = float(h3)

    # Topology
    betti_2 = conf_space_betti_numbers(2, 3, max_degree=10)
    betti_3 = conf_space_betti_numbers(3, 3, max_degree=12)

    # Identities
    inv_pass, inv_res = verify_cy_inversion(h1_f, h2_f, h3_f)
    inv2_pass, inv2_res = verify_two_param_inversion(h1_f, h2_f, h3_f)
    loop_pass, loop_res = verify_one_loop_trivial(h1_f, h2_f, h3_f)
    tree_pass, tree_res = verify_tree_factorization(h1_f, h2_f, h3_f)

    # Dunn decomposition
    dunn = DunnDecomposition(h1_f, h2_f, h3_f)

    # Feynman integrals
    tree_3 = tree_integral_n_points(3, h1_f, h2_f, h3_f)
    e3_3 = two_loop_e3_integral(h1_f, h2_f, h3_f)

    # Formality
    coh_2 = cohomology_algebra_generators(2, 3)
    coh_3 = cohomology_algebra_generators(3, 3)

    # FM compactification
    fm_3 = fm_compactification_strata(3, 3)

    # Partition function
    fh = factorization_homology_c3_tree_level(h1_f, h2_f, h3_f, max_charge=6)

    return {
        "parameters": {
            "h1": h1_f, "h2": h2_f, "h3": h3_f,
            "sigma3": h1_f * h2_f * h3_f,
            "CY_condition": abs(h1_f + h2_f + h3_f) < 1e-12,
        },
        "topology": {
            "linking_sphere": "S^5",
            "pi_1_Conf_2": "0",
            "betti_Conf_2": betti_2,
            "betti_Conf_3": betti_3,
            "euler_Conf_2": conf_space_euler_char(2, 3),
            "total_betti_Conf_3": conf_space_total_betti(3),
        },
        "identities": {
            "CY_inversion": {"pass": inv_pass, "residual": inv_res},
            "two_param_inversion": {"pass": inv2_pass, "residual": inv2_res},
            "one_loop_trivial": {"pass": loop_pass, "residual": loop_res},
            "tree_factorization": {"pass": tree_pass, "residual": tree_res},
        },
        "dunn_decomposition": {
            "factors": dunn.factor_data(),
            "cy_verified": dunn.verify_cy_condition(),
            "degeneration": dunn.e3_degeneration_chain(),
        },
        "feynman_integrals": {
            "tree_3pt": tree_3,
            "e3_3pt": e3_3,
        },
        "formality": {
            "Conf_2_generators": coh_2,
            "Conf_3_generators": coh_3,
        },
        "fm_compactification": fm_3,
        "partition_function": fh,
        "comparison_R3_C3": comparison_r3_vs_c3(),
    }
