r"""Hopf fibration decomposition of the S^3-framing for CY3 categories.

MATHEMATICAL CONTENT
====================

The S^3-framing required for CY-A_3 decomposes via the Hopf fibration

    S^1 --> S^3 --> S^2

into an S^2-framing (which IS CY-A_2, proved) plus an S^1-action (the
Connes B-operator), with a correction controlled by the Euler class of
the Hopf bundle.  This module records diagnostics for that chain-level
decomposition.  The raw termwise operator and the corrected TCFT operator
are different carriers; the module must not identify them.

THE HOPF FIBRATION DECOMPOSITION
=================================

Key fact: the Hopf fibration S^1 -> S^3 -> S^2 is nontrivial.
The Euler class e(eta) in H^2(S^2; Z) = Z is a generator.  Equivalently,
pi_3(S^2) = Z (generated by the Hopf map itself).

At the operadic level, Dunn additivity gives E_3 = E_1 tensor E_2.
The S^3-framing decomposes as:

    F^{(3)} = F^{(2)} circ B^{(1)} + Obs

where:
  - F^{(2)}: CC_n -> CC_{n-2} is the S^2-framing (CY-A_2, proved)
  - B^{(1)}: CC_n -> CC_{n+1} is the Connes B-operator (S^1-action)
  - Obs: the obstruction to the decomposition

THE CORRECTED OBSTRUCTION STATEMENT
===================================

The obstruction Obs lives in

    HH^3(C, C) / (im(F^{(2)} circ B) + im(B circ F^{(2)}))

and is controlled by three pieces of data:

(1) The Euler class of the Hopf bundle: e(eta) in H^2(S^2; Z) = Z.
    This is a TOPOLOGICAL invariant that measures the nontriviality
    of the S^3 -> S^2 fibration.  It is the same for ALL CY3 categories.

(2) The A-infinity compatibility: whether the framing commutes with
    the higher operations m_k.  For formal CY3 (m_k = 0 for k >= 3),
    this is automatic.  For non-formal CY3 (local P^2), the m_3
    correction introduces a genuine obstruction.

(3) The BV compatibility: whether the framing trivialization via
    holomorphic CS is compatible with the BV differential Delta.
    This is the ANALYTIC content, requiring Dolbeault resolution.

For a CY3 category C with cyclic A-infinity structure (A, mu_n, <-,->),
the Hopf diagnostic decomposes as:

    Obs(C) = Obs_top(C) + Obs_Ainf(C) + Obs_BV(C)

where:
  (a) Obs_top = 0 universally (pi_3(BSp) = 0, Thm s3-framing-vanishes).
  (b) Obs_Ainf for the raw termwise pair-contraction operator is not
      universally zero.  The strict cyclic CY3 witness gives

          [m_3,B^{(2)}_term][a|a|a|a|b] = 2 alpha [b] != 0.

      Costello supplies a corrected TCFT operator after choosing
      moduli-chain correction data:

          {sum_k b_k, B^{(2)}_TCFT} = 0.

      This is a total corrected identity, not the equality
      B^{(2)}_term = B^{(2)}_TCFT and not the per-k identity
      {b_k,B^{(2)}_TCFT}=0.  A derived vanishing statement requires
      explicit HH^{-2} degree-line and comparison hypotheses.
  (c) Obs_BV = obstruction to extending the Cech/Dolbeault homotopy
      to commute with the BV operator.  This is the HARD part.

For toric CY3: Obs_BV = 0 (torus equivariance provides the homotopy).
For compact CY3 with Cech homotopy: Obs_BV is a FORMAL POWER SERIES
in the OPE variable z.  Its convergence is a separate analytic question;
it does not erase a raw termwise A-infinity witness.

AP-CY6 WARNING: All results here are CONDITIONAL on CY-A_3 for d=3.
The decomposition itself is unconditional (it is a statement about
operads, not about the functor Phi), but its APPLICATION to constructing
A_X requires the full CY-A_3 programme.

CONVENTIONS
===========
  - Cohomological grading: |d| = +1
  - Bar uses DESUSPENSION: |s^{-1}v| = |v| - 1 (AP45)
  - CY dimension d = 3: Serre functor S = [3]
  - AP-CY2: CY trace is HC^-_3(C), NOT just HH_3 -> k
  - AP-CY6: A_X for CY3 is CONDITIONAL on this construction
  - Exact arithmetic via fractions.Fraction throughout

REFERENCES
==========
  Hopf, Math. Ann. 104 (1931), 637--665 (Hopf fibration)
  Dunn, J. Pure Appl. Alg. 50 (1988), 93--112 (Dunn additivity)
  Costello, arXiv:math/0412149 (TCFTs and CY categories)
  Costello-Li, arXiv:1604.00839 (holomorphic CS)
  Kontsevich-Vlassopoulos (S^d-framing)
  Lurie, Higher Algebra ch. 5 (E_n operads)
  Lorgat Vol III: standalone/m3_b2_obstruction_vol3.tex
  Lorgat Vol III: spectral_seq_obs_ainf.py, bidegree_decomposition_bB.py
"""

from __future__ import annotations

from dataclasses import dataclass
from fractions import Fraction
from typing import (
    Any, Dict, List, Optional, Sequence, Tuple,
)

F = Fraction


def _add_linear(
    target: Dict[Tuple[str, ...], Fraction],
    source: Dict[Tuple[str, ...], Fraction],
    scale: Fraction = F(1),
) -> Dict[Tuple[str, ...], Fraction]:
    """Add a finite bar-word linear combination with exact coefficients."""
    for word, coeff in source.items():
        target[word] = target.get(word, F(0)) + scale * coeff
        if target[word] == 0:
            del target[word]
    return target


def terminal_slot_b2_term(
    word: Sequence[str],
    pairing: Optional[Dict[Tuple[str, str], Fraction]] = None,
) -> Dict[Tuple[str, ...], Fraction]:
    r"""Terminal-slot model of the raw \(B^{(2)}_{\mathrm{term}}\) witness.

    This is not Costello's corrected TCFT operator.  It is the strict
    termwise pair-contraction convention used by
    ``standalone/m3_b2_obstruction_vol3.tex``.
    """
    if pairing is None:
        pairing = {
            ("a", "b"): F(1),
            ("b", "a"): F(1),
            ("e", "w"): F(1),
            ("w", "e"): F(1),
        }

    word_tuple = tuple(word)
    if len(word_tuple) < 2:
        return {}

    terminal = word_tuple[-1]
    out: Dict[Tuple[str, ...], Fraction] = {}
    for index, entry in enumerate(word_tuple[:-1]):
        coeff = pairing.get((entry, terminal), F(0))
        if coeff:
            reduced = word_tuple[:index] + word_tuple[index + 1:-1]
            out[reduced] = out.get(reduced, F(0)) + coeff
    return out


def m3_strict_witness_action(
    word: Sequence[str],
    alpha: Fraction = F(1),
) -> Dict[Tuple[str, ...], Fraction]:
    r"""Minimal cyclic CY3 witness operation \(m_3(a,a,a)=\alpha b\)."""
    word_tuple = tuple(word)
    out: Dict[Tuple[str, ...], Fraction] = {}
    for start in range(len(word_tuple) - 2):
        if word_tuple[start:start + 3] == ("a", "a", "a"):
            reduced = word_tuple[:start] + ("b",) + word_tuple[start + 3:]
            out[reduced] = out.get(reduced, F(0)) + alpha
    return out


def compose_bar_operators(
    first,
    second,
    word: Sequence[str],
) -> Dict[Tuple[str, ...], Fraction]:
    """Apply ``first`` and then ``second`` to a finite bar-word sum."""
    total: Dict[Tuple[str, ...], Fraction] = {}
    for mid_word, mid_coeff in first(word).items():
        for out_word, out_coeff in second(mid_word).items():
            total[out_word] = total.get(out_word, F(0)) + mid_coeff * out_coeff
    return total


def strict_m3_b2_term_witness(alpha: Fraction = F(1)) -> Dict[str, Any]:
    r"""Compute the strict nonzero witness for the raw termwise operator.

    With \(x=[a|a|a|a|b]\) and terminal-slot \(B^{(2)}_{\mathrm{term}}\),

        [m_3,B^{(2)}_{\mathrm{term}}]x = 2 alpha [b].

    The corrected TCFT operator is a different carrier and is not computed
    here.
    """
    x = ("a", "a", "a", "a", "b")
    m3 = lambda w: m3_strict_witness_action(w, alpha=alpha)
    b2 = terminal_slot_b2_term

    m3_after_b2 = compose_bar_operators(b2, m3, x)
    b2_after_m3 = compose_bar_operators(m3, b2, x)
    commutator: Dict[Tuple[str, ...], Fraction] = dict(m3_after_b2)
    _add_linear(commutator, b2_after_m3, scale=F(-1))

    coefficient = commutator.get(("b",), F(0))
    return {
        "word": x,
        "b2_then_m3": m3_after_b2,
        "m3_then_b2": b2_after_m3,
        "commutator": commutator,
        "coefficient_of_b": coefficient,
        "nonzero": coefficient != 0,
        "carrier": "B^{(2)}_term",
        "corrected_tcft_operator_equal_to_termwise": False,
        "hh_minus_two_requires_hypotheses": True,
    }


# =========================================================================
# 0. HOPF FIBRATION DATA
# =========================================================================

@dataclass(frozen=True)
class HopfFibrationData:
    r"""The Hopf fibration S^1 -> S^3 -> S^2 and its operadic content.

    The Hopf map eta: S^3 -> S^2 is the unique nontrivial element of
    pi_3(S^2) = Z.  Its Euler class e(eta) in H^2(S^2; Z) generates
    H^2(S^2; Z) = Z.

    At the operadic level:
      - S^1 corresponds to E_1 (associative, little intervals)
      - S^2 corresponds to E_2 (braided, little disks)
      - S^3 corresponds to E_3 (symmetric-braided at topological level)
      - The fibration S^1 -> S^3 -> S^2 corresponds to
        E_3 = E_1 tensor_{E_0} E_2 (Dunn additivity)

    The nontriviality of the Hopf fibration means the decomposition
    E_3 = E_1 tensor E_2 is NOT a direct product: the E_1 and E_2
    factors interact through the Euler class.
    """
    euler_class: int = 1  # generator of H^2(S^2; Z) = Z
    pi3_s2: int = 1       # pi_3(S^2) = Z, Hopf map is generator

    # Homotopy groups relevant to the framing obstruction
    pi2_sp: int = 0       # pi_2(Sp(2m)) = 0 for all m >= 1
    pi3_bsp: int = 0      # pi_3(BSp(2m)) = pi_2(Sp(2m)) = 0
    pi3_bu: int = 0       # pi_3(BU) = 0 (Bott periodicity, 3 is odd)

    # The Gysin sequence of the Hopf fibration:
    # ... -> H^{n-2}(S^2) -e-> H^n(S^2) -> H^n(S^3) -> H^{n-1}(S^2) -> ...
    # At n=2: H^0(S^2) -e-> H^2(S^2) -> H^2(S^3) -> H^1(S^2)
    #       : Z -(x1)-> Z -> 0 -> 0
    # So H^2(S^3) = 0, confirming pi_2(S^3) = 0.
    # At n=3: H^1(S^2) -e-> H^3(S^2) -> H^3(S^3) -> H^2(S^2)
    #       : 0 -> 0 -> Z -> Z
    # The connecting homomorphism H^3(S^3) -> H^2(S^2) is the Euler class.

    def topological_obstruction_vanishes(self) -> bool:
        """The topological S^3-framing obstruction vanishes."""
        return self.pi3_bsp == 0 and self.pi3_bu == 0

    def hopf_fibration_nontrivial(self) -> bool:
        """The Hopf fibration is nontrivial."""
        return self.euler_class != 0


# =========================================================================
# 1. THE CONNES HIERARCHY B^{(k)}
# =========================================================================

@dataclass
class ConnesHierarchyElement:
    """An element of the Connes hierarchy B^{(k)} for CY_d.

    For CY_d, the Connes operator B: CC_n -> CC_{n+1} admits
    a refinement:
        B^{(k)}: CC_n -> CC_{n+1-k}  for k = 0, 1, ..., d

    with B^{(0)} = B and B^{(d)} = F (the full S^d-framing map).

    The hierarchy satisfies the nilpotence relation:
        sum_{i+j=d} B^{(i)} circ B^{(j)} = 0

    For d=3:
        B^{(0)} B^{(3)} + B^{(1)} B^{(2)} + B^{(2)} B^{(1)}
            + B^{(3)} B^{(0)} = 0
    i.e.:
        [B, F] = -[B^{(1)}, B^{(2)}]

    The commutator [B, F] is therefore EXACT (equal to -[B^{(1)}, B^{(2)}]).
    This is the chain-level content of the Hopf fibration decomposition.
    """
    level: int           # k in B^{(k)}
    degree_shift: int    # CC_n -> CC_{n + 1 - k}, so shift = 1 - k
    cy_dim: int          # d


@dataclass
class ConnesHierarchy:
    """The full Connes hierarchy B^{(0)}, B^{(1)}, ..., B^{(d)} for CY_d.

    For d=3, the hierarchy has 4 levels:
      B^{(0)} = B (Connes operator, degree +1)
      B^{(1)} (degree 0, from Omega^1 piece of the volume form)
      B^{(2)} (degree -1, the S^2-framing map for the CY2 subfactor)
      B^{(3)} = F (degree -2, the full S^3-framing map)

    The decomposition F = B^{(2)} circ B^{(1)} + correction
    is the operadic content of the Hopf fibration.
    """
    cy_dim: int
    levels: List[ConnesHierarchyElement]

    @classmethod
    def for_cy3(cls) -> "ConnesHierarchy":
        """Construct the Connes hierarchy for CY_3."""
        levels = [
            ConnesHierarchyElement(level=0, degree_shift=1, cy_dim=3),
            ConnesHierarchyElement(level=1, degree_shift=0, cy_dim=3),
            ConnesHierarchyElement(level=2, degree_shift=-1, cy_dim=3),
            ConnesHierarchyElement(level=3, degree_shift=-2, cy_dim=3),
        ]
        return cls(cy_dim=3, levels=levels)

    def nilpotence_relation_terms(self) -> List[Tuple[int, int]]:
        """Terms in the nilpotence relation sum_{i+j=d} B^{(i)} B^{(j)} = 0.

        Returns list of (i, j) pairs summing to d.
        """
        return [(i, self.cy_dim - i) for i in range(self.cy_dim + 1)]

    def bf_commutator_decomposition(self) -> Dict[str, Any]:
        """Decompose [B, F] using the nilpotence relation.

        For d=3:
            B^{(0)} B^{(3)} + B^{(1)} B^{(2)}
                + B^{(2)} B^{(1)} + B^{(3)} B^{(0)} = 0

        Rearranging:
            [B^{(0)}, B^{(3)}] = -[B^{(1)}, B^{(2)}]

        i.e. [B, F] = -[B^{(1)}, B^{(2)}]

        The RHS is computable from the intermediate hierarchy maps.
        """
        if self.cy_dim != 3:
            return {"error": "Only implemented for CY_3"}

        return {
            "lhs": "[B^{(0)}, B^{(3)}] = [B, F]",
            "rhs": "-[B^{(1)}, B^{(2)}]",
            "interpretation": (
                "The commutator of the Connes operator with the "
                "S^3-framing map is EXACT: it equals the negative "
                "commutator of the intermediate hierarchy maps. "
                "This is the chain-level content of the Hopf fibration "
                "decomposition: B^{(1)} is the S^1-fiber contribution, "
                "B^{(2)} is the S^2-base contribution, and their "
                "commutator is the twist from the Euler class."
            ),
            "euler_class_role": (
                "The commutator [B^{(1)}, B^{(2)}] is nonzero precisely "
                "because the Hopf fibration is nontrivial (Euler class = 1). "
                "For a trivial S^1-bundle over S^2 (which would give "
                "S^1 x S^2, not S^3), we would have [B^{(1)}, B^{(2)}] = 0 "
                "and therefore [B, F] = 0."
            ),
        }


# =========================================================================
# 2. THE THREE-COMPONENT OBSTRUCTION DECOMPOSITION
# =========================================================================

@dataclass
class ObstructionComponent:
    """A single component of the three-fold obstruction decomposition."""
    name: str
    value: Optional[Fraction]
    vanishes: bool
    mechanism: str
    status: str  # "proved", "conditional", "open"
    carrier: str = "chain"

    def __repr__(self) -> str:
        if self.vanishes:
            v = "0"
        elif self.value is None:
            v = "open"
        else:
            v = str(self.value)
        return f"{self.name} = {v} [{self.status}; {self.carrier}]"


@dataclass
class HopfObstructionDecomposition:
    r"""The three-component decomposition of the S^3-framing obstruction.

    Obs(C) = Obs_top(C) + Obs_Ainf(C) + Obs_BV(C)

    where:
      Obs_top  = topological obstruction (in pi_3(BSp) or pi_3(BU))
      Obs_Ainf = A-infinity compatibility obstruction ([m_3, F^{(2)}])
      Obs_BV   = BV compatibility obstruction (analytic)

    The decomposition is the chain-level refinement of the Hopf fibration:
      - Obs_top corresponds to the base obstruction (S^2-framing exists)
      - Obs_Ainf corresponds to the fiber obstruction (S^1-compatibility)
      - Obs_BV corresponds to the twist (Euler class correction)
    """
    geometry: str
    obs_top: ObstructionComponent
    obs_ainf: ObstructionComponent
    obs_bv: ObstructionComponent

    def total_vanishes(self) -> bool:
        """Whether the total obstruction vanishes."""
        return (self.obs_top.vanishes
                and self.obs_ainf.vanishes
                and self.obs_bv.vanishes)

    def summary(self) -> Dict[str, Any]:
        return {
            "geometry": self.geometry,
            "obs_top": repr(self.obs_top),
            "obs_ainf": repr(self.obs_ainf),
            "obs_bv": repr(self.obs_bv),
            "total_vanishes": self.total_vanishes(),
        }


# =========================================================================
# 3. HOPF DECOMPOSITION FOR SPECIFIC GEOMETRIES
# =========================================================================

def hopf_decomposition_c3() -> HopfObstructionDecomposition:
    r"""Hopf fibration decomposition for C^3.

    C^3 is the simplest CY3.  All three obstruction components vanish:
      - Obs_top = 0 (pi_3(BSp) = 0, universal)
      - Obs_Ainf = 0 (C^3 is formal: m_k = 0 for k >= 3)
      - Obs_BV = 0 (torus equivariance provides the BV trivialization)

    The S^3-framing is trivial (F = 0) because the 3-point function
    of the free boson vanishes.
    """
    return HopfObstructionDecomposition(
        geometry="C^3",
        obs_top=ObstructionComponent(
            name="Obs_top(C^3)",
            value=F(0),
            vanishes=True,
            mechanism="pi_3(BSp(2m)) = 0 for all m >= 1",
            status="proved",
        ),
        obs_ainf=ObstructionComponent(
            name="Obs_Ainf(C^3)",
            value=F(0),
            vanishes=True,
            mechanism=(
                "C^3 is formal (m_k = 0 for k >= 3). "
                "The commutator [m_3, B^{(2)}_term] = 0 trivially."
            ),
            status="proved",
        ),
        obs_bv=ObstructionComponent(
            name="Obs_BV(C^3)",
            value=F(0),
            vanishes=True,
            mechanism=(
                "T^3-equivariance of C^3 provides the BV trivialization. "
                "The holomorphic CS functional is torus-equivariant."
            ),
            status="proved",
        ),
    )


def hopf_decomposition_conifold() -> HopfObstructionDecomposition:
    r"""Hopf fibration decomposition for the resolved conifold.

    The conifold X = Tot(O(-1)^2 -> P^1).
      - Obs_top = 0 (universal)
      - Obs_Ainf = 0 (conifold is formal: Kaledin's theorem)
      - Obs_BV = 0 (2 chambers, wall-crossing compatible with F)
    """
    return HopfObstructionDecomposition(
        geometry="resolved conifold",
        obs_top=ObstructionComponent(
            name="Obs_top(conifold)",
            value=F(0),
            vanishes=True,
            mechanism="pi_3(BSp(2m)) = 0, universal",
            status="proved",
        ),
        obs_ainf=ObstructionComponent(
            name="Obs_Ainf(conifold)",
            value=F(0),
            vanishes=True,
            mechanism=(
                "Conifold is formal (Kaledin: Ext algebra of smooth CY3 "
                "with unobstructed deformations is formal). "
                "[m_3, B^{(2)}_term] = 0 because m_3 = 0."
            ),
            status="proved",
        ),
        obs_bv=ObstructionComponent(
            name="Obs_BV(conifold)",
            value=F(0),
            vanishes=True,
            mechanism=(
                "Toric CY3: T^3-equivariant BV trivialization. "
                "Hocolim over 2 chambers with compatible wall-crossing."
            ),
            status="proved",
        ),
    )


def hopf_decomposition_local_p2() -> HopfObstructionDecomposition:
    r"""Hopf fibration decomposition for local P^2.

    Local P^2 = O(-3) -> P^2, the McKay quiver of Z_3.
      - Obs_top = 0 (universal)
      - Obs_Ainf != 0 for the raw termwise operator
        B^{(2)}_term.  The corrected standalone computation shows that
        [m_3, B^{(2)}_term] != 0: the commutator equals 2*alpha*[b]
        on the element [a|a|a|a|b].  The earlier claim that cyclic
        invariance forces the commutator to vanish is false.
      - Obs_BV = 0 (toric: T^3-equivariant BV trivialization)

    Costello's corrected TCFT operator may cancel the total boundary after
    moduli-chain correction data.  That is not equality with the raw
    termwise operator and is not recorded here as termwise vanishing.
    """
    witness = strict_m3_b2_term_witness()
    return HopfObstructionDecomposition(
        geometry="local P^2",
        obs_top=ObstructionComponent(
            name="Obs_top(local P^2)",
            value=F(0),
            vanishes=True,
            mechanism="pi_3(BSp(2m)) = 0, universal",
            status="proved",
        ),
        obs_ainf=ObstructionComponent(
            name="Obs_Ainf(local P^2)",
            value=witness["coefficient_of_b"],
            vanishes=False,
            mechanism=(
                "local P^2 is non-formal (m_3 != 0). Raw termwise carrier: "
                "[m_3, B^{(2)}_term][a|a|a|a|b] = 2*alpha*[b] != 0. "
                "Costello's corrected B^{(2)}_TCFT is a separate operator "
                "after moduli-chain correction data; toric BV vanishing "
                "does not prove termwise A-infinity vanishing."
            ),
            status="computed",
            carrier="B^{(2)}_term",
        ),
        obs_bv=ObstructionComponent(
            name="Obs_BV(local P^2)",
            value=F(0),
            vanishes=True,
            mechanism=(
                "Toric CY3: T^3-equivariant BV trivialization. "
                "Hocolim over 3 chambers with compatible wall-crossings."
            ),
            status="proved",
        ),
    )


def hopf_decomposition_quintic() -> HopfObstructionDecomposition:
    r"""Hopf fibration decomposition for the quintic threefold.

    Q = {f_5 = 0} in P^4, a smooth CY3.
      - Obs_top = 0 (universal)
      - Obs_Ainf: not resolved by cyclic invariance alone.  The termwise
        strict witness shows that nonzero m_3 can obstruct raw
        B^{(2)}_term compatibility.  A corrected TCFT or HH^{-2}
        comparison theorem is separate input.
      - Obs_BV: the Cech contracting homotopy provides a PERTURBATIVE
        BV trivialization (Thm cech-contracting-homotopy).
        The non-perturbative convergence is OPEN.

    Status: perturbatively proved, non-perturbatively open.
    """
    return HopfObstructionDecomposition(
        geometry="quintic threefold",
        obs_top=ObstructionComponent(
            name="Obs_top(quintic)",
            value=F(0),
            vanishes=True,
            mechanism="pi_3(BSp(2m)) = 0, universal",
            status="proved",
        ),
        obs_ainf=ObstructionComponent(
            name="Obs_Ainf(quintic)",
            value=None,
            vanishes=False,
            mechanism=(
                "The quintic is non-formal (m_3 != 0 from the "
                "superpotential). Cyclicity, Tsygan formality, and "
                "Costello's TCFT theorem do not imply "
                "[m_3, B^{(2)}_term] = 0. A derived vanishing claim "
                "requires explicit HH^{-2} filtration/comparison "
                "hypotheses."
            ),
            status="open",
            carrier="B^{(2)}_term",
        ),
        obs_bv=ObstructionComponent(
            name="Obs_BV(quintic)",
            value=F(0),
            vanishes=True,
            mechanism=(
                "Cech contracting homotopy (Thm cech-contracting-homotopy) "
                "provides the perturbative BV trivialization. "
                "Non-perturbative convergence: OPEN."
            ),
            status="conditional",
        ),
    )


def hopf_decomposition_k3e() -> HopfObstructionDecomposition:
    r"""Hopf fibration decomposition for K3 x E.

    K3 x E is a product CY3 = CY2 x CY1.
      - Obs_top = 0 (universal)
      - Obs_Ainf is open for the CY category.  DGMS formality applies to
        the de Rham cdga of the compact Kahler manifold; it is not a proof
        that the coherent CY category has no higher A-infinity operations
        on the chain model used by the S^3-framing obstruction.
      - Obs_BV: the Kummer route (Steps 1-4 proved) provides the BV
        trivialization for the orbifold resolution T^4/Z_2 x E.
        Step 5 (excision to the resolution) is conjectural.

    The de Rham cohomology model has trivial higher operations.  That
    statement is a diagnostic for one commutative dg algebra model, not a
    categorical vanishing theorem for D^b Coh(K3 x E), the Hall category,
    or the chain-level CY3 carrier used in this programme.

    CRITICAL INSIGHT: the Hopf fibration decomposition reveals that
    for K3 x E, the obstruction is NOT about the S^3-framing per se,
    but about the BV compatibility of the product decomposition
    F^{(3)}_{K3 x E} = F^{(2)}_{K3} tensor F^{(1)}_E.
    """
    return HopfObstructionDecomposition(
        geometry="K3 x E",
        obs_top=ObstructionComponent(
            name="Obs_top(K3 x E)",
            value=F(0),
            vanishes=True,
            mechanism="pi_3(BSp(2m)) = 0, universal",
            status="proved",
        ),
        obs_ainf=ObstructionComponent(
            name="Obs_Ainf(K3 x E)",
            value=None,
            vanishes=False,
            mechanism=(
                "DGMS proves formality of the de Rham cdga of a compact "
                "Kahler manifold. That does not prove A-infinity formality "
                "of the coherent CY category or identify B^{(2)}_term with "
                "B^{(2)}_TCFT. K3 x E therefore needs the same corrected "
                "TCFT comparison datum or HH^{-2} filtration theorem before "
                "raw termwise Obs_Ainf can be set to zero."
            ),
            status="open",
            carrier="B^{(2)}_term",
        ),
        obs_bv=ObstructionComponent(
            name="Obs_BV(K3 x E)",
            value=F(0),
            vanishes=True,
            mechanism=(
                "Kummer route: Steps 1-4 proved (prop:kummer-orbifold). "
                "Step 5 (excision) conjectural (conj:kummer-route). "
                "The product structure K3 x E decomposes F^{(3)} = "
                "F^{(2)}_{K3} tensor F^{(1)}_E. The S^2-framing of K3 "
                "is CY-A_2 (proved), and the S^1-action on E is the "
                "Connes operator. The BV compatibility of the tensor "
                "product is the content of Step 5."
            ),
            status="conditional",
        ),
    )


# =========================================================================
# 4. THE CYCLIC A-INFINITY COMPATIBILITY THEOREM
# =========================================================================

@dataclass
class CyclicAinfCompatibility:
    r"""Scope record for the A-infinity part of the Hopf diagnostic.

    Formal models have strict vanishing because \(m_k=0\) for \(k\ge 3\).
    Non-formal cyclicity alone does not kill the raw termwise commutator:
    the strict witness gives

        [m_3,B^{(2)}_term][a|a|a|a|b]=2 alpha [b].

    Costello's theorem concerns a corrected \(B^{(2)}_{\TCFT}\) and the
    total differential \(b=\sum_k b_k\).  A derived \(HH^{-2}\) vanishing
    statement is a separate filtered comparison theorem.
    """
    geometry: str
    is_formal: bool
    m3_nonzero: bool
    m3_compatible_with_f2: bool
    cyclic_invariance_verified: bool
    obs_ainf_vanishes: bool
    proof_steps: List[str]
    carrier: str = "B^{(2)}_term"
    hh_minus_two_hypothesis_required: bool = False

    def verification_summary(self) -> Dict[str, Any]:
        return {
            "geometry": self.geometry,
            "formal": self.is_formal,
            "m3_nonzero": self.m3_nonzero,
            "m3_compatible_with_F2": self.m3_compatible_with_f2,
            "cyclic_invariance": self.cyclic_invariance_verified,
            "Obs_Ainf_vanishes": self.obs_ainf_vanishes,
            "carrier": self.carrier,
            "HH_minus_two_hypothesis_required": (
                self.hh_minus_two_hypothesis_required
            ),
        }


def verify_cyclic_ainf_compatibility_formal(
    geometry: str,
) -> CyclicAinfCompatibility:
    """Verify raw termwise Obs_Ainf = 0 for a strictly formal model.

    For formal categories (m_k = 0 for k >= 3), the result is trivial:
    [m_k, B^{(2)}_term] = 0 because m_k = 0.

    Applies only after a formal model has actually been chosen.
    """
    return CyclicAinfCompatibility(
        geometry=geometry,
        is_formal=True,
        m3_nonzero=False,
        m3_compatible_with_f2=True,
        cyclic_invariance_verified=True,
        obs_ainf_vanishes=True,
        proof_steps=[
            f"{geometry} is formal: m_k = 0 for k >= 3.",
            "[m_k, B^{(2)}_term] = 0 trivially (both sides zero).",
            "Raw termwise Obs_Ainf = 0 on this formal model.",
        ],
    )


def verify_cyclic_ainf_compatibility_tcft(
    geometry: str,
) -> CyclicAinfCompatibility:
    r"""Record the corrected TCFT scope for a non-formal CY3 category.

    For non-formal categories where explicit \(m_3\) data is not available,
    Costello's theorem supplies a corrected TCFT operator after moduli-chain
    correction data.  It does not prove raw termwise vanishing:

        {sum_k b_k, B^{(2)}_TCFT} = 0.

    A derived \(E_1\)-Hochschild vanishing statement additionally requires
    explicit \(HH^{-2}\) degree-line and comparison hypotheses.
    """
    return CyclicAinfCompatibility(
        geometry=geometry,
        is_formal=False,
        m3_nonzero=True,
        m3_compatible_with_f2=False,
        cyclic_invariance_verified=False,
        obs_ainf_vanishes=False,
        proof_steps=[
            f"{geometry} is NOT A_inf formal: m_3 != 0 (Yukawa/theta-function).",
            "Cyclicity does not imply [m_k, B^{(2)}_term] = 0.",
            "Costello gives {sum_k b_k, B^{(2)}_TCFT} = 0 after corrections.",
            "No equality B^{(2)}_term = B^{(2)}_TCFT is part of the theorem.",
            "HH^{-2} vanishing requires explicit filtered comparison hypotheses.",
        ],
        carrier="B^{(2)}_term",
        hh_minus_two_hypothesis_required=True,
    )


def verify_cyclic_ainf_compatibility_nonformal(
    geometry: str,
    m3_data: Dict[Tuple[str, str, str], List[Tuple[str, Fraction]]],
    cy_pairing: Dict[Tuple[str, str], Fraction],
) -> CyclicAinfCompatibility:
    """Reject raw termwise Obs_Ainf vanishing from cyclicity alone.

    For non-formal categories (m_3 != 0), the cyclic A-infinity identity
    controls cyclic pairing of an operation with one additional input.
    It does not control every non-adjacent pair contraction in
    [m_3, B^{(2)}_term].  The strict witness demonstrates nonvanishing.

    The pairing checks below are retained as diagnostics; they do not
    certify termwise vanishing.
    """
    m3_nonzero = any(
        any(coeff != 0 for _, coeff in terms)
        for terms in m3_data.values()
    )

    # Count available cyclic pairing checks.  This is diagnostic only.
    # For a CY3 algebra, cyclicity is the n=3 A-infinity identity.
    # The pairing <m_3(a,b,c), d> requires |m_3(a,b,c)| + |d| = 3.
    # Since m_3 has degree 2-3 = -1, |m_3(a,b,c)| = |a|+|b|+|c|-1.
    # So we need |a|+|b|+|c|-1 + |d| = 3, i.e. |a|+|b|+|c|+|d| = 4.

    cyclic_checks_passed = True
    check_count = 0

    for (a_name, b_name, c_name), terms in m3_data.items():
        if not terms:
            continue
        for result_name, result_coeff in terms:
            if result_coeff == 0:
                continue
            # For each generator d, check the cyclic sum
            # <m_3(a,b,c), d> = result_coeff * <result, d>
            for (g1, g2), pairing_val in cy_pairing.items():
                if g1 == result_name and pairing_val != 0:
                    check_count += 1
                    # The cyclic A-infinity relation requires this
                    # to be cancelled by the other cyclic terms.
                    # For the CY3 quiver algebras we verify, this holds
                    # by construction from the potential W.

    cyclic_verified = cyclic_checks_passed and check_count > 0
    witness = strict_m3_b2_term_witness()

    proof_steps = [
        f"{geometry} is non-formal: m_3 != 0.",
        "Cyclic A-infinity identity: "
        "<m_3(a,b,c), d> + <m_3(d,a,b), c> + cyclic = 0.",
        "Those pairing checks do not control all non-adjacent "
        "B^{(2)}_term contractions.",
        "Strict witness: [m_3, B^{(2)}_term][a|a|a|a|b] = "
        f"{witness['coefficient_of_b']}*alpha*[b] for alpha=1.",
        "Costello/TCFT and HH^{-2} derived vanishing are separate inputs.",
    ]
    if check_count > 0:
        proof_steps.append(
            f"Recorded {check_count} explicit cyclic pairing diagnostics."
        )

    return CyclicAinfCompatibility(
        geometry=geometry,
        is_formal=False,
        m3_nonzero=m3_nonzero,
        m3_compatible_with_f2=False,
        cyclic_invariance_verified=cyclic_verified,
        obs_ainf_vanishes=False,
        proof_steps=proof_steps,
        carrier="B^{(2)}_term",
        hh_minus_two_hypothesis_required=True,
    )


# =========================================================================
# 5. THE BV OBSTRUCTION: PERTURBATIVE VS NON-PERTURBATIVE
# =========================================================================

@dataclass
class BVObstructionAnalysis:
    r"""Analysis of the BV compatibility obstruction Obs_BV.

    The BV obstruction is the HARD part of the S^3-framing programme.
    It asks: does the chain-level trivialization of the topological
    obstruction (via holomorphic CS) commute with the BV operator?

    For toric CY3: YES (torus equivariance).
    For compact CY3 with Cech homotopy: perturbatively YES
        (Thm cech-contracting-homotopy), non-perturbatively OPEN.

    THE STRUCTURE OF Obs_BV:

    The BV operator Delta = partial/partial Omega_3 acts on the
    cyclic bar complex CC_*(C). The holomorphic CS functional
    CS(dbar + A) = int_X Omega wedge tr(A dbar A + 2/3 A^3)
    provides a trivialization: delta_BV(CS) = int Omega F_A.

    The obstruction: CS is NOT E_2-equivariant (the holomorphic
    volume form Omega transforms with weight 1 under U(1) rotation).
    This breaks E_2 to E_1.

    But for the Hopf decomposition, we need only E_1 compatibility
    (the S^3-framing is an E_1 structure, not E_2). The question
    reduces to: does CS commute with the ORDERED product structure?

    For toric CY3: the torus action provides the ordering, and
    CS is equivariant.

    For compact CY3: the Cech homotopy provides a formal power
    series trivialization. Each term in the series is a well-defined
    Cech cochain. The convergence question: does the series of
    OPE coefficients produced by the HTT converge to holomorphic
    functions?

    The BV diagnostic is independent of the raw termwise A-infinity
    witness.  Convergence of the Cech-HTT series can close the analytic
    BV question only after the A-infinity carrier has been handled by
    strict formality, corrected TCFT data, or an HH^{-2} comparison.
    """
    geometry: str
    toric: bool
    obs_bv_perturbative: bool   # perturbative BV vanishes
    obs_bv_nonperturbative: bool  # non-perturbative BV vanishes
    convergence_proved: bool
    mechanism: str

    def is_resolved(self) -> bool:
        """Whether Obs_BV is fully resolved."""
        return self.obs_bv_perturbative and self.obs_bv_nonperturbative

    def is_perturbatively_resolved(self) -> bool:
        """Whether Obs_BV is resolved at the perturbative level."""
        return self.obs_bv_perturbative


def bv_obstruction_toric(geometry: str) -> BVObstructionAnalysis:
    """BV obstruction analysis for toric CY3."""
    return BVObstructionAnalysis(
        geometry=geometry,
        toric=True,
        obs_bv_perturbative=True,
        obs_bv_nonperturbative=True,
        convergence_proved=True,
        mechanism=(
            "T^3-equivariant holomorphic CS provides the BV "
            "trivialization. The torus action ensures E_1-compatibility."
        ),
    )


def bv_obstruction_compact(geometry: str) -> BVObstructionAnalysis:
    """BV obstruction analysis for compact CY3."""
    return BVObstructionAnalysis(
        geometry=geometry,
        toric=False,
        obs_bv_perturbative=True,
        obs_bv_nonperturbative=False,
        convergence_proved=False,
        mechanism=(
            "Cech contracting homotopy (algebraic, no PDE solving) "
            "provides the perturbative BV trivialization. "
            "Non-perturbative: convergence of the Cech-HTT series "
            "is the remaining open question. The series coefficients "
            "are rational functions on Cech intersections; their "
            "growth is controlled by the geometry of the affine cover."
        ),
    )


def bv_obstruction_k3e() -> BVObstructionAnalysis:
    """BV obstruction for K3 x E via the Kummer route."""
    return BVObstructionAnalysis(
        geometry="K3 x E",
        toric=False,
        obs_bv_perturbative=True,
        obs_bv_nonperturbative=False,
        convergence_proved=False,
        mechanism=(
            "K3 x E Kummer route: Steps 1-4 proved (prop:kummer-orbifold). "
            "The product decomposition F^{(3)} = F^{(2)}_{K3} tensor "
            "F^{(1)}_E reduces the BV obstruction to the S^2-framing "
            "of K3 (CY-A_2, proved) tensor the S^1-action on E "
            "(the Connes operator, classical). The remaining Step 5 "
            "(excision) requires the FH pairing identification."
        ),
    )


# =========================================================================
# 6. MASTER DECOMPOSITION: THE COMPLETE OBSTRUCTION LANDSCAPE
# =========================================================================

@dataclass
class HopfDecompositionResult:
    """Complete result of the Hopf fibration decomposition."""
    hopf_data: HopfFibrationData
    connes_hierarchy: ConnesHierarchy
    decompositions: Dict[str, HopfObstructionDecomposition]
    cyclic_ainf_results: Dict[str, CyclicAinfCompatibility]
    bv_results: Dict[str, BVObstructionAnalysis]

    @staticmethod
    def _component_status(component: ObstructionComponent) -> str:
        if component.vanishes:
            return f"0 [{component.status}; {component.carrier}]"
        if component.value is None:
            return f"open [{component.status}; {component.carrier}]"
        return f"{component.value} [{component.status}; {component.carrier}]"

    def obstruction_landscape(self) -> Dict[str, Dict[str, str]]:
        """Summary of the obstruction landscape across all geometries."""
        landscape = {}
        for geom, decomp in self.decompositions.items():
            landscape[geom] = {
                "Obs_top": self._component_status(decomp.obs_top),
                "Obs_Ainf": self._component_status(decomp.obs_ainf),
                "Obs_BV": self._component_status(decomp.obs_bv),
                "total": "0 [proved]" if decomp.total_vanishes()
                    else "open [conditional]",
            }
        return landscape

    def residual_obstruction(self) -> Dict[str, str]:
        """For each geometry, what remains to be proved."""
        residual = {}
        for geom, decomp in self.decompositions.items():
            if decomp.total_vanishes():
                bv = self.bv_results.get(geom)
                if bv and not bv.obs_bv_nonperturbative:
                    residual[geom] = (
                        "Perturbatively resolved. Non-perturbative: "
                        "convergence of Cech-HTT series."
                    )
                else:
                    residual[geom] = "Fully resolved."
            elif not decomp.obs_ainf.vanishes:
                residual[geom] = decomp.obs_ainf.mechanism
            else:
                residual[geom] = "Open: see decomposition."
        return residual


def master_hopf_decomposition() -> HopfDecompositionResult:
    """Run the complete Hopf fibration decomposition analysis.

    Computes the three-component obstruction decomposition for
    all standard CY3 geometries:
      - C^3 (trivial, F = 0)
      - Resolved conifold (formal, toric)
      - Local P^2 (non-formal, toric)
      - Quintic (compact, Cech homotopy)
      - K3 x E (product, Kummer route)

    Returns the complete obstruction landscape.
    """
    hopf_data = HopfFibrationData()
    connes = ConnesHierarchy.for_cy3()

    decomps = {
        "C^3": hopf_decomposition_c3(),
        "conifold": hopf_decomposition_conifold(),
        "local_P^2": hopf_decomposition_local_p2(),
        "quintic": hopf_decomposition_quintic(),
        "K3_x_E": hopf_decomposition_k3e(),
    }

    cyclic = {
        "C^3": verify_cyclic_ainf_compatibility_formal("C^3"),
        "conifold": verify_cyclic_ainf_compatibility_formal("conifold"),
        "local_P^2": verify_cyclic_ainf_compatibility_nonformal(
            "local P^2",
            m3_data={
                ("x_01", "y_12", "z_20"): [("e0", F(1))],
                ("y_01", "z_12", "x_20"): [("e0", F(1))],
                ("z_01", "x_12", "y_20"): [("e0", F(1))],
                ("x_01", "z_12", "y_20"): [("e0", F(-1))],
                ("z_01", "y_12", "x_20"): [("e0", F(-1))],
                ("y_01", "x_12", "z_20"): [("e0", F(-1))],
            },
            cy_pairing={
                ("e0", "e0*"): F(1),
                ("e1", "e1*"): F(1),
                ("e2", "e2*"): F(1),
                ("e0*", "e0"): F(1),
                ("e1*", "e1"): F(1),
                ("e2*", "e2"): F(1),
            },
        ),
        "quintic": verify_cyclic_ainf_compatibility_tcft("quintic"),
        "K3_x_E": verify_cyclic_ainf_compatibility_tcft("K3 x E"),
    }

    bv = {
        "C^3": bv_obstruction_toric("C^3"),
        "conifold": bv_obstruction_toric("conifold"),
        "local_P^2": bv_obstruction_toric("local P^2"),
        "quintic": bv_obstruction_compact("quintic"),
        "K3_x_E": bv_obstruction_k3e(),
    }

    return HopfDecompositionResult(
        hopf_data=hopf_data,
        connes_hierarchy=connes,
        decompositions=decomps,
        cyclic_ainf_results=cyclic,
        bv_results=bv,
    )


# =========================================================================
# 7. CONVERGENCE ANALYSIS FOR COMPACT CY3
# =========================================================================

@dataclass
class CechHTTConvergenceAnalysis:
    r"""Analysis of the convergence question for compact CY3.

    The Cech-HTT (homotopy transfer theorem) produces transferred
    operations mu_k^{ch} on Ext^*(E, E) from the Cech resolution.
    Each application of the Cech homotopy s introduces rational
    functions on the Cech intersections.

    For the quintic Q in P^4 with standard affine cover {U_i}:
      - Each U_i is affine (hyperplane complement)
      - Each intersection U_{i0} cap ... cap U_{iq} is affine
      - The Cech homotopy s: C^q -> C^{q-1} acts by prepending index 0
      - The HTT transfers: mu_k^{ch} involves k-1 applications of s
      - Each application of s introduces a denominator x_0 from the
        restriction to U_0

    The convergence question: for the OPE variable z, do the coefficients
    of the transferred operations converge as functions of z?

    Estimate: the Cech homotopy s is bounded on each intersection
    (rational functions on affine varieties are bounded away from
    the boundary of the cover). The key growth estimate:

        |mu_k^{ch}(a_1, ..., a_k; z)| <= C^k * k! * |z|^{-k}

    This is GEVREY-1 growth (matching the shadow class M prediction
    for non-formal CY3).  The quintic entry below records the separate
    finite-cover Cech-HTT convergence diagnostic; it is not a proof of
    raw termwise A-infinity vanishing.
    """
    geometry: str
    is_formal: bool
    cech_cover_size: int       # number of affine opens
    htt_terms: int             # number of terms in the HTT
    growth_type: str           # "polynomial", "Gevrey-1", "divergent"
    convergence_status: str    # "proved", "conditional", "open"

    def converges(self) -> bool:
        return self.convergence_status == "proved"


def convergence_quintic() -> CechHTTConvergenceAnalysis:
    """Convergence analysis for the quintic.

    FORMALITY STATUS (corrected, see formality_ainf_dcoh.py):
    The quintic is NOT A_infinity formal (m_3 != 0 from Yukawa coupling).
    However, the Cech-HTT coefficient series CONVERGES regardless of
    formality (the convergence bound depends on the Cech cover geometry,
    not on formality).  The htt_terms count is finite because the Cech
    complex has finite length (5 opens -> length 4), not because m_k = 0.
    """
    return CechHTTConvergenceAnalysis(
        geometry="quintic",
        is_formal=False,
        cech_cover_size=5,         # 5 affine opens from P^4
        htt_terms=5,               # finite Cech length, but m_k != 0 for k >= 3
        growth_type="convergent",  # Cech-HTT converges (Prop cech-htt-coefficient-convergence)
        convergence_status="proved",
    )


def convergence_general_compact() -> CechHTTConvergenceAnalysis:
    """Convergence analysis for general compact CY3."""
    return CechHTTConvergenceAnalysis(
        geometry="general compact CY3",
        is_formal=False,
        cech_cover_size=-1,       # depends on the CY3
        htt_terms=-1,             # infinitely many
        growth_type="Gevrey-1",   # shadow class M prediction
        convergence_status="open",
    )


# =========================================================================
# 8. K3 x E PRODUCT DECOMPOSITION
# =========================================================================

@dataclass
class ProductDecompositionK3E:
    r"""The product decomposition of the S^3-framing for K3 x E.

    For K3 x E = CY2 x CY1, the S^3-framing decomposes as:

        F^{(3)}_{K3 x E} = F^{(2)}_{K3} tensor B_E + correction

    where:
      - F^{(2)}_{K3}: CC_n(K3) -> CC_{n-2}(K3) is the S^2-framing
        of K3 (CY-A_2, PROVED)
      - B_E: CC_n(E) -> CC_{n+1}(E) is the Connes operator on E
        (the S^1-action, classical)
      - The correction comes from the Euler class of the Hopf bundle

    The tensor product acts on CC_*(K3 x E) = CC_*(K3) tensor CC_*(E).

    The key: F^{(2)}_{K3} is PROVED (CY-A_2), B_E is classical (Connes).
    The only remaining content is the correction term, which is
    TOPOLOGICAL (Euler class) and does not depend on the algebra.

    This means: for K3 x E, the S^3-framing obstruction reduces to
    the BV compatibility of the tensor product structure, which is
    the content of Kummer Step 5.

    DEGREE ACCOUNTING:
      F^{(2)}_{K3}: degree -1 on CC_*(K3)
      B_E: degree +1 on CC_*(E)
      F^{(2)} tensor B: degree -1+1 = 0 on CC_*(K3 x E)
      But F^{(3)} has degree -2.  So F^{(2)} tensor B is NOT F^{(3)}.

    The correct decomposition uses the full Connes hierarchy:
      F^{(3)}_{K3 x E} = sum_{i+j=3} B^{(i)}_{K3} tensor B^{(j)}_E

    where:
      B^{(0)}_{K3} tensor B^{(3)}_E: impossible (E is CY1, max level is 1)
      B^{(1)}_{K3} tensor B^{(2)}_E: impossible (E is CY1, max level is 1)
      B^{(2)}_{K3} tensor B^{(1)}_E: F^{(2)}_{K3} tensor B_E (degree -2: OK!)
      B^{(3)}_{K3} tensor B^{(0)}_E: impossible (K3 is CY2, max level is 2)

    So the ONLY contributing term is:
      F^{(3)}_{K3 x E} = F^{(2)}_{K3} tensor B_E

    Wait: check degrees. F^{(2)}_{K3}: CC_n -> CC_{n-1}, degree shift -1.
    B^{(1)}_E = B_E: CC_n -> CC_{n+1-1} = CC_n, degree shift 0.
    Actually B^{(k)} has degree shift 1-k. So B^{(1)} has shift 0.

    F^{(2)}_{K3} tensor B^{(1)}_E: total shift = -1 + 0 = -1.
    But F^{(3)} has shift 1-3 = -2.  Still wrong.

    Correction: for the PRODUCT CY3 = CY2 x CY1:
    The Kunneth formula for the cyclic bar complex gives:
      CC_*(K3 x E) ~ CC_*(K3) tensor CC_*(E)
    and the S^3-framing map on the product is:
      F^{(3)} = F^{(2)}_{K3} cap [E]
    where [E] is the fundamental class of E in HH_1(E).

    More precisely: the CY3 trace on K3 x E is:
      Tr_3 = Tr_{K3} tensor Tr_E: HH_2(K3) tensor HH_1(E) -> k tensor k -> k

    This gives F^{(3)} as the contraction using BOTH traces simultaneously.
    The degree shift: contracting 2 factors from K3 and 1 from E gives
    total contraction of 3, hence CC_n -> CC_{n-3}, shift -2.  Correct.
    """
    s2_framing_k3_proved: bool = True
    s1_action_e_classical: bool = True
    product_decomposition_valid: bool = True
    euler_class_contribution: Fraction = F(0)
    # The Euler class of the Hopf bundle contributes zero in the product case
    # because K3 x E is topologically S^2 x S^1 (NOT S^3) at the level of
    # the framing data.  The Hopf fibration correction vanishes for products.
    # This is the KEY SIMPLIFICATION for the K3 x E case.

    kummer_step5_status: str = "conjectural"

    def obstruction_reduces_to(self) -> str:
        return (
            "For K3 x E, the S^3-framing reduces to the proved S^2-framing "
            "of K3 (CY-A_2) combined with the classical Connes operator on E. "
            "The remaining content is Kummer Step 5: the excision argument "
            "for the orbifold resolution T^4/Z_2 x E. No S^3-framing "
            "obstruction per se; the obstruction is entirely in the "
            "BV compatibility of the product decomposition."
        )


# =========================================================================
# 9. OBSTRUCTION CLASS IDENTIFICATION
# =========================================================================

@dataclass
class ObstructionClassIdentification:
    r"""Identification of the chain-level obstruction class.

    The BV part of the chain-level S^3-framing obstruction is recorded by:

        alpha(C) in HH^3_{cyc}(C, C) / (topological + A-infinity)

    where:
      - HH^3_{cyc} is the cyclic Hochschild 3-cochains
      - The topological quotient removes Obs_top (which vanishes)
      - The A-infinity quotient is allowed only after either strict
        formality, a corrected TCFT comparison, or the explicit HH^{-2}
        filtration theorem has been supplied.

    The residual class alpha(C) is the BV obstruction Obs_BV, which
    lives in the ANALYTIC part of the Hochschild cohomology.

    For toric CY3: alpha(C) = 0 (torus equivariance kills it).
    For compact CY3 with the required A-infinity comparison supplied:
      alpha(C) is a formal power series governed by Cech-HTT data.
    For compact non-formal CY3: alpha(C) is a Gevrey-1 series
      requiring Borel resummation.

    The obstruction class alpha(C) has a concrete description:

    alpha(C) = [CS, Delta_BV] restricted to the E_1 bar complex

    where CS is the holomorphic Chern-Simons functional and Delta_BV
    is the BV operator.  The restriction to E_1 (rather than E_2)
    is the content of the E_1 universality theorem: we only need
    the framing to be compatible with the ORDERED product, not
    with the braiding.
    """
    geometry: str
    class_in_hh3: str
    value: str
    toric: bool
    formal: bool
    convergence: str

    def is_zero(self) -> bool:
        return self.value == "0"


def identify_obstruction_class(geometry: str) -> ObstructionClassIdentification:
    """Identify the chain-level obstruction class for a given geometry."""
    toric_geometries = {"C^3", "conifold", "local_P^2"}
    formal_geometries = {"C^3", "conifold", "K3_x_E"}

    is_toric = geometry in toric_geometries
    is_formal = geometry in formal_geometries

    if is_toric:
        return ObstructionClassIdentification(
            geometry=geometry,
            class_in_hh3="[CS, Delta_BV]|_{E_1}",
            value="0",
            toric=True,
            formal=is_formal,
            convergence="trivial (torus equivariance)",
        )
    elif is_formal:
        return ObstructionClassIdentification(
            geometry=geometry,
            class_in_hh3="[CS, Delta_BV]|_{E_1}",
            value="0 (formal, perturbative)",
            toric=False,
            formal=True,
            convergence="proved (finitely many Cech-HTT terms)",
        )
    else:
        return ObstructionClassIdentification(
            geometry=geometry,
            class_in_hh3="[CS, Delta_BV]|_{E_1}",
            value="open until TCFT/HH^{-2} comparison and BV convergence",
            toric=False,
            formal=False,
            convergence="open (requires corrected TCFT/HH^{-2} input)",
        )


# =========================================================================
# 10. FULL PROGRAMME STATUS
# =========================================================================

def full_programme_status() -> Dict[str, Any]:
    """Complete status of the CY-A_3 S^3-framing programme.

    The Hopf fibration decomposition reduces CY-A_3 to:

    1. Obs_top = 0: PROVED (universally, by two independent paths).
    2. Obs_Ainf: STRICTLY ZERO only on formal models.  The raw termwise
       non-formal claim is false: [m_3,B^{(2)}_term] has a strict
       nonzero witness.  Costello's corrected TCFT identity and HH^{-2}
       derived vanishing require separate hypotheses.
    3. Obs_BV: PROVED for toric CY3. PROVED perturbatively for
       compact CY3 with Cech homotopy. OPEN non-perturbatively
       for compact non-formal CY3.

    Remaining open questions: corrected TCFT/HH^{-2} comparison data for
    non-formal termwise witnesses, and convergence of the Cech-HTT series
    for compact non-formal CY3 categories.

    For the landscape of geometries relevant to Vol III:
      - C^3: FULLY RESOLVED
      - Conifold: FULLY RESOLVED
      - Local P^2: raw termwise A-infinity witness nonzero; BV toric
        part resolved
      - Quintic: A-infinity comparison open; Cech-HTT convergence is a
        separate diagnostic
      - K3 x E: product/BV route conditional; A-infinity comparison open
      - General compact CY3: PERTURBATIVELY RESOLVED
    """
    result = master_hopf_decomposition()

    return {
        "decomposition_theorem": (
            "The S^3-framing obstruction decomposes as "
            "Obs = Obs_top + Obs_Ainf + Obs_BV"
        ),
        "obs_top": "0 universally (pi_3(BSp) = pi_3(BU) = 0)",
        "obs_ainf": (
            "not universally zero for B^{(2)}_term; strict witness "
            "[m_3,B^{(2)}_term][a|a|a|a|b] = 2 alpha [b] != 0. "
            "Corrected TCFT and HH^{-2} derived vanishing require "
            "separate hypotheses."
        ),
        "obs_bv": {
            "toric": "0 (torus equivariance)",
            "compact": "perturbative Cech/Dolbeault diagnostic",
            "compact_nonformal": "open without TCFT/HH^{-2} comparison",
        },
        "landscape": result.obstruction_landscape(),
        "residual": result.residual_obstruction(),
        "single_remaining_question": (
            "Corrected TCFT/HH^{-2} comparison for non-formal raw "
            "termwise witnesses, plus Cech-HTT convergence for compact "
            "non-formal CY3 categories."
        ),
        "new_results": [
            "Raw termwise Obs_Ainf is not universally zero",
            "Strict witness: [m_3,B^{(2)}_term][a|a|a|a|b] = 2 alpha [b]",
            "Costello corrected TCFT identity is not B^{(2)}_term equality",
            "K3 x E product decomposition: no S^3 obstruction per se",
        ],
    }
