r"""
tilting_generator_cy3.py -- Tilting generators, Ext-quivers, and quiver-with-potential
for derived categories of CY3 varieties and related spaces.

Ground truth:
  Bondal, "Representations of associative algebras and coherent sheaves" (1990).
  Bondal-Van den Bergh, "Generators and representability of functors" (2003).
  Van den Bergh, "Non-commutative crepant resolutions" (2004).
  Beilinson, "Coherent sheaves on P^n" (1978).
  Bridgeland, "Flops and derived categories" (2002).
  Aspinwall et al., "Dirichlet branes and mirror symmetry" (2009).
  Keller-Yang, "Derived equivalences from mutations of quivers with potential" (2011).
  Ginzburg, "CY algebras" (2006).

MATHEMATICAL CONTENTS:

1. TILTING GENERATORS FOR SMOOTH PROJECTIVE VARIETIES.
   By the Bondal-Van den Bergh theorem (2003), for a smooth projective variety X
   over k, D^b(Coh(X)) has a tilting generator T: an object satisfying
     (i) thick(T) = D^b(Coh(X))  (T generates the category)
     (ii) Ext^{>0}(T, T) = 0     (T has no higher self-extensions)

   The endomorphism algebra A = End(T) then gives an equivalence:
     D^b(Coh(X)) ~ D^b(mod-A)

   For the BVdB theorem: the tilting generator exists for any smooth projective X.
   For SINGULAR varieties, Van den Bergh's noncommutative crepant resolution
   provides a tilting generator under suitable conditions (rational singularities).

2. BEILINSON'S THEOREM FOR P^n.
   The Beilinson collection on P^n is:
     T = O + O(1) + ... + O(n)
   This is a full strong exceptional collection: Ext^{>0}(O(i), O(j)) = 0 for
   all i <= j, and Ext^*(O(i), O(j)) = 0 for i > j+n (by Serre duality + vanishing).

   The Ext-quiver has n+1 vertices and arrows from Ext^1 computations.
   For P^n: Ext^1(O(i), O(j)) = H^1(P^n, O(j-i)) for 0 <= i < j <= n.
   By Bott's theorem: H^k(P^n, O(m)) is nonzero only when:
     - k=0 and m >= 0: dim = binom(n+m, n)
     - k=n and m <= -(n+1): dim = binom(-m-1, n)
   All other cohomology groups vanish.

   Therefore for P^n with the Beilinson collection:
     Ext^1(O(i), O(j)) = 0 for all 0 <= i < j <= n (since j-i <= n and
     H^1(P^n, O(j-i)) = 0 for all j-i > 0 by Bott vanishing).

   The NON-ZERO morphisms are Hom = H^0:
     Hom(O(i), O(j)) = H^0(P^n, O(j-i)) for j >= i.
     dim = binom(n + j - i, n).

   For P^3: arrows are generated by Hom(O(i), O(i+1)) = H^0(P^3, O(1)) = C^4.
   So the Beilinson quiver for P^3 has 4 vertices with 4 arrows between
   consecutive vertices.

3. RESTRICTION TO HYPERSURFACE: KOSZUL RESOLUTION.
   For a smooth hypersurface Y = {f_d = 0} in P^n of degree d:
     0 -> O(-d) -> O -> O_Y -> 0 (Koszul exact sequence)

   This gives for any coherent sheaf F on P^n:
     H^k(Y, F|_Y) fits in the long exact sequence:
     ... -> H^k(P^n, F(-d)) -> H^k(P^n, F) -> H^k(Y, F|_Y) -> H^{k+1}(P^n, F(-d)) -> ...

   For the quintic Q in P^4 (d=5, n=4):
     Ext^k_Q(O(i)|_Q, O(j)|_Q) = Ext^k_Q(O_Q, O(j-i)|_Q)
   We compute from the long exact sequence of Koszul.

4. COMPLETE INTERSECTION CY3.
   For a CI Y = {f_{d_1} = 0} ∩ ... ∩ {f_{d_r} = 0} in P^{n+r}:
   The Koszul resolution is:
     0 -> O(-D) -> ... -> ⊕ O(-d_i) -> O -> O_Y -> 0
   where D = d_1 + ... + d_r.
   CY condition: D = n+r+1 (so K_Y = O_Y).

   The Ext groups are computed from the multi-step Koszul filtration.

5. CY3 CONSTRAINT: SERRE DUALITY ON THE QUIVER.
   For a CY3 category with tilting generator T = ⊕ T_i:
     dim Ext^1(T_i, T_j) = dim Ext^2(T_j, T_i)
   This is Serre duality for a CY3 (omega_X = O_X, dim X = 3).
   Consequence: the Ext-quiver is CY3-SELF-DUAL.
   If there are a_{ij} arrows from i to j in the Ext^1 quiver,
   then there are a_{ji} arrows from j to i in the Ext^2 "reverse" quiver,
   and the quiver with potential (Q, W) must satisfy the CY3 Ginzburg condition.

6. SINGULAR CY3: CONIFOLD.
   The conifold singularity: xy = zw in C^4 (an ODP = ordinary double point).
   The small resolution X = Tot(O(-1) + O(-1) -> P^1) has:
     T = O_X + O_X(1)  (tilting on the resolution)
   giving the Klebanov-Witten quiver: 2 vertices, 4 arrows (2 in each direction),
   with potential W = tr(A_1 B_1 A_2 B_2 - A_1 B_2 A_2 B_1).

7. TILTING GENERATOR AND E_1 CHIRAL ALGEBRA.
   The tilting generator T determines the E_1 chiral algebra:
     A_X = Fact_X(End(T))
   For C^3: T = O, End(T) = C, Fact(C) = Heisenberg = W_{1+infty} at c=0.
   For the conifold: End(T) = the KW path algebra, giving a non-abelian chiral algebra.

CONVENTIONS:
  - Cohomological grading (|d| = +1).
  - All Fraction arithmetic for exact computations.
  - Ext^k(E, F) = H^k(RHom(E, F)).
  - For line bundles on P^n: Ext^k(O(i), O(j)) = H^k(P^n, O(j-i)).
  - Bott's formula for H^k(P^n, O(m)):
      k=0, m >= 0: binom(n+m, n)
      k=n, m <= -(n+1): binom(-m-1, n)
      all other: 0.

REFERENCES:
  Beilinson, "Coherent sheaves on P^n" (1978).
  Bondal, "Representations of associative algebras" (1990).
  Bondal-Van den Bergh, "Generators and representability" (2003).
  Van den Bergh, "Non-commutative crepant resolutions" (2004).
  Bridgeland, "Flops and derived categories" (2002).
  Keller-Yang, "Derived equivalences from mutations" (2011).
  Ginzburg, "CY algebras" (2006).
  Aspinwall et al., "Dirichlet branes and mirror symmetry" (2009).
  Candelas-de la Ossa-Green-Parkes, NPB 359 (1991).
"""

from __future__ import annotations

import math
from collections import defaultdict
from fractions import Fraction
from functools import lru_cache
from typing import Any, Dict, List, NamedTuple, Optional, Sequence, Tuple


# =========================================================================
# Section 0: Combinatorial utilities
# =========================================================================

def binomial(n: int, k: int) -> int:
    """Binomial coefficient C(n, k) for arbitrary integer n, non-negative k.

    Uses the generalized formula: C(n, k) = n*(n-1)*...*(n-k+1) / k!
    Returns 0 if k < 0 or (for non-negative n) if k > n.
    """
    if k < 0:
        return 0
    if k == 0:
        return 1
    # For non-negative n with k > n: return 0
    if n >= 0 and k > n:
        return 0
    result = 1
    for i in range(k):
        result = result * (n - i)
    result = result // math.factorial(k)
    return result


# =========================================================================
# Section 1: Cohomology of line bundles on P^n (Bott's theorem)
# =========================================================================

def h_k_pn_o_m(n: int, k: int, m: int) -> int:
    r"""Compute dim H^k(P^n, O(m)) via Bott's theorem.

    Bott's vanishing theorem for projective space:
      H^0(P^n, O(m)) = C(n+m, n) if m >= 0, else 0.
      H^n(P^n, O(m)) = C(-m-1, n) if m <= -(n+1), else 0.
      H^k(P^n, O(m)) = 0          for 0 < k < n.

    Proof sketch: Cech cohomology on the standard affine cover of P^n
    gives the explicit computation. The vanishing for 0 < k < n is
    Bott's theorem (the Euler sequence splits the tangent bundle
    cohomology; for line bundles, this reduces to the above).

    Parameters
    ----------
    n : dimension of P^n
    k : cohomological degree
    m : twist degree of O(m)

    Returns
    -------
    dim H^k(P^n, O(m))
    """
    if k < 0 or k > n:
        return 0
    if k == 0:
        # H^0(P^n, O(m)) = C(n+m, n) for m >= 0, else 0
        if m >= 0:
            return binomial(n + m, n)
        else:
            return 0
    elif k == n:
        # H^n(P^n, O(m)) = C(-m-1, n) for m <= -(n+1), else 0
        # This comes from Serre duality: H^n(P^n, O(m)) = H^0(P^n, O(-m-n-1))^*
        # So dim = C(n + (-m-n-1), n) = C(-m-1, n) when -m-1 >= 0, i.e., m <= -1
        # But actually: H^n(P^n, O(m)) != 0 only when m <= -(n+1).
        # By Serre duality: H^n(P^n, O(m)) ~ H^0(P^n, O(-m-n-1))^*
        # and H^0 != 0 iff -m-n-1 >= 0, i.e., m <= -(n+1).
        if m <= -(n + 1):
            return binomial(-m - 1, n)
        else:
            return 0
    else:
        # Bott vanishing: H^k(P^n, O(m)) = 0 for 0 < k < n
        return 0


def euler_char_pn_o_m(n: int, m: int) -> int:
    r"""Euler characteristic chi(P^n, O(m)) = sum_k (-1)^k H^k(P^n, O(m)).

    By Hirzebruch-Riemann-Roch: chi(P^n, O(m)) = C(n+m, n) for all m.
    (This formula holds for ALL m, including negative.)

    Verification: For m >= 0, only H^0 contributes: chi = C(n+m, n).
    For m <= -(n+1), only H^n contributes: chi = (-1)^n * C(-m-1, n).
    Check: C(n+m, n) with m <= -(n+1) gives C(n+m, n) with n+m <= -1,
    so C(n+m, n) = C(negative, n) = (-1)^n * C(n - (n+m) - 1, n) = (-1)^n * C(-m-1, n).
    Consistent.
    """
    return binomial(n + m, n)


# =========================================================================
# Section 2: Ext groups for line bundles on P^n
# =========================================================================

class ExtData(NamedTuple):
    """Ext group data between two objects in D^b(Coh(X))."""
    source: str  # label for source object
    target: str  # label for target object
    dims: Dict[int, int]  # degree k -> dim Ext^k

    @property
    def total_dim(self) -> int:
        return sum(self.dims.values())

    @property
    def euler(self) -> int:
        return sum((-1) ** k * d for k, d in self.dims.items())


def ext_line_bundles_pn(n: int, i: int, j: int) -> ExtData:
    """Compute Ext^*(O(i), O(j)) on P^n.

    Ext^k(O(i), O(j)) = H^k(P^n, O(j-i)).
    """
    m = j - i
    dims = {}
    for k in range(n + 1):
        d = h_k_pn_o_m(n, k, m)
        if d > 0:
            dims[k] = d
    return ExtData(source=f"O({i})", target=f"O({j})", dims=dims)


# =========================================================================
# Section 3: Beilinson exceptional collection on P^n
# =========================================================================

class ExceptionalCollection(NamedTuple):
    """An exceptional collection E_0, ..., E_r in D^b(Coh(X)).

    An exceptional collection satisfies:
      Ext^*(E_i, E_i) = k (in degree 0 only)
      Ext^*(E_i, E_j) = 0 for i > j
    It is STRONG if additionally Ext^{>0}(E_i, E_j) = 0 for all i, j.
    It is FULL if it generates D^b(Coh(X)).

    The tilting generator is T = bigoplus E_i.
    """
    objects: List[str]
    ext_matrix: Dict[Tuple[int, int], ExtData]
    is_exceptional: bool
    is_strong: bool
    is_full: bool
    variety: str


def beilinson_collection_pn(n: int) -> ExceptionalCollection:
    r"""Beilinson's exceptional collection on P^n: {O, O(1), ..., O(n)}.

    This is a full strong exceptional collection:
      Ext^k(O(i), O(j)) = H^k(P^n, O(j-i))
    For 0 <= i <= j <= n: j-i ranges from 0 to n.
      H^k(P^n, O(m)) for 0 <= m <= n: only H^0 is nonzero.
    So Ext^{>0}(O(i), O(j)) = 0 for i <= j (strong).
    For i > j: j-i < 0 and j-i >= -n, so m in {-n,...,-1}.
      H^k(P^n, O(m)) = 0 for all k when -n <= m <= -1 (Bott gap).
    So Ext^*(O(i), O(j)) = 0 for i > j (exceptional).

    FULL: This is Beilinson's theorem (1978).
    """
    objects = [f"O({i})" for i in range(n + 1)]
    ext_matrix: Dict[Tuple[int, int], ExtData] = {}

    is_exceptional = True
    is_strong = True

    for i in range(n + 1):
        for j in range(n + 1):
            ed = ext_line_bundles_pn(n, i, j)
            ext_matrix[(i, j)] = ed

            if i == j:
                # Must have Ext^* = k in degree 0 only
                if ed.dims != {0: 1}:
                    is_exceptional = False
            elif i > j:
                # Must have Ext^* = 0
                if ed.total_dim != 0:
                    is_exceptional = False
            else:
                # i < j: for strong, need Ext^{>0} = 0
                for k, d in ed.dims.items():
                    if k > 0 and d > 0:
                        is_strong = False

    return ExceptionalCollection(
        objects=objects,
        ext_matrix=ext_matrix,
        is_exceptional=is_exceptional,
        is_strong=is_strong,
        is_full=True,  # Beilinson's theorem
        variety=f"P^{n}",
    )


# =========================================================================
# Section 4: Ext-quiver of an exceptional collection
# =========================================================================

class QuiverData(NamedTuple):
    """Quiver data extracted from an exceptional collection or tilting generator.

    Vertices correspond to indecomposable summands of the tilting generator.
    Arrows from i to j are counted by dim Ext^1(T_i, T_j).
    For CY3: also record Ext^2 (= opposite arrows by Serre duality).
    """
    num_vertices: int
    vertex_labels: List[str]
    arrows: Dict[Tuple[int, int], int]  # (i, j) -> number of arrows i -> j
    ext2_arrows: Dict[Tuple[int, int], int]  # Ext^2 data
    variety: str
    is_cy3_self_dual: bool  # arrows(i,j) = ext2_arrows(j,i) for all i,j
    potential_terms: int  # number of terms in the potential W


def ext_quiver(ec: ExceptionalCollection, cy_dim: Optional[int] = None) -> QuiverData:
    r"""Extract the Ext-quiver from an exceptional collection.

    The quiver Q has:
      - Vertices: one for each object in the collection.
      - Arrows from i to j: dim Ext^1(E_i, E_j).
      - For CY3: Ext^2(E_j, E_i) = dim reverse arrows (Serre duality).

    The quiver with potential (Q, W) gives:
      D^b(Coh(X)) ~ D^b(Rep(Q, W))  (Bondal-type equivalence)

    For CY3: the potential W comes from the A_infinity m_3 product.
    The number of terms in W is related to dim Ext^2 (which counts
    relations in the path algebra).
    """
    n = len(ec.objects)
    arrows: Dict[Tuple[int, int], int] = {}
    ext2: Dict[Tuple[int, int], int] = {}

    for i in range(n):
        for j in range(n):
            ed = ec.ext_matrix[(i, j)]
            a1 = ed.dims.get(1, 0)
            a2 = ed.dims.get(2, 0)
            if a1 > 0:
                arrows[(i, j)] = a1
            if a2 > 0:
                ext2[(i, j)] = a2

    # CY3 self-duality check: dim Ext^1(E_i, E_j) = dim Ext^2(E_j, E_i)
    is_cy3 = True
    if cy_dim == 3:
        for i in range(n):
            for j in range(n):
                a1_ij = arrows.get((i, j), 0)
                a2_ji = ext2.get((j, i), 0)
                if a1_ij != a2_ji:
                    is_cy3 = False
                    break
            if not is_cy3:
                break
    else:
        is_cy3 = False  # not applicable

    # Potential terms: for a quiver with potential, the number of
    # potential terms equals the number of oriented 3-cycles weighted
    # by the A_infinity m_3 structure constants.
    # For the Beilinson quiver on P^n (n >= 3), potential terms come from
    # Ext^2 (= relations in the path algebra).
    potential_terms = sum(ext2.values())

    return QuiverData(
        num_vertices=n,
        vertex_labels=ec.objects,
        arrows=arrows,
        ext2_arrows=ext2,
        variety=ec.variety,
        is_cy3_self_dual=is_cy3,
        potential_terms=potential_terms,
    )


# =========================================================================
# Section 5: Restriction to hypersurface via Koszul resolution
# =========================================================================

def h_k_hypersurface_o_m(n: int, d: int, k: int, m: int) -> int:
    r"""Compute dim H^k(Y, O(m)|_Y) for Y = {f_d = 0} in P^n via Koszul.

    The Koszul exact sequence for Y (smooth hypersurface of degree d in P^n):
      0 -> O(-d) -> O -> O_Y -> 0

    gives the long exact sequence:
      ... -> H^k(P^n, O(m-d)) -> H^k(P^n, O(m)) -> H^k(Y, O(m)|_Y)
          -> H^{k+1}(P^n, O(m-d)) -> ...

    We compute H^k(Y, O(m)|_Y) from this LES.

    In general, the LES gives:
      H^k(Y, O(m)|_Y) = coker(H^k(P^n, O(m-d)) -> H^k(P^n, O(m)))
                       + ker(H^{k+1}(P^n, O(m-d)) -> H^{k+1}(P^n, O(m)))

    When the connecting maps are explicit, this reduces to:
      dim H^k(Y, ...) = dim H^k(P^n, O(m)) - dim im(alpha_k)
                       + dim ker(alpha_{k+1})
    where alpha_k: H^k(P^n, O(m-d)) -> H^k(P^n, O(m)) is multiplication by f_d.

    For line bundles on smooth hypersurfaces, the map alpha_k is:
    - INJECTIVE when both source and target are in the H^0 range (m-d >= 0, m >= 0)
    - SURJECTIVE when ... (depends on the specific case)
    - ZERO when source and target are in different cohomological ranges

    The dimension of Y is n-1. So H^k(Y, ...) = 0 for k > n-1.

    We compute this case by case using the explicit H^k(P^n, O(m)) values.
    """
    dim_Y = n - 1

    # H^k(Y, ...) = 0 for k > dim Y
    if k < 0 or k > dim_Y:
        return 0

    # The LES splits into short exact pieces.
    # Define a_k = dim H^k(P^n, O(m-d)) and b_k = dim H^k(P^n, O(m)).
    # The LES is:
    #   0 -> coker(a_k -> b_k) -> H^k(Y, ...) -> ker(a_{k+1} -> b_{k+1}) -> 0
    # But this is NOT always exact in this simple form. The full LES is:
    #
    # ... -> H^{k-1}(Y) -> H^k(P^n, O(m-d)) -f-> H^k(P^n, O(m)) -> H^k(Y) -> ...
    #
    # We need to track the connecting homomorphisms carefully.
    # For smooth hypersurfaces, there's a simpler approach: iterate.

    # For the specific cases we need (CY3 hypersurfaces), we use the
    # alternating sum (exact) plus case-by-case vanishing.

    # Strategy: compute via the Euler characteristic identity
    #   chi(Y, O(m)|_Y) = chi(P^n, O(m)) - chi(P^n, O(m-d))
    # and then use vanishing theorems to pin down individual H^k.

    # First compute all H^k(P^n, O(m)) and H^k(P^n, O(m-d)).
    a = [h_k_pn_o_m(n, kk, m - d) for kk in range(n + 1)]
    b = [h_k_pn_o_m(n, kk, m) for kk in range(n + 1)]

    # The Euler characteristic:
    chi_Y = sum((-1)**kk * b[kk] for kk in range(n + 1)) - \
            sum((-1)**kk * a[kk] for kk in range(n + 1))

    # For smooth CY hypersurface Y in P^n of degree d = n+1:
    # Kodaira vanishing: if m > 0, H^k(Y, O(m)|_Y) = 0 for k > 0
    #                    if m < 0, H^k(Y, O(m)|_Y) = 0 for k < dim_Y
    #                    (Kodaira: ample + positive => vanishing)

    # Case: m > 0 and m - d >= 0 (both in H^0 range)
    if m > 0 and m - d >= 0:
        # Only H^0 survives (Kodaira vanishing on Y for ample O(m)|_Y)
        # H^0(Y, O(m)|_Y) = H^0(P^n, O(m)) - H^0(P^n, O(m-d))
        # (the restriction map is surjective, and the kernel is f_d * H^0(O(m-d)))
        return b[0] - a[0] if k == 0 else 0

    # Case: m > 0 and m - d < 0 but m - d > -(n+1) (in the Bott gap)
    if m > 0 and m - d < 0 and m - d > -(n + 1):
        # H^k(P^n, O(m-d)) = 0 for all k (Bott gap: -(n) <= m-d <= -1)
        # So H^k(Y, O(m)|_Y) = H^k(P^n, O(m)) for k < dim_Y,
        # and the LES gives an exact answer.
        # By Kodaira on Y: H^k(Y, O(m)|_Y) = 0 for 0 < k < dim_Y when m > 0.
        # So only H^0 can be nonzero.
        if k == 0:
            return b[0]
        return 0

    # Case: m = 0
    if m == 0:
        # H^0(P^n, O) = 1, H^0(P^n, O(-d)) = 0
        # LES: 0 -> H^0(Y, O_Y) -> H^1(P^n, O(-d)) -> H^1(P^n, O) -> H^1(Y, O_Y) -> ...
        # H^1(P^n, O(-d)) = 0 (in Bott gap for d <= n)
        # H^1(P^n, O) = 0 (Bott)
        # So H^0(Y, O_Y) = 1 and H^1(Y, O_Y) comes from H^2(P^n, O(-d)).
        if k == 0:
            return 1
        # For CY: H^k(Y, O_Y) = h^{0,k}(Y).
        # By CY condition with omega_Y = O_Y:
        #   h^{0,k} = h^{dim_Y, dim_Y - k} by Hodge symmetry + Serre duality
        # For CY3 (dim_Y = 3): h^{0,0}=1, h^{0,1}=0, h^{0,2}=0, h^{0,3}=1.
        # For CY2 (dim_Y = 2, e.g. quartic in P^3): h^{0,0}=1, h^{0,1}=0, h^{0,2}=1.
        # More generally: from the LES, H^k(Y, O_Y) = ker(H^{k+1}(P^n, O(-d)) -> H^{k+1}(P^n, O)).
        # H^{k+1}(P^n, O(-d)) is zero unless k+1 = n and -d <= -(n+1), i.e., d >= n+1.
        # For CY (d = n+1): H^n(P^n, O(-(n+1))) = C(-(-n-1)-1, n) = C(n, n) = 1.
        # And H^n(P^n, O) = 0. So the map is 0 -> 1 -> 0, giving H^{n-1}(Y, O) = 1.
        # For k != 0 and k != n-1: H^k(Y, O_Y) = 0.
        if k == dim_Y and d == n + 1:
            return 1  # CY condition: h^{dim_Y,0} = 1
        return 0

    # Case: m < 0 and m > -(d):  (in the "interesting" range)
    # This is where Ext^1 and Ext^2 live for the CY restriction.
    if m < 0:
        # Use Serre duality on Y: H^k(Y, O(m)) = H^{dim_Y - k}(Y, O(-m))^*
        # (since omega_Y = O_Y for CY).
        # For CY (d = n+1): this is exact.
        if d == n + 1:
            # CY Serre duality
            return h_k_hypersurface_o_m(n, d, dim_Y - k, -m)
        # Non-CY case: omega_Y = O(d - n - 1)|_Y
        # Serre duality: H^k(Y, O(m)) = H^{dim_Y - k}(Y, O(d - n - 1 - m))^*
        return h_k_hypersurface_o_m(n, d, dim_Y - k, d - n - 1 - m)

    # Fallback: compute from the LES numerically
    # This handles edge cases not covered above.
    # For the LES: dim H^k(Y) = b[k] - im(alpha_k) + ker(alpha_{k+1})
    # In general, without knowing the maps, we use:
    #   dim H^k(Y) = b[k] + a[k+1] - (rank of combined map)
    # This is not computable in general. Return the Euler characteristic bound.
    # For our applications, the cases above should cover everything.
    return max(0, chi_Y) if k == 0 else 0


def ext_on_hypersurface(n: int, d: int, i: int, j: int) -> ExtData:
    r"""Compute Ext^*(O(i)|_Y, O(j)|_Y) for Y = {f_d = 0} in P^n.

    Ext^k_Y(O(i)|_Y, O(j)|_Y) = H^k(Y, O(j-i)|_Y)  (for line bundles).
    """
    m = j - i
    dim_Y = n - 1
    dims = {}
    for k in range(dim_Y + 1):
        val = h_k_hypersurface_o_m(n, d, k, m)
        if val > 0:
            dims[k] = val
    return ExtData(source=f"O({i})|_Y", target=f"O({j})|_Y", dims=dims)


# =========================================================================
# Section 6: Complete intersection CY3
# =========================================================================

def h_k_cicy_o_m(ambient_dim: int, degrees: Tuple[int, ...], k: int, m: int) -> int:
    r"""Compute dim H^k(Y, O(m)|_Y) for a CICY Y in P^n.

    Y is a complete intersection of hypersurfaces of degrees (d_1, ..., d_r) in P^n.
    dim Y = n - r.

    Uses iterated Koszul resolution:
      0 -> O(-D) -> ... -> ⊕ O(-d_i) -> O -> O_Y -> 0
    where D = sum(d_i).

    The cohomology is computed by iterating the hypersurface case:
    first restrict to the first hypersurface, then the second, etc.

    For small codimension (r = 1, 2), this is manageable.
    """
    n = ambient_dim
    r = len(degrees)
    dim_Y = n - r

    if k < 0 or k > dim_Y:
        return 0

    if r == 0:
        # Y = P^n itself
        return h_k_pn_o_m(n, k, m)

    if r == 1:
        return h_k_hypersurface_o_m(n, degrees[0], k, m)

    # For r >= 2: use the iterated Koszul resolution.
    # Strategy: write the Koszul complex for the last hypersurface as:
    #   0 -> F(-d_r) -> F -> F|_{Y_r} -> 0
    # where F is the restriction to the intersection of the first r-1 hypersurfaces.
    #
    # Alternatively: use the full Koszul resolution and take the alternating sum.
    # The full Koszul complex is:
    #   0 -> O(-D) -> ⊕_{|S|=r-1} O(-D_S) -> ... -> ⊕_i O(-d_i) -> O -> O_Y -> 0
    # where D_S = sum_{i in S} d_i.
    #
    # The Euler characteristic is:
    #   chi(Y, O(m)) = sum_{S subset [r]} (-1)^{|S|} chi(P^n, O(m - D_S))

    # For the full computation, we iterate the hypersurface case.
    # For r = 2: Y = Y_1 ∩ Y_2 where Y_1 = {f_{d_1} = 0}.
    # First restrict to Y_1 (a smooth hypersurface of degree d_1 in P^n),
    # then restrict to Y_2 ∩ Y_1 = Y (a hypersurface of degree d_2 in Y_1).

    # For CY3 (3,3) in P^5 (n=5, r=2, degrees=(3,3)):
    # Y_1 is a cubic 4-fold in P^5, then Y is a cubic surface in Y_1... no.
    # Y_1 is a smooth cubic 4-fold, Y is the intersection with another cubic.

    # Use the Koszul spectral sequence for CI.
    # For r = 2: the Koszul resolution of O_Y on P^n is:
    #   0 -> O(-d_1-d_2) -> O(-d_1) ⊕ O(-d_2) -> O -> O_Y -> 0
    # Long exact sequence approach: split into two short exact sequences.

    if r == 2:
        d1, d2 = degrees
        return _h_k_ci2_o_m(n, d1, d2, k, m)

    # For r >= 3: recursive approach
    # Not needed for our standard CY3 examples (which are r <= 2)
    # but include for completeness.
    # Use chi only.
    chi_Y = 0
    for mask in range(1 << r):
        sign = (-1) ** bin(mask).count('1')
        d_sum = sum(degrees[i] for i in range(r) if mask & (1 << i))
        chi_Y += sign * euler_char_pn_o_m(n, m - d_sum)

    # Without full vanishing analysis, return chi for k=0 (assuming vanishing
    # for k > 0, which holds for m >> 0).
    if m > 0 and k == 0:
        return chi_Y
    if m == 0:
        if k == 0:
            return 1
        if k == dim_Y and sum(degrees) == n + 1:
            return 1  # CY condition
        return 0
    if m < 0 and sum(degrees) == n + 1:
        # CY Serre duality
        return h_k_cicy_o_m(n, degrees, dim_Y - k, -m)

    return max(0, chi_Y) if k == 0 else 0


def _h_k_ci2_o_m(n: int, d1: int, d2: int, k: int, m: int) -> int:
    r"""H^k(Y, O(m)|_Y) for Y = CI(d1, d2) in P^n via the two-step Koszul.

    The Koszul complex is:
      0 -> O(-d1-d2) -> O(-d1) ⊕ O(-d2) -> O -> O_Y -> 0

    This gives a 3-term complex whose cohomology groups are related to
    H^k(P^n, O(m-d1-d2)), H^k(P^n, O(m-d1)), H^k(P^n, O(m-d2)), H^k(P^n, O(m)).

    The Euler characteristic:
      chi(Y, O(m)) = chi(P^n, O(m)) - chi(P^n, O(m-d1)) - chi(P^n, O(m-d2))
                   + chi(P^n, O(m-d1-d2))
    """
    dim_Y = n - 2
    if k < 0 or k > dim_Y:
        return 0

    # Compute all ambient cohomology groups
    c = [[h_k_pn_o_m(n, kk, m + shift) for kk in range(n + 1)]
         for shift in [0, -d1, -d2, -d1 - d2]]

    # Euler characteristic for verification
    chi_Y = sum((-1)**kk * c[0][kk] for kk in range(n+1)) \
          - sum((-1)**kk * c[1][kk] for kk in range(n+1)) \
          - sum((-1)**kk * c[2][kk] for kk in range(n+1)) \
          + sum((-1)**kk * c[3][kk] for kk in range(n+1))

    # Use vanishing to determine individual H^k
    # Case m > 0:
    if m > 0:
        # For m sufficiently positive: only H^0 survives
        # Specifically: if m > d1 + d2, all twists are >= 0 and only H^0 matters
        if m > d1 + d2:
            return (c[0][0] - c[1][0] - c[2][0] + c[3][0]) if k == 0 else 0
        # Otherwise use chi (all higher vanish by Kodaira on a CI of ample type)
        if k == 0:
            return chi_Y
        return 0

    if m == 0:
        if k == 0:
            return 1
        if k == dim_Y and d1 + d2 == n + 1:
            return 1  # CY condition
        return 0

    # m < 0: use Serre duality if CY
    if d1 + d2 == n + 1:
        return _h_k_ci2_o_m(n, d1, d2, dim_Y - k, -m)

    # Non-CY case with m < 0: use omega_Y = O(d1+d2-n-1)|_Y
    return _h_k_ci2_o_m(n, d1, d2, dim_Y - k, d1 + d2 - n - 1 - m)


def ext_on_cicy(ambient_dim: int, degrees: Tuple[int, ...], i: int, j: int) -> ExtData:
    r"""Compute Ext^*(O(i)|_Y, O(j)|_Y) for a CICY Y in P^n."""
    m = j - i
    dim_Y = ambient_dim - len(degrees)
    dims = {}
    for k in range(dim_Y + 1):
        val = h_k_cicy_o_m(ambient_dim, degrees, k, m)
        if val > 0:
            dims[k] = val
    return ExtData(source=f"O({i})|_Y", target=f"O({j})|_Y", dims=dims)


# =========================================================================
# Section 7: Tilting generators for specific varieties
# =========================================================================

class TiltingGenerator(NamedTuple):
    """A tilting generator T for D^b(Coh(X)).

    T = ⊕ T_i with Ext^{>0}(T, T) = 0 and thick(T) = D^b.
    The endomorphism algebra End(T) = ⊕ Hom(T_i, T_j) determines
    the quiver with relations.
    """
    summands: List[str]
    num_summands: int
    ext_matrix: Dict[Tuple[int, int], ExtData]
    is_tilting: bool  # Ext^{>0}(T, T) = 0
    is_generator: bool  # thick(T) = D^b
    variety: str
    cy_dimension: Optional[int]
    quiver: Optional[QuiverData]


def tilting_generator_pn(n: int) -> TiltingGenerator:
    r"""Beilinson tilting generator on P^n: T = O ⊕ O(1) ⊕ ... ⊕ O(n).

    For P^3: T = O ⊕ O(1) ⊕ O(2) ⊕ O(3).
    The Ext-quiver has n+1 vertices with dim Hom(O(i), O(i+1)) = n+1
    arrows from vertex i to vertex i+1 (for i = 0, ..., n-1).
    """
    ec = beilinson_collection_pn(n)
    quiver = ext_quiver(ec, cy_dim=None)

    return TiltingGenerator(
        summands=ec.objects,
        num_summands=n + 1,
        ext_matrix=ec.ext_matrix,
        is_tilting=ec.is_strong,  # strong exceptional => tilting
        is_generator=ec.is_full,
        variety=f"P^{n}",
        cy_dimension=None,  # P^n is Fano, not CY
        quiver=quiver,
    )


def tilting_generator_quintic() -> TiltingGenerator:
    r"""Tilting generator for D^b(Coh(Q)) where Q is the quintic CY3 in P^4.

    T = ⊕_{i=0}^{4} O(i)|_Q  (restriction of Beilinson collection).

    IMPORTANT: This is NOT an exceptional collection on Q. On P^4 it is
    exceptional, but the restriction to Q may have nonzero Ext groups
    between the restricted line bundles. However, T is still a GENERATOR
    (it generates the derived category) and may still be TILTING
    (have vanishing higher self-Ext).

    For the quintic:
      Ext^k_Q(O(i)|_Q, O(j)|_Q) = H^k(Q, O(j-i)|_Q)
    computed via the Koszul resolution of Q in P^4.
    """
    n = 4  # ambient P^4
    d = 5  # quintic
    num_summands = 5

    summands = [f"O({i})|_Q" for i in range(num_summands)]
    ext_matrix: Dict[Tuple[int, int], ExtData] = {}

    is_tilting = True

    for i in range(num_summands):
        for j in range(num_summands):
            ed = ext_on_hypersurface(n, d, i, j)
            ext_matrix[(i, j)] = ed

            # Check tilting condition: Ext^{>0}(T, T) = 0
            for k_deg, dim_val in ed.dims.items():
                if k_deg > 0 and dim_val > 0:
                    is_tilting = False

    quiver = _build_quiver_from_ext(num_summands, summands, ext_matrix, "quintic CY3", 3)

    return TiltingGenerator(
        summands=summands,
        num_summands=num_summands,
        ext_matrix=ext_matrix,
        is_tilting=is_tilting,
        is_generator=True,  # generates D^b by restriction of Beilinson
        variety="quintic CY3 in P^4",
        cy_dimension=3,
        quiver=quiver,
    )


def tilting_generator_cicy33() -> TiltingGenerator:
    r"""Tilting generator for the CICY (3,3) in P^5.

    The (3,3) complete intersection in P^5 is a CY3:
      Y = {f_3 = 0} ∩ {g_3 = 0} in P^5
    with h^{1,1} = 1, h^{2,1} = 73, chi = -144.

    T = ⊕_{i=0}^{5} O(i)|_Y  (restriction of line bundles from P^5).
    """
    n = 5  # ambient P^5
    degrees = (3, 3)
    num_summands = 6

    summands = [f"O({i})|_Y" for i in range(num_summands)]
    ext_matrix: Dict[Tuple[int, int], ExtData] = {}

    is_tilting = True

    for i in range(num_summands):
        for j in range(num_summands):
            ed = ext_on_cicy(n, degrees, i, j)
            ext_matrix[(i, j)] = ed
            for k_deg, dim_val in ed.dims.items():
                if k_deg > 0 and dim_val > 0:
                    is_tilting = False

    quiver = _build_quiver_from_ext(num_summands, summands, ext_matrix, "CICY (3,3) in P^5", 3)

    return TiltingGenerator(
        summands=summands,
        num_summands=num_summands,
        ext_matrix=ext_matrix,
        is_tilting=is_tilting,
        is_generator=True,
        variety="CICY (3,3) in P^5",
        cy_dimension=3,
        quiver=quiver,
    )


def _build_quiver_from_ext(
    num_summands: int,
    summands: List[str],
    ext_matrix: Dict[Tuple[int, int], ExtData],
    variety: str,
    cy_dim: Optional[int],
) -> QuiverData:
    """Build a QuiverData from an Ext matrix."""
    arrows: Dict[Tuple[int, int], int] = {}
    ext2: Dict[Tuple[int, int], int] = {}

    for i in range(num_summands):
        for j in range(num_summands):
            ed = ext_matrix[(i, j)]
            a1 = ed.dims.get(1, 0)
            a2 = ed.dims.get(2, 0)
            if a1 > 0:
                arrows[(i, j)] = a1
            if a2 > 0:
                ext2[(i, j)] = a2

    is_cy3 = True
    if cy_dim == 3:
        for i in range(num_summands):
            for j in range(num_summands):
                a1_ij = arrows.get((i, j), 0)
                a2_ji = ext2.get((j, i), 0)
                if a1_ij != a2_ji:
                    is_cy3 = False
                    break
            if not is_cy3:
                break
    else:
        is_cy3 = False

    return QuiverData(
        num_vertices=num_summands,
        vertex_labels=summands,
        arrows=arrows,
        ext2_arrows=ext2,
        variety=variety,
        is_cy3_self_dual=is_cy3,
        potential_terms=sum(ext2.values()),
    )


# =========================================================================
# Section 8: Conifold tilting generator (Van den Bergh NCCR)
# =========================================================================

class ConifoldTiltingData(NamedTuple):
    """Tilting generator data for the conifold resolution.

    The resolved conifold X = Tot(O(-1) ⊕ O(-1) -> P^1) has:
      T = O_X ⊕ O_X(1) (= O_P1 ⊕ O_P1(1) considered on the total space)

    The endomorphism algebra is the KW (Klebanov-Witten) path algebra:
      End(T) = ( Hom(O, O)   Hom(O, O(1)) )  =  ( C    C^2 )
               ( Hom(O(1),O) Hom(O(1),O(1)))     ( C^2  C   )

    where Hom(O, O(1)) = H^0(P^1, O(1)) = C^2 and
          Hom(O(1), O) = Ext^1(O(1), O) by Serre duality + CY3.
    But actually on the total space O(-1)⊕O(-1) -> P^1, the calculation
    uses the local CY3 structure.

    The KW quiver has:
      - 2 vertices (corresponding to O and O(1))
      - 2 arrows a_1, a_2: vertex 0 -> vertex 1
      - 2 arrows b_1, b_2: vertex 1 -> vertex 0
    with potential W = a_1 b_1 a_2 b_2 - a_1 b_2 a_2 b_1
                     = tr(a_1 [b_1, a_2] b_2)  (= commutator potential)
    """
    num_vertices: int
    arrows_01: int  # arrows from vertex 0 to vertex 1
    arrows_10: int  # arrows from vertex 1 to vertex 0
    is_cy3_self_dual: bool
    potential: str
    nccr_algebra_dim: int  # dim End(T) as a vector space


def conifold_tilting() -> ConifoldTiltingData:
    r"""Tilting generator for the resolved conifold.

    The resolved conifold is X = Tot(O(-1) ⊕ O(-1) -> P^1).
    The tilting generator is T = O_X ⊕ L where L = O(1) restricted to X.

    By Van den Bergh (2004), End(T) is a noncommutative crepant resolution
    (NCCR) of the conifold singularity xy = zw.

    The Ext computation on the total space X:
      The local CY3 condition means Ext^k(F, G) on X has Serre duality:
        Ext^k(F, G) ~ Ext^{3-k}(G, F)^*

      For T = O ⊕ O(1) on P^1 (the zero section):
        Hom(O, O) = C           Hom(O, O(1)) = C^2
        Hom(O(1), O) = 0        Hom(O(1), O(1)) = C

      But on the TOTAL SPACE (not just P^1), the CY3 structure gives
      additional Ext groups from the normal bundle O(-1)⊕O(-1).

      The correct computation uses the Koszul resolution of O_{P^1} in X:
        Ext^k_X(O_{P^1}, O_{P^1}) depends on the normal bundle.
        N_{P^1/X} = O(-1)⊕O(-1), so /\^k N^* = O(k) for k=0,1,2.
        Actually: /\^0 N^* = O, /\^1 N^* = O(1)⊕O(1), /\^2 N^* = O(2).

      The key result (Bridgeland 2002, Van den Bergh 2004):
        The KW quiver has 2 vertices with 2 arrows in each direction.
        dim End(T) = 1 + 2 + 2 + 1 = 6  (as vector space:
          Hom(0,0)=1, Hom(0,1)=2, Hom(1,0)=2, Hom(1,1)=1)

      This is NOT the naive P^1 computation but the CY3 computation.
    """
    return ConifoldTiltingData(
        num_vertices=2,
        arrows_01=2,
        arrows_10=2,
        is_cy3_self_dual=True,  # 2 = 2 (arrows balanced)
        potential="a1*b1*a2*b2 - a1*b2*a2*b1",
        nccr_algebra_dim=6,
    )


# =========================================================================
# Section 9: CY3 constraint verification
# =========================================================================

def verify_cy3_serre_duality(
    ext_matrix: Dict[Tuple[int, int], ExtData],
    num_summands: int,
) -> Tuple[bool, List[str]]:
    r"""Verify the CY3 Serre duality constraint on the Ext-quiver.

    For a CY3 X with tilting generator T = ⊕ T_i:
      dim Ext^1(T_i, T_j) = dim Ext^2(T_j, T_i)
      dim Ext^0(T_i, T_j) = dim Ext^3(T_j, T_i)

    This is Serre duality with omega_X = O_X and dim X = 3.

    Returns (is_satisfied, list of violations).
    """
    violations = []
    is_satisfied = True

    for i in range(num_summands):
        for j in range(num_summands):
            ed_ij = ext_matrix[(i, j)]
            ed_ji = ext_matrix[(j, i)]

            # Ext^1(T_i, T_j) = Ext^2(T_j, T_i)
            e1_ij = ed_ij.dims.get(1, 0)
            e2_ji = ed_ji.dims.get(2, 0)
            if e1_ij != e2_ji:
                violations.append(
                    f"Ext^1(T_{i}, T_{j})={e1_ij} != Ext^2(T_{j}, T_{i})={e2_ji}"
                )
                is_satisfied = False

            # Ext^0(T_i, T_j) = Ext^3(T_j, T_i)
            e0_ij = ed_ij.dims.get(0, 0)
            e3_ji = ed_ji.dims.get(3, 0)
            if e0_ij != e3_ji:
                violations.append(
                    f"Ext^0(T_{i}, T_{j})={e0_ij} != Ext^3(T_{j}, T_{i})={e3_ji}"
                )
                is_satisfied = False

    return is_satisfied, violations


# =========================================================================
# Section 10: Euler form and chi on derived categories
# =========================================================================

def euler_form_pn(n: int, i: int, j: int) -> int:
    r"""Euler form chi(O(i), O(j)) = sum_k (-1)^k dim Ext^k(O(i), O(j)) on P^n.

    By HRR: chi(O(i), O(j)) = chi(P^n, O(j-i)) = C(n+j-i, n).
    """
    return euler_char_pn_o_m(n, j - i)


def euler_form_hypersurface(n: int, d: int, i: int, j: int) -> int:
    r"""Euler form chi(O(i)|_Y, O(j)|_Y) for Y = {f_d=0} in P^n.

    chi(Y, O(m)|_Y) = chi(P^n, O(m)) - chi(P^n, O(m-d))
                     = C(n+m, n) - C(n+m-d, n).
    """
    m = j - i
    return euler_char_pn_o_m(n, m) - euler_char_pn_o_m(n, m - d)


def euler_form_cicy(ambient_dim: int, degrees: Tuple[int, ...], i: int, j: int) -> int:
    r"""Euler form chi(O(i)|_Y, O(j)|_Y) for a CICY Y in P^n.

    chi(Y, O(m)|_Y) = sum_{S subset degrees} (-1)^{|S|} chi(P^n, O(m - sum_S)).
    """
    m = j - i
    n = ambient_dim
    r = len(degrees)
    chi_val = 0
    for mask in range(1 << r):
        sign = (-1) ** bin(mask).count('1')
        d_sum = sum(degrees[idx] for idx in range(r) if mask & (1 << idx))
        chi_val += sign * euler_char_pn_o_m(n, m - d_sum)
    return chi_val


def euler_form_matrix_pn(n: int) -> List[List[int]]:
    """Euler form matrix for the Beilinson collection on P^n.

    Returns chi(O(i), O(j)) for 0 <= i, j <= n.
    """
    return [[euler_form_pn(n, i, j) for j in range(n + 1)] for i in range(n + 1)]


def euler_form_matrix_quintic() -> List[List[int]]:
    """Euler form matrix for the restricted Beilinson collection on the quintic."""
    return [[euler_form_hypersurface(4, 5, i, j) for j in range(5)] for i in range(5)]


def euler_form_matrix_cicy33() -> List[List[int]]:
    """Euler form matrix for the restricted Beilinson collection on CICY (3,3) in P^5."""
    return [[euler_form_cicy(5, (3, 3), i, j) for j in range(6)] for i in range(6)]


# =========================================================================
# Section 11: K3 tilting and the non-exceptional-collection case
# =========================================================================

class K3TiltingData(NamedTuple):
    """Tilting data for D^b(K3).

    K3 does NOT have a full exceptional collection (by a result of
    Bridgeland, proved via the lattice theory of the Mukai lattice:
    the rank of K_0(K3) = 24 but the Euler form has signature (4, 20),
    and a full exceptional collection would require the form to be
    upper-triangular with 1s on the diagonal, which is impossible for
    indefinite signature).

    However, by Bondal-Van den Bergh, a tilting generator EXISTS
    (it just cannot be a direct sum of line bundles forming an
    exceptional collection). The tilting generator is a more general
    object (e.g., a spherical object or a direct sum including
    structure sheaves of curves).

    For K3 x E: the tilting generator, if it exists, would be
    T_{K3} ⊠ T_E, but since T_{K3} is not an exceptional collection,
    the product tilting generator is also non-classical.
    """
    has_exceptional_collection: bool
    k0_rank: int
    mukai_lattice_signature: Tuple[int, int]
    bvdb_tilting_exists: bool
    tilting_is_line_bundle_sum: bool
    reason_no_exceptional: str


def k3_tilting_data() -> K3TiltingData:
    r"""K3 tilting data.

    K_0(K3) has rank 24 (= b_0 + b_2 + b_4 = 1 + 22 + 1).
    The Mukai lattice H*(K3, Z) = U^3 ⊕ E_8(-1)^2 has signature (4, 20).
    The Euler form on K_0 is:
      chi(E, F) = sum (-1)^k dim Ext^k(E, F) = -<v(E), v(F)>
    where v(E) is the Mukai vector and <-,-> is the Mukai pairing.

    A full exceptional collection of length 24 would require K_0 = Z^{24}
    with the Euler form being upper-triangular (1s on diagonal). But the
    Mukai pairing has signature (4, 20), so this is impossible.

    BVdB theorem still guarantees a tilting generator exists, but it is
    not a direct sum of exceptional objects.
    """
    return K3TiltingData(
        has_exceptional_collection=False,
        k0_rank=24,
        mukai_lattice_signature=(4, 20),
        bvdb_tilting_exists=True,
        tilting_is_line_bundle_sum=False,
        reason_no_exceptional=(
            "The Mukai lattice H*(K3, Z) = U^3 + E_8(-1)^2 has signature "
            "(4, 20). A full exceptional collection of length 24 would require "
            "the Euler form matrix to be upper-triangular with 1s on the "
            "diagonal, giving determinant 1 and positive-definite form "
            "on the quotient. But signature (4, 20) is indefinite, "
            "contradicting this requirement."
        ),
    )


def k3_times_e_tilting_data() -> Dict[str, Any]:
    r"""Tilting data for K3 x E.

    Since K3 lacks a full exceptional collection, K3 x E also lacks one.
    The tilting generator exists by BVdB (K3 x E is smooth projective)
    but is not a tensor product of exceptional collections.

    The K_0 rank:
      K_0(K3 x E) = K_0(K3) ⊗ K_0(E) has rank 24 * 2 = 48.
    (K_0(E) has rank 2: generated by O_E and O_E(p) for a point p.)
    """
    return {
        "variety": "K3 x E",
        "k0_rank": 48,
        "has_exceptional_collection": False,
        "bvdb_tilting_exists": True,
        "reason": "K3 factor lacks exceptional collection; K3 x E inherits this obstruction.",
        "cy_dimension": 3,
    }


# =========================================================================
# Section 12: E_1 chiral algebra from tilting generator
# =========================================================================

class E1ChiralFromTilting(NamedTuple):
    """The E_1 chiral algebra A_X = Fact_X(End(T)).

    The tilting generator T determines the E_1 chiral algebra:
      A_X = Fact_X(End(T))
    where Fact_X is the factorization envelope functor on X.

    For C^3: T = O_{C^3}, End(T) = C (trivial algebra).
      Fact(C) = Heisenberg = W_{1+infty} at c = 0.

    For the conifold: End(T) = KW path algebra.
      Fact(KW) = non-abelian chiral algebra.

    For the quintic: End(T) = (5x5 matrix of Ext groups).
      Fact(End(T)) = the quintic E_1 chiral algebra.
    """
    variety: str
    end_algebra_dim: int  # dim End(T) as a vector space
    end_algebra_description: str
    e1_chiral_description: str
    cy_dimension: Optional[int]


def e1_chiral_c3() -> E1ChiralFromTilting:
    """E_1 chiral algebra for C^3 from the tilting generator T = O.

    End(O_{C^3}) = C (the ground field). The factorization envelope of
    the trivial algebra is the Heisenberg/W_{1+infty} at c = 0.

    At sigma_3 != 0 (Omega-deformation): the deformed End(T) is
    non-trivial, and the factorization envelope produces the full
    W_{1+infty} at arbitrary c.
    """
    return E1ChiralFromTilting(
        variety="C^3",
        end_algebra_dim=1,
        end_algebra_description="C (ground field, trivial algebra)",
        e1_chiral_description="W_{1+infty} at c=0 (Heisenberg)",
        cy_dimension=3,
    )


def e1_chiral_conifold() -> E1ChiralFromTilting:
    """E_1 chiral algebra for the resolved conifold.

    End(T) = KW path algebra (dim 6).
    Fact(KW) = non-abelian E_1 chiral algebra.
    """
    return E1ChiralFromTilting(
        variety="resolved conifold",
        end_algebra_dim=6,
        end_algebra_description="Klebanov-Witten path algebra (2 vertices, 4 arrows, potential W)",
        e1_chiral_description="Non-abelian E_1 chiral algebra from KW quiver",
        cy_dimension=3,
    )


def e1_chiral_quintic() -> E1ChiralFromTilting:
    """E_1 chiral algebra for the quintic.

    End(T) = the path algebra of the quintic Ext-quiver (5 vertices).
    """
    tg = tilting_generator_quintic()
    total_dim = sum(ed.total_dim for ed in tg.ext_matrix.values())
    return E1ChiralFromTilting(
        variety="quintic CY3",
        end_algebra_dim=total_dim,
        end_algebra_description=f"Path algebra of quintic Ext-quiver ({tg.num_summands} vertices)",
        e1_chiral_description="Quintic E_1 chiral algebra from restricted Beilinson",
        cy_dimension=3,
    )


# =========================================================================
# Section 13: Hodge numbers of standard CY3 hypersurfaces and CICYs
# =========================================================================

def quintic_h11() -> int:
    """h^{1,1} of the quintic = 1."""
    return 1


def quintic_h21() -> int:
    """h^{2,1} of the quintic = 101."""
    return 101


def quintic_euler() -> int:
    """Euler characteristic of the quintic = -200."""
    return 2 * (quintic_h11() - quintic_h21())


def cicy33_h11() -> int:
    """h^{1,1} of CICY (3,3) in P^5 = 1."""
    return 1


def cicy33_h21() -> int:
    """h^{2,1} of CICY (3,3) in P^5 = 73."""
    return 73


def cicy33_euler() -> int:
    """Euler characteristic of CICY (3,3) in P^5 = -144."""
    return 2 * (cicy33_h11() - cicy33_h21())


def cicy_hodge(ambient_dim: int, degrees: Tuple[int, ...]) -> Tuple[int, int]:
    r"""Compute (h^{1,1}, h^{2,1}) for a CICY in P^n via the Lefschetz+Euler method.

    For a smooth CICY Y of dimension 3 in P^n with multi-degree (d_1, ..., d_r):
      h^{1,1} = 1 (by Lefschetz hyperplane theorem, for codimension <= n-4 = dim Y - 1)
      h^{2,1} = 1 - chi(Y)/2  (from chi = 2(h^{1,1} - h^{2,1}) with h^{1,1} = 1)

    The Euler characteristic:
      chi(Y) = integral over Y of c_3(TY)
    For a CI of type (d_1, ..., d_r) in P^n:
      chi = coefficient of H^n in n! * [prod_{i} d_i * H / (1 + d_i * H)]
            * [(1+H)^{n+1} / prod_{i} (1 + d_i * H)]... no.

    Actually, the Euler characteristic of a CI can be computed from the
    Chern classes of the tangent bundle of Y:
      TY = TP^n|_Y - N_{Y/P^n}
    where N = ⊕ O(d_i).

    The total Chern class:
      c(TY) = c(TP^n)|_Y / c(N)|_Y = (1+H)^{n+1} / prod_i (1 + d_i H)

    restricted to Y (where H is the hyperplane class and H^{dim Y + 1} = 0 on Y,
    but we need to integrate H^{dim Y} which is the degree = prod d_i).

    chi(Y) = integral_Y c_{dim Y}(TY)
           = deg(Y) * [coefficient of H^{dim Y} in c(TY)]
    where deg(Y) = prod d_i.

    Actually, for a CI of dimension dim_Y in P^n:
      chi(Y) = prod(d_i) * coefficient of t^{dim_Y} in
        [(1+t)^{n+1} / prod_i (1 + d_i t)] expanded in t, then evaluated
        at t = 0... no, we need the c_{dim_Y} coefficient.

    The correct formula: expand
      c(TY) = (1+H)^{n+1} / prod_i (1 + d_i H)
    as a polynomial in H (modulo H^{dim_Y + 1}), then
      chi(Y) = deg(Y) * coefficient of H^{dim_Y} in c_{dim_Y}(TY).

    Wait: c(TY) = 1 + c_1 + c_2 + c_3 + ..., and chi(Y) = integral c_{dim_Y}.
    For Y of dimension 3: chi = integral c_3(TY).
    On Y: H^3 integrates to deg(Y) = prod d_i.
    So chi = [coefficient of H^3 in c_3(TY)] * prod d_i.

    But c_3 is the degree-3 part of (1+H)^{n+1} / prod (1+d_i H), which is
    a formal power series in H.
    """
    n = ambient_dim
    r = len(degrees)
    dim_Y = n - r

    if dim_Y != 3:
        raise ValueError(f"Expected CY3 (dim 3), got dim {dim_Y}")

    # Check CY condition: sum(d_i) = n + 1
    if sum(degrees) != n + 1:
        raise ValueError(f"Not CY: sum of degrees {sum(degrees)} != {n+1}")

    # Compute c(TY) = (1+H)^{n+1} / prod (1+d_i H) as a polynomial in H
    # up to degree 3.

    # Numerator: (1+H)^{n+1}
    # Expand to get coefficients: C(n+1, k) for k = 0, 1, 2, 3.
    num = [binomial(n + 1, k) for k in range(4)]

    # Denominator: prod (1 + d_i H)
    # We need the inverse: 1 / prod(1 + d_i H) = prod 1/(1+d_i H)
    # Each factor: 1/(1+d_i H) = 1 - d_i H + d_i^2 H^2 - d_i^3 H^3 + ...
    # Product of geometric series truncated to degree 3.

    denom_inv = [Fraction(1), Fraction(0), Fraction(0), Fraction(0)]
    for di in degrees:
        # Multiply denom_inv by (1 - di H + di^2 H^2 - di^3 H^3)
        geo = [Fraction((-di) ** k) for k in range(4)]
        new = [Fraction(0)] * 4
        for a in range(4):
            for b in range(4 - a):
                new[a + b] += denom_inv[a] * geo[b]
        denom_inv = new

    # c(TY) = num * denom_inv
    c_ty = [Fraction(0)] * 4
    for a in range(4):
        for b in range(4 - a):
            c_ty[a + b] += Fraction(num[a]) * denom_inv[b]

    # c_3(TY) = c_ty[3] (the coefficient of H^3)
    c3 = c_ty[3]

    # chi(Y) = deg(Y) * c3
    deg_Y = 1
    for di in degrees:
        deg_Y *= di

    chi_Y = int(deg_Y * c3)

    # For Lefschetz: h^{1,1} = 1 for CI of dim >= 3 in P^n
    h11 = 1

    # chi = 2(h^{1,1} - h^{2,1}) => h^{2,1} = h^{1,1} - chi/2
    h21 = h11 - chi_Y // 2

    return (h11, h21)


# =========================================================================
# Section 14: Quiver with potential for CY3
# =========================================================================

class QuiverWithPotential(NamedTuple):
    """A quiver with potential (Q, W) satisfying the CY3/Ginzburg condition.

    The potential W is a linear combination of oriented cycles in Q.
    The Jacobian algebra Jac(Q, W) = kQ / (dW/da for each arrow a)
    is the endomorphism algebra of the tilting generator.

    For CY3: W comes from the A_infinity m_3 product (the CY3 formality
    theorem ensures m_k = 0 for k >= 4 in many cases).
    """
    num_vertices: int
    arrows: List[Tuple[int, int, str]]  # (source, target, label)
    potential_terms: List[Tuple[str, int]]  # (cycle_monomial, coefficient)
    is_cy3: bool
    jacobian_dim: Optional[int]  # dim Jac(Q, W) if finite


def conifold_qwp() -> QuiverWithPotential:
    """The Klebanov-Witten quiver with potential for the conifold.

    Q: 2 vertices {0, 1}.
    Arrows: a1, a2: 0 -> 1 and b1, b2: 1 -> 0.
    W = a1 b1 a2 b2 - a1 b2 a2 b1 (the commutator potential).

    The Jacobian relations:
      dW/da1 = b1 a2 b2 - b2 a2 b1 = 0
      dW/da2 = b2 a1 b1 - b1 a1 b2 = 0  (cyclic version)
      dW/db1 = a2 b2 a1 - a1 ... (similarly)
      dW/db2 = a1 b1 a2 - a2 b1 a1 = 0

    These are the commutativity relations of the conifold coordinate ring
    C[x, y, z, w] / (xy - zw).
    """
    arrows = [
        (0, 1, "a1"), (0, 1, "a2"),
        (1, 0, "b1"), (1, 0, "b2"),
    ]
    potential = [
        ("a1*b1*a2*b2", 1),
        ("a1*b2*a2*b1", -1),
    ]
    return QuiverWithPotential(
        num_vertices=2,
        arrows=arrows,
        potential_terms=potential,
        is_cy3=True,
        jacobian_dim=None,  # infinite-dimensional (conifold is non-compact)
    )


def p3_quiver() -> QuiverWithPotential:
    r"""The Beilinson quiver for P^3.

    4 vertices {0, 1, 2, 3} with 4 arrows between consecutive vertices:
      x_i^{(k)}: vertex k -> vertex k+1 for i = 0, 1, 2, 3 (corresponding
      to the 4 homogeneous coordinates on P^3).

    The potential W comes from the commutativity relations:
      x_i^{(k)} x_j^{(k+1)} = x_j^{(k)} x_i^{(k+1)}
    which are encoded as the potential:
      W = sum_{i<j, k} (x_i^{(k)} x_j^{(k+1)} x_m^{(k+2)} -
                         x_j^{(k)} x_i^{(k+1)} x_m^{(k+2)})
    (summing over all 3-cycles).

    NOTE: P^3 is NOT CY3. It is Fano. The quiver with potential structure
    still exists but does not satisfy the CY3 Ginzburg condition.
    """
    arrows = []
    for k in range(3):  # edges from vertex k to k+1
        for i in range(4):  # 4 arrows per edge
            arrows.append((k, k + 1, f"x{i}_{k}"))

    # Potential: commutativity relations as 3-cycles
    # Each relation x_i^{(k)} x_j^{(k+1)} = x_j^{(k)} x_i^{(k+1)}
    # generates a term in W.
    potential = []
    for k in range(1):  # only one 3-cycle layer (0->1->2->3 is a 3-step path)
        for i in range(4):
            for j in range(i + 1, 4):
                potential.append((f"x{i}_{0}*x{j}_{1}*x{i}_{2}", 1))
                potential.append((f"x{j}_{0}*x{i}_{1}*x{i}_{2}", -1))

    return QuiverWithPotential(
        num_vertices=4,
        arrows=arrows,
        potential_terms=potential,
        is_cy3=False,  # P^3 is Fano, not CY
        jacobian_dim=None,
    )


# =========================================================================
# Section 15: Bott's formula extended computations
# =========================================================================

def all_cohomology_pn_twist(n: int, m: int) -> Dict[int, int]:
    """All H^k(P^n, O(m)) in a single dict."""
    result = {}
    for k in range(n + 1):
        val = h_k_pn_o_m(n, k, m)
        if val > 0:
            result[k] = val
    return result


def cohomology_table_pn(n: int, m_range: Tuple[int, int]) -> List[Dict[str, Any]]:
    """Table of H^k(P^n, O(m)) for m in [m_range[0], m_range[1]]."""
    table = []
    for m in range(m_range[0], m_range[1] + 1):
        row = {"m": m}
        for k in range(n + 1):
            row[f"H^{k}"] = h_k_pn_o_m(n, k, m)
        row["chi"] = euler_char_pn_o_m(n, m)
        table.append(row)
    return table


# =========================================================================
# Section 16: Summary functions
# =========================================================================

def tilting_summary_pn(n: int) -> Dict[str, Any]:
    """Summary of tilting generator data for P^n."""
    tg = tilting_generator_pn(n)
    hom_dims = {}
    for i in range(n + 1):
        for j in range(n + 1):
            if i != j:
                ed = tg.ext_matrix[(i, j)]
                d0 = ed.dims.get(0, 0)
                if d0 > 0:
                    hom_dims[(i, j)] = d0
    return {
        "variety": f"P^{n}",
        "num_summands": n + 1,
        "is_tilting": tg.is_tilting,
        "is_generator": tg.is_generator,
        "hom_dimensions": hom_dims,
        "total_arrows": sum(tg.quiver.arrows.values()) if tg.quiver else 0,
    }


def tilting_summary_quintic() -> Dict[str, Any]:
    """Summary of tilting generator data for the quintic."""
    tg = tilting_generator_quintic()
    return {
        "variety": "quintic CY3",
        "num_summands": tg.num_summands,
        "is_tilting": tg.is_tilting,
        "is_generator": tg.is_generator,
        "cy_dimension": tg.cy_dimension,
        "quiver_arrows": dict(tg.quiver.arrows) if tg.quiver else {},
        "cy3_self_dual": tg.quiver.is_cy3_self_dual if tg.quiver else False,
    }


def tilting_summary_cicy33() -> Dict[str, Any]:
    """Summary of tilting generator data for CICY (3,3) in P^5."""
    tg = tilting_generator_cicy33()
    return {
        "variety": "CICY (3,3) in P^5",
        "num_summands": tg.num_summands,
        "is_tilting": tg.is_tilting,
        "is_generator": tg.is_generator,
        "cy_dimension": tg.cy_dimension,
        "quiver_arrows": dict(tg.quiver.arrows) if tg.quiver else {},
        "cy3_self_dual": tg.quiver.is_cy3_self_dual if tg.quiver else False,
    }
