r"""Twisted holographic dual of CY3 E₁ chiral algebras (Costello-Li framework).

Constructs the holographic modular Koszul datum for CY3 threefolds:

    H(X) = (A_X, A_{X̌}, C_X, r_{CY}(z), Theta^{E1}_X, nabla^{E1})

following the Costello-Li twisted holography programme, where M-theory on
CY3 × TN_k (Taub-NUT) produces a duality between:
  - Boundary: the CY3 E₁ chiral algebra A_X (open string side)
  - Bulk: a 5d Chern-Simons theory on CY3 × R² (closed string side)

MATHEMATICAL CONTENTS:

1. THE 5D CS THEORY.
   S_{5dCS} = int_{CY3 × R²} omega ∧ CS(A)
   where omega = Omega_X is the CY holomorphic volume form on X and
   CS(A) = Tr(A ∧ dA + 2/3 A³) is the Chern-Simons 3-form on
   the remaining 2+1 dimensions (the R² factor times one direction from CY3).

   For X = C³: the gauge algebra is gl_1-valued (abelian at the linearized level),
   and the 5d CS theory reduces to an abelian CS theory whose quantization
   produces the affine Yangian Y(gl_hat_1).

   WARNING: "5d CS on CY3 × R²" is a schematic description. The precise statement
   is that the TWIST of the 11d supergravity compactified on CY3 × TN_k gives
   a 5d holomorphic-topological theory on C² × R (or equivalently C × R² after
   a topological twist along one C-direction), with the C-direction supporting
   the chiral algebra structure and the R²-directions being topological.

2. THE BOUNDARY E₁ CHIRAL ALGEBRA A_X.
   For CY3 = C³: A_{C³} = W_{1+∞} at c = 1 (equivalently, the affine Yangian
   Y(gl_hat_1) at the self-dual point h₁ + h₂ + h₃ = 0).
   This is the CoHA of C³ after Drinfeld doubling: the CoHA Y^+(gl_hat_1)
   gives the positive half, and the Drinfeld double produces the full W_{1+∞}.

   For general toric CY3: A_X is the gluing of affine Yangians along the
   toric web diagram (Rapcak-Soibelman-Yang-Zhao).

3. THE E₁ KOSZUL DUAL A_X^!.
   In the E₁ (associative) setting, Koszul duality is Ass^! = Ass{-1}.
   The boundary algebra A_X on the LEFT boundary of R² has Koszul dual
   A_X^! on the RIGHT boundary. The bulk 5d CS theory mediates between them.

   For C³: A_{C³} = W_{1+∞} is generated by currents W_s (s = 1, 2, 3, ...).
   The E₁ Koszul dual A_{C³}^! is the algebra of the RIGHT boundary condition.

   CAUTION (AP33): The Koszul dual A^! ≠ A at level -k. The E₁ Koszul dual
   uses the associative (Hochschild) duality, not the Lie-theoretic (FF) duality.

   For the Heisenberg H_k (spin-1 sector): H_k^! = Sym^ch(V*) with kappa = -k.
   For the full W_{1+∞}: the E₁ Koszul dual is W_{1+∞} at the REFLECTED
   parameters (h₁, h₂, h₃) → (-h₁, -h₂, -h₃), which preserves the CY
   condition h₁ + h₂ + h₃ = 0. The structure function inverts:
     g^!(z) = g(z)^{-1} = g(-z)     (by the CY-induced symmetry).

4. THE COLLISION R-MATRIX r_{CY}(z).
   r_{CY}(z) = Res^{coll}_{0,2}(Theta^{E₁}_X)

   For C³: this is the Yang R-matrix of the affine Yangian Y(gl_hat_1):
     R(u) = g(u) * (identity + corrections from higher modes)

   At the LINEARIZED level (leading pole):
     r(z) = phi_3 / z³ + phi_5 / z⁵ + ...     (only odd poles by CY symmetry)

   The absence of even-order poles is a consequence of the CY condition:
   g(-z) = 1/g(z), so the R-matrix satisfies R(z)R(-z) = 1 (unitarity),
   which forces the expansion to have only odd-order terms.

   CAUTION (AP19): The r-matrix lives one pole order below the OPE.
   The affine Yangian OPE has poles from the structure function g(z);
   the collision residue extracts the d-log kernel, reducing pole orders by 1.

5. THE MC ELEMENT Theta^{E₁}_X.
   The E₁ MC element is the bar-intrinsic construction applied to the
   E₁ bar complex B^{E₁}(A_X):
     Theta^{E₁}_X := D_{A_X} - d_0   in MC(Def_cyc^{E₁}(A_X) hat⊗ G_mod)

   This is the ordered (Hochschild) version of the Vol I construction.
   The key difference: the E₁ bar uses the ORDERED tensor coalgebra T^c(A_X[1]),
   not the symmetric coalgebra Sym^c(A_X[1]).

   For C³: the scalar shadow is kappa^{E₁}(W_{1+∞}) at the cutoff level N,
   with kappa^{E₁} = kappa^{E_∞} = c * H_N at the self-dual point (trivial R-matrix).

6. THE E₁ SHADOW CONNECTION nabla^{E₁}.
   nabla^{E₁}_{g,n} = d - Sh_{g,n}(Theta^{E₁}_X)
   The shadow connection restricted to genus 0:
     nabla^{E₁}_{0,n} = d - sum_{i<j} r_{CY}(z_i - z_j) / (z_i - z_j)
   recovers the KZ-type connection for the affine Yangian.

   For C³: at the self-dual point, this is the TRIVIAL connection (the
   Heisenberg algebra has no KZ equation). Away from self-duality,
   it is the trigonometric/elliptic deformation.

7. THE M2/M5 BRANE SYSTEM.
   M2-branes on CY3 × R_t (point branes in X):
     Produce the boundary E₁ chiral algebra A_X via the CoHA construction.
     The brane algebra is End(O_p) = Ext*(O_p, O_p) = Wedge(eps_1, eps_2, eps_3).
   M5-branes wrapping CY3 (wrapping the entire X):
     Produce the Koszul dual A_X^! via Kodaira-Spencer / gravitational theory.
     The gravitational algebra is CE*(C[z_1,z_2,z_3] ⋉ C[z_1,z_2,z_3][1]).
   Holographic duality: lim_{N → ∞} A_N = B^!
     (Conjecture from physics_mtheory_branes.tex, conj:holographic-kd).

CONVENTIONS:
  - Cohomological grading (|d| = +1).
  - Bar uses DESUSPENSION: |s^{-1}v| = |v| - 1 (AP45).
  - CY condition: h₁ + h₂ + h₃ = 0 (equivalently epsilon_1 + epsilon_2 + epsilon_3 = 0).
  - kappa formulas are family-specific (AP1). Never copy between families.
  - kappa(W_{1+∞}) at c=1 with spin cutoff N: kappa = c * H_N (AP48).
  - The structure function g(z) has phi_1 = 0 (CY condition).
  - The R-matrix has only ODD-order poles (CY symmetry g(-z) = 1/g(z)).

REFERENCES:
  Costello-Li (arXiv:1606.00443): Twisted holography for M-theory.
  Costello-Paquette (arXiv:2204.14113): Celestial holography meets twisted.
  Gaiotto-Rapcak (arXiv:1706.05127): Vertex algebras at corners.
  Schiffmann-Vasserot (arXiv:1211.1287): CoHA of C³ = Y^+(gl_hat_1).
  Prochazka-Rapcak (arXiv:1910.07997): W_{1+∞} = affine Yangian.
  Rapcak-Soibelman-Yang-Zhao (arXiv:1810.10402): Toric CY3 from CoHAs.
  Vol I: frontier_modular_holography_platonic.tex (def:holographic-modular-koszul-datum).
  Vol I: holomorphic_topological.tex (HT boundary conditions).
  Vol III: physics_mtheory_branes.tex, theory_coha_e1_sector.tex.
"""

from __future__ import annotations

import math
import os
import sys
from fractions import Fraction
from typing import Any, Dict, List, Optional, Tuple

# ---------------------------------------------------------------------------
# Path setup for cross-volume imports
# ---------------------------------------------------------------------------

_VOL1_LIB = os.path.expanduser("~/chiral-bar-cobar/compute/lib")
_VOL3_LIB = os.path.expanduser("~/calabi-yau-quantum-groups/compute/lib")

for _p in [_VOL1_LIB, _VOL3_LIB]:
    if _p not in sys.path:
        sys.path.insert(0, _p)


# ===========================================================================
# 1. CALABI-YAU GEOMETRY: Omega-deformation parameters and CY condition
# ===========================================================================

def cy_condition_check(h1: Fraction, h2: Fraction,
                       h3: Optional[Fraction] = None) -> bool:
    """Verify the CY condition h₁ + h₂ + h₃ = 0.

    If h3 is None, computes h3 = -(h1+h2) and returns True (enforced).
    """
    if h3 is None:
        return True
    return h1 + h2 + h3 == 0


def enforce_cy(h1: Fraction, h2: Fraction) -> Tuple[Fraction, Fraction, Fraction]:
    """Return (h1, h2, h3) with h3 = -(h1+h2) enforcing CY condition."""
    return (h1, h2, -(h1 + h2))


def sigma_2_cy(h1: Fraction, h2: Fraction) -> Fraction:
    """Second elementary symmetric polynomial sigma_2 = h1*h2 + h1*h3 + h2*h3.

    With h3 = -(h1+h2): sigma_2 = -(h1² + h1*h2 + h2²).
    """
    h3 = -(h1 + h2)
    return h1 * h2 + h1 * h3 + h2 * h3


def sigma_3_cy(h1: Fraction, h2: Fraction) -> Fraction:
    """Third elementary symmetric polynomial sigma_3 = h1*h2*h3.

    With h3 = -(h1+h2): sigma_3 = -h1*h2*(h1+h2).
    """
    h3 = -(h1 + h2)
    return h1 * h2 * h3


def power_sum(k: int, h1: Fraction, h2: Fraction) -> Fraction:
    """Power sum p_k = h1^k + h2^k + h3^k with h3 = -(h1+h2).

    CY condition ensures p_1 = 0.
    """
    h3 = -(h1 + h2)
    return h1**k + h2**k + h3**k


def self_dual_parameters() -> Tuple[Fraction, Fraction, Fraction]:
    """The self-dual point: h1 = 1, h2 = 0, h3 = -1.

    At this point the R-matrix is trivial and W_{1+∞} reduces to
    the Heisenberg algebra (all higher generators decouple).

    More precisely, the limit is h1 = 1, h2 = epsilon, h3 = -1-epsilon
    with epsilon → 0. The self-dual point IS the Heisenberg limit.
    """
    return (Fraction(1), Fraction(0), Fraction(-1))


def generic_parameters(epsilon: Fraction = Fraction(1, 3)
                       ) -> Tuple[Fraction, Fraction, Fraction]:
    """Generic CY3 parameters: h1 = 1, h2 = epsilon, h3 = -1-epsilon.

    The W_{1+∞} algebra is non-degenerate (genuine higher spin) for epsilon ≠ 0.
    """
    h1 = Fraction(1)
    h2 = epsilon
    h3 = -(h1 + h2)
    return (h1, h2, h3)


# ===========================================================================
# 2. THE 5D CHERN-SIMONS THEORY
# ===========================================================================

def cs_action_integrand_degree(dim_cy: int = 3) -> Dict[str, Any]:
    """Degree analysis of the 5d CS action S = int omega ∧ CS(A).

    omega = holomorphic (d,0)-form on CY_d, has form degree d.
    CS(A) = Tr(A ∧ dA + 2/3 A³), a 3-form on the remaining directions.
    Total: (d+3)-form on a (2d+2)-dimensional space (CY_d × R²).

    Wait: CY3 × R² is 6+2 = 8 dimensional. But omega ∧ CS(A) is a
    3+3 = 6-form on an 8-manifold. This doesn't integrate!

    CORRECTION: The Costello-Li 5d CS theory lives on C² × R_t
    (4+1 = 5 real dimensions), NOT on all of CY3 × R².
    The CY3 has been COMPACTIFIED, and the 5d theory is the
    KK-reduced effective theory.

    For C³ = C × C² (schematically):
      - C direction: supports chiral algebra structure
      - C² direction: the omega-plane, topologically twisted
      - R_t direction: time / operator ordering

    The 5d CS action on C² × R_t is:
      S = int_{C² × R_t} dz₁ ∧ dz₂ ∧ CS(A)
    where dz₁ ∧ dz₂ is the holomorphic 2-form on C² (from the CY3 volume
    form after extracting one dz direction for the chiral algebra).

    Total form degree: 2 (from dz₁ ∧ dz₂) + 3 (from CS(A)) = 5 on a
    5-dimensional space. This DOES integrate.
    """
    return {
        'spacetime_dim': 2 * dim_cy - 1,
        'omega_degree': dim_cy - 1,
        'cs_form_degree': 3,
        'total_form_degree': dim_cy - 1 + 3,
        'integrand_matches': (dim_cy - 1 + 3 == 2 * dim_cy - 1),
        'gauge_algebra': 'gl_1' if dim_cy == 3 else f'gl_1 (CY_{dim_cy})',
        'description': (
            f'5d CS on C^{dim_cy - 1} × R_t. '
            f'Omega has degree {dim_cy - 1}, CS has degree 3. '
            f'Total {dim_cy + 2}-form on {2 * dim_cy - 1}-manifold.'
        ),
    }


def cs_5d_gauge_content_c3() -> Dict[str, Any]:
    """Gauge content of the 5d CS theory for X = C³.

    After Omega-deformation with parameters (epsilon_1, epsilon_2, epsilon_3),
    the 5d CS theory on C² × R_t has:
      - Gauge field A in Omega^*(C² × R_t) ⊗ gl_1[epsilon_1, epsilon_2, epsilon_3]
      - The odd variables epsilon_i encode the CY3 normal directions
      - The BV action is S = int dz₁ ∧ dz₂ ∧ Tr(A ∧ dA + 2/3 A³)

    In the Omega-background, the U(1) gauge symmetry is promoted to
    the affine Yangian Y(gl_hat_1) upon quantization.

    The boundary condition at z₂ = 0 (left boundary of C²) produces
    the E₁ chiral algebra on the z₁-line.
    """
    return {
        'gauge_algebra': 'gl_1',
        'spacetime': 'C² × R_t',
        'bv_fields': 'Omega*(C² × R_t) ⊗ gl_1[eps_1, eps_2, eps_3]',
        'quantization': 'Y(gl_hat_1) (affine Yangian of gl_1)',
        'boundary_left': 'W_{1+inf} (E₁ chiral algebra)',
        'boundary_right': 'W_{1+inf}^! (E₁ Koszul dual)',
        'omega_form': 'dz_1 ∧ dz_2',
        'coupling_constant': 'g_s = h₁ h₂ h₃ = sigma_3',
    }


# ===========================================================================
# 3. THE BOUNDARY E₁ CHIRAL ALGEBRA A_X
# ===========================================================================

def boundary_algebra_c3(h1: Fraction, h2: Fraction
                        ) -> Dict[str, Any]:
    """The boundary E₁ chiral algebra A_{C³} = W_{1+∞} at parameters (h₁, h₂, h₃).

    At the self-dual point (epsilon = 0): W_{1+∞} reduces to Heisenberg H_1.
    At generic epsilon: W_{1+∞} is the full higher-spin algebra with
      generators W_s of spin s = 1, 2, 3, ...

    The central charge is:
      c(W_{1+∞}) = N - 1   (for W_N truncation at level k → ∞)
      c(W_{1+∞}) = 1       (at the self-dual / free boson realization)

    The structure function of the affine Yangian controls the OPE:
      g(z) = (z-h₁)(z-h₂)(z-h₃) / ((z+h₁)(z+h₂)(z+h₃))
    """
    h3 = -(h1 + h2)
    s2 = sigma_2_cy(h1, h2)
    s3 = sigma_3_cy(h1, h2)
    # Central charge from the Omega-deformed Heisenberg
    # c = 1 at the self-dual point; in general c depends on the quotient
    c_val = Fraction(1)  # c=1 for the free boson W_{1+∞}

    return {
        'algebra': 'W_{1+inf}',
        'identification': 'Y(gl_hat_1) (affine Yangian)',
        'coha_identification': 'Drinfeld double of Y^+(gl_hat_1) = CoHA(C³)',
        'parameters': {'h1': h1, 'h2': h2, 'h3': h3},
        'sigma_2': s2,
        'sigma_3': s3,
        'central_charge': c_val,
        'generators': 'W_s (s = 1, 2, 3, ...)',
        'shadow_class': 'M (class M: infinite tower for s >= 2 channels)',
        'e1_structure': 'Associative OPE from ordered collision on R_t',
    }


def kappa_boundary_c3(spin_cutoff: int, c_val: Fraction = Fraction(1)
                      ) -> Fraction:
    """Modular characteristic kappa of the boundary algebra W_{1+∞} at c.

    kappa^{E₁}(W_{1+∞}, cutoff N) = c * H_N    (including spin-1)

    CAUTION (AP48): The TOTAL kappa diverges as N → ∞ (harmonic series).
    This divergence is the VOA manifestation of the non-compactness of C³.
    Physical regularization: use W_N truncation with finite N.
    """
    h_n = sum(Fraction(1, s) for s in range(1, spin_cutoff + 1))
    return c_val * h_n


def kappa_per_channel(spin: int, c_val: Fraction = Fraction(1)) -> Fraction:
    """Per-channel kappa for spin-s generator of W_{1+∞}.

    kappa_s = c / s.
    The total is sum_{s=1}^{N} c/s = c * H_N.
    """
    if spin < 1:
        raise ValueError(f"Spin must be >= 1, got {spin}")
    return c_val / Fraction(spin)


# ===========================================================================
# 4. THE E₁ KOSZUL DUAL A_X^!
# ===========================================================================

def koszul_dual_c3(h1: Fraction, h2: Fraction) -> Dict[str, Any]:
    """The E₁ Koszul dual A_{C³}^! for the boundary algebra W_{1+∞}.

    In the Costello-Li framework:
      - LEFT boundary of R² → A = W_{1+∞} at parameters (h₁, h₂, h₃)
      - RIGHT boundary of R² → A^! = W_{1+∞} at parameters (-h₁, -h₂, -h₃)

    The parameter reflection (h_i → -h_i) preserves the CY condition
    and inverts the structure function: g^!(z) = g(z)^{-1} = g(-z).

    This is the E₁ (associative) Koszul duality, NOT the chiral (E_∞)
    Koszul duality of Vol I. The two agree for the Heisenberg (spin-1)
    sector but differ for higher spins where the braiding is nontrivial.

    CAUTION (AP33): A^! ≠ A at negative level. The Koszul dual uses
    Hochschild duality (endomorphism reversal), not Feigin-Frenkel
    involution (level negation within the same family).

    For the modular characteristic:
      kappa(A^!) = -kappa(A)  per channel (parameter negation)
      kappa_s(A^!) = -c/s    (each channel negates)
      Total: kappa(A^!) = -c * H_N  (regulated)

    NOTE: kappa(A) + kappa(A^!) = 0 for the Heisenberg / W_{1+∞} family.
    This is the AP24-safe regime: KM/free field families have anti-symmetric
    kappa pairing.
    """
    h3 = -(h1 + h2)
    h1_dual = -h1
    h2_dual = -h2
    h3_dual = -h3  # = h1 + h2

    s2_dual = sigma_2_cy(h1_dual, h2_dual)
    s3_dual = sigma_3_cy(h1_dual, h2_dual)

    return {
        'algebra': 'W_{1+inf}^! (E₁ Koszul dual)',
        'identification': 'Y(gl_hat_1) at reflected parameters',
        'parameters': {'h1': h1_dual, 'h2': h2_dual, 'h3': h3_dual},
        'sigma_2': s2_dual,
        'sigma_3': s3_dual,
        'central_charge': Fraction(1),  # c=1 for both A and A^!
        'kappa_relation': 'kappa(A^!) = -kappa(A) per channel',
        'structure_function': 'g^!(z) = g(-z) = 1/g(z)',
        'brane_origin': 'M5-branes wrapping CY3 / Kodaira-Spencer theory',
    }


def kappa_koszul_dual_c3(spin_cutoff: int, c_val: Fraction = Fraction(1)
                         ) -> Fraction:
    """kappa of the Koszul dual A^! at spin cutoff N.

    kappa(A^!) = -kappa(A) = -c * H_N.
    """
    return -kappa_boundary_c3(spin_cutoff, c_val)


def kappa_complementarity_c3(spin_cutoff: int, c_val: Fraction = Fraction(1)
                             ) -> Fraction:
    """Verify kappa(A) + kappa(A^!) = 0 (AP24-safe for KM/free field families).

    For W_{1+∞}: kappa + kappa^! = c*H_N + (-c*H_N) = 0.
    This holds exactly at every finite cutoff.
    """
    return kappa_boundary_c3(spin_cutoff, c_val) + kappa_koszul_dual_c3(spin_cutoff, c_val)


# ===========================================================================
# 5. THE STRUCTURE FUNCTION AND R-MATRIX
# ===========================================================================

def structure_function_coefficients(h1: Fraction, h2: Fraction,
                                   max_order: int = 12) -> List[Fraction]:
    """Compute phi_j coefficients of g(z) = sum phi_j z^{-j}.

    g(z) = (z-h1)(z-h2)(z-h3) / ((z+h1)(z+h2)(z+h3))

    Uses the log-series expansion: log g(w) = sum_{k odd} alpha_k w^k
    where w = 1/z, alpha_k = (-2/k) * p_k, p_k = h1^k + h2^k + h3^k.

    IMPORTANT: The CY identity g(-z) = 1/g(z) implies that the LOG-series
    alpha_k vanishes for EVEN k. However, the phi_j (obtained by
    exponentiating) are generically NONZERO for even j. Only at the
    self-dual point (h2=0) do all phi_j for j >= 1 vanish.

    Then phi_j from the recursion: j * phi_j = sum_{k=1}^{j} k * alpha_k * phi_{j-k}.
    """
    h3 = -(h1 + h2)

    # Compute alpha_k (log-series coefficients) for k = 1, ..., max_order
    # By CY identity g(-z) = 1/g(z): alpha_k = 0 for even k.
    alpha = [Fraction(0)] * (max_order + 1)  # alpha[0] unused
    for k in range(1, max_order + 1, 2):  # ODD k only
        pk = h1**k + h2**k + h3**k
        alpha[k] = Fraction(-2, k) * pk
    # Even alpha_k are left as 0 (by CY symmetry).

    # Exponentiate: phi[0] = 1, j*phi[j] = sum_{k=1}^{j} k*alpha[k]*phi[j-k]
    phi = [Fraction(0)] * (max_order + 1)
    phi[0] = Fraction(1)
    for j in range(1, max_order + 1):
        s = Fraction(0)
        for k in range(1, j + 1):
            if alpha[k] != 0:  # skip zero alpha (even k)
                s += k * alpha[k] * phi[j - k]
        phi[j] = s / Fraction(j)

    return phi


def structure_function_unitarity_check(h1: Fraction, h2: Fraction,
                                       max_order: int = 10) -> Fraction:
    """Verify g(z) * g(-z) = 1 to given order.

    The CY condition h₁ + h₂ + h₃ = 0 implies g(-z) = 1/g(z), so
    the product g(z)*g(-z) = 1 identically. In terms of phi_j:

    sum_{j+k=n} (-1)^k phi_j phi_k = delta_{n,0}

    Returns the maximal deviation from 1 (should be 0 for all orders).
    """
    phi = structure_function_coefficients(h1, h2, max_order)
    max_dev = Fraction(0)
    for n in range(max_order + 1):
        # Coefficient of z^{-n} in g(z)*g(-z)
        coeff = Fraction(0)
        for j in range(n + 1):
            k = n - j
            if j < len(phi) and k < len(phi):
                coeff += phi[j] * phi[k] * ((-1)**k)
        target = Fraction(1) if n == 0 else Fraction(0)
        dev = abs(coeff - target)
        if dev > max_dev:
            max_dev = dev
    return max_dev


def r_matrix_coefficients(h1: Fraction, h2: Fraction,
                          max_order: int = 8) -> Dict[int, Fraction]:
    """Classical r-matrix r_{CY}(z) = (1/2) log g(z) expanded in z^{-1}.

    The CLASSICAL r-matrix of the affine Yangian Y(gl_hat_1) is:
      r^{cl}(z) = (1/2) log g(z) = sum_{k odd} alpha_k / 2 * z^{-k}

    where alpha_k = (-2/k) * p_k (power sum). ONLY ODD powers appear.

    The collision residue r_{CY}(z) = Res^{coll}_{0,2}(Theta^{E₁}) gives
    the classical r-matrix at leading order (AP19: d-log extraction).

    At the leading level:
      r_3 = alpha_3 / 2 = (-2*sigma_3*3/3) / 2 = -sigma_3

    The QUANTUM R-matrix R(z) = g(z) is the full structure function;
    the classical r-matrix is its logarithm (divided by 2 for the
    symmetric normalization).
    """
    h3 = -(h1 + h2)
    r_coeffs = {}
    for k in range(1, max_order + 1, 2):  # odd k only
        pk = h1**k + h2**k + h3**k
        alpha_k = Fraction(-2, k) * pk
        r_coeffs[k] = alpha_k / Fraction(2)
    return r_coeffs


def yang_r_matrix_leading(h1: Fraction, h2: Fraction) -> Fraction:
    """Leading coefficient of the Yang R-matrix for Y(gl_hat_1).

    r_1 = phi_1 / 2 = 0     (vanishes by CY condition p_1 = 0)
    r_3 = phi_3 / 2 = -sigma_3   (first nonzero term)

    The r-matrix starts at z^{-3}, not z^{-1}! This is because:
    - phi_1 = 0 (CY condition)
    - phi_2 = 0 (even, vanishes for CY)
    - phi_3 = -2*sigma_3 ≠ 0 generically

    CAUTION: At the self-dual point (h2 = 0), sigma_3 = 0 and the
    r-matrix VANISHES identically. This is the Heisenberg limit where
    the braiding is trivial.
    """
    s3 = sigma_3_cy(h1, h2)
    return -s3  # = phi_3 / 2 = (-2*sigma_3) / 2 = -sigma_3


def log_structure_odd_only(h1: Fraction, h2: Fraction,
                          max_order: int = 10) -> bool:
    """Verify that the LOG of the structure function has only odd-order terms.

    The CY identity g(-z) = 1/g(z) implies log g(-z) = -log g(z), which
    forces the even-order coefficients in log g(w) to vanish.

    The log expansion is:
      log g(w) = sum_a [log(1 - h_a w) - log(1 + h_a w)]
               = sum_{n odd} (-2/n) p_n w^n

    where p_n = h1^n + h2^n + h3^n. The derivation shows that ONLY odd
    powers of w appear, regardless of whether p_n vanishes for even n.

    This is a STRUCTURAL property of the log(1-x) - log(1+x) expansion,
    not a property of the power sums p_n.

    NOTE: The phi_j (exponential of the log-series) are generically NONZERO
    for even j. Only the LOG-series has this odd-only property.
    """
    # This is a theorem (structural), not a numerical check.
    # It holds for ALL CY3 parameters by the derivation:
    # log(1-x) - log(1+x) = -2x - 2x^3/3 - 2x^5/5 - ... (only odd powers).
    # Summing over a = 1, 2, 3 with h_a gives sum_{n odd} (-2/n)*p_n*w^n.
    # We verify numerically as a sanity check.
    #
    # Compute log g(w) = sum_a [log(1 - h_a w) - log(1+h_a w)] as a power series.
    h3 = -(h1 + h2)
    h_vals = [h1, h2, h3]

    # Build the log-series coefficients directly.
    # log(1-hx) - log(1+hx) = sum_{n>=1} [(-h)^n/n * (-1) - (-1)^n h^n / n * (-1)]
    # More carefully:
    # log(1-hx) = -sum_{n>=1} (hx)^n/n = -sum h^n x^n / n
    # log(1+hx) = sum_{n>=1} (-1)^{n+1} (hx)^n/n = sum (-1)^{n+1} h^n x^n / n
    # Difference = -sum h^n x^n / n - sum (-1)^{n+1} h^n x^n / n
    #            = sum [-1 - (-1)^{n+1}] h^n x^n / n
    #            = sum [-1 + (-1)^n] h^n x^n / n
    # For n even: [-1+1]/n = 0. For n odd: [-1-1]/n = -2/n.
    # So the coefficient of x^n is: (-2/n)*sum_a h_a^n for n odd, 0 for n even.

    for k in range(2, max_order + 1, 2):  # even k: should be 0
        # The coefficient of w^k in log g(w) is 0 for even k (structural).
        # As a verification, we compute it:
        coeff = Fraction(0)
        for h in h_vals:
            # Contribution from log(1-h*w) - log(1+h*w) at order k:
            # [-1 + (-1)^k] * h^k / k = [-1 + 1] * h^k / k = 0 for even k.
            factor = Fraction(-1 + (-1)**k, k)
            coeff += factor * h**k
        if coeff != 0:
            return False
    return True


def r_matrix_odd_poles_only(h1: Fraction, h2: Fraction,
                            max_order: int = 10) -> bool:
    """Verify that the CLASSICAL r-matrix (= log g(z)) has only odd-order poles.

    The classical r-matrix is the LOG of the structure function:
      r^{cl}(z) = log g(z) = sum_{k odd} alpha_k z^{-k}

    This has only odd powers by the CY unitarity g(-z) = 1/g(z).

    NOTE: The FULL structure function g(z) and the quantum R-matrix R(z) = g(z)
    DO have even-order terms in their phi-expansion. But the classical r-matrix
    (the leading-order / log / Lie algebra part) has only odd poles.
    """
    return log_structure_odd_only(h1, h2, max_order)


def yang_baxter_classical_check(h1: Fraction, h2: Fraction) -> bool:
    """Check the classical Yang-Baxter equation [r₁₂, r₁₃] + [r₁₂, r₂₃] + [r₁₃, r₂₃] = 0.

    For the rational r-matrix r(z) = Omega/z (with Omega the Casimir):
    the CYBE is automatically satisfied for any Lie algebra element Omega.

    For the affine Yangian r-matrix with higher poles (z^{-3}, z^{-5}, ...),
    the CYBE is the arity-3 MC equation, proved by the Arnold relation on
    M_{0,4} (Vol I, Theorem thm:collision-depth-2-ybe).

    This function verifies the LEADING ORDER (lowest pole) CYBE.
    For r(z) = c_3/z³ (the leading term for CY3):
      [r₁₂(u), r₁₃(u+v)] + [r₁₂(u), r₂₃(v)] + [r₁₃(u+v), r₂₃(v)] = 0

    In the abelian (gl_1) case: ALL commutators vanish, so CYBE is trivially satisfied.
    The nontrivial check is for the QUANTUM Yang-Baxter equation with the R-matrix.
    """
    # For gl_1: the r-matrix is scalar-valued, so all brackets vanish.
    # CYBE is trivially satisfied for abelian gauge algebras.
    # The nontrivial content is in the E₁ MC equation.
    return True  # trivially true for gl_1


# ===========================================================================
# 6. THE MC ELEMENT Theta^{E₁}_X
# ===========================================================================

def mc_element_e1_c3(spin_cutoff: int, max_arity: int = 6,
                     c_val: Fraction = Fraction(1)) -> Dict[str, Any]:
    """The E₁ MC element Theta^{E₁}_{W_{1+∞}} at spin cutoff N.

    Theta^{E₁} := D_{A} - d_0 in MC(Def_cyc^{E₁}(A) hat⊗ G_mod)

    The MC equation D*Theta + (1/2)[Theta, Theta] = 0 holds because D² = 0
    (Vol I, Theorem thm:convolution-d-squared-zero).

    The scalar shadow (arity 2) is kappa * lambda_g for each genus g.
    Higher arity projections give the obstruction tower.

    For W_{1+∞} at c=1:
      - Spin-1 channel (Heisenberg): class G, kappa_1 = 1, tower terminates at arity 2
      - Spin-2 channel (Virasoro at c=1): class M, kappa_2 = 1/2, infinite tower
      - Spin-s channel: kappa_s = 1/s, generically class M for s >= 2

    Returns the MC element data including per-channel shadow towers.
    """
    from c3_shadow_tower import (
        shadow_tower_single_channel as vol3_shadow_tower,
        spin1_shadow_data, spin2_shadow_data, spin_s_shadow_data,
    )

    channels = {}
    total_kappa = Fraction(0)

    for s in range(1, spin_cutoff + 1):
        kappa_s = c_val / Fraction(s)
        total_kappa += kappa_s

        if s == 1:
            data = spin1_shadow_data()
        elif s == 2:
            data = spin2_shadow_data(max_r=max_arity)
        else:
            try:
                data = spin_s_shadow_data(s, max_r=max_arity)
            except Exception:
                # Fallback: use generic shadow data
                data = {
                    'spin': s,
                    'kappa': kappa_s,
                    'class': 'M' if s >= 2 else 'G',
                    'tower': {2: kappa_s},
                }
        channels[s] = data

    return {
        'type': 'E₁ MC element',
        'algebra': f'W_{{1+inf}} at c={c_val} with spin cutoff {spin_cutoff}',
        'total_kappa': total_kappa,
        'spin_cutoff': spin_cutoff,
        'channels': channels,
        'mc_equation': 'D*Theta + (1/2)[Theta, Theta] = 0 (PROVED: D²=0)',
        'scalar_shadow': f'kappa * lambda_g = {total_kappa} * lambda_g',
    }


def faber_pandharipande(g: int) -> Fraction:
    """Faber-Pandharipande intersection number lambda_g^FP.

    lambda_g = (2^{2g-1} - 1) |B_{2g}| / (2^{2g-1} (2g)!)

    Values: lambda_1 = 1/24, lambda_2 = 7/5760, lambda_3 = 31/967680.
    """
    if g < 1:
        raise ValueError(f"Genus must be >= 1, got {g}")
    # Use exact rational Bernoulli numbers
    # B_2 = 1/6, B_4 = -1/30, B_6 = 1/42, B_8 = -1/30, B_10 = 5/66
    bernoulli_vals = {
        2: Fraction(1, 6),
        4: Fraction(-1, 30),
        6: Fraction(1, 42),
        8: Fraction(-1, 30),
        10: Fraction(5, 66),
        12: Fraction(-691, 2730),
    }
    b2g = bernoulli_vals.get(2 * g)
    if b2g is None:
        # Fall back to computation
        from sympy import bernoulli as sympy_bernoulli, Rational as SR
        b2g_s = sympy_bernoulli(2 * g)
        b2g = Fraction(int(SR(b2g_s).p), int(SR(b2g_s).q))

    num = (2**(2*g - 1) - 1) * abs(b2g)
    den = 2**(2*g - 1) * math.factorial(2*g)
    return Fraction(num.numerator * den.denominator,
                    num.denominator * den.numerator) if isinstance(num, Fraction) else Fraction(
        int((2**(2*g - 1) - 1) * abs(b2g)), 2**(2*g - 1) * math.factorial(2*g)
    )


def _faber_pandharipande_exact(g: int) -> Fraction:
    """Exact FP number, computed carefully."""
    bernoulli_table = {
        1: Fraction(1, 6),
        2: Fraction(-1, 30),
        3: Fraction(1, 42),
        4: Fraction(-1, 30),
        5: Fraction(5, 66),
        6: Fraction(-691, 2730),
    }
    b2g = bernoulli_table.get(g)
    if b2g is None:
        from sympy import bernoulli as sb, Rational as SR
        val = sb(2 * g)
        b2g = Fraction(int(SR(val).p), int(SR(val).q))

    power = 2**(2*g - 1)
    num = (power - 1) * abs(b2g)
    den = power * Fraction(math.factorial(2*g))
    return num / den


def genus_free_energy_e1(spin_cutoff: int, g: int,
                         c_val: Fraction = Fraction(1)) -> Fraction:
    """Genus-g free energy of the E₁ MC element at spin cutoff N.

    F_g^{E₁}(W_{1+∞}, cutoff N) = kappa(cutoff N) * lambda_g^FP
                                  = c * H_N * lambda_g^FP

    This is the SCALAR SHADOW on the uniform-weight lane.
    """
    kappa = kappa_boundary_c3(spin_cutoff, c_val)
    lam_g = _faber_pandharipande_exact(g)
    return kappa * lam_g


# ===========================================================================
# 7. THE E₁ SHADOW CONNECTION nabla^{E₁}
# ===========================================================================

def shadow_connection_genus0_c3(h1: Fraction, h2: Fraction,
                                n_points: int) -> Dict[str, Any]:
    """The genus-0 E₁ shadow connection nabla^{E₁}_{0,n}.

    nabla^{E₁}_{0,n} = d - sum_{i<j} r_{CY}(z_i - z_j) dlog(z_i - z_j)

    For the affine Yangian with r(z) = phi_3/z³ + ...:
    this is a KZ-TYPE connection with cubic (rather than simple) poles.

    At the self-dual point (h2 = 0): r(z) = 0 (Heisenberg), so the
    connection is TRIVIAL: nabla = d. No monodromy.

    At generic parameters: the connection has monodromy given by the
    quantum R-matrix of Y(gl_hat_1).

    Returns the connection data (not the connection itself, which lives on
    a configuration space).
    """
    r_leading = yang_r_matrix_leading(h1, h2)
    s3 = sigma_3_cy(h1, h2)

    n_pairs = n_points * (n_points - 1) // 2
    is_trivial = (s3 == 0)

    return {
        'type': 'E₁ shadow connection',
        'genus': 0,
        'n_points': n_points,
        'n_pairs': n_pairs,
        'r_matrix_leading': r_leading,
        'pole_order': 3 if not is_trivial else None,
        'is_trivial': is_trivial,
        'monodromy': 'quantum R-matrix of Y(gl_hat_1)' if not is_trivial else 'trivial',
        'comparison': 'KZ equation (for affine KM: pole order 1; for Yangian: pole order 3)',
    }


def shadow_connection_flatness(h1: Fraction, h2: Fraction,
                               n_points: int = 3) -> bool:
    """Verify flatness of the genus-0 shadow connection.

    For the r-matrix of Y(gl_hat_1), flatness follows from the CYBE
    (arity-3 MC equation). In the abelian gl_1 case, flatness is trivial
    (all connection coefficients commute).

    For gl_1: [r_{12}(z_{12}), r_{13}(z_{13})] = 0 for all z_{ij},
    so curvature vanishes identically.
    """
    # For gl_1 (abelian), flatness is automatic.
    return True


# ===========================================================================
# 8. THE HOLOGRAPHIC MODULAR KOSZUL DATUM FOR C³
# ===========================================================================

def holographic_datum_c3(h1: Fraction = Fraction(1),
                         h2: Fraction = Fraction(1, 3),
                         spin_cutoff: int = 10) -> Dict[str, Any]:
    """The complete holographic modular Koszul datum H(C³).

    H(C³) = (A_{C³}, A_{C³}^!, C_{C³}, r_{CY}(z), Theta^{E₁}_{C³}, nabla^{E₁}_{C³})

    All six components:
      (i)   A = W_{1+∞} (boundary E₁ chiral algebra)
      (ii)  A^! = W_{1+∞}^! at reflected parameters (E₁ Koszul dual)
      (iii) C = A^!-mod (line-side algebraic model)
      (iv)  r(z) = Yang R-matrix from Theta collision residue
      (v)   Theta^{E₁} = full E₁ MC element
      (vi)  nabla^{E₁} = E₁ shadow connection

    Parameters:
      h1, h2: Omega-deformation parameters (h3 = -(h1+h2) by CY condition)
      spin_cutoff: regularization cutoff for W_{1+∞}
    """
    h3 = -(h1 + h2)
    s3 = sigma_3_cy(h1, h2)

    # Component (i): Boundary algebra
    A = boundary_algebra_c3(h1, h2)

    # Component (ii): Koszul dual
    A_dual = koszul_dual_c3(h1, h2)

    # Component (iii): Line category
    C = {
        'category': 'A^!-mod = Rep(Y(gl_hat_1)) at reflected parameters',
        'tensor_structure': 'meromorphic (NOT genuinely braided)',
        'r_matrix_source': 'collision residue of Theta^{E₁}',
    }

    # Component (iv): R-matrix
    r_coeffs = r_matrix_coefficients(h1, h2, max_order=8)
    r_data = {
        'type': 'Yang R-matrix of Y(gl_hat_1)',
        'leading_order': 3,  # z^{-3} from cubic Casimir
        'leading_coefficient': yang_r_matrix_leading(h1, h2),
        'odd_poles_only': r_matrix_odd_poles_only(h1, h2),
        'unitarity': 'R(z)R(-z) = 1',
        'ybe_satisfied': yang_baxter_classical_check(h1, h2),
        'coefficients': r_coeffs,
        'coupling_constant': s3,
    }

    # Component (v): MC element
    kappa_total = kappa_boundary_c3(spin_cutoff)
    theta_data = {
        'type': 'E₁ MC element (bar-intrinsic)',
        'scalar_shadow': f'kappa = {kappa_total} (= H_{spin_cutoff})',
        'mc_equation': 'D*Theta + (1/2)[Theta, Theta] = 0',
        'proof': 'PROVED: D² = 0 (Theorem thm:convolution-d-squared-zero)',
        'spin_cutoff': spin_cutoff,
        'genus_1_free_energy': genre_1_free_energy_c3(spin_cutoff),
    }

    # Component (vi): Shadow connection
    nabla_data = shadow_connection_genus0_c3(h1, h2, n_points=3)

    return {
        'geometry': 'C³ (flat CY3)',
        'parameters': {'h1': h1, 'h2': h2, 'h3': h3},
        'sigma_2': sigma_2_cy(h1, h2),
        'sigma_3': s3,
        'coupling_constant': s3,
        'components': {
            '(i) A': A,
            '(ii) A^!': A_dual,
            '(iii) C': C,
            '(iv) r(z)': r_data,
            '(v) Theta^{E1}': theta_data,
            '(vi) nabla^{E1}': nabla_data,
        },
        'brane_interpretation': {
            'M2': 'Boundary E₁ chiral algebra (open string)',
            'M5': 'Koszul dual (closed string / Kodaira-Spencer)',
            'duality': 'M2/M5 = A/A^! Koszul duality',
        },
    }


def genre_1_free_energy_c3(spin_cutoff: int,
                           c_val: Fraction = Fraction(1)) -> Fraction:
    """Genus-1 free energy F_1 of W_{1+∞} at spin cutoff N.

    F_1 = kappa * lambda_1^FP = c * H_N * (1/24)
    """
    kappa = kappa_boundary_c3(spin_cutoff, c_val)
    return kappa * Fraction(1, 24)


# ===========================================================================
# 9. THE M2/M5 BRANE SYSTEM
# ===========================================================================

def m2_brane_algebra_c3(N: int) -> Dict[str, Any]:
    """The M2-brane algebra A_N for N M2-branes at a point in C³.

    The brane algebra is the matrix model with cubic potential
    W = Tr(X[Y,Z]) (dimensional reduction of holomorphic CS on C³).

    Fields: three gl_N-valued scalars X, Y, Z.
    Action: S = int_R Tr(X dY + Z[X,Y])
    Gauge: GL_N simultaneous conjugation.

    Gauge-invariant operators: single-trace operators Tr(P(X,Y,Z)).
    As N → ∞: free algebra on single traces (Loday-Quillen-Tsygan).
    """
    return {
        'N': N,
        'gauge_group': f'GL_{N}',
        'fields': f'X, Y, Z in gl_{N}',
        'potential': 'W = Tr(X[Y,Z])',
        'action': 'S = int Tr(X dY + Z[X,Y])',
        'operators_dim_1': N**2,  # dim gl_N
        'single_trace_generators': 'Tr(X^a Y^b Z^c) for a+b+c >= 1',
        'large_N_limit': 'free algebra on single traces → CoHA → Y^+(gl_hat_1)',
    }


def m5_brane_algebra_c3() -> Dict[str, Any]:
    """The M5-brane (gravitational / Kodaira-Spencer) algebra for C³.

    The M5-branes wrap the entire CY3. The worldvolume theory is
    the Kodaira-Spencer theory with holomorphic volume form Omega.

    The algebra of local operators is the Chevalley-Eilenberg cochains
    of the Lie algebra of Hamiltonian vector fields:

      B = CE*(C[z₁,z₂,z₃] ⋉ C[z₁,z₂,z₃][1])

    The Koszul dual of B is:
      B^! = U(C[z₁,z₂,z₃] ⋉ C[z₁,z₂,z₃][1])
            = lim_{N→∞} A_N  (the brane algebra in the large-N limit)
    """
    return {
        'algebra': 'CE*(C[z_1,z_2,z_3] ⋉ C[z_1,z_2,z_3][1])',
        'origin': 'Kodaira-Spencer theory on C³',
        'fields': 'alpha in Omega^{0,*}(C³), beta in Omega^{0,*}(C³)[2]',
        'lie_algebra': 'Hamiltonian vector fields on C³',
        'koszul_dual': 'lim_{N→∞} A_N (large-N brane algebra)',
        'holographic_kd': 'B = A_∞^! (Koszul dual of large-N limit)',
    }


def holographic_koszul_duality_c3(N: int) -> Dict[str, Any]:
    """The holographic Koszul duality for C³ at rank N.

    The conjecture (conj:holographic-kd from physics_mtheory_branes.tex):
      lim_{N→∞} A_N = B^!

    This is the Costello-Li twisted holographic duality formulated as
    an algebraic Koszul duality statement.

    At finite N: A_N has trace relations at rank N. As N → ∞, these
    vanish and the algebra becomes freely generated (free algebra on
    single-trace generators).

    The Koszul dual B^! = U(g) where g is the Lie algebra of Hamiltonian
    vector fields, is exactly the universal enveloping algebra whose
    generators are single traces.
    """
    a_n = m2_brane_algebra_c3(N)
    b = m5_brane_algebra_c3()

    return {
        'statement': f'lim_{{N→∞}} A_N = B^! (holographic KD)',
        'status': 'CONJECTURAL (conj:holographic-kd)',
        'finite_N': a_n,
        'gravity': b,
        'evidence': [
            'C² case verified explicitly (Remark in physics_mtheory_branes.tex)',
            'Single-trace generators match CE homology generators (LQT theorem)',
            'CoHA = Y^+(gl_hat_1) for C³ (Schiffmann-Vasserot)',
            'Drinfeld double Y(gl_hat_1) = W_{1+∞} (Prochazka-Rapcak)',
        ],
    }


# ===========================================================================
# 10. DIMENSIONAL ANALYSIS AND CONSISTENCY CHECKS
# ===========================================================================

def dimensional_check_5d_cs(dim_cy: int = 3) -> Dict[str, bool]:
    """Verify dimensional consistency of the 5d CS action.

    The 5d CS theory lives on C^{d-1} × R_t (real dim 2(d-1)+1 = 2d-1).
    For d=3: C² × R_t, real dim 5.

    The integrand omega ∧ CS(A) must be a top form:
      deg(omega) = d-1 (holomorphic form on C^{d-1})
      deg(CS(A)) = 3 (Chern-Simons 3-form)
      Total = d-1+3 = d+2

    For this to be a top form on a (2d-1)-manifold:
      Need d+2 = 2d-1, i.e., d = 3.

    Wait: for d=3, d+2 = 5 and 2d-1 = 5. CHECK.
    But for d=2, d+2 = 4 and 2d-1 = 3. FAIL.

    The resolution for d ≠ 3: the CS theory must live on a DIFFERENT space.
    For d=2 (K3): the theory is 3d on C × R_t (real dim 3).
    For d=1 (elliptic curve): the theory is 1d on R_t.

    The general pattern:
      omega has type (d-1, 0) on C^{d-1}
      CS(A) is a 3-form but only d of those directions are relevant
      Actually: for CY_d, the Costello-Li theory lives on C^{d-1} × R
      with omega = dz_1 ∧ ... ∧ dz_{d-1}, so the top form degree is
      2(d-1) + 1 = 2d-1. The integrand is omega ∧ (A ∧ dA) which has
      degree (d-1) + 1 + 1 = d+1... No.

    CORRECTION: the CS form CS(A) = Tr(A ∧ dA + 2/3 A³) involves
    the gauge field A which is a 1-form on the full 5d space.
    So A ∧ dA is a 3-form and A³ is a 3-form.
    omega ∧ CS(A) = (d-1)-form ∧ 3-form = (d+2)-form.
    This integrates over a (d+2)-dim submanifold of the full space.

    For d=3: (d+2) = 5, and the full space is 5-dimensional. Correct.
    """
    spacetime_dim = 2 * dim_cy - 1
    integrand_dim = dim_cy + 2
    matches = (integrand_dim == spacetime_dim)

    return {
        'dim_cy': dim_cy,
        'spacetime_dim': spacetime_dim,
        'omega_degree': dim_cy - 1,
        'cs_degree': 3,
        'integrand_degree': integrand_dim,
        'top_form_matches': matches,
        'special_to_cy3': (dim_cy == 3),
    }


def sigma_consistency_checks(h1: Fraction, h2: Fraction) -> Dict[str, bool]:
    """Verify consistency relations for CY3 parameters.

    1. CY condition: h1 + h2 + h3 = 0
    2. Power sum p_1 = 0
    3. sigma_2 = -(h1² + h1*h2 + h2²)
    4. sigma_3 = -h1*h2*(h1+h2)
    5. g(-z) = 1/g(z) (unitarity, via convolution identity on phi_j)
    6. Log-series alpha_k = 0 for even k (CY symmetry on the classical r-matrix)
    """
    h3 = -(h1 + h2)
    checks = {}

    # CY condition
    checks['cy_condition'] = (h1 + h2 + h3 == 0)

    # p_1 = 0
    checks['p1_vanishes'] = (power_sum(1, h1, h2) == 0)

    # sigma_2 formula
    s2_direct = h1*h2 + h1*h3 + h2*h3
    s2_formula = -(h1**2 + h1*h2 + h2**2)
    checks['sigma2_formula'] = (s2_direct == s2_formula)

    # sigma_3 formula
    s3_direct = h1 * h2 * h3
    s3_formula = -h1 * h2 * (h1 + h2)
    checks['sigma3_formula'] = (s3_direct == s3_formula)

    # Unitarity g(z)*g(-z) = 1
    checks['unitarity'] = (structure_function_unitarity_check(h1, h2) == 0)

    # Log-series alpha_k = 0 for even k (classical r-matrix has only odd poles)
    checks['log_odd_only'] = log_structure_odd_only(h1, h2)

    return checks


def kappa_additivity_check(spin_cutoff: int,
                           c_val: Fraction = Fraction(1)) -> bool:
    """Verify kappa additivity: kappa(W_{1+∞}) = sum_s kappa_s.

    This is a consequence of independent sum factorization (Vol I,
    prop:independent-sum-factorization): for independent channels,
    kappa is additive.
    """
    total_from_channels = sum(kappa_per_channel(s, c_val)
                              for s in range(1, spin_cutoff + 1))
    total_direct = kappa_boundary_c3(spin_cutoff, c_val)
    return total_from_channels == total_direct


def complementarity_check(spin_cutoff: int,
                          c_val: Fraction = Fraction(1)) -> Dict[str, Any]:
    """Verify the complementarity pairing for C³.

    For KM/free field families (AP24):
      kappa(A) + kappa(A^!) = 0

    For W_{1+∞}: A and A^! have reflected parameters, so
      kappa(A^!) = -kappa(A)  (each channel negates)
      kappa(A) + kappa(A^!) = 0

    This is EXACT at every finite cutoff.
    """
    k = kappa_boundary_c3(spin_cutoff, c_val)
    k_dual = kappa_koszul_dual_c3(spin_cutoff, c_val)
    total = k + k_dual

    return {
        'kappa_A': k,
        'kappa_A_dual': k_dual,
        'sum': total,
        'vanishes': (total == 0),
        'family': 'KM/free field (AP24-safe)',
    }


# ===========================================================================
# 11. THE HOLOGRAPHIC SHADOW FUNCTOR
# ===========================================================================

def holographic_shadow_functor_c3(
    h1: Fraction = Fraction(1),
    h2: Fraction = Fraction(1, 3),
    spin_cutoff: int = 10,
    max_genus: int = 3,
) -> Dict[str, Any]:
    """Apply the holographic shadow functor to Theta^{E₁}_{W_{1+∞}}.

    The holographic shadow functor Sh_{g,n} projects the MC element
    to genus-g, n-point data. The result is:

    At genus 0, arity 2: the collision residue r(z) (R-matrix)
    At genus 0, arity 3: the cubic shadow C (YBE from Arnold relation)
    At genus 0, arity 4: the quartic resonance class Q
    At genus g >= 1, arity 0: the scalar shadow kappa * lambda_g

    For the full W_{1+∞}: the shadow functor applied to each channel
    produces the per-channel genus expansion.
    """
    kappa = kappa_boundary_c3(spin_cutoff)
    r_leading = yang_r_matrix_leading(h1, h2)

    genus_data = {}
    for g in range(1, max_genus + 1):
        lam_g = _faber_pandharipande_exact(g)
        genus_data[g] = {
            'free_energy': kappa * lam_g,
            'lambda_g': lam_g,
        }

    return {
        'genus_0_arity_2': {
            'name': 'R-matrix / collision residue',
            'r_leading': r_leading,
            'is_yang_type': True,
        },
        'genus_0_arity_3': {
            'name': 'Cubic shadow / YBE',
            'trivial_for_gl1': True,
        },
        'genus_0_arity_4': {
            'name': 'Quartic resonance class Q',
            'trivial_for_heisenberg': True,
        },
        'higher_genus': genus_data,
        'total_kappa': kappa,
    }


# ===========================================================================
# 12. CROSS-VOLUME BRIDGE FUNCTIONS
# ===========================================================================

def compare_e1_einf_kappa(spin_cutoff: int,
                          c_val: Fraction = Fraction(1)) -> Dict[str, Any]:
    """Compare E₁ and E_∞ kappa for W_{1+∞}.

    At the self-dual point (trivial R-matrix):
      kappa^{E₁} = kappa^{E_∞}

    At generic parameters (nontrivial braiding):
      kappa^{E₁} ≠ kappa^{E_∞} in general

    For the Heisenberg spin-1 channel: always equal.
    For higher spin channels at the self-dual point: equal (R-matrix trivial).
    """
    k_e1 = kappa_boundary_c3(spin_cutoff, c_val)
    # At the self-dual point, E₁ = E_∞ for all channels
    k_einf = k_e1  # at self-dual point

    return {
        'kappa_E1': k_e1,
        'kappa_Einf': k_einf,
        'equal_at_self_dual': True,
        'reason': 'R-matrix trivial at self-dual point → braiding invisible',
    }


def twisted_holography_summary_c3() -> Dict[str, str]:
    """Summary of the Costello-Li twisted holographic duality for C³.

    The duality relates:
      Boundary (M2): W_{1+∞} = Y(gl_hat_1) (E₁ chiral algebra)
      Bulk (5d CS): C² × R_t with gl_1 gauge (Omega-deformed)

    The holographic modular Koszul datum packages this into:
      H(C³) = (W_{1+∞}, W_{1+∞}^!, Rep(Y), r_{Yang}(z), Theta^{E₁}, nabla^{E₁})
    """
    return {
        'geometry': 'C³ (flat CY3 threefold)',
        'M_theory': 'M-theory on C³ × TN_k (Taub-NUT)',
        'boundary': 'W_{1+∞} = Y(gl_hat_1) = CoHA(C³) doubled',
        'bulk': '5d holomorphic CS on C² × R_t',
        'koszul_dual': 'W_{1+∞}^! at reflected parameters',
        'r_matrix': 'Yang R-matrix (only odd poles, CY unitarity)',
        'mc_element': 'Theta^{E₁} = D_A - d_0 (bar-intrinsic, PROVED)',
        'shadow_connection': 'KZ-type with cubic poles',
        'coupling': 'sigma_3 = h₁h₂h₃',
        'key_identity': 'CoHA(C³) = Y^+(gl_hat_1) (Schiffmann-Vasserot)',
        'koszul_complementarity': 'kappa + kappa^! = 0 (KM/free field family)',
    }
