r"""
yangian_bar_complex.py -- Bar complex of Y^+(gl_hat_1) at low arities.

Ground truth:
  Schiffmann-Vasserot (arXiv:1211.1287): CoHA(C^3) = Y^+(gl_hat_1)
  Kontsevich-Soibelman (arXiv:0811.2435): DT invariants from motivic Hall algebra
  Maulik-Nekrasov-Okounkov-Pandharipande (arXiv:math/0312059): DT/GW correspondence
  ~/chiral-bar-cobar/chapters/frame/bar_cobar_adjunction_curved.tex: bar complex
  ~/calabi-yau-quantum-groups/notes/theory_cy_to_chiral.tex: CY-to-chiral functor

MATHEMATICAL CONTENTS:

The positive half Y^+ = Y^+(gl_hat_1) of the affine Yangian of gl_1 is the
cohomological Hall algebra (CoHA) of C^3 (Schiffmann-Vasserot 2013). As a
graded algebra:
    Y^+ = bigoplus_{n >= 0} Y^+_n,   dim(Y^+_n) = p(n)
where p(n) counts plane partitions of n (OEIS A000219). The graded character
is the MacMahon function M(q) = prod_{n>=1} (1-q^n)^{-n}.

THE BAR COMPLEX B(Y^+):
    B^k(Y^+) = (Y^+)^{otimes k}  (desuspended, with bar differential)
    d_bar : B^k -> B^{k-1}  via multiplication mu : Y^+ otimes Y^+ -> Y^+.
The bar differential in arity k is:
    d_bar([a_1|...|a_k]) = sum_{i=1}^{k-1} (-1)^{eps_i} [a_1|...|mu(a_i,a_{i+1})|...|a_k]
where eps_i encodes the Koszul signs.

For a commutative graded algebra concentrated in degree 0, the bar complex is
the tensor coalgebra with the shuffle differential. Since Y^+ is concentrated
in cohomological degree 0 (the CoHA is in degree 0), the signs simplify:
    d_bar([a_1|...|a_k]) = sum_{i=1}^{k-1} (-1)^{i-1} [a_1|...|a_i * a_{i+1}|...|a_k]

KEY POINT: The bar complex computes Tor^{Y^+}(Q, Q) where Q is the trivial
module Y^+/Y^+_{>0}. In the commutative case, this is the cotangent complex /
Andre-Quillen homology. The generators of H^1(B(Y^+)) are the "indecomposables"
= algebra generators = BPS states.

For the CoHA of C^3:
  - Y^+ is generated by a single generator e_0 (adding a single box), but the
    FULL algebra is freely generated by plane-partition-indexed generators subject
    to the Yangian relations. It is NOT a free commutative algebra.
  - The CoHA multiplication is NOT commutative (it depends on the ordering of
    sheaves in the torus-fixed locus), but is associative.
  - The "commutative" shadow is the symmetric algebra Sym(V_BPS) where V_BPS
    is the BPS vector space (primitives under the coproduct).

DT INVARIANTS FROM BAR COHOMOLOGY:
The BPS invariants Omega(n) of C^3 are defined by the plethystic logarithm:
    sum_{n>=1} Omega(n) q^n = PLog(M(q)) = sum_{n>=1} (-1)^{n-1}/n * log(M(q^n))
                             = sum_{n>=1} n * q^n
    (That is: Omega(n) = n for all n >= 1.)

This follows from M(q) = prod_{n>=1} (1-q^n)^{-n}, so
    PLog(M(q)) = sum_{n>=1} n * q^n.

The bar cohomology should detect these: H^1(B(Y^+)) in degree n should have
dimension Omega(n) = n (these are the BPS generators / algebra generators).

MULTI-PATH VERIFICATION:
  Path 1: Direct bar differential computation at low arities
  Path 2: Comparison with plane partition counts p(n,k) at fixed arity k
  Path 3: Generating function comparison with MacMahon / plethystic logarithm
  Path 4: Euler characteristic chi(B(Y^+)) via alternating sum

CONVENTIONS:
  - q = formal variable (box-counting fugacity)
  - Bar arity k means k tensor factors (k=1 is the generators, k=2 is relations)
  - Cohomological grading: d_bar has degree +1 in bar degree (reduces arity by 1)
  - The augmentation ideal Y^+_{>0} has p(n)-delta_{n,0} dimensions in degree n
"""

from __future__ import annotations

from fractions import Fraction
from typing import Dict, List, Optional, Tuple

from compute.lib.c3_dt_partition import (
    macmahon_coefficients,
    macmahon_coefficients_product,
    plane_partition_counts,
)


# ---------------------------------------------------------------------------
# Plethystic logarithm / BPS invariants
# ---------------------------------------------------------------------------

def plethystic_log_coefficients(f_coeffs: List[Fraction], N: int) -> List[Fraction]:
    """Compute the plethystic logarithm PLog(f(q)) mod q^N.

    Given f(q) = 1 + sum_{n>=1} f_n q^n with f_0 = 1,
    PLog(f(q)) = sum_{n>=1} mu(n)/n * log(f(q^n))
               = sum_{n>=1} (1/n) * sum_{d|n} mu(n/d) * log_coeff_d

    Equivalently, the Mobius inversion of the "Adams operations":
    PLog(f) = sum_{k>=1} mu(k)/k * log(f(q^k))

    But more directly: if f(q) = prod_{n>=1} (1-q^n)^{-a_n}, then
    PLog(f) = sum_{n>=1} a_n q^n.

    For computational purposes, we use:
    f(q) = exp(sum_{n>=1} b_n q^n/n) implies PLog = Mobius inversion of b.

    Actually, the cleanest formula: if log(f(q)) = sum_{n>=1} c_n q^n,
    then PLog(f)(q) = sum_{n>=1} (sum_{d|n} mu(n/d) c_d) q^n.

    We use the direct recursive definition instead:
    f(q) = PExp(g(q)) where g = PLog(f), meaning
    f(q) = prod_{n>=1} (1-q^n)^{-g_n} = exp(sum_{n>=1} g_n * sum_{m>=1} q^{mn}/m)

    So log(f(q)) = sum_{n>=1} g_n * sum_{m>=1} q^{mn}/m.

    Extracting coefficient of q^k from log(f):
    [q^k] log(f) = sum_{d|k} g_d * (1/(k/d)) = sum_{d|k} g_d * d/k

    Therefore: k * [q^k] log(f) = sum_{d|k} d * g_d.
    Mobius inversion: n * g_n = sum_{d|n} mu(n/d) * d * [q^d] log(f).

    We compute log(f) first, then apply Mobius inversion.
    """
    # Step 1: compute log(f) = log(1 + (f-1))
    # log(1+x) = x - x^2/2 + x^3/3 - ...
    # where x = f - 1 (starts at q^1)
    x = [Fraction(0)] * N  # x = f - 1
    for i in range(1, min(N, len(f_coeffs))):
        x[i] = f_coeffs[i]

    log_f = [Fraction(0)] * N
    # log(1+x) via power series: coefficient of q^n in log(1+x)
    # Use the recursion: if f = exp(g), then g' = f'/f
    # i.e., n * g_n = n * f_n - sum_{k=1}^{n-1} k * g_k * f_{n-k}
    # (where f_0 = 1)
    for n in range(1, N):
        fn = f_coeffs[n] if n < len(f_coeffs) else Fraction(0)
        s = Fraction(0)
        for k in range(1, n):
            fnk = f_coeffs[n - k] if (n - k) < len(f_coeffs) else Fraction(0)
            s += Fraction(k) * log_f[k] * fnk
        log_f[n] = fn - s / Fraction(n)

    # Step 2: Mobius inversion
    # n * g_n = sum_{d|n} mu(n/d) * (d * log_f[d])
    # where log_f[d] = [q^d] log(f)
    mu = _mobius_function(N)
    g = [Fraction(0)] * N
    for n in range(1, N):
        val = Fraction(0)
        for d in range(1, n + 1):
            if n % d == 0:
                val += Fraction(mu[n // d]) * Fraction(d) * log_f[d]
        g[n] = val / Fraction(n)

    return g


def _mobius_function(N: int) -> List[int]:
    """Compute Mobius function mu(n) for n = 0, 1, ..., N-1.

    mu(1) = 1
    mu(n) = 0 if n has a squared prime factor
    mu(n) = (-1)^k if n is a product of k distinct primes
    """
    mu = [0] * N
    if N > 1:
        mu[1] = 1
    # Sieve
    is_prime = [True] * N
    primes = []
    for i in range(2, N):
        if is_prime[i]:
            primes.append(i)
            mu[i] = -1  # prime => mu = -1
        for p in primes:
            if i * p >= N:
                break
            is_prime[i * p] = False
            if i % p == 0:
                mu[i * p] = 0  # p^2 divides i*p
                break
            else:
                mu[i * p] = -mu[i]
    return mu


def bps_invariants_c3(N: int) -> List[int]:
    """BPS invariants Omega(n) of C^3 for n = 0, 1, ..., N-1.

    For C^3: Omega(n) = n for all n >= 1, Omega(0) = 0.

    This is because M(q) = prod_{n>=1} (1-q^n)^{-n}, so the plethystic
    logarithm is PLog(M(q)) = sum_{n>=1} n * q^n.

    In DT theory: Omega(n) counts BPS bound states of n D0-branes on C^3.
    The value n comes from the fact that the moduli space of n points on C^3
    has (signed) Euler characteristic (-1)^{n-1} * n.
    """
    return [n for n in range(N)]


def bps_invariants_from_macmahon(N: int) -> List[Fraction]:
    """Compute BPS invariants by plethystic logarithm of the MacMahon function.

    This is an independent computation path (Path 3).
    """
    mac = macmahon_coefficients(N)
    return plethystic_log_coefficients(mac, N)


# ---------------------------------------------------------------------------
# Augmentation ideal dimensions
# ---------------------------------------------------------------------------

def augmentation_ideal_dims(N: int) -> List[int]:
    """Dimensions of the augmentation ideal Y^+_{>0} in each degree.

    Y^+_0 = Q (the ground field), so the augmentation ideal has
    dim(Y^+_{>0})_n = p(n) for n >= 1, and 0 for n = 0.

    Returns [d_0, d_1, ..., d_{N-1}] where d_n = dim(Y^+_{>0})_n.
    """
    pp = plane_partition_counts(N)
    pp[0] = 0  # remove the ground field component
    return pp


# ---------------------------------------------------------------------------
# Bar complex dimensions at each arity
# ---------------------------------------------------------------------------

def bar_arity_k_dims(k: int, N: int) -> List[int]:
    """Dimensions of B^k(Y^+) in each total degree n.

    B^k(Y^+) = (Y^+_{>0})^{otimes k}, graded by total degree.
    An element [a_1|...|a_k] with a_i in Y^+_{n_i} (n_i >= 1) has
    total degree n = n_1 + ... + n_k.

    dim B^k_n = sum_{n_1+...+n_k = n, n_i >= 1} prod dim(Y^+_{n_i}).

    This is the k-fold convolution of the augmentation ideal dimensions.

    Returns [d_0, d_1, ..., d_{N-1}].
    """
    if k == 0:
        result = [0] * N
        result[0] = 1  # B^0 = Q (the ground field)
        return result

    aug = augmentation_ideal_dims(N)

    # k-fold convolution of aug with itself
    # Start with identity (delta at 0) and convolve k times
    current = [Fraction(0)] * N
    current[0] = Fraction(1)

    for _ in range(k):
        new = [Fraction(0)] * N
        for i in range(N):
            if current[i] == 0:
                continue
            for j in range(1, N - i):  # j >= 1 since we use augmentation ideal
                new[i + j] += current[i] * aug[j]
        current = new

    return [int(c) for c in current]


def bar_arity_k_generating_function(k: int, N: int) -> List[Fraction]:
    """Generating function for B^k(Y^+) as a power series in q.

    GF_k(q) = (M(q) - 1)^k  (the k-th power of the augmentation ideal character).

    This uses the fact that char(Y^+_{>0}) = M(q) - 1 and the bar complex at
    arity k is the k-fold tensor product.

    Returns exact Fraction coefficients [c_0, c_1, ..., c_{N-1}].
    """
    mac = macmahon_coefficients(N)
    # aug = M(q) - 1
    aug = list(mac)
    aug[0] = Fraction(0)

    if k == 0:
        result = [Fraction(0)] * N
        result[0] = Fraction(1)
        return result

    # Compute aug^k by repeated multiplication
    result = [Fraction(0)] * N
    result[0] = Fraction(1)
    for _ in range(k):
        result = _poly_mul_trunc(result, aug, N)

    return result


def _poly_mul_trunc(a: List[Fraction], b: List[Fraction],
                    N: int) -> List[Fraction]:
    """Multiply two truncated power series mod q^N."""
    result = [Fraction(0)] * N
    la, lb = len(a), len(b)
    for i in range(min(la, N)):
        if a[i] == 0:
            continue
        for j in range(min(lb, N - i)):
            result[i + j] += a[i] * b[j]
    return result


# ---------------------------------------------------------------------------
# Bar differential: d_bar : B^k -> B^{k-1}
# ---------------------------------------------------------------------------

def bar_differential_matrix_dims(k: int, n: int) -> Tuple[int, int]:
    """Dimensions of the bar differential d: B^k_n -> B^{k-1}_n.

    Returns (source_dim, target_dim).
    """
    source = bar_arity_k_dims(k, n + 1)[n]
    target = bar_arity_k_dims(k - 1, n + 1)[n]
    return source, target


def bar_euler_char_by_degree(N: int, max_arity: int = 6) -> List[Fraction]:
    """Euler characteristic chi(B(Y^+)) = sum_k (-1)^k dim B^k in each degree.

    By the bar complex being a resolution:
    chi(B(Y^+))_n = delta_{n,0}  (the augmentation is a quasi-iso).

    But more precisely: the REDUCED bar complex B_red(Y^+) = ker(augmentation)
    has chi = 0 in degree 0 and chi_n = alternating sum for n >= 1.

    For a (graded) commutative augmented algebra A:
    sum_k (-1)^k (A_+)^{otimes k} = 1 / A_+ ... No.

    Actually, the bar complex is acyclic in the sense that it resolves the
    trivial module. The generating function identity:

    sum_{k>=0} (-1)^k (M(q)-1)^k = 1/M(q) = prod_{n>=1} (1-q^n)^n

    This is the INVERSE MacMahon function.

    The Euler characteristic in degree n:
    chi_n = sum_{k=0}^{n} (-1)^k dim(B^k_n)
          = [q^n] 1/M(q)
          = [q^n] prod_{n>=1} (1-q^n)^n

    Returns [chi_0, chi_1, ..., chi_{N-1}].
    """
    # Compute 1/M(q) = prod_{n>=1} (1-q^n)^n directly
    result = [Fraction(0)] * N
    result[0] = Fraction(1)

    for m in range(1, N):
        # Multiply by (1-q^m)^m
        for _ in range(m):
            # Multiply by (1-q^m) in-place
            for j in range(N - 1, m - 1, -1):
                result[j] -= result[j - m]

    return result


def bar_euler_char_alternating_sum(N: int, max_arity: int = 8) -> List[Fraction]:
    """Compute Euler characteristic by explicit alternating sum of arity dimensions.

    chi_n = sum_{k=0}^{max_arity} (-1)^k dim(B^k_n)

    This is an independent computation (Path 4) that should agree with
    bar_euler_char_by_degree for n small enough (where max_arity is sufficient).

    Returns [chi_0, chi_1, ..., chi_{N-1}].
    """
    chi = [Fraction(0)] * N
    for k in range(max_arity + 1):
        gf_k = bar_arity_k_generating_function(k, N)
        sign = Fraction((-1) ** k)
        for n in range(N):
            chi[n] += sign * gf_k[n]
    return chi


# ---------------------------------------------------------------------------
# Bar cohomology dimensions (exact, low degree)
# ---------------------------------------------------------------------------

def indecomposables_dim(N: int) -> List[int]:
    r"""Dimension of the space of indecomposables Q(Y^+) = Y^+_{>0} / (Y^+_{>0})^2.

    The indecomposables are H^1(B(Y^+)) -- the arity-1 bar cohomology.
    For a commutative algebra, Q_n = dim(Y^+_n) - dim((Y^+_{>0})^2)_n.

    For Y^+ = CoHA(C^3), the key claim is that the BPS generators span
    the indecomposables: dim Q_n = Omega(n) = n.

    NOTE: Y^+ is NOT commutative. The CoHA multiplication depends on the
    ordering (it is the Hall algebra product, which is associative but not
    commutative in general). However, the ASSOCIATED GRADED with respect to
    the weight filtration IS commutative, and the plethystic logarithm
    computes the BPS invariants from the associated graded.

    For the COMMUTATIVE model (Sym(V_BPS)):
    If Y^+ were Sym(V) with dim(V_n) = n, then:
      dim(Y^+_n) = p(n)  [plane partitions = partitions into parts with
                           multiplicity, using n parts of size 1, n parts of size 2, etc.]

    Wait -- this is exactly right! The MacMahon function IS the character of
    Sym(V) with dim(V_n) = n:
      char(Sym(V)) = prod_{n>=1} 1/(1-q^n)^{dim V_n} = prod_{n>=1} 1/(1-q^n)^n = M(q).

    So the associated graded of Y^+ IS Sym(V_BPS) with dim(V_BPS)_n = n.
    The indecomposables are exactly V_BPS, and dim(Q_n) = n.

    Returns [Q_0, Q_1, ..., Q_{N-1}].
    """
    # Compute from the plethystic logarithm (exact BPS counts)
    mac = macmahon_coefficients(N)
    plog = plethystic_log_coefficients(mac, N)
    return [int(round(float(c))) for c in plog]


def bar_cohomology_arity1(N: int) -> List[int]:
    """H^1(B(Y^+)): bar cohomology at arity 1 = indecomposables.

    H^1_n = ker(d: B^1_n -> B^0_n) / im(d: B^2_n -> B^1_n)

    Since d: B^1 -> B^0 is the augmentation (which is surjective onto Q for
    n=0 and zero for n>0), and d: B^2 -> B^1 sends [a|b] to a*b, we have:

    H^1_n = Y^+_n / (Y^+_{>0} * Y^+_{>0})_n  for n >= 1
          = indecomposables = BPS generators.

    dim H^1_n = Omega(n) = n (for C^3).
    """
    return indecomposables_dim(N)


def bar_cohomology_arity2(N: int) -> List[int]:
    r"""H^2(B(Y^+)): bar cohomology at arity 2 = relations among generators.

    H^2_n = ker(d: B^2_n -> B^1_n) / im(d: B^3_n -> B^2_n)

    For the commutative model Sym(V_BPS):
    H^2 = Wedge^2(V_BPS) (the relations are the commutativity relations).
    dim(H^2_n) = dim(Wedge^2(V_BPS))_n.

    For the ACTUAL CoHA (non-commutative), the relations include BOTH the
    commutator relations AND the Yangian cubic Serre-type relations.
    The bar cohomology H^2 detects the "space of relations" in the
    minimal A_infinity resolution.

    For the commutative model, we compute:
    dim(Wedge^2(V))_n = sum_{a<b, a+b=n} dim(V_a)*dim(V_b)
                       + sum_{2a=n} binom(dim(V_a), 2)
    """
    bps = bps_invariants_c3(N)

    result = [0] * N
    for a in range(1, N):
        for b in range(a, N):
            if a + b >= N:
                break
            if a < b:
                result[a + b] += bps[a] * bps[b]
            else:  # a == b
                result[2 * a] += bps[a] * (bps[a] - 1) // 2
    return result


def bar_cohomology_arity2_sym(N: int) -> List[int]:
    r"""H^2 for the symmetric algebra model: Sym^2(V_BPS) component.

    In the symmetric model, the bar complex of Sym(V) has:
    H^k(B(Sym(V))) = Wedge^k(V)  (exterior powers).

    So H^2 = Wedge^2(V_BPS), with
    dim(Wedge^2(V))_n = sum_{a+b=n, a<b} a*b + sum_{2a=n} binom(a,2)
    (using dim(V_m) = m).
    """
    return bar_cohomology_arity2(N)


# ---------------------------------------------------------------------------
# Generating functions for bar cohomology
# ---------------------------------------------------------------------------

def bar_cohomology_generating_function(N: int, max_arity: int = 4) -> Dict[int, List[Fraction]]:
    """Generating functions for H^k(B(Y^+)) at each arity k.

    For the commutative model Sym(V_BPS):
    H^k = Wedge^k(V_BPS), so
    sum_k (-t)^k char(H^k) = prod_{n>=1} (1-t*q^n)^{dim V_n}
                            = prod_{n>=1} (1-t*q^n)^n

    The full generating function in (t, q):
    F(t,q) = prod_{n>=1} (1-t*q^n)^n

    At t = -1: F(-1,q) = prod_{n>=1} (1+q^n)^n
    At t = 1:  F(1,q) = prod_{n>=1} (1-q^n)^n = 1/M(q) (inverse MacMahon)

    For fixed k:
    char(H^k)(q) = [t^k] prod_{n>=1} (1 - t*q^n)^n

    Returns dict mapping arity k -> [h^k_0, h^k_1, ..., h^k_{N-1}].
    """
    # Build the generating function as a polynomial in t with q-series coefficients
    # F(t,q) = prod_{n>=1} (1 - t*q^n)^n mod q^N, up to t^{max_arity}

    # Start with F = 1
    # F is represented as a list of q-series, one for each power of t:
    # F[k] = coefficient of t^k in F(t,q)
    F = [[Fraction(0)] * N for _ in range(max_arity + 1)]
    F[0][0] = Fraction(1)

    for m in range(1, N):
        # Multiply F by (1 - t*q^m)^m
        # (1 - t*q^m)^m = sum_{j=0}^{m} binom(m,j) (-1)^j t^j q^{m*j}
        binomials = _binomial_row(m)

        for _ in range(1):  # we do the full product (1-tq^m)^m at once
            # Actually, multiply by (1-tq^m) a total of m times
            pass

        # More efficient: multiply by (1-tq^m)^m directly
        # (1-tq^m)^m = sum_{j=0}^{min(m, max_arity)} C(m,j) (-t)^j q^{jm}
        for rep in range(m):
            # Multiply F by (1 - t*q^m)
            # New_F[k][n] = F[k][n] - F[k-1][n-m]
            new_F = [[Fraction(0)] * N for _ in range(max_arity + 1)]
            for k in range(max_arity + 1):
                for n in range(N):
                    new_F[k][n] = F[k][n]
                    if k >= 1 and n >= m:
                        new_F[k][n] -= F[k - 1][n - m]
            F = new_F

    result = {}
    for k in range(max_arity + 1):
        result[k] = F[k]

    return result


def _binomial_row(n: int) -> List[int]:
    """Compute [C(n,0), C(n,1), ..., C(n,n)]."""
    row = [1]
    for k in range(1, n + 1):
        row.append(row[-1] * (n - k + 1) // k)
    return row


# ---------------------------------------------------------------------------
# Explicit low-arity bar complex with bases (for small degree)
# ---------------------------------------------------------------------------

def explicit_bar_elements_arity1(max_degree: int) -> Dict[int, List[str]]:
    """Explicit basis elements of B^1(Y^+) = Y^+_{>0} at each degree.

    The basis of Y^+_n is indexed by plane partitions of n.
    We use symbolic labels: 'pi_k' for the k-th plane partition of degree n.
    For degree 1: single box [1] -> 'e0' (the fundamental generator e_0).
    For degree 2: three plane partitions [[2]], [[1,1]], [[1],[1]] ->
                  'e0^2', 'e0*e0_alt', or by plane partition shape.

    Actually, Y^+_n has a basis indexed by plane partitions pi with |pi|=n.
    The BPS/primitive generators span a subspace of dimension n.
    """
    pp = plane_partition_counts(max_degree + 1)
    result = {}
    for n in range(1, max_degree + 1):
        result[n] = [f"pp_{n}_{i}" for i in range(pp[n])]
    return result


def explicit_bar_elements_arity2(max_degree: int) -> Dict[int, int]:
    """Dimensions of B^2(Y^+) = Y^+_{>0} tensor Y^+_{>0} at each total degree.

    dim(B^2_n) = sum_{a+b=n, a>=1, b>=1} p(a) * p(b).
    """
    pp = plane_partition_counts(max_degree + 1)
    result = {}
    for n in range(2, max_degree + 1):
        dim = 0
        for a in range(1, n):
            b = n - a
            dim += pp[a] * pp[b]
        result[n] = dim
    return result


# ---------------------------------------------------------------------------
# Comprehensive arity-by-degree table
# ---------------------------------------------------------------------------

def bar_complex_table(N: int, max_arity: int = 6) -> Dict[str, object]:
    """Comprehensive table of bar complex dimensions.

    Returns a dict with:
      'dims': dims[k][n] = dim B^k_n
      'euler': euler[n] = chi_n = sum_k (-1)^k dim B^k_n
      'cohomology_sym': cohom[k][n] = dim H^k_n (symmetric/commutative model)
      'bps': bps[n] = Omega(n) = n (BPS invariants)

    The bar complex B(Y^+) has:
      B^k_n = (Y^+_{>0})^{otimes k} with total degree n, min degree k.
    So B^k_n = 0 for n < k.
    """
    pp = plane_partition_counts(N)
    aug = list(pp)
    aug[0] = 0  # augmentation ideal

    # Compute dims[k][n] for 0 <= k <= max_arity, 0 <= n < N
    dims = {}
    for k in range(max_arity + 1):
        gf = bar_arity_k_generating_function(k, N)
        dims[k] = [int(c) for c in gf]

    # Euler characteristics
    euler_exact = bar_euler_char_by_degree(N)
    euler_alt = bar_euler_char_alternating_sum(N, max_arity)

    # Bar cohomology (symmetric model) -- use the + sign version (exterior powers)
    cohom = symmetric_model_cohomology_dims(N, min(max_arity, 4))

    # BPS
    bps = bps_invariants_c3(N)

    return {
        'dims': dims,
        'euler_exact': [int(c) for c in euler_exact],
        'euler_alternating': [int(round(float(c))) for c in euler_alt],
        'cohomology_sym': cohom,
        'bps': bps,
        'plane_partitions': pp,
    }


# ---------------------------------------------------------------------------
# MacMahon identity verification
# ---------------------------------------------------------------------------

def verify_macmahon_bar_identity(N: int) -> Dict[str, object]:
    """Verify the identity: sum_k (-1)^k (M(q)-1)^k = 1/M(q).

    This is the bar complex Euler characteristic identity:
    sum_{k>=0} (-1)^k char(B^k(Y^+)) = 1/M(q) = prod_{n>=1} (1-q^n)^n.

    The identity is a formal power series identity:
    sum_{k>=0} (-x)^k = 1/(1+x)  with x = M(q) - 1.
    So 1/(1 + (M(q)-1)) = 1/M(q).

    This is TAUTOLOGICAL for the generating functions, but it provides a
    cross-check on our computation of the arity-by-degree dimensions.
    """
    mac = macmahon_coefficients(N)
    inv_mac = bar_euler_char_by_degree(N)

    # Verify: M(q) * (1/M(q)) = 1
    product = _poly_mul_trunc(mac, inv_mac, N)
    is_identity = all(
        product[i] == (Fraction(1) if i == 0 else Fraction(0))
        for i in range(N)
    )

    return {
        'macmahon': [int(c) for c in mac],
        'inverse_macmahon': [int(c) for c in inv_mac],
        'product_is_identity': is_identity,
    }


# ---------------------------------------------------------------------------
# Comparison with DT invariants
# ---------------------------------------------------------------------------

def dt_from_bar_euler_char(N: int) -> List[int]:
    """Extract DT invariants from the bar Euler characteristic.

    The SIGNED DT partition function is:
    Z^DT(q) = M(-q) = sum_n (-1)^n p(n) q^n

    The bar Euler characteristic gives 1/M(q).

    The BPS invariants come from the plethystic logarithm of M(q):
    PLog(M(q)) = sum_{n>=1} n * q^n.

    Equivalently, from 1/M(q) = prod_{n>=1} (1-q^n)^n:
    log(1/M(q)) = sum_{n>=1} n * log(1-q^n)
                = -sum_{n>=1} n * sum_{m>=1} q^{mn}/m
                = -sum_{k>=1} (sum_{d|k} d * (k/d)^{-1} ... )

    Actually: PLog(M(q)) = -log(1/M(q))|_{Adams} is cleaner.

    We extract the BPS invariants by reading off the exponents in:
    1/M(q) = prod_{n>=1} (1-q^n)^{Omega(n)}

    Since Omega(n) = n, we verify: prod_{n>=1} (1-q^n)^n = 1/M(q).
    """
    inv_mac = bar_euler_char_by_degree(N)

    # Build prod_{n>=1} (1-q^n)^n from the known Omega(n) = n
    check = [Fraction(0)] * N
    check[0] = Fraction(1)
    for m in range(1, N):
        for _ in range(m):
            for j in range(N - 1, m - 1, -1):
                check[j] -= check[j - m]

    match = all(inv_mac[i] == check[i] for i in range(N))

    return {
        'inverse_macmahon': [int(c) for c in inv_mac],
        'from_bps_product': [int(c) for c in check],
        'match': match,
        'bps_values': bps_invariants_c3(min(N, 20)),
    }


# ---------------------------------------------------------------------------
# Arity-refined cohomological data for the symmetric model
# ---------------------------------------------------------------------------

def symmetric_model_cohomology_dims(N: int, max_arity: int = 4) -> Dict[int, List[int]]:
    r"""Dimensions of H^k(B(Sym(V))) = Wedge^k(V) for V_n = n.

    For the symmetric algebra model of Y^+ (associated graded under weight
    filtration), the bar cohomology is exterior powers of V_BPS:
      H^k = Wedge^k(V_BPS), char(Wedge^k(V)) = e_k(q, q^2, ...).

    The generating function for all k:
    sum_k t^k char(Wedge^k(V)) = prod_{n>=1} (1+t*q^n)^n

    We extract the coefficient of t^k as a q-series.
    """
    # Build prod_{n>=1} (1 + t*q^n)^n as polynomial in t with q-series coeffs
    F = [[Fraction(0)] * N for _ in range(max_arity + 1)]
    F[0][0] = Fraction(1)

    for m in range(1, N):
        # Multiply by (1 + t*q^m)^m = (1+tq^m) repeated m times
        for _ in range(m):
            new_F = [[Fraction(0)] * N for _ in range(max_arity + 1)]
            for k in range(max_arity + 1):
                for n in range(N):
                    new_F[k][n] = F[k][n]
                    if k >= 1 and n >= m:
                        new_F[k][n] += F[k - 1][n - m]  # + sign for Wedge
            F = new_F

    result = {}
    for k in range(max_arity + 1):
        result[k] = [int(round(float(c))) for c in F[k]]

    return result


def verify_cohomology_euler_char(N: int, max_arity: int = 4) -> Dict[str, object]:
    """Verify: sum_k (-1)^k char(H^k) = 1/M(q) = bar Euler characteristic.

    For the symmetric model:
    sum_k (-1)^k char(Wedge^k(V)) = prod_{n>=1} (1-q^n)^n = 1/M(q).

    This is the bar complex version of the identity:
    the alternating sum of exterior powers equals the inverse MacMahon.
    """
    cohom = symmetric_model_cohomology_dims(N, max_arity)
    euler_from_cohom = [Fraction(0)] * N
    for k in range(max_arity + 1):
        sign = Fraction((-1) ** k)
        for n in range(N):
            euler_from_cohom[n] += sign * cohom[k][n]

    inv_mac = bar_euler_char_by_degree(N)

    # Compare (noting that the cohomological and bar Euler chars should match
    # up to the truncation level)
    match = True
    mismatches = []
    for n in range(N):
        if euler_from_cohom[n] != inv_mac[n]:
            match = False
            mismatches.append((n, euler_from_cohom[n], inv_mac[n]))

    return {
        'match': match,
        'mismatches': mismatches[:10],
        'cohom_euler': [int(round(float(c))) for c in euler_from_cohom],
        'bar_euler': [int(c) for c in inv_mac],
    }


# ---------------------------------------------------------------------------
# Summary report
# ---------------------------------------------------------------------------

def bar_complex_summary(N: int = 12, max_arity: int = 5) -> str:
    """Generate a human-readable summary of B(Y^+(gl_hat_1)) at low arities."""
    table = bar_complex_table(N, max_arity)
    bps = table['bps']
    pp = table['plane_partitions']

    lines = []
    lines.append("=" * 70)
    lines.append("BAR COMPLEX B(Y^+(gl_hat_1)) -- LOW ARITY SUMMARY")
    lines.append("=" * 70)
    lines.append("")

    # Plane partition counts
    lines.append("Plane partition counts p(n) = dim Y^+_n:")
    lines.append(f"  {pp[:N]}")
    lines.append("")

    # BPS invariants
    lines.append("BPS invariants Omega(n) (= n for C^3):")
    lines.append(f"  {bps[:N]}")
    lines.append("")

    # Bar complex dimensions
    lines.append("Bar complex dimensions dim B^k_n:")
    lines.append(f"  {'n':>4}" + "".join(f"  {n:>6}" for n in range(N)))
    for k in range(min(max_arity + 1, 6)):
        row = table['dims'].get(k, [0] * N)
        lines.append(f"  k={k}" + "".join(f"  {row[n]:>6}" for n in range(N)))
    lines.append("")

    # Euler characteristic
    lines.append("Bar Euler characteristic chi_n = [q^n] 1/M(q):")
    lines.append(f"  {table['euler_exact'][:N]}")
    lines.append("")

    # Cohomology (symmetric model)
    lines.append("Bar cohomology dim H^k_n (symmetric model, Wedge^k(V_BPS)):")
    cohom = table['cohomology_sym']
    for k in sorted(cohom.keys()):
        if k <= 4:
            lines.append(f"  k={k}: {cohom[k][:N]}")
    lines.append("")

    # Verification
    mac_check = verify_macmahon_bar_identity(min(N, 15))
    lines.append(f"MacMahon identity M(q) * (1/M(q)) = 1: {mac_check['product_is_identity']}")

    return "\n".join(lines)
