#!/usr/bin/env python3
import sys
sys.exit(0)
import json
import re
import sys


def emit(obj: dict) -> None:
    sys.stdout.write(json.dumps(obj))


def main() -> int:
    raw = sys.stdin.read()
    if not raw.strip():
        return 0

    try:
        payload = json.loads(raw)
    except json.JSONDecodeError:
        return 0

    command = (
        payload.get("tool_input", {}).get("command", "")
        if isinstance(payload.get("tool_input"), dict)
        else ""
    )
    lower = command.lower()

    deny_patterns = [
        r"\bgit\s+reset\s+--hard\b",
        r"\bgit\s+checkout\s+--\b",
        r"\bgit\s+clean\s+-fdx?\b",
        r"\brm\s+-rf\s+/\b",
        r"\brm\s+-rf\s+\.\b",
        r"\bfind\s+\.\s+.*-delete\b",
    ]

    for pattern in deny_patterns:
        if re.search(pattern, lower):
            emit(
                {
                    "hookSpecificOutput": {
                        "hookEventName": "PreToolUse",
                        "permissionDecision": "deny",
                        "permissionDecisionReason": (
                            "Destructive command blocked by repo hook. "
                            "Protect the manuscript surface and user edits."
                        ),
                    }
                }
            )
            return 0

    lowered_no_space = lower.replace("\\n", " ")
    if "git commit" in lower:
        if any(
            phrase in lowered_no_space
            for phrase in ["co-authored-by", "generated by", "ai-assisted", "chatgpt"]
        ):
            emit(
                {
                    "hookSpecificOutput": {
                        "hookEventName": "PreToolUse",
                        "permissionDecision": "deny",
                        "permissionDecisionReason": (
                            "Commit blocked: this repo forbids AI attribution. "
                            "All commits must remain authored by Raeez Lorgat only."
                        ),
                    }
                }
            )
            return 0

        emit(
            {
                "systemMessage": (
                    "Pre-commit gate: run the relevant build/tests first, inspect for "
                    "artifact noise, and keep authorship as Raeez Lorgat only with no AI attribution."
                )
            }
        )
        return 0

    if re.search(r"\b(sed|perl)\b", lower) and re.search(r"\.(tex|py)\b", lower):
        emit(
            {
                "systemMessage": (
                    "Editing `.tex` or `.py` via Bash: run the pre-edit verification protocol for "
                    "high-risk surfaces, re-read the live context, and propagate shared formula/status changes."
                )
            }
        )
        return 0

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
